version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    cooldown:
      min-release-age: "3 days"
    commit-message:
      prefix: "chore"
      include: "scope"
