/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */
import type { ColorCategory } from './awsMeta'

export type BookmarkIndexDoc = {
  shortName: string
  fullName: string
  gunaUntuk: string
  category: ColorCategory
  sectionId: string
}

export const bookmarkIndex: BookmarkIndexDoc[] = [
  {
    "shortName": "IAM",
    "fullName": "AWS Identity and Access Management",
    "gunaUntuk": "Control who can access what AWS resources",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "STS",
    "fullName": "AWS Security Token Service",
    "gunaUntuk": "Generate temporary security credentials",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "Directory Service",
    "fullName": "AWS Directory Service",
    "gunaUntuk": "Managed Microsoft Active Directory, AD Connector, or Simple AD for AWS workloads",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "IAM Identity Center",
    "fullName": "AWS IAM Identity Center (SSO)",
    "gunaUntuk": "Centralized SSO untuk multiple AWS accounts",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "IAM Access Analyzer",
    "fullName": "AWS IAM Access Analyzer",
    "gunaUntuk": "Detect resources yang ter-expose ke public / account luar / Org luar",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "AWS RAM",
    "fullName": "AWS Resource Access Manager",
    "gunaUntuk": "Share AWS resources merentas account / OU dalam Organization",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "IAM Roles Anywhere",
    "fullName": "AWS IAM Roles Anywhere",
    "gunaUntuk": "Give on-prem / non-AWS servers temporary AWS credentials without access keys",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "AWS Artifact",
    "fullName": "AWS Artifact",
    "gunaUntuk": "Download AWS compliance reports & accept agreements",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "Cognito",
    "fullName": "Amazon Cognito",
    "gunaUntuk": "User sign-up/sign-in, federated identity (Google/Facebook), mobile app auth",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "RAM",
    "fullName": "AWS Resource Access Manager",
    "gunaUntuk": "Share subnets, Transit Gateway, Route 53 resolver rules cross-account",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "AWS Organizations",
    "fullName": "AWS Organizations + Control Tower + SCPs",
    "gunaUntuk": "Manage multiple AWS accounts centrally with guardrails",
    "category": "d1iam",
    "sectionId": "d1-iam"
  },
  {
    "shortName": "Security Groups",
    "fullName": "VPC Security Groups",
    "gunaUntuk": "Instance-level firewall — control inbound/outbound per EC2/ENI",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "NACLs",
    "fullName": "Network Access Control Lists",
    "gunaUntuk": "Subnet-level firewall, stateless, boleh block IP",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "WAF",
    "fullName": "AWS Web Application Firewall",
    "gunaUntuk": "Protect against SQL injection, XSS, rate limiting",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "AWS Shield",
    "fullName": "AWS Shield Standard & Advanced",
    "gunaUntuk": "DDoS protection Layer 3/4 (Standard) and Layer 7 (Advanced)",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Network Firewall",
    "fullName": "AWS Network Firewall",
    "gunaUntuk": "VPC-level managed firewall — stateful deep packet inspection, domain filtering, IDS/IPS",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "VPC Flow Logs",
    "fullName": "VPC Flow Logs",
    "gunaUntuk": "Capture IP traffic metadata to/from ENIs — troubleshoot SG/NACL, security analysis, compliance",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "GuardDuty",
    "fullName": "Amazon GuardDuty",
    "gunaUntuk": "Automated threat detection: crypto-mining, unusual API calls, compromised instances",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Detective",
    "fullName": "Amazon Detective",
    "gunaUntuk": "Investigate and analyze security findings from GuardDuty, Security Hub, Macie",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Inspector",
    "fullName": "Amazon Inspector",
    "gunaUntuk": "Find OS/software vulnerabilities, CVEs, unintended network exposure in EC2, ECR images, Lambda",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Macie",
    "fullName": "Amazon Macie",
    "gunaUntuk": "Discover and protect sensitive data in S3: PII, credentials, financial data, compliance",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Security Hub",
    "fullName": "AWS Security Hub",
    "gunaUntuk": "Central view of security findings across accounts + compliance checks",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Firewall Manager",
    "fullName": "AWS Firewall Manager",
    "gunaUntuk": "Centrally manage firewall rules across all accounts in an Organization",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Penetration Testing",
    "fullName": "AWS Penetration Testing Policy",
    "gunaUntuk": "Faham polisi AWS untuk security testing & Acceptable Use Policy",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "Security Stack",
    "fullName": "AWS Security Services — Custom Rules & Integration",
    "gunaUntuk": "Faham service mana boleh custom rules vs auto, macam mana security services integrate, + keyword cost tolak jawapan ke versi jimat/premium",
    "category": "d1net",
    "sectionId": "d1-netsec"
  },
  {
    "shortName": "KMS",
    "fullName": "AWS Key Management Service",
    "gunaUntuk": "Encrypt data at rest, manage encryption keys",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "Secrets Manager",
    "fullName": "AWS Secrets Manager",
    "gunaUntuk": "Store dan auto-rotate credentials, API keys, DB passwords",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "S3 Object Lock",
    "fullName": "Amazon S3 Object Lock",
    "gunaUntuk": "WORM compliance, prevent deletion/modification",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "S3 Glacier Vault",
    "fullName": "Amazon S3 Glacier Vault Lock & Access Policy",
    "gunaUntuk": "WORM compliance for Glacier archives — enforce retention policies that cannot be changed",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "Amazon Redshift",
    "fullName": "Amazon Redshift — Encryption & DataShare",
    "gunaUntuk": "Encrypt data warehouse at rest (KMS) and in transit (SSL); share data cross-account via DataShare",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "CloudTrail",
    "fullName": "AWS CloudTrail",
    "gunaUntuk": "Audit who did what and when — compliance, forensics, account activity",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "ACM",
    "fullName": "AWS Certificate Manager",
    "gunaUntuk": "Provision free SSL/TLS certificates for ALB, CloudFront, API Gateway",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "CloudHSM",
    "fullName": "AWS CloudHSM",
    "gunaUntuk": "FIPS 140-2 Level 3 compliance, customer-exclusive HSM hardware",
    "category": "d1data",
    "sectionId": "d1-data"
  },
  {
    "shortName": "Direct Connect",
    "fullName": "AWS Direct Connect",
    "gunaUntuk": "Private dedicated connection from on-premises to AWS",
    "category": "d1connect",
    "sectionId": "d1-connect"
  },
  {
    "shortName": "Site-to-Site VPN",
    "fullName": "AWS Site-to-Site VPN",
    "gunaUntuk": "Encrypted IPSec tunnel from on-premises network to VPC over internet",
    "category": "d1connect",
    "sectionId": "d1-connect"
  },
  {
    "shortName": "Client VPN",
    "fullName": "AWS Client VPN",
    "gunaUntuk": "Allow individual users to authenticate and connect to a VPC from their devices",
    "category": "d1connect",
    "sectionId": "d1-connect"
  },
  {
    "shortName": "VPC",
    "fullName": "Amazon Virtual Private Cloud",
    "gunaUntuk": "Isolated private network — the foundation for all AWS resources",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "CIDR & Subnets",
    "fullName": "IP Addressing & Subnet Calculator",
    "gunaUntuk": "Plan IP address ranges — VPC perlu CIDR sebelum boleh buat subnets",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "Private/Public/Elastic IP",
    "fullName": "EC2 IP Addresses — Private vs Public vs Elastic",
    "gunaUntuk": "Tentukan macam mana EC2 dialamatkan — internal (Private), internet sementara (Public), atau internet statik yang tak berubah (Elastic)",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "Internet Gateway",
    "fullName": "VPC Internet Gateway (IGW)",
    "gunaUntuk": "Connect VPC to internet (bidirectional) — kena ada untuk public subnet",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "NAT Gateway",
    "fullName": "Network Address Translation Gateway",
    "gunaUntuk": "Private subnet instances download patches/call APIs without being exposed to internet",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "Route Tables",
    "fullName": "VPC Route Tables",
    "gunaUntuk": "Control traffic direction: public subnet → IGW, private subnet → NAT GW",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "SG vs NACL",
    "fullName": "Security Groups vs Network ACLs — Defence Layers",
    "gunaUntuk": "Two-layer defence: SG guards each EC2, NACL guards each subnet",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "Laluan Packet VPC",
    "fullName": "Perjalanan Satu Packet — VPC Traffic Flow (end-to-end)",
    "gunaUntuk": "Faham urutan checkpoint satu packet lalui dari internet sampai EC2 dan balik — kunci untuk semua soalan troubleshoot VPC",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "VPC Peering",
    "fullName": "VPC Peering Connection",
    "gunaUntuk": "Connect 2 VPCs privately — same account, cross-account, atau cross-region",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "Transit Gateway",
    "fullName": "AWS Transit Gateway",
    "gunaUntuk": "Connect 3+ VPCs dan on-premises networks melalui satu hub yang transitive",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "VPC Endpoints",
    "fullName": "VPC Endpoints (Gateway & Interface)",
    "gunaUntuk": "Access S3/DynamoDB (free) atau AWS services lain (paid) dari private subnet secara private",
    "category": "d1net",
    "sectionId": "d1-vpc"
  },
  {
    "shortName": "Region & AZ",
    "fullName": "AWS Global Infrastructure — Region, Availability Zone, Edge",
    "gunaUntuk": "Faham geografi AWS — asas semua keputusan HA, DR, latency & data residency",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "Auto Scaling Groups",
    "fullName": "Amazon EC2 Auto Scaling",
    "gunaUntuk": "Automatically scale EC2 instances based on load",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "RDS Multi-AZ",
    "fullName": "Amazon RDS Multi-AZ Deployment",
    "gunaUntuk": "High availability for RDS — automatic failover",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "RDS Read Replicas",
    "fullName": "Amazon RDS Read Replicas",
    "gunaUntuk": "Scale read traffic, reporting queries, multi-region read access",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "RDS Proxy",
    "fullName": "Amazon RDS Proxy",
    "gunaUntuk": "Connection pooling for RDS — handle too many connections from Lambda/Auto Scaling",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "Global Accelerator",
    "fullName": "AWS Global Accelerator",
    "gunaUntuk": "Route global users to nearest healthy endpoint via AWS backbone",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "Aurora",
    "fullName": "Amazon Aurora",
    "gunaUntuk": "High-performance relational DB, MySQL/PostgreSQL compatible, enterprise HA",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "Aurora Serverless",
    "fullName": "Amazon Aurora Serverless",
    "gunaUntuk": "Unpredictable/intermittent workloads — auto-scale DB capacity, pay per second",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "DynamoDB",
    "fullName": "Amazon DynamoDB",
    "gunaUntuk": "Serverless key-value/document store, single-digit ms latency at any scale",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "DAX",
    "fullName": "Amazon DynamoDB Accelerator (DAX)",
    "gunaUntuk": "Read-heavy DynamoDB workloads needing microsecond response times",
    "category": "d2ha",
    "sectionId": "d2-ha"
  },
  {
    "shortName": "Backup & Restore",
    "fullName": "DR Pattern: Backup & Restore",
    "gunaUntuk": "Non-critical systems, lowest cost DR strategy",
    "category": "d2dr",
    "sectionId": "d2-dr"
  },
  {
    "shortName": "Pilot Light",
    "fullName": "DR Pattern: Pilot Light",
    "gunaUntuk": "Core DB running in DR region, app servers off until needed",
    "category": "d2dr",
    "sectionId": "d2-dr"
  },
  {
    "shortName": "Warm Standby",
    "fullName": "DR Pattern: Warm Standby",
    "gunaUntuk": "Scaled-down full stack running in DR, quick scale up",
    "category": "d2dr",
    "sectionId": "d2-dr"
  },
  {
    "shortName": "Multi-Site Active/Active",
    "fullName": "DR Pattern: Multi-Site Active/Active",
    "gunaUntuk": "Mission-critical — full capacity in both regions simultaneously",
    "category": "d2dr",
    "sectionId": "d2-dr"
  },
  {
    "shortName": "AWS Elastic Disaster Recovery",
    "fullName": "AWS Elastic Disaster Recovery (AWS DRS)",
    "gunaUntuk": "DR-as-a-service: continuously replicate on-prem/cloud/EC2 servers to AWS",
    "category": "d2dr",
    "sectionId": "d2-dr"
  },
  {
    "shortName": "AWS Backup",
    "fullName": "AWS Backup",
    "gunaUntuk": "Centralized backup across EC2, RDS, EFS, DynamoDB, S3",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "S3 Versioning & CRR",
    "fullName": "S3 Versioning + Cross-Region Replication",
    "gunaUntuk": "Protect against accidental deletion, cross-region DR for S3",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "EBS Snapshots",
    "fullName": "Amazon EBS Snapshots",
    "gunaUntuk": "Point-in-time backup of EBS volumes, cross-region DR",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "FSx",
    "fullName": "Amazon FSx",
    "gunaUntuk": "Managed file systems: Windows SMB, HPC Lustre, NetApp ONTAP, OpenZFS",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "Storage Gateway",
    "fullName": "AWS Storage Gateway",
    "gunaUntuk": "Hybrid cloud storage — on-premises apps guna AWS storage secara seamless",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "DataSync",
    "fullName": "AWS DataSync",
    "gunaUntuk": "One-time or recurring data migration from on-premises to S3, EFS, or FSx; also EFS cross-region replication",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "DMS",
    "fullName": "AWS Database Migration Service",
    "gunaUntuk": "Migrate databases to AWS — homogeneous (MySQL→RDS MySQL) or heterogeneous (Oracle→Aurora)",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "Snow Family",
    "fullName": "AWS Snow Family",
    "gunaUntuk": "Petabyte-scale data transfer bila internet terlalu lambat/mahal, atau edge computing",
    "category": "d2backup",
    "sectionId": "d2-backup"
  },
  {
    "shortName": "Transfer Family",
    "fullName": "AWS Transfer Family",
    "gunaUntuk": "Legacy FTP/SFTP/FTPS/AS2 file transfers stored directly into S3 or EFS — no code changes needed",
    "category": "d2migrate",
    "sectionId": "d2-migrate"
  },
  {
    "shortName": "AWS MGN",
    "fullName": "AWS Application Migration Service (MGN)",
    "gunaUntuk": "Migrate servers (physical/virtual/cloud) to AWS EC2 with minimal downtime",
    "category": "d2migrate",
    "sectionId": "d2-migrate"
  },
  {
    "shortName": "Migration Hub",
    "fullName": "AWS Migration Hub",
    "gunaUntuk": "Single pane of glass to track application migrations across multiple AWS tools",
    "category": "d2migrate",
    "sectionId": "d2-migrate"
  },
  {
    "shortName": "AWS Outposts",
    "fullName": "AWS Outposts",
    "gunaUntuk": "Run AWS services on-premises for compliance, low latency, or data residency requirements",
    "category": "d2migrate",
    "sectionId": "d2-migrate"
  },
  {
    "shortName": "EC2",
    "fullName": "Elastic Compute Cloud",
    "gunaUntuk": "Run any workload, full control",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "Lambda",
    "fullName": "AWS Lambda",
    "gunaUntuk": "Serverless, event-driven",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "Elastic Beanstalk",
    "fullName": "AWS Elastic Beanstalk",
    "gunaUntuk": "Deploy app tanpa urus server",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "ECS",
    "fullName": "Elastic Container Service",
    "gunaUntuk": "Run & orchestrate Docker containers (AWS-native, bukan Kubernetes)",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "EKS",
    "fullName": "Elastic Kubernetes Service",
    "gunaUntuk": "Container orchestration guna K8s",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "EKS Variants",
    "fullName": "EKS Anywhere vs EKS Distro vs ECS Anywhere",
    "gunaUntuk": "Run container workloads on-premises with varying levels of AWS integration",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "AWS LB Controller",
    "fullName": "AWS Load Balancer Controller",
    "gunaUntuk": "Auto-provision AWS load balancers (ALB/NLB) dari Kubernetes Ingress/Service resources",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "EC2 User Data",
    "fullName": "EC2 User Data Scripts",
    "gunaUntuk": "Auto-configure EC2 instance on first boot",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "EC2 Hibernation",
    "fullName": "Amazon EC2 Hibernation",
    "gunaUntuk": "Preserve in-memory state across stop/start — fast resume for memory-intensive apps",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "EC2 Metadata",
    "fullName": "EC2 Instance Metadata Service (IMDS)",
    "gunaUntuk": "Get info about the running instance from within the instance",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "Recycle Bin",
    "fullName": "AWS Recycle Bin (AMI & EBS Snapshots)",
    "gunaUntuk": "Recover accidentally deleted AMIs and EBS snapshots within a defined retention period",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "AWS Batch",
    "fullName": "AWS Batch",
    "gunaUntuk": "Run batch / long-running compute jobs at scale without managing EC2 infrastructure",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "Fargate",
    "fullName": "AWS Fargate",
    "gunaUntuk": "Run container (ECS/EKS) tanpa urus EC2 langsung",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "ECR",
    "fullName": "Amazon Elastic Container Registry",
    "gunaUntuk": "Simpan, version & deploy Docker image secara private dalam AWS",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "Instance Store",
    "fullName": "Amazon EC2 Instance Store",
    "gunaUntuk": "Temporary block storage physically attached to the host server — highest IOPS, zero cost",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "ENI/ENA/EFA",
    "fullName": "EC2 Network Interfaces — ENI · ENA · EFA",
    "gunaUntuk": "Network connectivity dan performance — pilih ikut keperluan (standard vs high-throughput vs HPC)",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "Lambda@Edge",
    "fullName": "AWS Lambda@Edge",
    "gunaUntuk": "Run Lambda functions AT CloudFront edge locations — customize content delivery closer to users",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "EC2 Tenancy",
    "fullName": "EC2 Tenancy & Dedicated Hosts",
    "gunaUntuk": "Pilih tahap isolation hardware — shared vs dedicated instance vs dedicated host",
    "category": "compute",
    "sectionId": "d3-compute"
  },
  {
    "shortName": "EBS",
    "fullName": "Elastic Block Store",
    "gunaUntuk": "Block storage, attach ke 1 EC2",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "EBS Volume Types",
    "fullName": "Amazon EBS — Volume Types & Multi-Attach",
    "gunaUntuk": "Choose right EBS type for workload: random I/O vs sequential, IOPS vs throughput, cost vs performance",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "EFS",
    "fullName": "Elastic File System",
    "gunaUntuk": "Shared file storage for multiple EC2 instances simultaneously",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "S3",
    "fullName": "Simple Storage Service",
    "gunaUntuk": "Object storage: images, video, backup, data lake, static website",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "S3 Access Control",
    "fullName": "S3 Access Control & Policies (IAM · Bucket Policy · ACL · BPA)",
    "gunaUntuk": "Kawal siapa boleh access bucket/object — pilih antara IAM Policy, Bucket Policy, ACL, atau Block Public Access",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "S3 Glacier",
    "fullName": "Amazon S3 Glacier (storage classes)",
    "gunaUntuk": "Archive jangka panjang, jarang/tak pernah access (compliance, backup lama)",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "S3 Storage Classes",
    "fullName": "S3 Storage Classes — 7 Main Tiers + Express One Zone",
    "gunaUntuk": "Pilih S3 class ikut access pattern + retrieval speed + kos (the THE exam storage decision)",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "S3 Lifecycle",
    "fullName": "S3 Lifecycle Management",
    "gunaUntuk": "Automatically transition objects to cheaper storage classes + expire old objects",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "S3 CORS",
    "fullName": "S3 Cross-Origin Resource Sharing (CORS)",
    "gunaUntuk": "Allow web apps on one domain to access S3 resources on a different domain",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "S3 Pre-Signed URL",
    "fullName": "S3 Pre-Signed URLs",
    "gunaUntuk": "Grant temporary time-limited access to a single S3 object without sharing credentials",
    "category": "storage",
    "sectionId": "d3-storage"
  },
  {
    "shortName": "CloudFront",
    "fullName": "Amazon CloudFront",
    "gunaUntuk": "Deliver content laju via edge locations + serve private content securely",
    "category": "network",
    "sectionId": "d3-network"
  },
  {
    "shortName": "ALB",
    "fullName": "Application Load Balancer",
    "gunaUntuk": "HTTP/HTTPS path-based routing, microservices, containers",
    "category": "network",
    "sectionId": "d3-network"
  },
  {
    "shortName": "NLB",
    "fullName": "Network Load Balancer",
    "gunaUntuk": "TCP/UDP, low latency, static IP, PrivateLink endpoint service, cross-VPC with IP targets",
    "category": "network",
    "sectionId": "d3-network"
  },
  {
    "shortName": "GWLB",
    "fullName": "Gateway Load Balancer",
    "gunaUntuk": "Salur SEMUA trafik melalui fleet virtual appliance (firewall / IDS / IPS / DPI) secara terpusat & transparent",
    "category": "network",
    "sectionId": "d3-network"
  },
  {
    "shortName": "Route 53",
    "fullName": "Amazon Route 53",
    "gunaUntuk": "DNS management, domain routing",
    "category": "network",
    "sectionId": "d3-network"
  },
  {
    "shortName": "Route 53 Routing Policies",
    "fullName": "Amazon Route 53 — Routing Policies",
    "gunaUntuk": "Control how DNS traffic is routed to resources",
    "category": "network",
    "sectionId": "d3-network"
  },
  {
    "shortName": "SQS",
    "fullName": "Simple Queue Service",
    "gunaUntuk": "Decouple services, async queue",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "SNS",
    "fullName": "Simple Notification Service",
    "gunaUntuk": "Push notification ke many subscribers (fan-out)",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "Kinesis",
    "fullName": "Amazon Kinesis (Data Streams vs Firehose)",
    "gunaUntuk": "Ingest & process real-time streaming data (logs, clickstream, IoT, metrics)",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "Kinesis Video Streams",
    "fullName": "Amazon Kinesis Video Streams (KVS)",
    "gunaUntuk": "Ingest, simpan, playback & proses VIDEO/audio live dari beribu kamera/IoT device (CCTV, drone, dashcam, video doorbell) untuk ML/playback",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "API Gateway",
    "fullName": "Amazon API Gateway",
    "gunaUntuk": "Manage & expose REST, HTTP, dan WebSocket APIs",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "EventBridge",
    "fullName": "Amazon EventBridge",
    "gunaUntuk": "Serverless event bus: decouple services, schedule tasks, react to AWS service changes",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "Step Functions",
    "fullName": "AWS Step Functions",
    "gunaUntuk": "Coordinate multi-step processes with error handling, retry, and branching",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "Amazon MQ",
    "fullName": "Amazon MQ",
    "gunaUntuk": "Migrate existing ActiveMQ/RabbitMQ message brokers to AWS without code changes",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "Kinesis Data Firehose",
    "fullName": "Amazon Kinesis Data Firehose",
    "gunaUntuk": "Capture and load streaming data to S3, Redshift, OpenSearch, Splunk automatically",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "AppFlow",
    "fullName": "AWS AppFlow",
    "gunaUntuk": "Automated no-code data transfer between SaaS apps (Salesforce, ServiceNow, Slack) and AWS services",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "AppSync",
    "fullName": "AWS AppSync",
    "gunaUntuk": "Build GraphQL APIs with real-time data sync and offline capability",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "Amplify",
    "fullName": "AWS Amplify",
    "gunaUntuk": "Build and host fullstack web/mobile apps with managed backend services",
    "category": "messaging",
    "sectionId": "d3-messaging"
  },
  {
    "shortName": "CloudFormation",
    "fullName": "AWS CloudFormation",
    "gunaUntuk": "Automate infrastructure deployment, consistent environment",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "SSM",
    "fullName": "AWS Systems Manager",
    "gunaUntuk": "Manage, patch, and run commands on EC2 instances at scale",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "AWS Config",
    "fullName": "AWS Config",
    "gunaUntuk": "Track configuration changes and compliance of AWS resources",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "CodeCommit",
    "fullName": "AWS CodeCommit",
    "gunaUntuk": "Private Git repository dalam AWS ecosystem",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "CI/CD Pipeline",
    "fullName": "CodeCommit → CodeBuild → CodeDeploy → CodePipeline",
    "gunaUntuk": "Automate build, test, and deploy pipeline end-to-end",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "CloudWatch",
    "fullName": "Amazon CloudWatch",
    "gunaUntuk": "Monitor metrics, collect logs, set alarms, create dashboards for AWS resources",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "X-Ray",
    "fullName": "AWS X-Ray",
    "gunaUntuk": "Distributed tracing — debug latency and errors across microservices and serverless",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "AWS Health Dashboard",
    "fullName": "AWS Health Dashboard",
    "gunaUntuk": "See AWS service issues and scheduled changes that affect YOUR specific account/resources",
    "category": "infra",
    "sectionId": "d3-infra"
  },
  {
    "shortName": "Pilih Database",
    "fullName": "Which AWS Database? — purpose-built selector",
    "gunaUntuk": "Pilih database betul ikut shape data + access pattern (THE exam decision)",
    "category": "d3db",
    "sectionId": "d3-db"
  },
  {
    "shortName": "DocumentDB",
    "fullName": "Amazon DocumentDB",
    "gunaUntuk": "JSON document store, MongoDB-compatible workloads migrate to AWS",
    "category": "d3db",
    "sectionId": "d3-db"
  },
  {
    "shortName": "Neptune",
    "fullName": "Amazon Neptune",
    "gunaUntuk": "Social networks, fraud detection, knowledge graphs, recommendation engines",
    "category": "d3db",
    "sectionId": "d3-db"
  },
  {
    "shortName": "Keyspaces",
    "fullName": "Amazon Keyspaces",
    "gunaUntuk": "Migrate Apache Cassandra workloads, IoT telemetry, time-series data",
    "category": "d3db",
    "sectionId": "d3-db"
  },
  {
    "shortName": "Timestream",
    "fullName": "Amazon Timestream (for LiveAnalytics)",
    "gunaUntuk": "IoT sensor readings, app/DevOps metrics, apa-apa data yang ada timestamp & masuk berterusan",
    "category": "d3db",
    "sectionId": "d3-db"
  },
  {
    "shortName": "MemoryDB",
    "fullName": "Amazon MemoryDB (Valkey / Redis OSS compatible)",
    "gunaUntuk": "Primary database in-memory: microsecond reads + durability, untuk microservices yang perlu laju TAPI tak boleh hilang data",
    "category": "d3db",
    "sectionId": "d3-db"
  },
  {
    "shortName": "Redshift",
    "fullName": "Amazon Redshift",
    "gunaUntuk": "Data warehouse: complex/recurring analytics atas structured data berskala besar",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "QuickSight",
    "fullName": "Amazon QuickSight",
    "gunaUntuk": "Business intelligence dashboards, data visualization, ML-powered analytics",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "Athena",
    "fullName": "Amazon Athena",
    "gunaUntuk": "Ad-hoc SQL analysis of data in S3 without loading to a database",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "Glue",
    "fullName": "AWS Glue",
    "gunaUntuk": "ETL jobs, data catalog for data lake, prepare and transform data for analytics",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "Lake Formation",
    "fullName": "AWS Lake Formation",
    "gunaUntuk": "Fine-grained access control on data lake (row/column/cell) + simplify & accelerate creation of a secure data lake",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "EMR",
    "fullName": "Amazon EMR",
    "gunaUntuk": "Process petabyte-scale data with Spark, Hadoop, Hive, Presto — full control",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "OpenSearch",
    "fullName": "Amazon OpenSearch Service",
    "gunaUntuk": "Full-text search, real-time log/event analytics, dashboard visualisation",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "MSK",
    "fullName": "Amazon MSK",
    "gunaUntuk": "Real-time event streaming dengan Kafka API — migrate or build Kafka workloads",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "Kendra",
    "fullName": "Amazon Kendra",
    "gunaUntuk": "Intelligent enterprise search across diverse document repositories",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "Data Exchange",
    "fullName": "AWS Data Exchange",
    "gunaUntuk": "Subscribe to and access third-party datasets for analytics",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "AWS AI/ML Services",
    "fullName": "AWS AI Services — Polly, Rekognition, Lex, Comprehend, Textract, Transcribe, Translate",
    "gunaUntuk": "AI/ML services untuk audio, video, text, image analysis without training models",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "SageMaker",
    "fullName": "Amazon SageMaker",
    "gunaUntuk": "Build, train, and deploy custom ML models with full control",
    "category": "d3analytics",
    "sectionId": "d3-analytics"
  },
  {
    "shortName": "On-Demand",
    "fullName": "EC2 On-Demand Instances",
    "gunaUntuk": "Workload tak menentu, short-term, testing",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Reserved Instances",
    "fullName": "EC2 Reserved Instances (RI)",
    "gunaUntuk": "Workload steady predictable 24/7 untuk 1-3 tahun",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Spot Instances",
    "fullName": "EC2 Spot Instances",
    "gunaUntuk": "Batch jobs, fault-tolerant & stateless workloads, flexible timing",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Savings Plans",
    "fullName": "AWS Savings Plans (SP)",
    "gunaUntuk": "Steady compute spend tapi nak fleksibiliti tukar instance/region — auto-apply",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Compute Optimizer",
    "fullName": "AWS Compute Optimizer",
    "gunaUntuk": "Rightsizing recommendations for EC2, Lambda, EBS, ECS on Fargate, Auto Scaling Groups",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Trusted Advisor",
    "fullName": "AWS Trusted Advisor",
    "gunaUntuk": "Identify idle resources, cost optimization recommendations",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "AWS Budgets",
    "fullName": "AWS Budgets",
    "gunaUntuk": "Set cost/usage thresholds and get alerted before overspending",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Cost Explorer",
    "fullName": "AWS Cost Explorer",
    "gunaUntuk": "Visualise and analyse AWS costs — understand patterns, get RI/SP recommendations",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Cost Anomaly Detection",
    "fullName": "AWS Cost Anomaly Detection",
    "gunaUntuk": "Detect unusual/anomalous AWS spend patterns and alert departments automatically",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Instance Scheduler",
    "fullName": "Instance Scheduler on AWS",
    "gunaUntuk": "Auto start/stop EC2 + RDS on a fixed weekday schedule with minimal ops overhead",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Cost & Usage Report",
    "fullName": "AWS Cost and Usage Report (CUR)",
    "gunaUntuk": "Raw line-item billing paling granular untuk custom/deep cost analysis",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Cost Allocation Tags",
    "fullName": "AWS Cost Allocation Tags",
    "gunaUntuk": "Track & group kos ikut team / projek / environment",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "Consolidated Billing",
    "fullName": "AWS Organizations Consolidated Billing",
    "gunaUntuk": "Gabung billing banyak account, kongsi volume/RI/SP discount",
    "category": "pricing",
    "sectionId": "d4-pricing"
  },
  {
    "shortName": "S3 Storage Tiers",
    "fullName": "Amazon S3 Storage Classes — Cost View (the TOTAL bill, bukan storage je)",
    "gunaUntuk": "Pilih tier yang paling MURAH all-in untuk access pattern data — cost-optimization (D4 angle, bukan retrieval-speed)",
    "category": "d4store",
    "sectionId": "d4-storage"
  },
  {
    "shortName": "S3 Intelligent-Tiering",
    "fullName": "S3 Intelligent-Tiering",
    "gunaUntuk": "Data dengan access pattern tak menentu",
    "category": "d4store",
    "sectionId": "d4-storage"
  },
  {
    "shortName": "CloudFront",
    "fullName": "Amazon CloudFront",
    "gunaUntuk": "Reduce data transfer cost, cache content dekat user",
    "category": "d4net",
    "sectionId": "d4-network"
  },
  {
    "shortName": "VPC Endpoints",
    "fullName": "AWS VPC Endpoints",
    "gunaUntuk": "EC2 → S3/DynamoDB tanpa kena NAT Gateway fees",
    "category": "d4net",
    "sectionId": "d4-network"
  },
  {
    "shortName": "ElastiCache",
    "fullName": "Amazon ElastiCache",
    "gunaUntuk": "Cache frequent queries, reduce RDS cost",
    "category": "d4db",
    "sectionId": "d4-database"
  },
  {
    "shortName": "DynamoDB On-Demand",
    "fullName": "Amazon DynamoDB On-Demand",
    "gunaUntuk": "Unpredictable traffic, serverless apps",
    "category": "d4db",
    "sectionId": "d4-database"
  },
  {
    "shortName": "DR Cost Spectrum",
    "fullName": "Disaster Recovery — Cost vs RTO/RPO Spectrum",
    "gunaUntuk": "Pick the cheapest DR pattern that still meets stated RTO/RPO — exam loves budget + recovery-time trade-offs",
    "category": "d4dr",
    "sectionId": "d4-dr"
  },
  {
    "shortName": "Operational Excellence",
    "fullName": "Well-Architected: Operational Excellence",
    "gunaUntuk": "Run and monitor systems to deliver business value and continually improve processes",
    "category": "d1iam",
    "sectionId": "wa-pillars"
  },
  {
    "shortName": "Security",
    "fullName": "Well-Architected: Security",
    "gunaUntuk": "Protect information, systems, and assets via risk assessments and mitigation strategies",
    "category": "d1iam",
    "sectionId": "wa-pillars"
  },
  {
    "shortName": "Reliability",
    "fullName": "Well-Architected: Reliability",
    "gunaUntuk": "Ensure workload performs correctly and consistently, including recovery from failures",
    "category": "d1iam",
    "sectionId": "wa-pillars"
  },
  {
    "shortName": "Performance Efficiency",
    "fullName": "Well-Architected: Performance Efficiency",
    "gunaUntuk": "Use computing resources efficiently to meet requirements and maintain efficiency as demand changes",
    "category": "d1iam",
    "sectionId": "wa-pillars"
  },
  {
    "shortName": "Cost Optimization",
    "fullName": "Well-Architected: Cost Optimization",
    "gunaUntuk": "Run systems to deliver business value at the lowest price point",
    "category": "d1iam",
    "sectionId": "wa-pillars"
  },
  {
    "shortName": "Sustainability",
    "fullName": "Well-Architected: Sustainability",
    "gunaUntuk": "Minimize environmental impacts of running cloud workloads",
    "category": "d1iam",
    "sectionId": "wa-pillars"
  },
  {
    "shortName": "Litestream",
    "fullName": "Litestream (SQLite Streaming Replication)",
    "gunaUntuk": "Continuously replicate a SQLite database to S3 (or GCS / Azure Blob) for near-zero-cost backup and restore",
    "category": "tools",
    "sectionId": "extras-tools"
  }
]
