/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */
export const deepNotesLinkIndex = [
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "IAM",
    "searchBlob": "iam aws identity and access management users groups roles policies least privilege mfa principals identity federation mengurus identiti dan akses kepada perkhidmatan dan sumber aws dengan policies create iam role untuk ec2 boleh read s3 — attach role ke ec2, bukan hardcode credentials dalam code  iam & identity"
  },
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "STS",
    "searchBlob": "sts aws security token service temporary credentials assumerole cross-account federation menyediakan credentials sementara (access key, secret key, session token) untuk access aws resources developer nak test dengan aws account lain — assumerole via sts, dapat temp credentials tanpa perlu iam user baru  iam & identity"
  },
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "Directory Service",
    "searchBlob": "directory service aws directory service active directory managed microsoft ad ad connector simple ad ldap kerberos group policy on-premises ad aws directory service ada tiga pilihan: (1) aws managed microsoft ad — full ad dalam aws. (2) ad connector — proxy ke on-premises ad. (3) simple ad — samba-based, lightweight, bukan full ad.   iam & identity"
  },
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "IAM Identity Center",
    "searchBlob": "iam identity center aws iam identity center (sso) sso single sign-on multiple accounts federation saml 2.0 active directory saas integration ec2 windows fleet manager membolehkan pengguna login sekali dan access multiple aws accounts dan business applications staff login dengan corporate email (microsoft ad / okta), dapat access semua 10 aws accounts yang dibenarkan tanpa login semula  iam & identity"
  },
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "Penetration Testing",
    "searchBlob": "penetration testing aws penetration testing policy penetration testing security assessment acceptable use policy aup no prior approval 8 services prohibited activities aws membenarkan pelanggan menjalankan security assessments atau penetration tests terhadap infrastruktur aws mereka sendiri tanpa kelulusan awal untuk 8 perkhidmatan yang dibenarkan. activities yang dilarang termasuk dos/ddos simulation, port flooding, dan dns zone walking. security team nak test ec2 instances atau rds databases untuk vulnerabilities — dibenarkan tanpa minta izin aws terlebih dahulu. \"aws acceptable use policy\", \"penetration testing position\", \"security assessments on aws\" → aws allow for some resources without prior authorization (not all, not none). 8 permitted services include ec2, rds, cloudfront, aurora, api gateways, lambda, lightsail, elastic beanstalk. iam & identity"
  },
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "Cognito",
    "searchBlob": "cognito amazon cognito user pools identity pools oauth jwt federated identity mfa user auth untuk web/mobile apps. user pools (authentication) vs identity pools (aws credentials).  \"web app perlu user registration dan login\" → cognito user pools. \"mobile app user perlu access s3 directly\" → identity pool untuk temp aws credentials. iam & identity"
  },
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "RAM",
    "searchBlob": "ram aws resource access manager cross-account sharing shared subnets transit gateway sharing no resource duplication aws organizations centralized resources membenarkan perkongsian resources aws merentasi akaun tanpa pendua.  \"company ada 10 aws accounts, semua perlu access sama subnet\" → aws ram share the subnet. bukan vpc peering untuk ni. iam & identity"
  },
  {
    "sectionId": "d1-iam",
    "sectionTitle": "IAM & Identity",
    "sectionIcon": "🔑",
    "shortName": "AWS Organizations",
    "searchBlob": "aws organizations aws organizations + control tower + scps multi-account scps guardrails control tower management account ou management account exemption scp cannot grant s3 block public access scp mengurus pelbagai aws accounts dalam satu organisasi dengan service control policies (scps) sebagai guardrails prevent semua dev accounts dari disable cloudtrail — scp: deny cloudtrail:stoplogging. control tower automate setup multi-account environment  iam & identity"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "Security Groups",
    "searchBlob": "security groups vpc security groups stateful instance-level allow only custom sg default inbound denied outbound allowed mengawal inbound dan outbound traffic pada peringkat ec2 secara stateful. custom sg baru: tiada inbound rules (semua inbound ditolak secara implicit), ada satu default outbound rule yang allow semua traffic ke 0.0.0.0/0. default sg (yang auto-create bersama vpc): ada inbound allow dari dalam group yang sama. web server sg: allow port 443 dari 0.0.0.0/0. db sg: allow port 3306 dari web-sg je — db hanya boleh diakses dari web servers, bukan dari internet. exam: \"new custom sg, no rules — what is default state?\" → inbound: no rules = all denied. outbound: default rule = all allowed to 0.0.0.0/0. jangan confuse dengan default sg (berbeza). network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "NACLs",
    "searchBlob": "nacls network access control lists stateless subnet-level allow & deny numbered rules explicit both ways mengawal traffic masuk dan keluar subnet secara stateless — kena ada rule eksplisit untuk inbound dan outbound block ip range 192.168.1.0/24 dari masuk subnet — tambah deny rule dalam nacl (security groups tak boleh explicitly deny)  network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "WAF",
    "searchBlob": "waf aws web application firewall layer 7 sql injection xss rate limiting managed rules alb cloudfront uri-specific rate-based rule targeted throttling menapis requests http/https berbahaya sebelum sampai ke aplikasi dengan rules dan managed rule groups api kena sql injection attack — deploy waf dengan aws managed rules kat alb atau cloudfront. boleh rate limit 1000 req/ip per minit  network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "AWS Shield",
    "searchBlob": "aws shield aws shield standard & advanced ddos layer 3/4 shield standard shield advanced drt always-on shield standard free shield advanced paid custom mitigation real-time visibility melindungi dari serangan ddos — standard free untuk semua, advanced untuk protection 24/7 + ddos response team website kena volumetric ddos — shield standard protect automatically. enterprise nak protection + cost protection + drt = shield advanced  network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "Network Firewall",
    "searchBlob": "network firewall aws network firewall deep packet inspection stateful vpc-level intrusion prevention domain filtering menyediakan firewall managed untuk inspect dan filter traffic dalam vpc dengan stateful rules dan intrusion prevention company policy semua outbound traffic kena inspect untuk block malicious domains — deploy network firewall kat centralized vpc, route semua traffic melaluinya  network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "GuardDuty",
    "searchBlob": "guardduty amazon guardduty threat detection ml cloudtrail logs vpc flow logs no agents findings s3 protection management events data events object-level api pengesanan ancaman menggunakan ml pada cloudtrail, vpc flow logs, dns logs.  \"ec2 buat unusual api calls ke cryptocurrency mining\" → guardduty detect and alert. tak perlu install agents. network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "Detective",
    "searchBlob": "detective amazon detective security investigation forensics guardduty findings root cause behavior graph post-incident amazon detective automatically collects log data (cloudtrail, vpc flow logs, guardduty findings) dan guna ml/graph analysis untuk visualize security investigations. bagi timeline, entity relationships, dan root cause analysis.  \"guardduty flagged suspicious ec2 activity — siasatan lanjut untuk faham scope dan root cause\" → amazon detective. network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "Inspector",
    "searchBlob": "inspector amazon inspector vulnerability scanning cve ec2 ecr automated security findings pengimbasan kelemahan automatik untuk ec2 dan container images.  \"audit ec2 instances untuk known cves dan security misconfigurations\" → amazon inspector. bukan guardduty (yang untuk active threats). network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "Macie",
    "searchBlob": "macie amazon macie pii detection sensitive data s3 ml-based data privacy gdpr data discovery policy findings macie adalah data security service yang guna machine learning dan pattern matching untuk discover sensitive data dalam s3. ia maintain inventory semua s3 buckets, monitor access control, dan alert bila bucket jadi publicly accessible atau ada sensitive data terdetect.  \"audit s3 buckets untuk cari data sensitif yang ter-upload secara tak sengaja\" → amazon macie. keyword: pii, sensitive data, s3 data discovery. network security"
  },
  {
    "sectionId": "d1-netsec",
    "sectionTitle": "Network Security",
    "sectionIcon": "🛡️",
    "shortName": "Penetration Testing",
    "searchBlob": "penetration testing aws penetration testing policy penetration testing pentest security assessment aup acceptable use policy no prior approval 8 services aws membenarkan customers jalankan security assessments dan penetration tests terhadap aws infrastructure mereka tanpa kelulusan awal untuk 8 services: ec2, rds, cloudfront, aurora, api gateway, lambda, lightsail, elastic beanstalk. aktiviti yang dilarang: dos/ddos simulation, dns zone walking, port/protocol/request flooding.  \"what is aws position on penetration testing?\" → aws allow pentest on some resources without prior authorization. bukan semua resources, bukan tiada langsung — 8 services spesifik sahaja. network security"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "KMS",
    "searchBlob": "kms aws key management service encryption at rest cmk key rotation sse-kms envelope encryption cloudtrail audit asymmetric keys digital signing multi-region keys aws:sourcevpce mencipta dan mengurus cryptographic keys untuk encrypt/decrypt data di pelbagai aws services encrypt s3, rds, ebs — enable sse-kms. semua penggunaan key di-audit dalam cloudtrail. kms key rotation auto setahun sekali  data protection"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "Secrets Manager",
    "searchBlob": "secrets manager aws secrets manager auto-rotation credentials api keys no hardcoded secrets lambda integration menyimpan, mendapatkan semula dan memutar rahsia secara automatik tanpa perlu update aplikasi lambda function perlu db password — jangan letak dalam env var atau code. store dalam secrets manager, lambda retrieve masa runtime. auto-rotate setiap 30 hari  data protection"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "S3 Object Lock",
    "searchBlob": "s3 object lock amazon s3 object lock worm compliance retention period governance mode compliance mode legal hold menghalang objek s3 dari dihapuskan atau diubah suai dalam tempoh tertentu untuk pematuhan kawal selia financial records kena simpan 7 tahun tak boleh diubah — enable object lock compliance mode. governance mode untuk internal policy yang admin boleh override  data protection"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "S3 Glacier Vault",
    "searchBlob": "s3 glacier vault amazon s3 glacier vault lock & access policy vault lock vault access policy worm compliance immutable retention glacier archive dua policies berbeza: (1) vault lock policy = immutable selepas locked, enforce compliance controls (worm, retention). cannot be changed. (2) vault access policy = mutable, untuk access control (siapa boleh access). untuk compliance = vault lock.   data protection"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "Amazon Redshift",
    "searchBlob": "amazon redshift amazon redshift — encryption & datashare redshift kms encryption at rest ssl tls in transit aes-256 data warehouse datashare cross-account analytics no etl aqua query accelerator ra3 redshift menyimpan data secara terenkripsi menggunakan kms (aes-256) untuk data at rest. ssl/tls encrypt data in transit antara client dan cluster. redshift tidak guna ebs — ia manage storage sendiri. redshift datashare membenarkan cross-account data sharing tanpa etl atau data duplication.  \"encrypt unencrypted redshift data at rest\" → enable kms. at rest ≠ in transit. moving cluster to private subnet = network security, bukan encryption. data protection"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "CloudTrail",
    "searchBlob": "cloudtrail aws cloudtrail api audit who did what compliance forensics account activity 90-day retention cloudtrail lake sql query long-term retention 7 years management events data events control plane data plane s3 object-level lambda invocations multi-region trail insight events merekod setiap api call dalam aws account: siapa buat, bila, dari mana, apa hasilnya. default simpan 90 hari. boleh hantar ke s3 untuk long-term retention. security team nak tau siapa delete s3 bucket semalam — cloudtrail log ada: user, timestamp, source ip, action. \"who deleted this resource?\", \"compliance audit log of all api activity\" → cloudtrail. bukan cloudwatch (yang untuk metrics/logs dari apps). cloudtrail = who did what. cloudwatch = what is happening now. data protection"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "ACM",
    "searchBlob": "acm aws certificate manager ssl tls https free certificate auto-renewal alb cloudfront api gateway dns validation email validation pending validation menyediakan, mengurus dan auto-renew ssl/tls certificates secara percuma. attach terus ke alb, cloudfront, atau api gateway. cert tidak boleh di-export dari acm untuk install sendiri dalam ec2.  \"website perlu https\" → request acm cert, attach ke alb atau cloudfront (free). ingat: acm certs tak boleh export untuk pakai dalam ec2 sendiri — untuk tu kena beli cert luar. data protection"
  },
  {
    "sectionId": "d1-data",
    "sectionTitle": "Data Protection",
    "sectionIcon": "🔐",
    "shortName": "CloudHSM",
    "searchBlob": "cloudhsm aws cloudhsm dedicated hsm fips 140-2 level 3 customer control single-tenant hardware security tde oracle rds transparent data encryption ebk pbk backup hardware security module yang dedicated untuk kau sahaja — bukan shared infrastructure macam kms. kau control dan manage keys sendiri. aws tak boleh access keys kau.  \"compliance requires customer-exclusive control of encryption keys with dedicated hardware\" → cloudhsm. bukan kms (kms = shared, aws-managed). cloudhsm = dedicated hardware, kau control. kms = multi-tenant, aws managed. fips 140-2 level 3 = cloudhsm. level 2 = kms. data protection"
  },
  {
    "sectionId": "d1-connect",
    "sectionTitle": "Connectivity",
    "sectionIcon": "🔗",
    "shortName": "Direct Connect",
    "searchBlob": "direct connect aws direct connect dedicated connection private consistent latency 1gbps/10gbps no internet menyediakan sambungan jaringan peribadi yang berdedikasi antara data center on-premises dengan aws company transfer 100tb data sebulan dari on-prem ke aws — direct connect lebih murah (no internet data transfer charges), consistent latency berbanding internet  connectivity"
  },
  {
    "sectionId": "d1-connect",
    "sectionTitle": "Connectivity",
    "sectionIcon": "🔗",
    "shortName": "Site-to-Site VPN",
    "searchBlob": "site-to-site vpn aws site-to-site vpn ipsec encrypted internet-based virtual private gateway quick setup cost-effective mewujudkan sambungan vpn yang disulitkan antara on-premises network dengan aws vpc menggunakan internet sedia ada small office nak access resources dalam vpc secara selamat — setup site-to-site vpn. lebih murah dan cepat setup dari direct connect tapi latency tak konsisten  connectivity"
  },
  {
    "sectionId": "d1-connect",
    "sectionTitle": "Connectivity",
    "sectionIcon": "🔗",
    "shortName": "Client VPN",
    "searchBlob": "client vpn aws client vpn client vpn user authentication openvpn saml authorization rules per-user access remote access temporary access managed vpn endpoint yang individual users install client (openvpn-compatible) and authenticate via ad, saml, or mutual certificate auth. each user's connection is governed by authorization rules that restrict access to specific subnets.  \"small vendor team needs temporary authenticated access to specific vpc subnets, cost-efficient\" → client vpn. site-to-site vpn = entire on-premises network connects to aws (not per-user). client vpn = individual user level access. connectivity"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "VPC",
    "searchBlob": "vpc amazon virtual private cloud vpc cidr subnet public private isolated network default vpc private network vpc ialah private network terpencil dalam aws cloud. macam tailscale yang buat private overlay network antara devices kau, tapi vpc lebih fundamental — ia adalah \"tanah\" dimana resources kau dilahirkan, bukan tunnel yang menghubungkan tempat yang dah ada. kau tentukan ip range (cidr), buat subnets, configure route tables dan gateways. semua ec2, rds, lambda dalam vpc kau sendiri — orang lain tak boleh access kecuali kau explicitly benarkan. default vpc dah ada di setiap region. \"deploy web servers dengan databases yang tak boleh diakses dari internet\" → ec2 dalam public subnet, rds dalam private subnet, dalam satu vpc. vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "CIDR & Subnets",
    "searchBlob": "cidr & subnets ip addressing & subnet calculator cidr subnet mask ip addressing /24 /26 /27 5 reserved ips usable hosts cidr (classless inter-domain routing) tentukan berapa banyak ip dalam sesebuah network. format: <network address>/<prefix length>, contoh 172.31.0.0/16.\n\nnombor ip (e.g. 172.31.0.0) — kau yang pilih masa create vpc, dari rfc 1918 private ranges:\n• 10.0.0.0/8 — besar, enterprise\n• 172.16.0.0/12 → 172.16–31.x.x — aws default vpc guna 172.31.0.0/16\n• 192.168.0.0/16 — rumah/pejabat kecil\nranges ni tak boleh route kat internet — private sahaja, sebab tu ec2 private subnet pakai ip macam ni.\n\nnombor selepas slash (/16, /24) = prefix length = berapa bits \"dikunci\" sebagai network. ipv4 ada 32 bits total. baki bits = hosts.\n• /16 → 16 bits kunci, 16 bits bebas → 2^16 = 65,536 ips\n• /24 → 24 bits kunci, 8 bits bebas → 2^8 = 256 ips\n• /25 → 25 bits kunci, 7 bits bebas → 2^7 = 128 ips\n\naws reserve 5 ips setiap subnet: .0 network, .1 vpc router, .2 dns, .3 future, .255 broadcast. 192.168.0.0/26 → 32−26=6 bits, 2^6=64 ips, tolak 5 = 59 usable. vpc /16 boleh dibahagi kepada banyak subnets /24 atau /26. \"exam soal berapa usable ips dalam /27?\" → 32 total, tolak 5 = 27 usable. aws always reserves 5 ips per subnet. vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "Internet Gateway",
    "searchBlob": "internet gateway vpc internet gateway (igw) igw internet gateway public subnet bidirectional free 0.0.0.0/0 igw enable komunikasi dua arah antara vpc dan internet. highly available, horizontally scaled, free. satu vpc = satu igw sahaja. sebuah subnet baru jadi \"public\" bila ada 3 syarat: (1) igw attached ke vpc, (2) route table ada 0.0.0.0/0 → igw, (3) ec2 ada public/elastic ip. web server ec2 dalam public subnet — route table ada 0.0.0.0/0 → igw-xxx. ec2 dapat public ip, users dari internet boleh reach web server. \"public subnet boleh access internet\" → internet gateway. route table mesti ada 0.0.0.0/0 → igw untuk subnet jadi public. vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "NAT Gateway",
    "searchBlob": "nat gateway network address translation gateway nat outbound only private subnet elastic ip paid no inbound bastion host cross-az cost per-az nat gateway data transfer charges nat gw allow instances dalam private subnet buat outbound connection ke internet (download packages, call external apis) tanpa exposed kepada inbound connections. nat gw duduk dalam public subnet (bukan private!), ada elastic ip. private subnet route: 0.0.0.0/0 → nat gw. rds dalam private subnet perlu download security patches. traffic: rds → nat gw (public subnet) → igw → internet. internet tak boleh initiate connection masuk ke rds. \"private subnet ec2 perlu access internet tapi tak nak exposed\" → nat gateway. letak nat gw dalam public subnet, route private subnet 0.0.0.0/0 → nat gw. vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "Route Tables",
    "searchBlob": "route tables vpc route tables route table routing 0.0.0.0/0 local route subnet association main route table setiap subnet mesti associate dengan satu route table. route table ada rules yang tentukan ke mana traffic pergi. tanpa route yang betul, internet tak boleh reach walaupun ada igw. main route table (default) dan custom route tables boleh ada dalam satu vpc. public rt: 172.16.0.0/16 → local, 0.0.0.0/0 → igw. private rt: 172.16.0.0/16 → local, 0.0.0.0/0 → nat-gw. \"subnet tak dapat access internet walaupun ada igw\" → check route table! ada 0.0.0.0/0 → igw? subnet dah associate dengan route table tu? vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "SG vs NACL",
    "searchBlob": "sg vs nacl security groups vs network acls — defence layers sg nacl stateful stateless instance-level subnet-level deny defense-in-depth sg dan nacl bekerja bersama sebagai firewall berlapis. sg (stateful) bekerja pada peringkat ec2 — ingat connections, reply auto dibenarkan, allow-only rules. nacl (stateless) bekerja pada peringkat subnet — check tiap packet, perlu explicit rules untuk inbound dan outbound, boleh deny ips.  \"block specific ip range\" → nacl deny rule (sg cannot deny). \"allow web servers talk to db on port 3306 only\" → security group. best practice: guna kedua-dua untuk defense-in-depth. vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "VPC Peering",
    "searchBlob": "vpc peering vpc peering connection vpc peering cross-account cross-region non-transitive no ip overlap private routing vpc peering allow dua vpc communicate menggunakan private ips seolah-olah dalam network yang sama. non-transitive — kalau a↔b dan b↔c, a tidak boleh reach c secara automatik. kena buat a↔c peering berasingan. production vpc (172.16.0.0/16) peer dengan shared services vpc (10.0.0.0/16) — team boleh access shared tools secara private. \"connect dua vpc\" → vpc peering. ingat: ip ranges tak boleh overlap! non-transitive — a reach c kena buat a↔c peering sendiri. 3+ vpcs all-to-all = guna transit gateway. vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "Transit Gateway",
    "searchBlob": "transit gateway aws transit gateway transit gateway hub transitive routing many vpcs replace peering mesh on-premises cross-account ecmp vpn throughput multiple tunnels aggregate bandwidth tgw bertindak sebagai network transit hub yang boleh connect ribuan vpcs, vpns, dan direct connect. menggantikan peering mesh yang kompleks. transitive — vpc a boleh reach vpc c melalui tgw tanpa a↔c peering. tanpa tgw, 10 vpcs = n*(n-1)/2 = 45 peering connections. company ada 10 vpcs dari pelbagai teams + 2 on-premises data centers → satu tgw connect semua. kos naik tapi operationally jauh lebih simple. \"many vpcs perlu communicate dengan satu sama lain\" → transit gateway. \"hanya 2 vpcs\" → vpc peering (simpler, lebih murah). tgw = transitive, vpc peering = non-transitive. vpc & networking"
  },
  {
    "sectionId": "d1-vpc",
    "sectionTitle": "VPC & Networking",
    "sectionIcon": "🏘️",
    "shortName": "VPC Endpoints",
    "searchBlob": "vpc endpoints vpc endpoints (gateway & interface) vpc endpoint gateway endpoint interface endpoint privatelink s3 dynamodb no internet free dua jenis: gateway endpoint (s3 + dynamodb, free, guna route table) dan interface endpoint (services lain via privatelink, ada eni dalam subnet, berbayar). traffic tak keluar ke internet langsung — lebih selamat dan murah (jimat nat gw data fees). ec2 private subnet banyak upload ke s3. tanpa endpoint: bayar nat gw per gb. dengan s3 gateway endpoint (free): traffic terus dalam aws network. \"access s3/dynamodb dari private subnet tanpa internet\" → gateway vpc endpoint (free). \"access ecr, ssm, atau services lain privately\" → interface endpoint (privatelink). vpc & networking"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "Auto Scaling Groups",
    "searchBlob": "auto scaling groups amazon ec2 auto scaling horizontal scaling scale out/in launch template scaling policies desired capacity min/max oldestlaunchtemplate termination policy ami rollout menambah atau mengurangkan bilangan ec2 instances secara automatik berdasarkan policies, schedules, atau metrics  e-commerce traffic spike masa sale event — asg scale out bila cpu >70%, tambah ec2 instances automatik. bila traffic turun, scale in untuk jimat kos. set minimum=2 untuk high availability. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "RDS Multi-AZ",
    "searchBlob": "rds multi-az amazon rds multi-az deployment automatic failover standby different az sync replication same endpoint ha only automated backups manual snapshot point-in-time restore retention period menyimpan satu salinan database standby dalam availability zone berbeza yang akan take over secara automatik jika primary fail  production rds kat az-1 fail — automatic failover ke standby kat az-2 dalam 1-2 minit. same connection endpoint, app tak perlu tukar config. bukan untuk scale reads — guna read replicas untuk tu. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "RDS Read Replicas",
    "searchBlob": "rds read replicas amazon rds read replicas read scaling async replication cross-region up to 15 replicas read-only multi-region promote to master mencipta salinan database read-only untuk mengagihkan beban queries baca. async replication dari primary. boleh cross-region — master kat frankfurt, replicas kat us, singapore, tokyo untuk serve local users laju. up to 15 read replicas. boleh promoted to master untuk dr. multinational company: master db kat eu-frankfurt, cross-region read replicas kat us, ap, sa — local users baca dari nearest replica tanpa hantar semua traffic ke frankfurt. multi-region database design → rds cross-region read replicas. reporting queries slow down production → create read replica in same/different region, point reporting app ke replica. ingat: multi-az = same region ha (failover). read replicas = read scaling + cross-region reads. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "RDS Proxy",
    "searchBlob": "rds proxy amazon rds proxy connection pooling too many connections lambda scaling idle connections connection multiplexing rds proxy duduk antara application dan rds, multiplex connections. bila lambda scale up kepada 1000 instances, rds proxy pool connections — rds hanya nampak bilangan connections yang manageable. mengatasi \"too many connections\" errors.  \"lambda functions causing too many rds connections\" → rds proxy. \"idle connections from auto scaling ec2\" → rds proxy. read replicas = read scaling. multi-az = ha. rds proxy = connection management. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "Global Accelerator",
    "searchBlob": "global accelerator aws global accelerator global routing aws backbone anycast static ip tcp/udp failover <30s two static ips ip caching iot hipaa menggunakan aws global network untuk route traffic ke endpoint yang paling dekat dan sihat, bukan melalui internet awam  app dengan users dari us dan asia — global accelerator route via aws backbone (bukan public internet), lagi laju. kalau satu region fail, auto-failover ke region lain dalam <30 saat. beza dengan cloudfront: ga untuk tcp/udp apps, bukan static content caching. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "Aurora",
    "searchBlob": "aurora amazon aurora mysql compatible postgresql compatible 6 copies 3 azs auto storage 256 tib fast failover 15 read replicas global database cross-region dr rto 1 min rpo 1s aurora simpan 6 salinan data merentasi 3 azs secara automatik. storage auto-grow hingga 256 tib. up to 15 read replicas dengan lag <10ms. failover automatik dalam <30 saat. replace rds mysql production — aurora bagi ha automatik, 6 copies, failover <30s, storage auto-scale, tanpa manage sendiri. \"high availability relational db, auto-failover, multiple copies\" → aurora. bukan rds multi-az (aurora lebih canggih: 6 copies vs 1 standby, failover 30s vs 1-2 minit). aurora serverless untuk unpredictable/intermittent workloads. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "Aurora Serverless",
    "searchBlob": "aurora serverless amazon aurora serverless scale to zero acu pay per second intermittent dev/test auto-pause variable traffic v1 vs v2 0.5 acu increments no connection drops aurora serverless v2 auto-scale capacity dalam fractions of seconds dari minimum hingga ratusan acus, dalam increments 0.5 acu. boleh scale to near-zero (auto-pause/resume) bila idle.  \"dev/test database hanya pakai waktu office hours\", \"app traffic sangat unpredictable, nak zero db cost masa idle\" → aurora serverless. keywords: intermittent, variable traffic, dev/test, scale to zero. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "DynamoDB",
    "searchBlob": "dynamodb amazon dynamodb nosql key-value serverless millisecond latency dax global tables streams auto-scale partition key lsi gsi secondary index provisioned on-demand hot partition item collection hash attribute range attribute nested attributes fully managed nosql database. auto-scale, no servers. dynamodb streams capture changes untuk event-driven patterns. dax (dynamodb accelerator) untuk microsecond reads. global tables untuk multi-region active-active. shopping cart, user sessions, real-time leaderboards, gaming scores — workloads yang perlu high throughput, low latency, dan serverless. \"serverless nosql millisecond latency at any scale\" → dynamodb. \"microsecond reads for dynamodb\" → dax. \"multi-region active-active database\" → dynamodb global tables. \"capture dynamodb changes → trigger lambda\" → dynamodb streams. high availability & scaling"
  },
  {
    "sectionId": "d2-ha",
    "sectionTitle": "High Availability & Scaling",
    "sectionIcon": "⚡",
    "shortName": "DAX",
    "searchBlob": "dax amazon dynamodb accelerator (dax) dynamodb accelerator microsecond latency in-memory cache read caching drop-in compatible fully managed, highly available in-memory cache khusus untuk dynamodb. drop-in compatible — tak perlu tukar application logic, cuma point ke dax endpoint. hanya cache read operations (getitem, query, scan).  \"dynamodb read latency perlu microseconds, bukan milliseconds\" → dax. \"cache untuk rds/aurora\" → elasticache, bukan dax (dax khusus dynamodb sahaja). high availability & scaling"
  },
  {
    "sectionId": "d2-dr",
    "sectionTitle": "Disaster Recovery Patterns",
    "sectionIcon": "🔄",
    "shortName": "Backup & Restore",
    "searchBlob": "backup & restore dr pattern: backup & restore rpo: hours/days rto: hours lowest cost no standby infra s3/glacier backup strategi dr paling asas — backup data ke s3/glacier, restore bila diperlukan. tiada infrastruktur standby di dr region  non-critical archival system — backup snapshots ke s3/glacier regularly. rpo: hours/days. rto: hours. paling murah tapi paling lambat recover. guna bila downtime beberapa jam boleh diterima. disaster recovery patterns"
  },
  {
    "sectionId": "d2-dr",
    "sectionTitle": "Disaster Recovery Patterns",
    "sectionIcon": "🔄",
    "shortName": "Pilot Light",
    "searchBlob": "pilot light dr pattern: pilot light rpo: minutes rto: minutes-hours core db running app servers off medium cost hanya core components (database) yang running kat dr region scaled down. app servers dilancarkan hanya bila disaster berlaku  core db replicated ke dr region (running minimal). app servers off. disaster berlaku — turn on app servers, scale up, point dns ke dr. rpo: minutes, rto: minutes to hours. lebih murah dari warm standby. disaster recovery patterns"
  },
  {
    "sectionId": "d2-dr",
    "sectionTitle": "Disaster Recovery Patterns",
    "sectionIcon": "🔄",
    "shortName": "Warm Standby",
    "searchBlob": "warm standby dr pattern: warm standby rpo: seconds/minutes rto: minutes scaled-down active quick scale up higher cost versi scaled-down penuh dari aplikasi running di dr region. boleh handle traffic pada kapasiti rendah, scale up bila failover diperlukan  dr region running dengan 2 ec2 (vs 20 in prod). disaster — scale up asg, route 53 failover ke dr. rpo: seconds/minutes, rto: minutes. lebih mahal dari pilot light tapi lagi cepat recover. disaster recovery patterns"
  },
  {
    "sectionId": "d2-dr",
    "sectionTitle": "Disaster Recovery Patterns",
    "sectionIcon": "🔄",
    "shortName": "Multi-Site Active/Active",
    "searchBlob": "multi-site active/active dr pattern: multi-site active/active rpo: near-zero rto: seconds full capacity both highest cost mission-critical zero downtime kedua-dua regions running full capacity serentak dengan traffic diagihkan. tiada downtime bila satu region fail  banking app yang tak boleh ada downtime — full production environment kat dua regions. route 53 weighted routing 50/50. satu region fail → 100% traffic ke region sihat automatik. rpo: near-zero, rto: seconds. paling mahal tapi paling reliable. disaster recovery patterns"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "AWS Backup",
    "searchBlob": "aws backup aws backup centralized backup backup plans retention cross-region compliance automated efs backup backup audit manager monitoring mengurus backup terpusat untuk pelbagai aws services dengan backup policies, retention rules dan cross-region backup  company kena comply dengan policy backup 90-hari untuk semua databases — aws backup create backup plan, auto backup rds + dynamodb + efs setiap hari, retain 90 hari, auto copy ke dr region. backup & storage resilience"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "S3 Versioning & CRR",
    "searchBlob": "s3 versioning & crr s3 versioning + cross-region replication versioning crr accidental deletion cross-region replication srr point-in-time recovery versioning simpan semua versi object untuk recovery. crr auto-replicate objects ke s3 bucket dalam region lain untuk disaster recovery  developer accidentally delete important file dalam s3 — versioning enable restore previous version. crr auto-copy semua objects ke dr bucket kat region lain untuk disaster recovery. backup & storage resilience"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "EBS Snapshots",
    "searchBlob": "ebs snapshots amazon ebs snapshots incremental backup point-in-time cross-az cross-region copy ec2 recovery mencipta backup incremental ebs volume ke s3 untuk recovery atau create volumes baru dalam az atau region lain  ec2 kena ransomware, os corrupted — restore ebs dari snapshot semalam. atau copy snapshot ke region lain untuk dr, create new ec2 dari snapshot tu. backup & storage resilience"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "FSx",
    "searchBlob": "fsx amazon fsx windows smb ntfs active directory lustre hpc netapp ontap openzfs managed file system s3 integration dra datasync multi-az single-az posix empat pilihan: fsx for windows (smb/ntfs, ad integration), fsx for lustre (high-throughput hpc, s3 integration), fsx for netapp ontap (enterprise nas migration), fsx for openzfs.  \"windows apps perlu smb file share\" → fsx for windows. \"hpc workload perlu high-throughput scratch storage\" → fsx for lustre. \"migrate on-prem netapp storage ke aws\" → fsx for netapp ontap. backup & storage resilience"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "Storage Gateway",
    "searchBlob": "storage gateway aws storage gateway hybrid storage file gateway volume gateway tape gateway on-premises nfs smb iscsi tiga jenis: file gateway (nfs/smb → s3), volume gateway (iscsi block storage → ebs snapshots), tape gateway (virtual tape library → s3 glacier). on-premises apps tak perlu tahu depa sebenarnya guna cloud storage.  \"on-premises apps nak access s3 via nfs\" → file gateway. \"replace physical tape library dengan cloud backup\" → tape gateway. \"ongoing hybrid access\" → storage gateway. bukan datasync (yang untuk one-time migration). backup & storage resilience"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "DataSync",
    "searchBlob": "datasync aws datasync data migration automated transfer s3 efs fsx nfs smb hdfs one-time migration efs cross-region private network no public internet automated data transfer service yang handle scheduling, verification, dan network optimization. boleh transfer data dari nfs, smb, hdfs, atau s3-compatible storage ke aws. juga boleh replicate efs data antara regions melalui aws private network.  \"migrate 50tb dari on-premises nas ke s3\" → datasync (lebih laju dan auto-verify vs manual). datasync = migration task. storage gateway = ongoing hybrid access. ingat perbezaan ni — exam favourite! backup & storage resilience"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "DMS",
    "searchBlob": "dms aws database migration service database migration minimal downtime homogeneous heterogeneous schema conversion tool cdc replication multi-az dms replicate data dari source ke target dengan minimal downtime. source database kekal running semasa migration. schema conversion tool (sct) untuk convert schema bila beza engine.  \"migrate oracle on-prem ke aurora postgresql\" → dms + sct (heterogeneous). \"migrate mysql on-prem ke rds mysql\" → dms sahaja (homogeneous). source kekal up masa migration — near-zero downtime. backup & storage resilience"
  },
  {
    "sectionId": "d2-backup",
    "sectionTitle": "Backup & Storage Resilience",
    "sectionIcon": "🗂️",
    "shortName": "Snow Family",
    "searchBlob": "snow family aws snow family snowcone snowball edge snowmobile physical transfer petabyte edge computing offline migration opshub 210tb physical devices: snowcone (8-14tb, smallest, edge compute), snowball edge storage optimized (210tb), snowball edge compute optimized (28tb nvme, 104 vcpus). encrypt data, hantar ke aws, aws load ke s3.  \"transfer 100tb data tapi internet ambil berbulan-bulan atau bandwidth mahal\" → snow family. rule of thumb: >1 week via internet → consider snowball. petabyte-scale → order multiple snowball edge devices. backup & storage resilience"
  },
  {
    "sectionId": "d2-migrate",
    "sectionTitle": "Migration & Transfer",
    "sectionIcon": "🚚",
    "shortName": "Transfer Family",
    "searchBlob": "transfer family aws transfer family sftp ftp ftps as2 s3 backend efs backend managed ftp legacy protocol b2b file transfer no code change fully managed sftp, ftps, ftp, dan as2 endpoints. files yang di-upload terus land dalam s3 atau efs. partner companies boleh hantar files guna protokol lama tanpa kena tukar workflow mereka.  \"partner hantar files guna sftp protocol, nak store dalam s3\" → transfer family. fully managed sftp endpoint — tak perlu setup ec2 sftp server sendiri. migration & transfer"
  },
  {
    "sectionId": "d2-migrate",
    "sectionTitle": "Migration & Transfer",
    "sectionIcon": "🚚",
    "shortName": "AWS MGN",
    "searchBlob": "aws mgn aws application migration service (mgn) mgn lift-and-shift server migration ec2 migration block replication minimal downtime mgn melakukan continuous block-level replication dari source server ke aws. bila ready cutover, mgn launch ec2 instance dari replikasi latest. minimal downtime. gantikan cloudendure migration.   migration & transfer"
  },
  {
    "sectionId": "d2-migrate",
    "sectionTitle": "Migration & Transfer",
    "sectionIcon": "🚚",
    "shortName": "Migration Hub",
    "searchBlob": "migration hub aws migration hub migration tracking dashboard home region strategy recommendations orchestrator refactor spaces migration hub aggregates migration status dari pelbagai tools (dms, mgn, datasync) ke satu dashboard. kau boleh group resources into applications dan track progress setiap migration. requires setting a home region.  \"migrating 50 servers using mgn + 10 databases using dms — nak track semua dari satu tempat\" → migration hub. track progress, view status, group by application. migration & transfer"
  },
  {
    "sectionId": "d2-migrate",
    "sectionTitle": "Migration & Transfer",
    "sectionIcon": "🚚",
    "shortName": "AWS Outposts",
    "searchBlob": "aws outposts aws outposts outposts on-premises aws data residency compliance local processing hybrid aws outposts adalah physical rack aws yang dihantar dan dipasang dalam data center kau. kau boleh run ec2, rds, ecs, eks, s3 on outposts — semua dengan aws apis yang sama. data tak keluar dari premise kau.   migration & transfer"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "EC2",
    "searchBlob": "ec2 elastic compute cloud full control custom os lift and shift menyediakan kapasiti compute yang boleh diubah saiz dalam cloud host web server, run database, legacy app migration  compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "Lambda",
    "searchBlob": "lambda aws lambda serverless event-driven no server management melaksanakan kod tanpa perlu mengurus server resize image bila upload ke s3, webhook handler, scheduled tasks  compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "Elastic Beanstalk",
    "searchBlob": "elastic beanstalk aws elastic beanstalk paas deploy app developer friendly mengurus deployment, scaling dan monitoring aplikasi secara automatik deploy node.js / python app tanpa urus ec2 sendiri  compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "ECS",
    "searchBlob": "ecs elastic container service docker containers microservices task definition json template fargate ec2 launch type service mengurus dan menjalankan docker containers pada cluster run microservices dalam docker, e-commerce modules  compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "EKS",
    "searchBlob": "eks elastic kubernetes service kubernetes k8s container orchestration irsa iam roles for service accounts pod identity mengurus kubernetes cluster untuk container orchestration large-scale containerized apps yang guna k8s  compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "EKS Variants",
    "searchBlob": "eks variants eks anywhere vs eks distro vs ecs anywhere eks anywhere eks distro ecs anywhere on-premises kubernetes hybrid containers aws menyediakan pelbagai pilihan untuk run containers on-premises dengan degrees berbeza dari aws control plane dependency.   compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "EC2 User Data",
    "searchBlob": "ec2 user data ec2 user data scripts bootstrap launch script cloud-init first boot initialization 16kb limit skrip yang dijalankan sekali masa instance pertama kali launch — install software, configure app, pull code dari repo. max 16kb. guna bash script atau cloud-init. launch ec2 → user data install apache + download web app secara automatik. developer tak perlu ssh masuk untuk setup. \"ec2 fleet baru launch perlu auto-install software tanpa manual ssh\" → user data. keyword: during instance launch, bootstrap, initialization script. compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "EC2 Hibernation",
    "searchBlob": "ec2 hibernation amazon ec2 hibernation hibernation ram save ebs root fast resume in-memory state encrypted root volume hibernation saves seluruh ram contents ke ebs root volume. bila resume, os dan app state adalah exactly sama seperti sebelum — tiada re-initialization. berbeza dengan stop/start (yang lose ram state) dan reboot (yang restart os).   compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "EC2 Metadata",
    "searchBlob": "ec2 metadata ec2 instance metadata service (imds) 169.254.169.254 instance info imdsv2 hostname ip address iam role name menyediakan data tentang instance itu sendiri — ip address, instance id, iam role name, security groups, hostname. accessible dari dalam instance via http://169.254.169.254/latest/meta-data/ app dalam ec2 nak tau public ip dia sendiri atau nama iam role yang attached — query metadata endpoint tanpa perlu aws cli. \"script dalam ec2 nak retrieve iam role credentials atau instance id\" → instance metadata. bukan untuk run scripts. keyword: 169.254.169.254, info about instance. compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "Recycle Bin",
    "searchBlob": "recycle bin aws recycle bin (ami & ebs snapshots) recycle bin ami recovery ebs snapshot recovery accidental deletion retention period recycle bin menyimpan amis dan ebs snapshots yang deleted untuk tempoh yang kau tentukan (up to 1 year). kalau terhapus, boleh restore dari recycle bin. selepas retention period, permanently deleted.   compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "AWS Batch",
    "searchBlob": "aws batch aws batch aws batch batch computing managed job queue ec2 fleet replace third-party aws batch menguruskan semua infrastruktur untuk batch jobs: provision compute resources yang sesuai, schedule jobs dalam queues, monitor dan scale ec2 fleet secara automatik. menggantikan third-party batch software seperti pbs, slurm, lsf.  \"company guna third-party software untuk manage ec2 fleet untuk batch jobs, nak switch ke aws managed service\" → aws batch. compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "Fargate",
    "searchBlob": "fargate aws fargate serverless containers ecs eks no ec2 management pay per vcpu/memory zero infra fargate adalah serverless compute engine untuk ecs dan eks. kau define cpu/memory per task, fargate provision dan manage compute automatically. bayar per vcpu/memory per second.  \"run containers without managing ec2 instances\" → fargate. ecs on ec2 = kau manage ec2 (patching, scaling). ecs/eks on fargate = aws manage compute. fargate lagi mahal tapi zero infra management. compute"
  },
  {
    "sectionId": "d3-compute",
    "sectionTitle": "Compute",
    "sectionIcon": "🖥️",
    "shortName": "ECR",
    "searchBlob": "ecr amazon elastic container registry container registry docker images private registry iam integration vulnerability scanning ecs eks fully managed private container registry. integrated dengan iam untuk access control. images boleh di-scan secara automatik untuk vulnerabilities. native integration dengan ecs, eks, dan fargate.  \"store container images untuk ecs/eks deployment\" → ecr. bukan docker hub (public). ecr = private, iam-controlled, vulnerability scanning built-in. images auto-encrypt at rest dengan kms. compute"
  },
  {
    "sectionId": "d3-storage",
    "sectionTitle": "Storage",
    "sectionIcon": "💾",
    "shortName": "EBS",
    "searchBlob": "ebs elastic block store block storage single ec2 persistent disk instance store ephemeral elastic volumes resize encryption data in transit menyediakan block-level storage yang boleh di-attach kepada ec2 instance os drive untuk ec2, database storage  storage"
  },
  {
    "sectionId": "d3-storage",
    "sectionTitle": "Storage",
    "sectionIcon": "💾",
    "shortName": "EBS Volume Types",
    "searchBlob": "ebs volume types amazon ebs — volume types & multi-attach gp3 io2 st1 sc1 multi-attach provisioned iops throughput hdd ebs types ebs ada 4 jenis: ssd-backed (gp2, gp3, io1, io2) untuk iops-intensive, hdd-backed (st1, sc1) untuk throughput-intensive sequential.   storage"
  },
  {
    "sectionId": "d3-storage",
    "sectionTitle": "Storage",
    "sectionIcon": "💾",
    "shortName": "EFS",
    "searchBlob": "efs elastic file system shared storage multiple ec2 nfs general purpose max i/o provisioned throughput bursting throughput elastic throughput tls 1.2 mount helper -o tls tcp 2049 cross-vpc efs efs mount target managed nfs (network file system) that scales automatically. multiple ec2 instances across azs can mount and read/write the same file system at the same time. web content serving across 20 ec2 instances, shared config files, content management systems multi-ec2 shared storage → efs. single-instance persistent block storage → ebs. object storage (images, backups) → s3. storage"
  },
  {
    "sectionId": "d3-storage",
    "sectionTitle": "Storage",
    "sectionIcon": "💾",
    "shortName": "S3",
    "searchBlob": "s3 simple storage service object storage static website backup unlimited menyimpan dan mendapatkan semula sebarang jumlah data sebagai objects store images, videos, backups, static website hosting  storage"
  },
  {
    "sectionId": "d3-storage",
    "sectionTitle": "Storage",
    "sectionIcon": "💾",
    "shortName": "S3 Glacier",
    "searchBlob": "s3 glacier amazon s3 glacier archiving long-term storage infrequent access cold storage menyediakan arkib data jangka panjang dengan kos yang rendah store old financial records, compliance archives, log archives  storage"
  },
  {
    "sectionId": "d3-network",
    "sectionTitle": "Networking & Delivery",
    "sectionIcon": "🌐",
    "shortName": "CloudFront",
    "searchBlob": "cloudfront amazon cloudfront cdn edge location low latency static content oac origin access control lambda@edge sse-kms private s3 menghantar content kepada pengguna melalui edge locations global dengan latency rendah deliver images & videos untuk global users, static website laju  networking & delivery"
  },
  {
    "sectionId": "d3-network",
    "sectionTitle": "Networking & Delivery",
    "sectionIcon": "🌐",
    "shortName": "ALB",
    "searchBlob": "alb application load balancer path-based routing http layer 7 ip targets cross-vpc microservices mengagihkan traffic http/https berdasarkan path atau host rules (layer 7). boleh route ke instances dalam peered vpcs menggunakan ip address sebagai target — bukan hanya dalam satu vpc. myshop.com/products → service a, myshop.com/cart → service b. cross-vpc: route ke ec2 instances dalam peered vpcs guna ip targets. cross-vpc load balancing: company ada 3 vpcs peered. guna satu alb dengan ip address targets untuk route ke instances dalam semua 3 vpcs. classic load balancer (clb) tak boleh buat ni — clb hanya support instance id targets dalam same vpc. networking & delivery"
  },
  {
    "sectionId": "d3-network",
    "sectionTitle": "Networking & Delivery",
    "sectionIcon": "🌐",
    "shortName": "NLB",
    "searchBlob": "nlb network load balancer tcp udp layer 4 static ip ip targets cross-vpc low latency mengagihkan traffic tcp/udp pada layer 4 dengan latency sangat rendah. seperti alb, nlb juga boleh route ke instances dalam peered vpcs menggunakan ip address targets. gaming servers, iot, voip. cross-vpc: nlb dengan ip targets route ke instances dalam peered vpcs. nlb diperlukan bila: (1) perlukan static ip atau elastic ip untuk load balancer, (2) tcp/udp traffic bukan http, (3) extreme performance/low latency. untuk cross-vpc dengan ip targets, both nlb dan alb boleh digunakan. networking & delivery"
  },
  {
    "sectionId": "d3-network",
    "sectionTitle": "Networking & Delivery",
    "sectionIcon": "🌐",
    "shortName": "Route 53",
    "searchBlob": "route 53 amazon route 53 dns domain routing policy failover alias record cname apex domain root domain cannot cname apex mengurus dns dan mengarahkan traffic kepada endpoint yang betul point domain ke server, failover ke backup region  networking & delivery"
  },
  {
    "sectionId": "d3-network",
    "sectionTitle": "Networking & Delivery",
    "sectionIcon": "🌐",
    "shortName": "Route 53 Routing Policies",
    "searchBlob": "route 53 routing policies amazon route 53 — routing policies failover active-passive health check weighted latency-based geolocation simple evaluate target health hybrid failover two alias records on-premises secondary pelbagai routing policies untuk optimize availability, performance, failover, dan geolocation berdasarkan health checks dan rules  alb (primary) unhealthy → route 53 failover policy auto-redirect ke s3 static error page (secondary). health check detect alb down, traffic pindah ke secondary automatik. bukan cloudfront — cf cache content tapi tak handle active-passive failover. networking & delivery"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "SQS",
    "searchBlob": "sqs simple queue service queue decouple async pull-based visibility timeout fifo dlq at-least-once exactly-once long polling short polling batch operations duplicate messages queue policy cross-account sqs resource-based policy sns sqs lambda fan-out mengurus queue untuk menghantar mesej antara komponen aplikasi secara asynchronous. standard queue: at-least-once delivery, best-effort ordering. fifo queue: exactly-once, strict order. order processing queue — ec2/lambda poll sqs, proses order, delete message bila siap. spot instance terminated masa process sqs message → message tidak hilang. ia akan visible semula selepas visibility timeout expired. message hanya deleted bila consumer call deletemessage api selepas berjaya process. messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "SNS",
    "searchBlob": "sns simple notification service pub/sub push notification fan-out broadcast topic subscription filter policy message filtering sns fifo cross-account sns s3 event notification push-based pub/sub messaging service — publisher hantar message ke sns topic, semua subscribers terima serentak. subscribers boleh jadi sqs, lambda, http/s endpoints, email, sms. push-based (sns hantar ke subscriber), bukan pull-based macam sqs. s3 upload → sns topic → fan-out ke 3 sqs queues (thumbnail, metadata, archive) sekaligus. \"s3 event perlu trigger multiple downstream processes simultaneously\" → sns fan-out. s3 event notification → sns topic → multiple sqs queues. s3 hanya boleh hantar 1 event notification per prefix+suffix combination ke 1 destination — sns fan-out bypasses this limitation. messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "Kinesis",
    "searchBlob": "kinesis amazon kinesis real-time streaming data pipeline analytics memproses dan menganalisis data streaming secara real-time real-time analytics, live dashboard, clickstream data  messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "API Gateway",
    "searchBlob": "api gateway amazon api gateway rest api websocket api management throttling mapping templates backward compatibility vtl response transformation cache key cors vpc link cross-account lambda mencipta, mengurus dan mendedahkan api pada mana-mana skala frontend → api gateway → lambda → dynamodb  messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "EventBridge",
    "searchBlob": "eventbridge amazon eventbridge event bus event-driven cron schedule rule-based routing decouple saas integration cloudwatch events schema registry archive replay eventbridge pipes eventbridge scheduler eventbridge route events dari sources (ec2 state change, s3 upload, custom apps, saas) ke targets (lambda, sqs, sns, step functions) berdasarkan rules. gantikan cloudwatch events. boleh schedule events (cron/rate). ec2 instance terminate → eventbridge rule detect → trigger lambda untuk cleanup. atau schedule lambda setiap hari pukul 9pm. \"ec2 instance stop → trigger lambda automatically\" → eventbridge rule. \"schedule lambda every day at midnight\" → eventbridge scheduler. bukan sns (yang untuk broadcast notifications, bukan event routing). messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "Step Functions",
    "searchBlob": "step functions aws step functions workflow state machine orchestration retry logic error handling lambda orchestration visual workflow distributed map parallel processing visual workflow orchestration. setiap step boleh timeout, retry, atau branch ikut result. integrate dengan lambda, ecs, glue, dynamodb, dan 200+ services. state machine dengan json definition.  \"order processing: validate → charge card → notify warehouse → send email, dengan error handling pada setiap step\" → step functions. bukan lambda je (lambda tak ada built-in retry/branching logic across services). messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "Amazon MQ",
    "searchBlob": "amazon mq amazon mq activemq rabbitmq amqp mqtt lift-and-shift message broker legacy migration open protocols stomp openwire managed message broker service yang support activemq dan rabbitmq. guna amqp, mqtt, stomp, openwire protocols. untuk lift-and-shift apps yang dah guna standard protocols.  \"company ada on-premises app guna activemq, nak migrate ke aws tanpa tukar code\" → amazon mq. app baru? → guna sqs/sns (simpler, cheaper, cloud-native). amazon mq = migration/legacy. sqs = cloud-native new apps. messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "Kinesis Data Firehose",
    "searchBlob": "kinesis data firehose amazon kinesis data firehose delivery stream s3 delivery redshift opensearch no consumer code buffer transform with lambda fully managed delivery stream — tak perlu tulis consumer code. buffer data sebelum write. boleh transform inline dengan lambda. kinesis data streams = real-time processing (kena tulis consumer). firehose = delivery/loading (no consumer needed).  \"ingest clickstream data to s3 for analysis\" → kinesis firehose (automatic, no consumer code). \"real-time fraud detection processing streaming events\" → kinesis data streams (more control, write consumer). ingat perbezaan streams vs firehose! messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "AppFlow",
    "searchBlob": "appflow aws appflow appflow saas integration salesforce servicenow no-code connector data transfer bidirectional s3 redshift fully managed integration service dengan 50+ built-in saas connectors. boleh transfer data bidirectionally antara saas platforms dan s3, redshift, eventbridge. support scheduling, field mapping, filtering, and data transformation.  \"company guna salesforce dan servicenow, nak sync data ke s3 untuk analytics tanpa custom code\" → appflow. datasync = file/storage migration (nfs, smb, s3). glue = etl untuk structured data. appflow = saas api connectors. messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "AppSync",
    "searchBlob": "appsync aws appsync graphql real-time subscriptions websocket offline sync conflict resolution resolvers dynamodb multiple data sources mobile amplify fully managed graphql service. automatically generates resolvers untuk dynamodb, lambda, aurora, opensearch, http. real-time subscriptions via websocket. offline data sync untuk mobile/web apps (conflict resolution built-in). combine multiple data sources dalam single graphql query. mobile app perlukan real-time chat + offline support → appsync graphql api. frontend query satu endpoint, appsync resolve dari dynamodb + lambda + aurora sekaligus. \"mobile app needs real-time updates and offline data sync with automatic conflict resolution\" → appsync. \"rest api for microservices\" → api gateway. appsync = graphql + real-time + offline. api gateway = rest/websocket + throttling + api keys. messaging & serverless"
  },
  {
    "sectionId": "d3-messaging",
    "sectionTitle": "Messaging & Serverless",
    "sectionIcon": "📨",
    "shortName": "Amplify",
    "searchBlob": "amplify aws amplify fullstack ci/cd frontend hosting mobile react next.js cognito appsync backend-as-a-service git deploy cdn platform untuk build fullstack apps. amplify hosting = ci/cd + cdn hosting untuk ssr/ssg web apps (connect git repo, auto-deploy). amplify studio = visual builder untuk backend (auth, data, storage). backend powered by cognito (auth), appsync (api), dynamodb (data), s3 (storage). react/next.js app → connect github repo ke amplify → auto build + deploy ke cdn. add auth dengan cognito, api dengan appsync, storage dengan s3 — semua managed. \"developer team wants to quickly deploy a react web app with ci/cd, authentication, and a graphql backend without managing infrastructure\" → amplify. bukan ec2 + manual setup. bukan elastic beanstalk (yang untuk traditional server apps). messaging & serverless"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "CloudFormation",
    "searchBlob": "cloudformation aws cloudformation iac infrastructure as code template stack rollback repeatable deployment lambda-backed custom resource ami lookup dynamic parameters multi-region template mappings outputs cross-stack reference fn::importvalue cfn-init cfn-signal cfn-hup cfn-get-metadata change set drift detection stack rollback deletionpolicy nested stacks aws::cloudformation::stack modular templates mengurus dan menyediakan infrastruktur aws secara automatik menggunakan template (iac) deploy ec2 + s3 + rds sekaligus dari satu template yaml/json, replicate environment dev/staging/prod  infrastructure"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "SSM",
    "searchBlob": "ssm aws systems manager run command patch manager parameter store session manager no ssh fleet management parallel execution amazonssmmanagedinstancecore securestring kms standard tier advanced tier bastion-free secrets manager auto-rotation suite alat untuk visibility dan kawalan ke atas infrastruktur aws. run command jalankan commands pada existing instances tanpa ssh. patch manager automate os patching. parameter store simpan config/secrets. perlu patch 500 ec2 instances serentak — ssm patch manager buat semua tanpa perlu ssh satu-satu. run command untuk restart service pada semua app servers. \"manage existing instances remotely, run commands without ssh, patch fleet at scale\" → ssm run command. bukan user data (user data hanya masa launch sahaja). infrastructure"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "AWS Config",
    "searchBlob": "aws config aws config compliance audit config changes config rules resource history drift detection auto-remediation conformance packs config aggregator ssm automation managed rules custom rules memantau dan merekod konfigurasi aws resources dari masa ke masa. boleh set rules untuk enforce compliance — contoh: \"semua s3 mesti ada encryption\". bukan untuk run scripts. security team nak tau siapa yang ubah security group semalam dan bila — aws config simpan history semua config changes. \"audit config changes, check compliance, who changed what and when\" → aws config. keyword: configuration changes, compliance, audit trail, resource history. infrastructure"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "CodeCommit",
    "searchBlob": "codecommit aws codecommit git source control version control private repo iam integration managed source control service — store, version, dan collaborate on code securely dalam aws. integrate terus dengan iam untuk access control, dan native dengan codepipeline/codebuild. dev team simpan code dalam codecommit → setiap push trigger codepipeline automatically. \"source control dalam aws\", \"private git repository\", \"version control integrated dengan iam\" → codecommit. infrastructure"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "CI/CD Pipeline",
    "searchBlob": "ci/cd pipeline codecommit → codebuild → codedeploy → codepipeline ci/cd codepipeline codebuild codedeploy devops automation pipeline suite 4 perkhidmatan: codecommit (store code) → codebuild (compile + test) → codedeploy (deploy ke ec2/lambda/ecs) → codepipeline (orchestrate semua steps automatically bila ada code push). developer push ke codecommit → codepipeline detect → codebuild run tests → codedeploy push ke production ec2 — semua automatik. soalan sebut \"automate deployment\", \"ci/cd pipeline in aws\", \"deploy code automatically on push\" → codepipeline sebagai orchestrator utama. infrastructure"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "CloudWatch",
    "searchBlob": "cloudwatch amazon cloudwatch metrics logs alarms dashboards cpu monitoring custom metrics log groups vpc flow logs cloudwatch agent unified agent memory utilization detailed monitoring logs insights query logs sql-like cloudwatch metrics (cpu, network, custom app metrics). cloudwatch logs (lambda logs, ec2 app logs, vpc flow logs — set retention). cloudwatch alarms (trigger sns/auto scaling bila threshold exceeded). dashboards untuk visualize. ec2 cpu >80% → cloudwatch alarm → sns notification ke team. lambda error logs → cloudwatch logs untuk debug. \"cpu ec2 melebihi 80%, send alert\" → cloudwatch alarm. \"view logs dari lambda\" → cloudwatch logs. \"custom app metric\" → cloudwatch custom metrics. cloudwatch = metrics & logs. cloudtrail = api audit. ingat perbezaan! infrastructure"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "X-Ray",
    "searchBlob": "x-ray aws x-ray distributed tracing service map latency analysis microservices lambda tracing bottleneck debugging sqs tracing end-to-end trace bottleneck detection x-ray insights anomaly detection x-ray trace setiap request dari masuk (api gateway) hingga keluar (dynamodb), nampak berapa lama setiap component ambil masa. service map visual tunjuk bottleneck. works dengan lambda, ec2, ecs, api gateway.  \"api lambat, tak tahu kat mana bottleneck dalam 10 microservices\" → x-ray service map. trace request dari api gateway → lambda → dynamodb dan nampak mana paling slow. keywords: distributed tracing, latency, microservices debugging. infrastructure"
  },
  {
    "sectionId": "d3-infra",
    "sectionTitle": "Infrastructure",
    "sectionIcon": "🏗️",
    "shortName": "AWS Health Dashboard",
    "searchBlob": "aws health dashboard aws health dashboard service health personal health dashboard scheduled changes account events eventbridge operational issues maintenance notification dua bahagian: (1) service health dashboard — overall aws service status (public, semua org boleh tengok). (2) aws health dashboard (account-specific) — personalized view of operational issues, scheduled maintenance/changes, dan event yang affect resources dalam account kau.  \"aws region kau experiencing issue — adakah resources saya affected?\" → aws health dashboard (account view), bukan general service health page. boleh integrate dengan eventbridge untuk auto-notify (e.g. lambda → slack) bila ada event affecting your resources. infrastructure"
  },
  {
    "sectionId": "d3-db",
    "sectionTitle": "Databases",
    "sectionIcon": "🗄️",
    "shortName": "DocumentDB",
    "searchBlob": "documentdb amazon documentdb mongodb compatible document store json collections nosql mongodb migration fully managed document database yang compatible dengan mongodb apis. store data sebagai json documents dalam collections. auto-scale storage hingga 64tb.  \"migrate mongodb to aws managed service\" → documentdb. not neptune (graph). not dynamodb (key-value). documentdb = document/mongodb. keywords: json, semi-structured data, mongodb compatible, collections. databases"
  },
  {
    "sectionId": "d3-db",
    "sectionTitle": "Databases",
    "sectionIcon": "🗄️",
    "shortName": "Neptune",
    "searchBlob": "neptune amazon neptune graph database social network fraud detection gremlin sparql relationships knowledge graph fully managed graph database. optimized untuk traverse relationships dalam data. support gremlin (property graph) dan sparql (rdf). highly connected datasets.  \"social network: cari semua mutual friends antara dua users\" → neptune (graph query efficient). \"fraud detection: cari pattern dalam linked transactions\" → neptune. bukan dynamodb (key-value) atau rds (relational tabular). keywords: graph, relationships, connected data. databases"
  },
  {
    "sectionId": "d3-db",
    "sectionTitle": "Databases",
    "sectionIcon": "🗄️",
    "shortName": "Keyspaces",
    "searchBlob": "keyspaces amazon keyspaces cassandra compatible cql wide column iot telemetry time-series high write throughput fully managed cassandra-compatible database. guna cql (cassandra query language) yang sama. serverless — auto-scale, pay per request. high write throughput.  \"migrate apache cassandra to fully managed aws service\" → amazon keyspaces. same cql queries, no server management. atau iot telemetry data yang perlu high write throughput. keywords: cassandra, cql, wide column. databases"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "QuickSight",
    "searchBlob": "quicksight amazon quicksight quicksight bi dashboard forecasting ml insights visualization s3 direct spice iot analytics serverless bi service. connect directly to s3, rds, redshift, athena, or other sources. build dashboards and visualizations. ml insights feature includes anomaly detection, forecasting (seasonality, trends), and auto-narratives — no separate ml infrastructure needed.  \"executive dashboards dari iot data dalam s3 dengan forecasting, no data warehouse\" → quicksight + s3 direct. quicksight bukan untuk ad-hoc sql (→ athena), bukan untuk etl (→ glue). keywords: dashboard, forecast, trend, bi, visualization. analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "Athena",
    "searchBlob": "athena amazon athena serverless sql s3 queries pay per scan parquet orc glue catalog log analysis ad-hoc serverless interactive query service. point ke s3, tulis sql, dapat results. bayar per tb data yang di-scan. sokong csv, json, parquet, orc. pair dengan glue data catalog sebagai metadata store.  \"analyse cloudtrail logs atau alb access logs dalam s3 guna sql\" → athena. \"ad-hoc analysis tanpa setup database\" → athena. bukan redshift (yang untuk structured, recurring analytics dengan dedicated cluster). analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "Glue",
    "searchBlob": "glue aws glue etl data catalog spark serverless crawler data lake transform parquet schema discovery dynamodb schema inference glue data catalog = metadata store untuk semua data assets (s3, rds, redshift). glue etl = serverless spark jobs untuk transform data. glue crawler = auto-discover dan catalog schema dari s3/databases.  \"transform raw csv dalam s3 ke parquet format untuk athena\" → glue etl job. \"auto-catalog all data sources for data lake\" → glue crawler + data catalog. keywords: etl, data lake, data catalog, transform, spark. analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "Lake Formation",
    "searchBlob": "lake formation aws lake formation lake formation row-level security column-level cell-level fine-grained access data lake glue data catalog lake formation duduk atas s3 + glue data catalog dan enforce fine-grained permissions. glue data catalog je hanya ada table/column metadata — lake formation enforce actual access control hingga row, column, dan cell level.   analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "EMR",
    "searchBlob": "emr amazon emr hadoop spark hive presto big data cluster petabyte managed spot instances managed cluster platform untuk big data frameworks. kau choose cluster size, instance types, frameworks. spot instances untuk cost saving. lebih control dari glue — untuk complex custom jobs.  \"process petabytes of log data using custom spark jobs\" → emr. \"machine learning training on large datasets\" → emr. glue = serverless etl (simpler, less control). emr = full cluster (more control, more complex). keywords: hadoop, spark, big data cluster. analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "OpenSearch",
    "searchBlob": "opensearch amazon opensearch service search engine log analytics elasticsearch compatible kibana real-time analytics full-text search fuzzy managed opensearch (elasticsearch fork) cluster. ingestion via kinesis firehose atau lambda. visualise dengan opensearch dashboards (kibana). guna untuk search yang perlu ranking, fuzzy matching, atau aggregations.  \"e-commerce product search dengan fuzzy matching\" → opensearch. \"ingest dan search application logs real-time dengan visualisation\" → opensearch. dynamodb = exact key lookups. opensearch = full-text search. keywords: search engine, log analytics, elasticsearch. analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "MSK",
    "searchBlob": "msk amazon msk kafka managed streaming event streaming migration kafka api real-time pipeline brokers no ssh event source mapping msk serverless auto scaling storage fully managed apache kafka service. aws manage brokers, zookeeper, patching. kau guna kafka producer/consumer api yang sama. cross-az untuk ha.  \"migrate on-premises apache kafka cluster ke aws\" → amazon msk. atau streaming pipeline yang perlu kafka api compatibility. kinesis = aws-native proprietary. msk = kafka-compatible (for migration or kafka expertise teams). analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "Kendra",
    "searchBlob": "kendra amazon kendra kendra enterprise search ml search semantic search natural language query faqs unstructured documents intelligent search ml-powered enterprise search. indexes pdfs, word docs, html, emails, faqs across s3, sharepoint, confluence, databases. understands natural language queries to return precise answers, not just keyword matches.  \"enterprise wants to search across internal docs, faqs, emails, pdfs with natural language queries\" → kendra. \"e-commerce product search with spell-check/synonyms\" → opensearch (keyword search engine). kendra = understanding context + intent. opensearch = scalable keyword/full-text search. analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "Data Exchange",
    "searchBlob": "data exchange aws data exchange data exchange third-party data data marketplace data subscription market data financial data data products s3 delivery licensing marketplace for external data products. providers publish datasets (market data, financial data, regulatory filings, weather, etc.). subscribers browse, subscribe, data delivered directly to s3. handles licensing and subscription management automatically.  \"company wants to subscribe to market data, economic indicators, and regulatory filings from third-party providers and deliver them to their aws accounts for analytics\" → aws data exchange. kinesis = your own real-time data. data exchange = external third-party data products. analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "AWS AI/ML Services",
    "searchBlob": "aws ai/ml services aws ai services — polly, rekognition, lex, comprehend, textract, transcribe, translate polly transcribe lex rekognition comprehend textract translate kinesis video streams text-to-speech speech-to-text chatbot image analysis startspeechsynthesistask audiobook ocr nlp sentiment analysis entity recognition document extraction machine translation aws menyediakan pelbagai ai services ready-to-use: speech, vision, nlp, document processing.   analytics & streaming"
  },
  {
    "sectionId": "d3-analytics",
    "sectionTitle": "Analytics & Streaming",
    "sectionIcon": "📊",
    "shortName": "SageMaker",
    "searchBlob": "sagemaker amazon sagemaker sagemaker custom ml training automl autopilot hyperparameter tuning model deployment mlops feature store pipelines end-to-end managed ml platform: data prep (data wrangler, feature store), training (built-in algorithms, custom code in any framework), automl (autopilot), hpo, model registry, and deployment (real-time, serverless, batch, async endpoints). supports ci/cd via sagemaker pipelines.  \"build a churn prediction model from historical data using custom python code, tune hyperparameters, and deploy to a real-time endpoint\" → sagemaker. pre-built ai services (polly, lex, rekognition, comprehend) = no training needed, call the api. sagemaker = you control the model. analytics & streaming"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "On-Demand",
    "searchBlob": "on-demand ec2 on-demand instances no commitment flexible short-term highest cost menyediakan kapasiti compute tanpa komitmen jangka panjang pada kadar tetap per jam  startup baru launch app, tak tahu lagi berapa traffic. atau developer nak test environment kejap je — tak nak commit lama. ec2 pricing models"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "Reserved Instances",
    "searchBlob": "reserved instances ec2 reserved instances 1 or 3 year up to 72% discount predictable steady state menyediakan diskaun sehingga 72% berbanding on-demand dengan komitmen 1 atau 3 tahun  e-commerce company yang dah established, database server mesti run 24/7 sepanjang tahun. jimat besar kalau commit 1-3 tahun. ec2 pricing models"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "Spot Instances",
    "searchBlob": "spot instances ec2 spot instances up to 90% discount interruptible batch jobs fault-tolerant menggunakan kapasiti ec2 yang tidak digunakan pada harga sehingga 90% lebih murah  data science team nak process big dataset — tak kisah kalau interrupted. atau render farm untuk video yang boleh resume. jangan guna untuk critical production server. ec2 pricing models"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "Savings Plans",
    "searchBlob": "savings plans aws savings plans flexible hourly commitment up to 66% discount compute savings menawarkan diskaun sehingga 66% dengan komitmen penggunaan dalam usd/jam tanpa terikat instance type  company yang nak jimat macam reserved tapi plan nak tukar instance type atau region dalam masa terdekat. lebih flexible dari reserved instances. ec2 pricing models"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "Compute Optimizer",
    "searchBlob": "compute optimizer aws compute optimizer rightsizing ml recommendations ec2 optimization lambda optimization cost savings underutilized compute optimizer analyse historical utilization metrics (14 days) menggunakan ml untuk recommend optimal resource configurations. bagi projected cost savings, performance risk, dan comparison antara current vs recommended.  \"ec2 instances consistently underutilized, nak reduce cost without manual analysis\" → compute optimizer untuk get rightsizing recommendations. ec2 pricing models"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "Trusted Advisor",
    "searchBlob": "trusted advisor aws trusted advisor cost recommendations idle resources rightsizing underutilized service limits five categories menganalisis persekitaran aws dan memberikan cadangan untuk optimasi kos, security, dan performance  cfo tanya \"mana resources kita yang membazir?\" — trusted advisor akan highlight ec2 yang underutilized, s3 buckets tak pakai, elastic ips yang idle, dan bagi estimate savings. ec2 pricing models"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "AWS Budgets",
    "searchBlob": "aws budgets aws budgets budget alerts cost threshold sns notification usage budget forecast alert before overspend budget actions buat budget untuk kos, usage, atau reserved instance coverage. alert via email atau sns bila actual atau forecast spend melebihi threshold yang ditetapkan.  \"alert bila monthly ec2 cost nak cecah $1000\" → aws budgets. bukan cost explorer (yang untuk analysis/visualization, bukan alerting). budgets = proactive alerts. cost explorer = reactive analysis. ec2 pricing models"
  },
  {
    "sectionId": "d4-pricing",
    "sectionTitle": "EC2 Pricing Models",
    "sectionIcon": "💰",
    "shortName": "Cost Explorer",
    "searchBlob": "cost explorer aws cost explorer cost analysis spending visualization ri recommendations usage patterns rightsizing forecast hourly granularity anomaly detection interactive ui untuk analyse aws spending by service, account, tag, region. bagi ri dan savings plans recommendations. boleh forecast future costs. granular hingga hourly.  \"nak tengok mana service paling banyak cost bulan lepas\" → cost explorer. \"dapat recommendations untuk beli reserved instances\" → cost explorer. bukan trusted advisor (general recommendations). bukan budgets (alerts). cost explorer = visualization & analysis. ec2 pricing models"
  },
  {
    "sectionId": "d4-storage",
    "sectionTitle": "Storage Cost Optimization",
    "sectionIcon": "💾",
    "shortName": "S3 Storage Tiers",
    "searchBlob": "s3 storage tiers amazon s3 storage classes storage classes lifecycle policy infrequent access glacier glacier instant retrieval glacier deep archive one zone-ia min storage charge menyediakan pelbagai kelas storan dengan harga berbeza berdasarkan keperluan akses data  log files yang baru = s3 standard. log files 30 hari lepas = s3-ia. log files setahun lepas untuk compliance = s3 glacier. guna s3 lifecycle policy untuk auto-move between tiers. storage cost optimization"
  },
  {
    "sectionId": "d4-storage",
    "sectionTitle": "Storage Cost Optimization",
    "sectionIcon": "💾",
    "shortName": "S3 Intelligent-Tiering",
    "searchBlob": "s3 intelligent-tiering s3 intelligent-tiering auto-tiering unpredictable access no retrieval fees memindahkan objek secara automatik antara access tiers berdasarkan corak penggunaan  media company simpan assets — ada video yang viral tiba-tiba, ada yang tak pernah ditonton. tak boleh predict mana yang akan kena access. intelligent-tiering auto-optimize kos tanpa perlu urus manually. storage cost optimization"
  },
  {
    "sectionId": "d4-network",
    "sectionTitle": "Networking Cost Optimization",
    "sectionIcon": "🌐",
    "shortName": "CloudFront",
    "searchBlob": "cloudfront amazon cloudfront reduce data transfer edge caching cdn cost saving mengurangkan kos data transfer dengan menyimpan cache content di edge locations  website ada users dari us, europe, asia. tanpa cloudfront, setiap request kena bayar data transfer dari origin server. dengan cloudfront, content cached kat edge location dekat user — jimat kos transfer + lagi laju. networking cost optimization"
  },
  {
    "sectionId": "d4-network",
    "sectionTitle": "Networking Cost Optimization",
    "sectionIcon": "🌐",
    "shortName": "VPC Endpoints",
    "searchBlob": "vpc endpoints aws vpc endpoints no nat fees private connection s3 gateway no internet menghubungkan vpc kepada perkhidmatan aws secara terus tanpa melalui internet awam  ec2 dalam private subnet selalu upload/download dari s3. kalau guna nat gateway, kena bayar per gb. pasang vpc endpoint → traffic pergi terus dalam aws network, no nat fees, lagi jimat. networking cost optimization"
  },
  {
    "sectionId": "d4-database",
    "sectionTitle": "Database Cost Optimization",
    "sectionIcon": "🗄️",
    "shortName": "ElastiCache",
    "searchBlob": "elasticache amazon elasticache redis memcached in-memory reduce db load caching sub-millisecond leaderboards session store lazy loading write-through cache miss ttl multi-threaded persistence replication menyediakan in-memory caching untuk mengurangkan beban dan kos pada database utama  e-commerce app — product listing query kena berjuta kali sehari. tanpa cache, rds kena scale up (mahal). dengan elasticache (redis), query popular disimpan dalam memory — rds tak terlalu terbeban, kos lebih rendah. database cost optimization"
  },
  {
    "sectionId": "d4-database",
    "sectionTitle": "Database Cost Optimization",
    "sectionIcon": "🗄️",
    "shortName": "DynamoDB On-Demand",
    "searchBlob": "dynamodb on-demand amazon dynamodb on-demand nosql pay per request serverless auto-scale unpredictable traffic menyediakan kapasiti database nosql yang skala secara automatik dan dikenakan caj berdasarkan permintaan sebenar  app baru yang tak tahu lagi berapa reads/writes per second. dynamodb on-demand auto-scale dan kau bayar per request je — tak perlu provision capacity in advance. kalau traffic rendah, bayar rendah. database cost optimization"
  },
  {
    "sectionId": "wa-pillars",
    "sectionTitle": "Six Pillars",
    "sectionIcon": "🏛️",
    "shortName": "Operational Excellence",
    "searchBlob": "operational excellence well-architected: operational excellence iac automation runbooks ci/cd monitoring continuous improvement operational excellence fokus pada automation, monitoring, dan continuous improvement. key practices: iac (cloudformation), ci/cd, runbooks, post-incident reviews.   six pillars"
  },
  {
    "sectionId": "wa-pillars",
    "sectionTitle": "Six Pillars",
    "sectionIcon": "🏛️",
    "shortName": "Security",
    "searchBlob": "security well-architected: security least privilege iam encryption detective controls data protection incident response security pillar: identity and access management, detective controls, infrastructure protection, data protection, incident response. principle of least privilege.   six pillars"
  },
  {
    "sectionId": "wa-pillars",
    "sectionTitle": "Six Pillars",
    "sectionIcon": "🏛️",
    "shortName": "Reliability",
    "searchBlob": "reliability well-architected: reliability multi-az auto-recovery rto rpo disaster recovery horizontal scaling fault isolation reliability fokus pada distributed system design, recovery planning, dan scaling. multi-az, backups, auto-healing, chaos engineering.   six pillars"
  },
  {
    "sectionId": "wa-pillars",
    "sectionTitle": "Six Pillars",
    "sectionIcon": "🏛️",
    "shortName": "Performance Efficiency",
    "searchBlob": "performance efficiency well-architected: performance efficiency right-sizing serverless caching cdn global deployment benchmarking selection of right resource types/sizes, monitoring performance, making informed decisions to maintain efficiency as business needs evolve.   six pillars"
  },
  {
    "sectionId": "wa-pillars",
    "sectionTitle": "Six Pillars",
    "sectionIcon": "🏛️",
    "shortName": "Cost Optimization",
    "searchBlob": "cost optimization well-architected: cost optimization right-sizing reserved instances spot savings plans eliminate waste cost allocation tags avoid unnecessary costs, right-size resources, use appropriate pricing models (reserved, spot, savings plans), measure efficiency.   six pillars"
  },
  {
    "sectionId": "wa-pillars",
    "sectionTitle": "Six Pillars",
    "sectionIcon": "🏛️",
    "shortName": "Sustainability",
    "searchBlob": "sustainability well-architected: sustainability sustainability carbon footprint environmental impact 6th pillar serverless utilisation renewable energy 2021 sustainability pillar (ditambah 2021) fokus pada reducing carbon footprint: maximise utilisation, use efficient hardware, minimise resources provisioned, adopt serverless/managed services.   six pillars"
  },
  {
    "sectionId": "extras-tools",
    "sectionTitle": "Open-Source Database Tools",
    "sectionIcon": "🛠️",
    "shortName": "Litestream",
    "searchBlob": "litestream litestream (sqlite streaming replication) sqlite wal s3 replication sidecar open-source backup not aws native single server cheap db litestream berjalan sebagai sidecar process sebelah app kau. ia shadow-read sqlite wal (write-ahead log) dan stream setiap perubahan ke s3 secara real-time tanpa kena pause app. bila server restart atau crash, litestream restore snapshot + wal terbaru dari s3 sebelum app start. kos storage = s3 rate sahaja (~$0.023/gb). tiada managed db fee. deploy app di single ec2 atau fly.io dengan sqlite. litestream stream wal ke s3. kalau instance crash, launch baru → litestream restore dari s3 dalam beberapa saat → app up semula. zero data loss. bukan saa-c03 exam content. guna dalam real-world: small saas, indie apps, side projects yang nak avoid rds cost ($50–300+/month) tapi masih nak reliable backup. open-source database tools"
  }
] as const
