/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */
export const labsLinkIndex = [
  {
    "slug": "access-amazon-sqs-using-amazon-vpc-interface-endpoint",
    "title": "Access Amazon SQS using Amazon VPC Interface Endpoint"
  },
  {
    "slug": "access-s3-from-private-ec2-instance-using-vpc-endpoint",
    "title": "Access S3 from Private EC2 instance using VPC Endpoint"
  },
  {
    "slug": "allocating-elastic-ip-and-associating-it-to-ec2-instance",
    "title": "Allocating Elastic IP and Associating it to EC2 Instance"
  },
  {
    "slug": "amazon-cloudformation-s3-url-stack-challenge",
    "title": "Amazon CloudFormation S3 URL Stack Challenge"
  },
  {
    "slug": "amazon-rds-challenge-cloudsql-catalyst",
    "title": "Amazon RDS-CloudSQL Catalyst-Challenge"
  },
  {
    "slug": "amazon-vpc-endpoint-challenge",
    "title": "Amazon VPC Endpoint challenge"
  },
  {
    "slug": "api-gateway-creating-resources-and-methods",
    "title": "API Gateway - Creating Resources and Methods"
  },
  {
    "slug": "auditing-resource-compliance-with-aws-config",
    "title": "Auditing Resource Compliance with AWS config"
  },
  {
    "slug": "aws-vpc-nacl-lab-case-study",
    "title": "AWS VPC NACL Lab - Case study"
  },
  {
    "slug": "balance-load-across-containers-through-application-load-balancer-in-ecs",
    "title": "Balance load across containers through Application Load Balancer in ECS"
  },
  {
    "slug": "block-and-unblock-access-to-cloudfront-distribution-using-aws-waf",
    "title": "Block and Unblock access to CloudFront distribution using AWS WAF"
  },
  {
    "slug": "blocking-web-traffic-with-waf-in-aws",
    "title": "Blocking web traffic with WAF in AWS"
  },
  {
    "slug": "build-a-real-time-data-streaming-system-with-amazon-kinesis-data-stream-and-kinesis-agent",
    "title": "Build a real time data streaming system with Amazon Kinesis Data Stream and Kinesis Agent"
  },
  {
    "slug": "build-amazon-vpc-with-public-and-private-subnets-from-scratch",
    "title": "Build Amazon VPC with Public and Private Subnets (from Scratch)"
  },
  {
    "slug": "build-api-gateway-with-different-stages-using-stage-variables",
    "title": "Build API Gateway with different stages using stage variables"
  },
  {
    "slug": "build-api-gateway-with-lambda-integration",
    "title": "Build API Gateway with Lambda Integration"
  },
  {
    "slug": "build-api-gateway-with-path-parameter-and-query-string-parameter",
    "title": "Build API Gateway with path parameter and Query string parameter"
  },
  {
    "slug": "challenge-build-a-real-time-data-streaming-system-with-amazon-kinesis-data-stream-and-kinesis-agent",
    "title": "Challenge - Build a real time data streaming system with Amazon Kinesis Data Stream and Kinesis Agent"
  },
  {
    "slug": "challenge-deploying-amazon-rds-multi-az-and-read-replica-simulate-failover",
    "title": "Challenge - Deploying Amazon RDS Multi-AZ and Read Replica, Simulate Failover"
  },
  {
    "slug": "challenge-discover-sensitive-data-present-in-s3-bucket-using-amazon-macie",
    "title": "Challenge - Discover sensitive data present in S3 bucket using Amazon Macie"
  },
  {
    "slug": "challenge-how-to-encrypt-an-s3-bucket-using-aws-kms-and-monitor-the-activities-with-cloudtrail",
    "title": "Challenge - How to Encrypt an S3 bucket using AWS KMS and monitor the activities with CloudTrail"
  },
  {
    "slug": "challenge-lab-introduction-to-aws-elastic-load-balancing-challenge",
    "title": "Challenge - Introduction to AWS Elastic Load Balancing"
  },
  {
    "slug": "ami-backup-challenge-relaunch-the-backup",
    "title": "Challenge : Creating New EC2 Instance using Snapshot"
  },
  {
    "slug": "dynamodb-global-secondary-index-table-indexing",
    "title": "Challenge : DynamoDB & Global Secondary Index"
  },
  {
    "slug": "amazon-cloudfront-challenge-secure-cdn",
    "title": "Challenge : Introduction to Amazon CloudFront"
  },
  {
    "slug": "challenge-connecting-an-ec2-instance-and-a-db-instance-automatically",
    "title": "Challenge Connecting an EC2 instance and a DB instance Automatically"
  },
  {
    "slug": "challenge-amazonecsfargate-container-deployment-basics",
    "title": "Challenge Lab - Amazon Elastic Container Service using Fargate"
  },
  {
    "slug": "dynamodb-challenge-nosql-setup-with-aws",
    "title": "Challenge Lab - AWS DynamoDB NOSQL Setup"
  },
  {
    "slug": "challenge-stepfunctions-workflow-basics",
    "title": "Challenge Lab - AWS Step Functions"
  },
  {
    "slug": "challenge-master-vpc",
    "title": "Challenge Lab - Build Amazon VPC with Public and Private Subnets (from Scratch)"
  },
  {
    "slug": "challenge-lab-api-gateway-stage-variables-for-seamless-environment-management",
    "title": "Challenge Lab - Build API Gateway with different stages using stage variables"
  },
  {
    "slug": "challenge-apigatewaylambdaintegration-serverless-api-setup",
    "title": "Challenge Lab - Build API Gateway with Lambda Integration"
  },
  {
    "slug": "challenge-lab-configuring-ebs-volume-to-ecs-task",
    "title": "Challenge Lab - Configuring EBS Volume to ECS task"
  },
  {
    "slug": "challenge-vpcfortress-security-citadel",
    "title": "Challenge Lab - Configuring Layered Security in an AWS VPC"
  },
  {
    "slug": "challenge-vpc-cloudforge-infrastructure-blueprint",
    "title": "Challenge Lab - Create Virtual Private Cloud (VPC) with AWS CloudFormation"
  },
  {
    "slug": "challenge-lab-hands-on-with-ec2-instance-hibernation",
    "title": "Challenge Lab - EC2 Instance Hibernation"
  },
  {
    "slug": "challenge-lab-exporting-amazon-rds-snapshot-to-s3-for-secure-backup",
    "title": "Challenge Lab - Exporting Amazon RDS Snapshot to S3 for Secure Backup"
  },
  {
    "slug": "challenge-lab-protect-your-website-with-aws-waf",
    "title": "Challenge Lab - Implementing AWS WAF with ALB to block SQL Injection, Geo Location and Query string"
  },
  {
    "slug": "aws-lamada-challenge-serverless-flow",
    "title": "Challenge Lab - Introduction to Amazon Lambda"
  },
  {
    "slug": "challenge-efsmount-shared-storage-sync",
    "title": "Challenge Lab - Mount EFS on EC2"
  },
  {
    "slug": "challenge-lab-ec2-vpc-and-load-balancer-integration-and-debugging",
    "title": "Challenge Lab - Resolve Connectivity Issues Between VPC, EC2 Instances, and Load Balancer"
  },
  {
    "slug": "challenge-lab-configuring-and-testing-sqs-visibility-timeout-and-delivery-delay",
    "title": "Challenge Lab - Testing SQS Visibility Timeout and Message Delay in Action"
  },
  {
    "slug": "challenge-lab-enable-sticky-sessions-in-application-load-balancer",
    "title": "Challenge Lab – Enable Sticky sessions in Application Load balancer"
  },
  {
    "slug": "challenge-lab-accessing-s3-from-a-private-ec2-instance-without-internet-access",
    "title": "Challenge Lab : Access S3 from Private EC2 instance using VPC Endpoint"
  },
  {
    "slug": "challenge-lab-data-integration-and-transformation-with-aws-glue",
    "title": "Challenge Lab : Data Integration and Transformation with AWS Glue"
  },
  {
    "slug": "challenge-lab-find-vulnerabilities-on-inspector2-using-lambda-scanning",
    "title": "Challenge Lab : Find vulnerabilities on Inspector2 using Lambda scanning"
  },
  {
    "slug": "challenge-lab-automating-amazon-guardduty-setup-with-terraform",
    "title": "Challenge Lab : Introduction to Amazon GuardDuty using Terraform"
  },
  {
    "slug": "challenge-lab-setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer",
    "title": "Challenge Lab : Setting up the VPC environment, launching EC2 instances, and testing reachability using the AWS Reachability Analyzer"
  },
  {
    "slug": "challenge-lab-understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform",
    "title": "Challenge Lab : Understanding and Configuring Layered Security in an AWS VPC Using Terraform"
  },
  {
    "slug": "challenge-lab-allocating-elastic-ip-and-associating-it-to-ec2-instance",
    "title": "Challenge Lab- Allocating Elastic IP and Associating it to EC2 Instance"
  },
  {
    "slug": "challenge-lab-access-amazon-sqs-using-amazon-vpc-interface-endpoint",
    "title": "Challenge Lab: Access Amazon SQS using Amazon VPC Interface Endpoint"
  },
  {
    "slug": "challenge-lab-analyzing-expense-data-with-amazon-athena",
    "title": "Challenge Lab: Analyzing Expense Data with Amazon Athena"
  },
  {
    "slug": "challenge-apigatewayresourcesmethods-api-setup-basics",
    "title": "Challenge Lab: API Gateway - Creating Resources and Methods"
  },
  {
    "slug": "challenge-lab-building-a-dynamic-api-with-path-and-query-string-parameters",
    "title": "Challenge Lab: Building a Dynamic API with Path and Query String Parameters"
  },
  {
    "slug": "challenge-lab-cloudfront-distribution-with-ec2-s3-integration",
    "title": "Challenge Lab: CloudFront Distribution with EC2 & S3 Integration"
  },
  {
    "slug": "challenge-amazoneksclustersetup-eks-basics",
    "title": "Challenge Lab: Create a cluster in Amazon EKS and install kubectl"
  },
  {
    "slug": "challenge-lab-dynamodb-table-operations-using-aws-console-and-nosql-workbench",
    "title": "Challenge Lab: Create a DynamoDB table and perform various table operations using NoSQL Workbench"
  },
  {
    "slug": "challenge-lab-deploying-scalable-ec2-instances-using-launch-templates",
    "title": "Challenge Lab: Create and Configure Amazon EC2 Auto Scaling with Launch Templates"
  },
  {
    "slug": "challenge-lab-multi-ip-ec2-deployment-with-elastic-network-interfaces",
    "title": "Challenge Lab: Create Elastic Network Interface - Multiple IPs on an EC2"
  },
  {
    "slug": "challenge-lab-building-a-dynamic-workflow-with-aws-step-functions",
    "title": "Challenge Lab: Creating a workflow using different States with AWS Step Functions"
  },
  {
    "slug": "challenge-lab-data-protection-using-aws-key-management-service",
    "title": "Challenge Lab: Data Protection Using AWS Key Management Service"
  },
  {
    "slug": "challenge-lab-deploy-and-connect-to-a-redis-cluster-using-amazon-elasticache",
    "title": "Challenge Lab: Deploy and Connect to a Redis Cluster using Amazon ElastiCache"
  },
  {
    "slug": "challenge-apigatewaycloudwatchlogs-logging-setup",
    "title": "Challenge Lab: Enabling CloudWatch Logs in API Gateway"
  },
  {
    "slug": "challenge-lab-enable-developer-controlled-encryption-with-aws-kms-cmks",
    "title": "Challenge Lab: Encrypt S3 bucket, EBS Volume and AMI using AWS KMS"
  },
  {
    "slug": "challenge-lab-encrypt-an-amazon-rds-instance-using-snapshot-migration-and-kms",
    "title": "Challenge Lab: How to Encrypt an Unencrypted RDS DB Instance"
  },
  {
    "slug": "challenge-amazonguarddutyintroduction-threat-detection-basics",
    "title": "Challenge Lab: Introduction to Amazon GuardDuty"
  },
  {
    "slug": "challenge-lab-launch-manage-a-spot-ec2-web-server",
    "title": "Challenge Lab: Launch & Manage a Spot EC2 Web Server"
  },
  {
    "slug": "challenge-lab-migrating-ebs-volumes-from-gp2-to-gp3",
    "title": "Challenge Lab: Migrating EBS volumes from gp2 to gp3"
  },
  {
    "slug": "challenge-lab-secure-secret-management-with-aws-secrets-manager-and-ecs",
    "title": "Challenge Lab: Secure Secret Management with AWS Secrets Manager and ECS"
  },
  {
    "slug": "challenge-lab-set-up-a-free-vpn-server-using-openvpn-on-aws",
    "title": "Challenge Lab: Set Up a Free VPN Server Using OpenVPN on AWS"
  },
  {
    "slug": "challenge-lab-stream-and-store-vpc-flow-logs-using-kinesis-firehose-and-s3",
    "title": "Challenge Lab: Transfer data to S3 using Amazon Kinesis Firehose"
  },
  {
    "slug": "iam-challenge-access-control-to-usersservices",
    "title": "Challenge- IAM- Access Control to Users Services"
  },
  {
    "slug": "challenge-amazonsesintroduction-sending-emails-with-ses",
    "title": "Challenge: Amazon_SES_Introduction - Sending Emails with SES"
  },
  {
    "slug": "challenge-awsvpcnacllab-case-study-on-vpc-nacl-configuration-and-compliance-auditing",
    "title": "Challenge: AWS_VPC_NACL_Lab - Case Study on VPC, NACL Configuration, and Compliance Auditing"
  },
  {
    "slug": "challenge-s3transferacceleration-comparing-data-transfer-speeds",
    "title": "Challenge: Comparing Data Transfer Speeds with S3 Transfer Acceleration"
  },
  {
    "slug": "connect-rds-from-instance-challenge-mysql-access",
    "title": "Challenge: Connecting RDS from EC2 Instance"
  },
  {
    "slug": "challenge-apigatewayintroduction-api-basics",
    "title": "Challenge: Introduction to Amazon API Gateway"
  },
  {
    "slug": "challenge-waffirewall-web-traffic-shield",
    "title": "Challenge: WAFFirewall - Web Traffic Shield"
  },
  {
    "slug": "check-compliance-status-of-s3-bucket-using-aws-config",
    "title": "Check Compliance status of S3 Bucket using AWS Config"
  },
  {
    "slug": "cloudwatch-alarms-dashboard",
    "title": "CloudWatch Resource Monitoring — Alarms, SNS Notifications & Dashboards"
  },
  {
    "slug": "comparing-data-transfer-speeds-with-s3-transfer-acceleration",
    "title": "Comparing Data Transfer Speeds with S3 Transfer Acceleration"
  },
  {
    "slug": "configure-email-notification-on-s3-bucket-event-amazon-sns-challenge",
    "title": "Configure Email Notification on S3 Bucket Event - Amazon SNS Challenge"
  },
  {
    "slug": "configure-nat-instance-and-stream-web-logs-to-cloudwatch-using-cloudwatch-agent",
    "title": "Configure NAT Instance and Stream Web Logs to CloudWatch Using CloudWatch Agent"
  },
  {
    "slug": "configure-wordpress-website-using-aws-console-challenge",
    "title": "Configure WordPress Website Using AWS Console Challenge"
  },
  {
    "slug": "configuring-amazon-fsx-for-lustre-with-ec2-instances-for-shared-high-performance-storage-access",
    "title": "Configuring Amazon FSx for Lustre with EC2 Instances for Shared High-Performance Storage Access"
  },
  {
    "slug": "configuring-ebs-volume-to-ecs-task",
    "title": "Configuring EBS Volume to ECS task"
  },
  {
    "slug": "launch-amazon-ec2-instance-launch-amazon-rds-instance-connecting-rds-from-ec2-instance",
    "title": "Connecting RDS from EC2 Instance"
  },
  {
    "slug": "create-a-cluster-in-amazon-eks-and-install-kubectl",
    "title": "Create a cluster in Amazon EKS and install kubectl"
  },
  {
    "slug": "create-a-docker-container-using-dockerfile-and-store-the-image-in-ecr",
    "title": "Create a Docker container using Dockerfile and store the image in ECR"
  },
  {
    "slug": "create-a-dynamodb-table-and-perform-various-table-operations-using-nosql-workbench",
    "title": "Create a DynamoDB table and perform various table operations using NoSQL Workbench"
  },
  {
    "slug": "create-a-sample-web-application-and-monitor-it-in-aws-x-ray",
    "title": "Create a sample Web Application and monitor it in AWS X-Ray"
  },
  {
    "slug": "create-and-configure-amazon-ec2-auto-scaling-with-launch-templates",
    "title": "Create and Configure Amazon EC2 Auto Scaling with Launch Templates"
  },
  {
    "slug": "create-elastic-network-interface-multiple-ips-on-an-ec2",
    "title": "Create Elastic Network Interface - Multiple IPs on an EC2"
  },
  {
    "slug": "create-redis-cluster-using-elasticache",
    "title": "Create Redis cluster using ElastiCache"
  },
  {
    "slug": "create-vpc-environment-challenge",
    "title": "Create VPC Environment challenge"
  },
  {
    "slug": "creating-a-cloudwatch-dashboard-for-ec2-instance-challenge",
    "title": "Creating a CloudWatch Dashboard and a Widget Challenge"
  },
  {
    "slug": "creating-a-user-pool-in-aws-cognito",
    "title": "Creating a User Pool in AWS Cognito"
  },
  {
    "slug": "creating-a-user-pool-in-aws-cognito-using-terraform",
    "title": "Creating a User Pool in AWS Cognito Using Terraform"
  },
  {
    "slug": "creating-a-workflow-using-different-states-with-aws-step-functions",
    "title": "Creating a workflow using different States with AWS Step Functions"
  },
  {
    "slug": "creating-an-application-load-balancer-and-auto-scaling-group-in-aws",
    "title": "Creating an Application Load Balancer and Auto Scaling Group in AWS"
  },
  {
    "slug": "creating-an-application-load-balancer-from-aws-cli",
    "title": "Creating an Application Load Balancer from AWS CLI"
  },
  {
    "slug": "creating-an-s3-lifecycle-policy",
    "title": "Creating an S3 Lifecycle Policy"
  },
  {
    "slug": "creating-and-configuring-a-network-load-balancer-in-aws",
    "title": "Creating and configuring a network load balancer in AWS"
  },
  {
    "slug": "creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket",
    "title": "Creating and Subscribing to SNS Topics, Adding SNS event for S3 bucket"
  },
  {
    "slug": "creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket-challenge-bucket-monitor",
    "title": "Creating and Subscribing to SNS Topics, Adding SNS event for S3 bucket Challenge - Bucket Monitor"
  },
  {
    "slug": "creating-aws-vpc-flow-logs-and-generating-traffic",
    "title": "Creating AWS VPC Flow Logs and Generating Traffic"
  },
  {
    "slug": "creating-events-in-cloudwatch-challenge",
    "title": "Creating Events in CloudWatch Challenge"
  },
  {
    "slug": "creating-nat-gateways-in-aws",
    "title": "Creating NAT Gateways in AWS"
  },
  {
    "slug": "creating-new-ec2-instance-using-snapshot",
    "title": "Creating New EC2 Instance using Snapshot"
  },
  {
    "slug": "creating-serverless-contact-forms-with-aws",
    "title": "Creating Serverless Contact Forms with AWS"
  },
  {
    "slug": "cross-region-image-viewer-using-vpc-peering",
    "title": "Cross Region Image Viewer using VPC Peering"
  },
  {
    "slug": "data-integration-and-transformation-with-aws-glue",
    "title": "Data Integration and Transformation with AWS Glue"
  },
  {
    "slug": "deploy-container-using-aws-app-runner",
    "title": "Deploy Container using AWS App Runner"
  },
  {
    "slug": "deploying-a-highly-available-web-application-and-bastion-host-in-aws",
    "title": "Deploying a Highly Available Web Application and Bastion Host in AWS"
  },
  {
    "slug": "deploying-a-highly-available-web-application-and-bastion-host-in-aws-challenge-bastion-setup",
    "title": "Deploying a Highly Available Web Application and Bastion Host in AWS Challenge - Bastion Setup"
  },
  {
    "slug": "deploying-amazon-rds-multi-az-and-read-replica-simulate-failover",
    "title": "Deploying Amazon RDS Multi-AZ and Read Replica, Simulate Failover"
  },
  {
    "slug": "deploying-aws-file-gateway-on-vmware-esxi-to-enable-hybrid-cloud-storage-with-enterprise-grade-security-and-scalability",
    "title": "Deploying AWS File Gateway on VMware ESXi to enable hybrid cloud storage with enterprise-grade security and scalability"
  },
  {
    "slug": "difference-between-sqs-visibility-timeout-and-delay-queue",
    "title": "Difference between SQS Visibility Timeout and Delay Queue"
  },
  {
    "slug": "discover-sensitive-data-present-in-s3-bucket-using-amazon-macie",
    "title": "Discover sensitive data present in S3 bucket using Amazon Macie"
  },
  {
    "slug": "dynamodb-global-secondary-index",
    "title": "DynamoDB & Global Secondary Index"
  },
  {
    "slug": "ebs-multi-attach",
    "title": "EBS Multi- Attach"
  },
  {
    "slug": "ec2-challenge-cloud-core-compute-quest",
    "title": "EC2 Challenge-Cloud-Core Compute Quest"
  },
  {
    "slug": "enable-sticky-sessions-in-application-load-balancer",
    "title": "Enable sticky sessions in Application Load balancer"
  },
  {
    "slug": "enable-vpc-peering-through-transit-gateway-challenge",
    "title": "Enable VPC Peering through Transit Gateway Challenge"
  },
  {
    "slug": "enabling-cloudwatch-logs-in-api-gateway",
    "title": "Enabling CloudWatch Logs in API Gateway"
  },
  {
    "slug": "encrypt-s3-bucket-ebs-volume-and-ami-using-aws-kms",
    "title": "Encrypt S3 bucket, EBS Volume and AMI using AWS KMS"
  },
  {
    "slug": "encryption-and-decryption-using-kms",
    "title": "Encryption and Decryption Using KMS"
  },
  {
    "slug": "export-amazon-rds-db-snapshot-to-s3",
    "title": "Export Amazon RDS DB Snapshot to S3"
  },
  {
    "slug": "find-vulnerabilities-on-inspector2-using-lambda-scanning",
    "title": "Find vulnerabilities on Inspector2 using Lambda scanning"
  },
  {
    "slug": "getting-started-with-amazon-elastic-container-service-using-fargate",
    "title": "Getting Started with Amazon Elastic Container Service using Fargate"
  },
  {
    "slug": "hibernating-an-ec2-instance",
    "title": "Hibernating an EC2 Instance"
  },
  {
    "slug": "how-to-create-a-static-website-using-amazon-s3",
    "title": "How to Create a static website using Amazon S3"
  },
  {
    "slug": "how-to-create-virtual-private-cloud-vpc-with-aws-cloudformation",
    "title": "How to Create Virtual Private Cloud (VPC) with AWS CloudFormation"
  },
  {
    "slug": "how-to-enable-versioning-amazon-s3",
    "title": "How to enable versioning Amazon S3"
  },
  {
    "slug": "how-to-encrypt-an-s3-bucket-using-aws-kms-and-monitor-the-activities-with-cloudtrail",
    "title": "How to Encrypt an S3 bucket using AWS KMS and monitor the activities with CloudTrail"
  },
  {
    "slug": "how-to-encrypt-an-unencrypted-rds-db-instance",
    "title": "How to Encrypt an Unencrypted RDS DB Instance"
  },
  {
    "slug": "how-to-query-into-rds-mysql-using-aws-lambda",
    "title": "How to Query into RDS MySQL Using AWS Lambda"
  },
  {
    "slug": "how-to-setup-a-free-vpn-server-in-aws",
    "title": "How to setup a free VPN server in AWS"
  },
  {
    "slug": "hybrid-monitoring-system-deploymentusing-prometheus-with-grafana-on-awsand-vmware",
    "title": "Hybrid Monitoring System Deployment using Prometheus with Grafana on AWS and VMware"
  },
  {
    "slug": "hybrid-web-app-using-vmware-ubuntu-and-aws-rds",
    "title": "Hybrid web app using VMware Ubuntu and AWS RDS"
  },
  {
    "slug": "implement-data-backup-on-ubuntu-vmware-to-amazon-s3",
    "title": "Implement Data Backup on Ubuntu VMware to Amazon S3"
  },
  {
    "slug": "implementing-aws-waf-with-alb-to-block-sql-injection-geo-location-and-query-string",
    "title": "Implementing AWS WAF with ALB to block SQL Injection, Geo Location and Query string"
  },
  {
    "slug": "implementing-vpc-peering-on-aws",
    "title": "Implementing VPC peering on AWS"
  },
  {
    "slug": "integrating-api-gateway-with-lambda-function-challenge",
    "title": "Integrating API Gateway with Lambda Function Challenge"
  },
  {
    "slug": "introduction-sqs-deadletter-queue",
    "title": "Introduction SQS DeadLetter Queue"
  },
  {
    "slug": "introduction-to-amazon-api-gateway",
    "title": "Introduction to Amazon API Gateway"
  },
  {
    "slug": "introduction-to-amazon-aurora-challenge-aurora-connect",
    "title": "Introduction to Amazon Aurora Connect - Challenge Lab"
  },
  {
    "slug": "introduction-to-amazon-auto-scaling",
    "title": "Introduction to Amazon Auto Scaling"
  },
  {
    "slug": "introduction-to-amazon-cloudformation",
    "title": "Introduction to Amazon CloudFormation"
  },
  {
    "slug": "introduction-to-amazon-cloudfront",
    "title": "Introduction to Amazon CloudFront"
  },
  {
    "slug": "ec2-intro",
    "title": "Introduction to Amazon EC2"
  },
  {
    "slug": "introduction-to-amazon-elastic-compute-cloud-ec2",
    "title": "Introduction to Amazon Elastic Compute Cloud (EC2)"
  },
  {
    "slug": "introduction-to-amazon-elastic-container-service-ecs",
    "title": "Introduction to Amazon Elastic Container Service (ECS)"
  },
  {
    "slug": "introduction-to-amazon-guardduty",
    "title": "Introduction to Amazon GuardDuty"
  },
  {
    "slug": "introduction-to-amazon-guardduty-using-terraform",
    "title": "Introduction to Amazon GuardDuty using Terraform"
  },
  {
    "slug": "introduction-to-amazon-lambda",
    "title": "Introduction to Amazon Lambda"
  },
  {
    "slug": "introduction-to-amazon-simple-email-service-ses",
    "title": "Introduction to Amazon Simple Email Service SES"
  },
  {
    "slug": "introduction-to-amazon-simple-storage-service-s3",
    "title": "Introduction to Amazon Simple Storage Service (S3)"
  },
  {
    "slug": "introduction-to-aws-dynamodb",
    "title": "Introduction to AWS DynamoDB"
  },
  {
    "slug": "introduction-to-aws-elastic-beanstalk",
    "title": "Introduction to AWS Elastic Beanstalk"
  },
  {
    "slug": "introduction-to-aws-elastic-load-balancing",
    "title": "Introduction to AWS Elastic Load Balancing"
  },
  {
    "slug": "iam-intro",
    "title": "Introduction to AWS Identity & Access Management (IAM)"
  },
  {
    "slug": "introduction-to-aws-identity-access-management-iam",
    "title": "Introduction to AWS Identity Access Management (IAM)"
  },
  {
    "slug": "introduction-to-aws-relational-database-service",
    "title": "Introduction to AWS Relational Database Service"
  },
  {
    "slug": "introduction-to-aws-step-functions",
    "title": "Introduction to AWS Step Functions"
  },
  {
    "slug": "introduction-to-creating-aws-vpc-flow-logs",
    "title": "Introduction to Creating AWS VPC Flow Logs"
  },
  {
    "slug": "introduction-to-simple-queuing-service-sqs",
    "title": "Introduction to Simple Queuing Service (SQS)"
  },
  {
    "slug": "introduction-to-simple-queuing-service-sqs-challenge-queue-configuration",
    "title": "Introduction to Simple Queuing Service (SQS) Challenge - Queue Configuration"
  },
  {
    "slug": "launch-a-spot-instance-with-amazon-ec2",
    "title": "Launch a Spot Instance with Amazon EC2"
  },
  {
    "slug": "launch-ecs-container-challenge",
    "title": "Launch ECS Container Challenge"
  },
  {
    "slug": "migrating-ebs-volumes-from-gp2-to-gp3",
    "title": "Migrating EBS volumes from gp2 to gp3"
  },
  {
    "slug": "migrating-local-vm-ubuntu-database-to-aws-rds",
    "title": "Migrating Local VM Ubuntu Database to AWS RDS"
  },
  {
    "slug": "mount-elastic-file-system-efs-on-ec2",
    "title": "Mount Elastic File System (EFS) on EC2"
  },
  {
    "slug": "nat-gateway-aws-vpc-challenge",
    "title": "NAT gateway - AWS VPC Challenge"
  },
  {
    "slug": "peer-vpc-with-transit-gateway-and-its-components",
    "title": "Peer VPC with Transit Gateway and its components"
  },
  {
    "slug": "peer-vpc-with-transit-gateway-and-its-components-using-terraform",
    "title": "Peer VPC with Transit Gateway and its components using Terraform"
  },
  {
    "slug": "perform-etl-operation-in-glue-with-s3",
    "title": "Perform ETL operation in Glue with S3"
  },
  {
    "slug": "query-items-in-dynamodb-with-partiql-statements",
    "title": "Query items in DynamoDB with PartiQL Statements"
  },
  {
    "slug": "query-vpc-flow-log-using-amazon-athena",
    "title": "Query VPC Flow log using Amazon Athena"
  },
  {
    "slug": "querying-data-in-s3-with-amazon-athena",
    "title": "Querying Data in S3 with Amazon Athena"
  },
  {
    "slug": "resizing-amazon-ebs-volume",
    "title": "Resizing Amazon EBS Volume"
  },
  {
    "slug": "resizing-amazon-ebs-volume-challege-disk-scaling",
    "title": "Resizing Amazon EBS Volume Challege - Disk Scaling"
  },
  {
    "slug": "s3-batch-operation",
    "title": "S3 Batch Operation"
  },
  {
    "slug": "scaling-ec2-with-sqs",
    "title": "Scaling EC2 with SQS"
  },
  {
    "slug": "serverless-email-sender-with-amazon-simple-email-service",
    "title": "Serverless Email Sender with Amazon Simple-Email-Service"
  },
  {
    "slug": "setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer",
    "title": "Setting up the VPC environment, launching EC2 instances, and testing reachability using the AWS Reachability Analyzer"
  },
  {
    "slug": "setup-cross-region-replication-and-versioning-in-s3",
    "title": "Setup Cross Region Replication and Versioning in S3"
  },
  {
    "slug": "transfer-data-to-s3-using-amazon-kinesis-firehose",
    "title": "Transfer data to S3 using Amazon Kinesis Firehose"
  },
  {
    "slug": "troubleshooting-connectivity-issues-between-vpc-ec2-and-load-balancer",
    "title": "Troubleshooting Connectivity Issues Between VPC, EC2, and Load Balancer"
  },
  {
    "slug": "understanding-and-configuring-layered-security-in-an-aws-vpc",
    "title": "Understanding and Configuring Layered Security in an AWS VPC"
  },
  {
    "slug": "understanding-cloudfront-origin-groups",
    "title": "Understanding CloudFront Origin Groups"
  },
  {
    "slug": "use-aws-secrets-manager-secret-with-amazon-ecs",
    "title": "Use AWS Secrets Manager secret with Amazon ECS"
  },
  {
    "slug": "using-cloudwatch-for-resource-monitoring-create-cloudwatch-alarms-and-dashboards",
    "title": "Using CloudWatch for Resource Monitoring, Create CloudWatch Alarms and Dashboards"
  },
  {
    "slug": "wokwi-iot-device-simulation-with-aws-iot-core-real-time-dashboard",
    "title": "Wokwi IoT Device Simulation with AWS IoT Core Real-Time Dashboard"
  },
  {
    "slug": "working-with-cloudfront-distributions-and-restricted-region-challenge",
    "title": "Working with CloudFront distributions and Restricted Region Challenge"
  }
] as const
