// Auto-generated by scripts/generate-labs-checklist.ts — do not edit
export type ChecklistSectionId =
  | 'compute'
  | 'storage'
  | 'security'
  | 'database'
  | 'management'
  | 'networking'
  | 'analytics'
  | 'containers'

export type ChecklistLabEntry = {
  index: number
  title: string
  slug: string | null
  duration: string
  sectionId: ChecklistSectionId
  externalUrl: string | null
}

export const checklistSections: Array<{ id: ChecklistSectionId; label: string }> = [
  {
    "id": "compute",
    "label": "Compute"
  },
  {
    "id": "storage",
    "label": "Storage"
  },
  {
    "id": "security",
    "label": "Security, Identity & Compliance"
  },
  {
    "id": "database",
    "label": "Database"
  },
  {
    "id": "management",
    "label": "Management & Governance"
  },
  {
    "id": "networking",
    "label": "Networking & Content Delivery"
  },
  {
    "id": "analytics",
    "label": "Analytics"
  },
  {
    "id": "containers",
    "label": "Containers"
  }
]

/** Labs embedded in the video course outline (STUDY-CHECKLIST.md) */
export const labsChecklistTotal = 22

export const labsChecklistOrder: ChecklistLabEntry[] = [
  {
    "index": 1,
    "title": "Introduction to Amazon Elastic Compute Cloud",
    "slug": null,
    "duration": "EC2) (30m",
    "sectionId": "compute",
    "externalUrl": null
  },
  {
    "index": 2,
    "title": "Creating an application load balancer from AWS CLI",
    "slug": null,
    "duration": "1h",
    "sectionId": "compute",
    "externalUrl": null
  },
  {
    "index": 3,
    "title": "Creating an Application Load Balancer and Auto Scaling Group in AWS",
    "slug": null,
    "duration": "1h 30m",
    "sectionId": "compute",
    "externalUrl": null
  },
  {
    "index": 4,
    "title": "Creating and configuring a network load balancer in AWS",
    "slug": null,
    "duration": "1h",
    "sectionId": "compute",
    "externalUrl": null
  },
  {
    "index": 5,
    "title": "Creating S3 Lifecycle Policy",
    "slug": null,
    "duration": "30m",
    "sectionId": "storage",
    "externalUrl": null
  },
  {
    "index": 6,
    "title": "Introduction to Amazon GuardDuty",
    "slug": "introduction-to-amazon-guardduty",
    "duration": "30m",
    "sectionId": "security",
    "externalUrl": "https://business.whizlabs.com/labs/introduction-to-amazon-guardduty"
  },
  {
    "index": 7,
    "title": "Discover sensitive data present in S3 bucket using Amazon Macie",
    "slug": "discover-sensitive-data-present-in-s3-bucket-using-amazon-macie",
    "duration": "1h",
    "sectionId": "security",
    "externalUrl": "https://business.whizlabs.com/labs/discover-sensitive-data-present-in-s3-bucket-using-amazon-macie"
  },
  {
    "index": 8,
    "title": "Deploying Amazon RDS Multi-AZ and Read Replica, Simulate Failover",
    "slug": "deploying-amazon-rds-multi-az-and-read-replica-simulate-failover",
    "duration": "1h 30m",
    "sectionId": "database",
    "externalUrl": "https://business.whizlabs.com/labs/deploying-amazon-rds-multi-az-and-read-replica-simulate-failover"
  },
  {
    "index": 9,
    "title": "Create Redis cluster using ElastiCache",
    "slug": "create-redis-cluster-using-elasticache",
    "duration": "1h",
    "sectionId": "database",
    "externalUrl": "https://business.whizlabs.com/labs/create-redis-cluster-using-elasticache"
  },
  {
    "index": 10,
    "title": "Using CloudWatch for Resource Monitoring, Create CloudWatch Alarms and Dashboards",
    "slug": null,
    "duration": "1h 30m",
    "sectionId": "management",
    "externalUrl": null
  },
  {
    "index": 11,
    "title": "Check Compliance status of S3 Bucket using AWS Config",
    "slug": null,
    "duration": "1h 30m",
    "sectionId": "management",
    "externalUrl": null
  },
  {
    "index": 12,
    "title": "Auditing Resource Compliance with AWS config",
    "slug": "auditing-resource-compliance-with-aws-config",
    "duration": "45m",
    "sectionId": "management",
    "externalUrl": "https://business.whizlabs.com/labs/auditing-resource-compliance-with-aws-config"
  },
  {
    "index": 13,
    "title": "Introduction to Amazon CloudFormation",
    "slug": "introduction-to-amazon-cloudformation",
    "duration": "30m",
    "sectionId": "management",
    "externalUrl": "https://business.whizlabs.com/labs/introduction-to-amazon-cloudformation"
  },
  {
    "index": 14,
    "title": "Build Amazon VPC with Public and Private Subnets from Scratch",
    "slug": "build-amazon-vpc-with-public-and-private-subnets-from-scratch",
    "duration": "30m",
    "sectionId": "networking",
    "externalUrl": "https://business.whizlabs.com/labs/build-amazon-vpc-with-public-and-private-subnets-from-scratch"
  },
  {
    "index": 15,
    "title": "Creating AWS VPC Flow Logs and Generating Traffic",
    "slug": null,
    "duration": "1h",
    "sectionId": "networking",
    "externalUrl": null
  },
  {
    "index": 16,
    "title": "Creating NAT Gateways in AWS",
    "slug": "creating-nat-gateways-in-aws",
    "duration": "1h 30m",
    "sectionId": "networking",
    "externalUrl": "https://business.whizlabs.com/labs/creating-nat-gateways-in-aws"
  },
  {
    "index": 17,
    "title": "Peer VPC with Transit Gateway and its components",
    "slug": "peer-vpc-with-transit-gateway-and-its-components",
    "duration": "1h 15m",
    "sectionId": "networking",
    "externalUrl": "https://business.whizlabs.com/labs/peer-vpc-with-transit-gateway-and-its-components"
  },
  {
    "index": 18,
    "title": "Introduction to Amazon CloudFront",
    "slug": "introduction-to-amazon-cloudfront",
    "duration": "1h 30m",
    "sectionId": "networking",
    "externalUrl": "https://business.whizlabs.com/labs/introduction-to-amazon-cloudfront"
  },
  {
    "index": 19,
    "title": "Transfer data to S3 using Amazon Kinesis Firehose",
    "slug": "transfer-data-to-s3-using-amazon-kinesis-firehose",
    "duration": "1h 30m",
    "sectionId": "analytics",
    "externalUrl": "https://business.whizlabs.com/labs/transfer-data-to-s3-using-amazon-kinesis-firehose"
  },
  {
    "index": 20,
    "title": "Perform ETL operation in Glue with S3",
    "slug": null,
    "duration": "45m",
    "sectionId": "analytics",
    "externalUrl": null
  },
  {
    "index": 21,
    "title": "Create a cluster in Amazon EKS and install kubectl",
    "slug": "create-a-cluster-in-amazon-eks-and-install-kubectl",
    "duration": "1h",
    "sectionId": "containers",
    "externalUrl": "https://business.whizlabs.com/labs/create-a-cluster-in-amazon-eks-and-install-kubectl"
  },
  {
    "index": 22,
    "title": "Create a Docker container using Dockerfile and store the image in ECR",
    "slug": null,
    "duration": "1h",
    "sectionId": "containers",
    "externalUrl": null
  }
]
