// Auto-generated by scripts/generate-labs-library-order.ts — do not edit
export type LibrarySectionId = 'guided' | 'challenge' | 'project' | 'sandbox'

export type LibraryLabEntry = {
  index: number
  title: string
  slug: string
  duration: string
  sectionId: LibrarySectionId
  externalUrl: string
}

export const librarySections: Array<{ id: LibrarySectionId; label: string }> = [
  {
    "id": "guided",
    "label": "Guided labs"
  },
  {
    "id": "challenge",
    "label": "Challenges"
  },
  {
    "id": "project",
    "label": "Projects"
  },
  {
    "id": "sandbox",
    "label": "Sandboxes"
  }
]

/** SAA-C03 library labs not in domain catalog or study checklist */
export const labsLibraryTotal = 74

export const labsLibraryOrder: LibraryLabEntry[] = [
  {
    "index": 1,
    "title": "AWS EFS Shared Storage Lab: Mounting EFS on AWS EC2 and Local VMware Ubuntu Desktop GUI Access",
    "slug": "aws-efs-shared-storage-lab-mounting-efs-on-aws-ec2-and-local-vmware-ubuntu-desktop-gui-access",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/aws-efs-shared-storage-lab-mounting-efs-on-aws-ec2-and-local-vmware-ubuntu-desktop-gui-access"
  },
  {
    "index": 2,
    "title": "Challenge : Introduction to Amazon CloudFront",
    "slug": "amazon-cloudfront-challenge-secure-cdn",
    "duration": "1h 45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/amazon-cloudfront-challenge-secure-cdn"
  },
  {
    "index": 3,
    "title": "Challenge Lab - AWS DynamoDB NOSQL Setup",
    "slug": "dynamodb-challenge-nosql-setup-with-aws",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/dynamodb-challenge-nosql-setup-with-aws"
  },
  {
    "index": 4,
    "title": "Challenge Lab - Build Amazon VPC with Public and Private Subnets (from Scratch)",
    "slug": "challenge-master-vpc",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-master-vpc"
  },
  {
    "index": 5,
    "title": "Challenge : Creating New EC2 Instance using Snapshot",
    "slug": "ami-backup-challenge-relaunch-the-backup",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/ami-backup-challenge-relaunch-the-backup"
  },
  {
    "index": 6,
    "title": "Challenge Lab - Introduction to Amazon Lambda",
    "slug": "aws-lamada-challenge-serverless-flow",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/aws-lamada-challenge-serverless-flow"
  },
  {
    "index": 7,
    "title": "Challenge Lab - Create Virtual Private Cloud (VPC) with AWS CloudFormation",
    "slug": "challenge-vpc-cloudforge-infrastructure-blueprint",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-vpc-cloudforge-infrastructure-blueprint"
  },
  {
    "index": 8,
    "title": "Challenge: Connecting RDS from EC2 Instance",
    "slug": "connect-rds-from-instance-challenge-mysql-access",
    "duration": "1h 10m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/connect-rds-from-instance-challenge-mysql-access"
  },
  {
    "index": 9,
    "title": "Challenge- IAM- Access Control to Users Services",
    "slug": "iam-challenge-access-control-to-usersservices",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/iam-challenge-access-control-to-usersservices"
  },
  {
    "index": 10,
    "title": "Introduction to Amazon Aurora Connect - Challenge Lab",
    "slug": "introduction-to-amazon-aurora-challenge-aurora-connect",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/introduction-to-amazon-aurora-challenge-aurora-connect"
  },
  {
    "index": 11,
    "title": "Resizing Amazon EBS Volume Challege - Disk Scaling",
    "slug": "resizing-amazon-ebs-volume-challege-disk-scaling",
    "duration": "1h 30m",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/resizing-amazon-ebs-volume-challege-disk-scaling"
  },
  {
    "index": 12,
    "title": "Challenge : DynamoDB & Global Secondary Index",
    "slug": "dynamodb-global-secondary-index-table-indexing",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/dynamodb-global-secondary-index-table-indexing"
  },
  {
    "index": 13,
    "title": "Deploying a Highly Available Web Application and Bastion Host in AWS Challenge - Bastion Setup",
    "slug": "deploying-a-highly-available-web-application-and-bastion-host-in-aws-challenge-bastion-setup",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/deploying-a-highly-available-web-application-and-bastion-host-in-aws-challenge-bastion-setup"
  },
  {
    "index": 14,
    "title": "Introduction to Simple Queuing Service (SQS) Challenge - Queue Configuration",
    "slug": "introduction-to-simple-queuing-service-sqs-challenge-queue-configuration",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/introduction-to-simple-queuing-service-sqs-challenge-queue-configuration"
  },
  {
    "index": 15,
    "title": "Challenge Lab - Configuring Layered Security in an AWS VPC",
    "slug": "challenge-vpcfortress-security-citadel",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-vpcfortress-security-citadel"
  },
  {
    "index": 16,
    "title": "Challenge: WAFFirewall - Web Traffic Shield",
    "slug": "challenge-waffirewall-web-traffic-shield",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-waffirewall-web-traffic-shield"
  },
  {
    "index": 17,
    "title": "Challenge Lab -  Mount EFS on EC2",
    "slug": "challenge-efsmount-shared-storage-sync",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-efsmount-shared-storage-sync"
  },
  {
    "index": 18,
    "title": "Challenge Lab - AWS Step Functions",
    "slug": "challenge-stepfunctions-workflow-basics",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-stepfunctions-workflow-basics"
  },
  {
    "index": 19,
    "title": "Challenge Lab - Amazon Elastic Container Service using Fargate",
    "slug": "challenge-amazonecsfargate-container-deployment-basics",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-amazonecsfargate-container-deployment-basics"
  },
  {
    "index": 20,
    "title": "Challenge Lab: Create a cluster in Amazon EKS and install kubectl",
    "slug": "challenge-amazoneksclustersetup-eks-basics",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-amazoneksclustersetup-eks-basics"
  },
  {
    "index": 21,
    "title": "Challenge Lab: API Gateway - Creating Resources and Methods",
    "slug": "challenge-apigatewayresourcesmethods-api-setup-basics",
    "duration": "30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-apigatewayresourcesmethods-api-setup-basics"
  },
  {
    "index": 22,
    "title": "Challenge: Introduction to Amazon API Gateway",
    "slug": "challenge-apigatewayintroduction-api-basics",
    "duration": "30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-apigatewayintroduction-api-basics"
  },
  {
    "index": 23,
    "title": "Challenge Lab: Enabling CloudWatch Logs in API Gateway\t",
    "slug": "challenge-apigatewaycloudwatchlogs-logging-setup",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-apigatewaycloudwatchlogs-logging-setup"
  },
  {
    "index": 24,
    "title": "Challenge Lab - Build API Gateway with Lambda Integration",
    "slug": "challenge-apigatewaylambdaintegration-serverless-api-setup",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-apigatewaylambdaintegration-serverless-api-setup"
  },
  {
    "index": 25,
    "title": "Challenge: AWS_VPC_NACL_Lab - Case Study on VPC, NACL Configuration, and Compliance Auditing",
    "slug": "challenge-awsvpcnacllab-case-study-on-vpc-nacl-configuration-and-compliance-auditing",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-awsvpcnacllab-case-study-on-vpc-nacl-configuration-and-compliance-auditing"
  },
  {
    "index": 26,
    "title": "Challenge: Comparing Data Transfer Speeds with S3 Transfer Acceleration",
    "slug": "challenge-s3transferacceleration-comparing-data-transfer-speeds",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-s3transferacceleration-comparing-data-transfer-speeds"
  },
  {
    "index": 27,
    "title": "Challenge Lab: Introduction to Amazon GuardDuty",
    "slug": "challenge-amazonguarddutyintroduction-threat-detection-basics",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-amazonguarddutyintroduction-threat-detection-basics"
  },
  {
    "index": 28,
    "title": "Challenge: Amazon_SES_Introduction - Sending Emails with SES",
    "slug": "challenge-amazonsesintroduction-sending-emails-with-ses",
    "duration": "25m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-amazonsesintroduction-sending-emails-with-ses"
  },
  {
    "index": 29,
    "title": "Challenge Lab: Access Amazon SQS using Amazon VPC Interface Endpoint",
    "slug": "challenge-lab-access-amazon-sqs-using-amazon-vpc-interface-endpoint",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-access-amazon-sqs-using-amazon-vpc-interface-endpoint"
  },
  {
    "index": 30,
    "title": "Challenge Lab: CloudFront Distribution with EC2 & S3 Integration",
    "slug": "challenge-lab-cloudfront-distribution-with-ec2-s3-integration",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-cloudfront-distribution-with-ec2-s3-integration"
  },
  {
    "index": 31,
    "title": "Challenge Lab - EC2 Instance Hibernation",
    "slug": "challenge-lab-hands-on-with-ec2-instance-hibernation",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-hands-on-with-ec2-instance-hibernation"
  },
  {
    "index": 32,
    "title": "Challenge Lab: Migrating EBS volumes from gp2 to gp3",
    "slug": "challenge-lab-migrating-ebs-volumes-from-gp2-to-gp3",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-migrating-ebs-volumes-from-gp2-to-gp3"
  },
  {
    "index": 33,
    "title": "Challenge Lab : Understanding and Configuring Layered Security in an AWS VPC Using Terraform",
    "slug": "challenge-lab-understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform"
  },
  {
    "index": 34,
    "title": "Challenge Lab : Introduction to Amazon GuardDuty using Terraform",
    "slug": "challenge-lab-automating-amazon-guardduty-setup-with-terraform",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-automating-amazon-guardduty-setup-with-terraform"
  },
  {
    "index": 35,
    "title": "Challenge Lab : Introduction SQS DeadLetter Queue",
    "slug": "challenge-lab-introduction-sqs-deadletter-queue",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-introduction-sqs-deadletter-queue"
  },
  {
    "index": 36,
    "title": "Challenge Lab : Data Integration and Transformation with AWS Glue",
    "slug": "challenge-lab-data-integration-and-transformation-with-aws-glue",
    "duration": "2h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-data-integration-and-transformation-with-aws-glue"
  },
  {
    "index": 37,
    "title": "Challenge Lab : Setting up the VPC environment, launching EC2 instances, and testing reachability using the AWS Reachability Analyzer",
    "slug": "challenge-lab-setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer"
  },
  {
    "index": 38,
    "title": "Challenge Lab : Find vulnerabilities on Inspector2 using Lambda scanning",
    "slug": "challenge-lab-find-vulnerabilities-on-inspector2-using-lambda-scanning",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-find-vulnerabilities-on-inspector2-using-lambda-scanning"
  },
  {
    "index": 39,
    "title": "Challenge Lab - Resolve Connectivity Issues Between VPC, EC2 Instances, and Load Balancer",
    "slug": "challenge-lab-ec2-vpc-and-load-balancer-integration-and-debugging",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-ec2-vpc-and-load-balancer-integration-and-debugging"
  },
  {
    "index": 40,
    "title": "Challenge Lab - Configuring EBS Volume to ECS task",
    "slug": "challenge-lab-configuring-ebs-volume-to-ecs-task",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-configuring-ebs-volume-to-ecs-task"
  },
  {
    "index": 41,
    "title": "Challenge Lab: Building a Dynamic API with Path and Query String Parameters",
    "slug": "challenge-lab-building-a-dynamic-api-with-path-and-query-string-parameters",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-building-a-dynamic-api-with-path-and-query-string-parameters"
  },
  {
    "index": 42,
    "title": "Challenge Lab: Creating a workflow using different States with AWS Step Functions",
    "slug": "challenge-lab-building-a-dynamic-workflow-with-aws-step-functions",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-building-a-dynamic-workflow-with-aws-step-functions"
  },
  {
    "index": 43,
    "title": "Challenge Lab - Implementing AWS WAF with ALB to block SQL Injection, Geo Location and Query string",
    "slug": "challenge-lab-protect-your-website-with-aws-waf",
    "duration": "2h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-protect-your-website-with-aws-waf"
  },
  {
    "index": 44,
    "title": "Challenge Lab: Launch & Manage a Spot EC2 Web Server",
    "slug": "challenge-lab-launch-manage-a-spot-ec2-web-server",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-launch-manage-a-spot-ec2-web-server"
  },
  {
    "index": 45,
    "title": "Challenge Lab - Testing SQS Visibility Timeout and Message Delay in Action",
    "slug": "challenge-lab-configuring-and-testing-sqs-visibility-timeout-and-delivery-delay",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-configuring-and-testing-sqs-visibility-timeout-and-delivery-delay"
  },
  {
    "index": 46,
    "title": "Challenge Lab: Transfer data to S3 using Amazon Kinesis Firehose",
    "slug": "challenge-lab-stream-and-store-vpc-flow-logs-using-kinesis-firehose-and-s3",
    "duration": "1h 45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-stream-and-store-vpc-flow-logs-using-kinesis-firehose-and-s3"
  },
  {
    "index": 47,
    "title": "Challenge Lab: Data Protection Using AWS Key Management Service",
    "slug": "challenge-lab-data-protection-using-aws-key-management-service",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-data-protection-using-aws-key-management-service"
  },
  {
    "index": 48,
    "title": "Migrating Local VM Ubuntu Database to AWS RDS",
    "slug": "migrating-local-vm-ubuntu-database-to-aws-rds",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/migrating-local-vm-ubuntu-database-to-aws-rds"
  },
  {
    "index": 49,
    "title": "Creating and Subscribing to SNS Topics, Adding SNS event for S3 bucket Challenge -  Bucket Monitor",
    "slug": "creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket-challenge-bucket-monitor",
    "duration": "45m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket-challenge-bucket-monitor"
  },
  {
    "index": 50,
    "title": "Challenge Lab: Create and Configure Amazon EC2 Auto Scaling with Launch Templates",
    "slug": "challenge-lab-deploying-scalable-ec2-instances-using-launch-templates",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-deploying-scalable-ec2-instances-using-launch-templates"
  },
  {
    "index": 51,
    "title": "EC2  Challenge-Cloud-Core Compute Quest",
    "slug": "ec2-challenge-cloud-core-compute-quest",
    "duration": "30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/ec2-challenge-cloud-core-compute-quest"
  },
  {
    "index": 52,
    "title": "Challenge Lab: Deploy and Connect to a Redis Cluster using Amazon ElastiCache",
    "slug": "challenge-lab-deploy-and-connect-to-a-redis-cluster-using-amazon-elasticache",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-deploy-and-connect-to-a-redis-cluster-using-amazon-elasticache"
  },
  {
    "index": 53,
    "title": "Challenge Lab: Set Up a Free VPN Server Using OpenVPN on AWS",
    "slug": "challenge-lab-set-up-a-free-vpn-server-using-openvpn-on-aws",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-set-up-a-free-vpn-server-using-openvpn-on-aws"
  },
  {
    "index": 54,
    "title": "Challenge Lab: Create Elastic Network Interface - Multiple IPs on an EC2",
    "slug": "challenge-lab-multi-ip-ec2-deployment-with-elastic-network-interfaces",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-multi-ip-ec2-deployment-with-elastic-network-interfaces"
  },
  {
    "index": 55,
    "title": "Challenge Lab - Build API Gateway with different stages using stage variables",
    "slug": "challenge-lab-api-gateway-stage-variables-for-seamless-environment-management",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-api-gateway-stage-variables-for-seamless-environment-management"
  },
  {
    "index": 56,
    "title": "Challenge Lab: Analyzing Expense Data with Amazon Athena",
    "slug": "challenge-lab-analyzing-expense-data-with-amazon-athena",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-analyzing-expense-data-with-amazon-athena"
  },
  {
    "index": 57,
    "title": "Challenge Lab : Access S3 from Private EC2 instance using VPC Endpoint",
    "slug": "challenge-lab-accessing-s3-from-a-private-ec2-instance-without-internet-access",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-accessing-s3-from-a-private-ec2-instance-without-internet-access"
  },
  {
    "index": 58,
    "title": "Creating a User Pool in AWS Cognito Using Terraform",
    "slug": "creating-a-user-pool-in-aws-cognito-using-terraform",
    "duration": "45m",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/creating-a-user-pool-in-aws-cognito-using-terraform"
  },
  {
    "index": 59,
    "title": "Challenge Lab: Create a DynamoDB table and perform various table operations using NoSQL Workbench",
    "slug": "challenge-lab-dynamodb-table-operations-using-aws-console-and-nosql-workbench",
    "duration": "1h 15m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-dynamodb-table-operations-using-aws-console-and-nosql-workbench"
  },
  {
    "index": 60,
    "title": "Understanding and Configuring Layered Security in an AWS VPC Using Terraform",
    "slug": "understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform"
  },
  {
    "index": 61,
    "title": "Challenge Lab: How to Encrypt an Unencrypted RDS DB Instance",
    "slug": "challenge-lab-encrypt-an-amazon-rds-instance-using-snapshot-migration-and-kms",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-encrypt-an-amazon-rds-instance-using-snapshot-migration-and-kms"
  },
  {
    "index": 62,
    "title": "Challenge Lab - Exporting Amazon RDS Snapshot to S3 for Secure Backup",
    "slug": "challenge-lab-exporting-amazon-rds-snapshot-to-s3-for-secure-backup",
    "duration": "2h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-exporting-amazon-rds-snapshot-to-s3-for-secure-backup"
  },
  {
    "index": 63,
    "title": "Amazon RDS-CloudSQL Catalyst-Challenge",
    "slug": "amazon-rds-challenge-cloudsql-catalyst",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/amazon-rds-challenge-cloudsql-catalyst"
  },
  {
    "index": 64,
    "title": "Introduction to Amazon GuardDuty using Terraform",
    "slug": "introduction-to-amazon-guardduty-using-terraform",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/introduction-to-amazon-guardduty-using-terraform"
  },
  {
    "index": 65,
    "title": "Serverless Email Sender with Amazon Simple-Email-Service",
    "slug": "serverless-email-sender-with-amazon-simple-email-service",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/serverless-email-sender-with-amazon-simple-email-service"
  },
  {
    "index": 66,
    "title": "Challenge Lab: Encrypt S3 bucket, EBS Volume and AMI using AWS KMS",
    "slug": "challenge-lab-enable-developer-controlled-encryption-with-aws-kms-cmks",
    "duration": "1h 30m",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-enable-developer-controlled-encryption-with-aws-kms-cmks"
  },
  {
    "index": 67,
    "title": "Deploy Container using AWS App Runner",
    "slug": "deploy-container-using-aws-app-runner",
    "duration": "30m",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/deploy-container-using-aws-app-runner"
  },
  {
    "index": 68,
    "title": "Hybrid Monitoring System Deployment using Prometheus with Grafana on AWS and VMware",
    "slug": "hybrid-monitoring-system-deploymentusing-prometheus-with-grafana-on-awsand-vmware",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/hybrid-monitoring-system-deploymentusing-prometheus-with-grafana-on-awsand-vmware"
  },
  {
    "index": 69,
    "title": "Deploying AWS File Gateway on VMware  ESXi to enable hybrid cloud storage with enterprise-grade security and scalability",
    "slug": "deploying-aws-file-gateway-on-vmware-esxi-to-enable-hybrid-cloud-storage-with-enterprise-grade-security-and-scalability",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/deploying-aws-file-gateway-on-vmware-esxi-to-enable-hybrid-cloud-storage-with-enterprise-grade-security-and-scalability"
  },
  {
    "index": 70,
    "title": "Challenge Lab: Secure Secret Management with AWS Secrets Manager and ECS",
    "slug": "challenge-lab-secure-secret-management-with-aws-secrets-manager-and-ecs",
    "duration": "1h",
    "sectionId": "challenge",
    "externalUrl": "https://business.whizlabs.com/labs/challenge-lab-secure-secret-management-with-aws-secrets-manager-and-ecs"
  },
  {
    "index": 71,
    "title": "Implement Data Backup on Ubuntu VMware to Amazon S3",
    "slug": "implement-data-backup-on-ubuntu-vmware-to-amazon-s3",
    "duration": "45m",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/implement-data-backup-on-ubuntu-vmware-to-amazon-s3"
  },
  {
    "index": 72,
    "title": "Hybrid web app using VMware Ubuntu and AWS RDS",
    "slug": "hybrid-web-app-using-vmware-ubuntu-and-aws-rds",
    "duration": "1h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/hybrid-web-app-using-vmware-ubuntu-and-aws-rds"
  },
  {
    "index": 73,
    "title": "Creating a User Pool in AWS Cognito",
    "slug": "creating-a-user-pool-in-aws-cognito",
    "duration": "30m",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/creating-a-user-pool-in-aws-cognito"
  },
  {
    "index": 74,
    "title": "Data Integration and Transformation with AWS Glue",
    "slug": "data-integration-and-transformation-with-aws-glue",
    "duration": "2h",
    "sectionId": "guided",
    "externalUrl": "https://business.whizlabs.com/labs/data-integration-and-transformation-with-aws-glue"
  }
]
