// Auto-generated by scripts/compile-saa-cert-labs.ts — do not edit
import type { LabLevel } from '@/lib/labs'

export type SaaCertLab = {
  /** 1-based row number from the source catalog table. */
  n: number
  /** Matches the slug used in data/labsCatalog.ts (URL's last path segment). */
  slug: string
  name: string
  type: string
  level: LabLevel
  duration: string
  certifications: string[]
  url: string
}

export const saaCertLabs: SaaCertLab[] = [
  {
    "n": 1,
    "slug": "api-gateway-creating-resources-and-methods",
    "name": "API Gateway - Creating Resources and Methods",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "20m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/api-gateway-creating-resources-and-methods"
  },
  {
    "n": 2,
    "slug": "aws-efs-shared-storage-lab-mounting-efs-on-aws-ec2-and-local-vmware-ubuntu-desktop-gui-access",
    "name": "AWS EFS Shared Storage Lab: Mounting EFS on AWS EC2 and Local VMware Ubuntu Desktop GUI Access",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/aws-efs-shared-storage-lab-mounting-efs-on-aws-ec2-and-local-vmware-ubuntu-desktop-gui-access"
  },
  {
    "n": 3,
    "slug": "aws-vpc-nacl-lab-case-study",
    "name": "AWS VPC NACL Lab - Case study",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/aws-vpc-nacl-lab-case-study"
  },
  {
    "n": 4,
    "slug": "access-amazon-sqs-using-amazon-vpc-interface-endpoint",
    "name": "Access Amazon SQS using Amazon VPC Interface Endpoint",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/access-amazon-sqs-using-amazon-vpc-interface-endpoint"
  },
  {
    "n": 5,
    "slug": "access-s3-from-private-ec2-instance-using-vpc-endpoint",
    "name": "Access S3 from Private EC2 instance using VPC Endpoint",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/access-s3-from-private-ec2-instance-using-vpc-endpoint"
  },
  {
    "n": 6,
    "slug": "allocating-elastic-ip-and-associating-it-to-ec2-instance",
    "name": "Allocating Elastic IP and Associating it to EC2 Instance",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/allocating-elastic-ip-and-associating-it-to-ec2-instance"
  },
  {
    "n": 7,
    "slug": "amazon-cloudformation-s3-url-stack-challenge",
    "name": "Amazon CloudFormation S3 URL Stack Challenge",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/amazon-cloudformation-s3-url-stack-challenge"
  },
  {
    "n": 8,
    "slug": "amazon-rds-challenge-cloudsql-catalyst",
    "name": "Amazon RDS-CloudSQL Catalyst-Challenge",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/amazon-rds-challenge-cloudsql-catalyst"
  },
  {
    "n": 9,
    "slug": "amazon-vpc-endpoint-challenge",
    "name": "Amazon VPC Endpoint challenge",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/amazon-vpc-endpoint-challenge"
  },
  {
    "n": 10,
    "slug": "balance-load-across-containers-through-application-load-balancer-in-ecs",
    "name": "Balance load across containers through Application Load Balancer in ECS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/balance-load-across-containers-through-application-load-balancer-in-ecs"
  },
  {
    "n": 11,
    "slug": "block-and-unblock-access-to-cloudfront-distribution-using-aws-waf",
    "name": "Block and Unblock access to CloudFront distribution using AWS WAF",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/block-and-unblock-access-to-cloudfront-distribution-using-aws-waf"
  },
  {
    "n": 12,
    "slug": "blocking-web-traffic-with-waf-in-aws",
    "name": "Blocking web traffic with WAF in AWS",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/blocking-web-traffic-with-waf-in-aws"
  },
  {
    "n": 13,
    "slug": "build-api-gateway-with-lambda-integration",
    "name": "Build API Gateway with Lambda Integration",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/build-api-gateway-with-lambda-integration"
  },
  {
    "n": 14,
    "slug": "build-api-gateway-with-different-stages-using-stage-variables",
    "name": "Build API Gateway with different stages using stage variables",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/build-api-gateway-with-different-stages-using-stage-variables"
  },
  {
    "n": 15,
    "slug": "build-api-gateway-with-path-parameter-and-query-string-parameter",
    "name": "Build API Gateway with path parameter and Query string parameter",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/build-api-gateway-with-path-parameter-and-query-string-parameter"
  },
  {
    "n": 16,
    "slug": "build-amazon-vpc-with-public-and-private-subnets-from-scratch",
    "name": "Build Amazon VPC with Public and Private Subnets (from Scratch)",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/build-amazon-vpc-with-public-and-private-subnets-from-scratch"
  },
  {
    "n": 17,
    "slug": "build-a-real-time-data-streaming-system-with-amazon-kinesis-data-stream-and-kinesis-agent",
    "name": "Build a real time data streaming system with Amazon Kinesis Data Stream and Kinesis Agent",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Machine Learning - Specialty",
      "AWS Certified Data Analytics - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/build-a-real-time-data-streaming-system-with-amazon-kinesis-data-stream-and-kinesis-agent"
  },
  {
    "n": 18,
    "slug": "challenge-build-a-real-time-data-streaming-system-with-amazon-kinesis-data-stream-and-kinesis-agent",
    "name": "Challenge - Build a real time data streaming system with Amazon Kinesis Data Stream and Kinesis Agent",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Machine Learning - Specialty",
      "AWS Certified Data Analytics - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-build-a-real-time-data-streaming-system-with-amazon-kinesis-data-stream-and-kinesis-agent"
  },
  {
    "n": 19,
    "slug": "challenge-deploying-amazon-rds-multi-az-and-read-replica-simulate-failover",
    "name": "Challenge - Deploying Amazon RDS Multi-AZ and Read Replica, Simulate Failover",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "2h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-deploying-amazon-rds-multi-az-and-read-replica-simulate-failover"
  },
  {
    "n": 20,
    "slug": "challenge-discover-sensitive-data-present-in-s3-bucket-using-amazon-macie",
    "name": "Challenge - Discover sensitive data present in S3 bucket using Amazon Macie",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Security - Specialty",
      "AWS Certified Machine Learning - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-discover-sensitive-data-present-in-s3-bucket-using-amazon-macie"
  },
  {
    "n": 21,
    "slug": "challenge-how-to-encrypt-an-s3-bucket-using-aws-kms-and-monitor-the-activities-with-cloudtrail",
    "name": "Challenge - How to Encrypt an S3 bucket using AWS KMS and monitor the activities with CloudTrail",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-how-to-encrypt-an-s3-bucket-using-aws-kms-and-monitor-the-activities-with-cloudtrail"
  },
  {
    "n": 22,
    "slug": "challenge-lab-introduction-to-aws-elastic-load-balancing-challenge",
    "name": "Challenge - Introduction to AWS Elastic Load Balancing",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-introduction-to-aws-elastic-load-balancing-challenge"
  },
  {
    "n": 23,
    "slug": "ami-backup-challenge-relaunch-the-backup",
    "name": "Challenge : Creating New EC2 Instance using Snapshot",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/ami-backup-challenge-relaunch-the-backup"
  },
  {
    "n": 24,
    "slug": "dynamodb-global-secondary-index-table-indexing",
    "name": "Challenge : DynamoDB & Global Secondary Index",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/dynamodb-global-secondary-index-table-indexing"
  },
  {
    "n": 25,
    "slug": "amazon-cloudfront-challenge-secure-cdn",
    "name": "Challenge : Introduction to Amazon CloudFront",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/amazon-cloudfront-challenge-secure-cdn"
  },
  {
    "n": 26,
    "slug": "challenge-connecting-an-ec2-instance-and-a-db-instance-automatically",
    "name": "Challenge Connecting an EC2 instance and a DB instance Automatically",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-connecting-an-ec2-instance-and-a-db-instance-automatically"
  },
  {
    "n": 27,
    "slug": "challenge-efsmount-shared-storage-sync",
    "name": "Challenge Lab -  Mount EFS on EC2",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-efsmount-shared-storage-sync"
  },
  {
    "n": 28,
    "slug": "dynamodb-challenge-nosql-setup-with-aws",
    "name": "Challenge Lab - AWS DynamoDB NOSQL Setup",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/dynamodb-challenge-nosql-setup-with-aws"
  },
  {
    "n": 29,
    "slug": "challenge-stepfunctions-workflow-basics",
    "name": "Challenge Lab - AWS Step Functions",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-stepfunctions-workflow-basics"
  },
  {
    "n": 30,
    "slug": "challenge-amazonecsfargate-container-deployment-basics",
    "name": "Challenge Lab - Amazon Elastic Container Service using Fargate",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-amazonecsfargate-container-deployment-basics"
  },
  {
    "n": 31,
    "slug": "challenge-apigatewaylambdaintegration-serverless-api-setup",
    "name": "Challenge Lab - Build API Gateway with Lambda Integration",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-apigatewaylambdaintegration-serverless-api-setup"
  },
  {
    "n": 32,
    "slug": "challenge-lab-api-gateway-stage-variables-for-seamless-environment-management",
    "name": "Challenge Lab - Build API Gateway with different stages using stage variables",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-api-gateway-stage-variables-for-seamless-environment-management"
  },
  {
    "n": 33,
    "slug": "challenge-master-vpc",
    "name": "Challenge Lab - Build Amazon VPC with Public and Private Subnets (from Scratch)",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-master-vpc"
  },
  {
    "n": 34,
    "slug": "challenge-lab-configuring-ebs-volume-to-ecs-task",
    "name": "Challenge Lab - Configuring EBS Volume to ECS task",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-configuring-ebs-volume-to-ecs-task"
  },
  {
    "n": 35,
    "slug": "challenge-vpcfortress-security-citadel",
    "name": "Challenge Lab - Configuring Layered Security in an AWS VPC",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-vpcfortress-security-citadel"
  },
  {
    "n": 36,
    "slug": "challenge-vpc-cloudforge-infrastructure-blueprint",
    "name": "Challenge Lab - Create Virtual Private Cloud (VPC) with AWS CloudFormation",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-vpc-cloudforge-infrastructure-blueprint"
  },
  {
    "n": 37,
    "slug": "challenge-lab-hands-on-with-ec2-instance-hibernation",
    "name": "Challenge Lab - EC2 Instance Hibernation",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-hands-on-with-ec2-instance-hibernation"
  },
  {
    "n": 38,
    "slug": "challenge-lab-exporting-amazon-rds-snapshot-to-s3-for-secure-backup",
    "name": "Challenge Lab - Exporting Amazon RDS Snapshot to S3 for Secure Backup",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "2h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-exporting-amazon-rds-snapshot-to-s3-for-secure-backup"
  },
  {
    "n": 39,
    "slug": "challenge-lab-protect-your-website-with-aws-waf",
    "name": "Challenge Lab - Implementing AWS WAF with ALB to block SQL Injection, Geo Location and Query string",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "2h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-protect-your-website-with-aws-waf"
  },
  {
    "n": 40,
    "slug": "aws-lamada-challenge-serverless-flow",
    "name": "Challenge Lab - Introduction to Amazon Lambda",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/aws-lamada-challenge-serverless-flow"
  },
  {
    "n": 41,
    "slug": "challenge-lab-ec2-vpc-and-load-balancer-integration-and-debugging",
    "name": "Challenge Lab - Resolve Connectivity Issues Between VPC, EC2 Instances, and Load Balancer",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-ec2-vpc-and-load-balancer-integration-and-debugging"
  },
  {
    "n": 42,
    "slug": "challenge-lab-configuring-and-testing-sqs-visibility-timeout-and-delivery-delay",
    "name": "Challenge Lab - Testing SQS Visibility Timeout and Message Delay in Action",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-configuring-and-testing-sqs-visibility-timeout-and-delivery-delay"
  },
  {
    "n": 43,
    "slug": "challenge-lab-accessing-s3-from-a-private-ec2-instance-without-internet-access",
    "name": "Challenge Lab : Access S3 from Private EC2 instance using VPC Endpoint",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-accessing-s3-from-a-private-ec2-instance-without-internet-access"
  },
  {
    "n": 44,
    "slug": "challenge-lab-data-integration-and-transformation-with-aws-glue",
    "name": "Challenge Lab : Data Integration and Transformation with AWS Glue",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "2h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Machine Learning - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-data-integration-and-transformation-with-aws-glue"
  },
  {
    "n": 45,
    "slug": "challenge-lab-find-vulnerabilities-on-inspector2-using-lambda-scanning",
    "name": "Challenge Lab : Find vulnerabilities on Inspector2 using Lambda scanning",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-find-vulnerabilities-on-inspector2-using-lambda-scanning"
  },
  {
    "n": 46,
    "slug": "challenge-lab-introduction-sqs-deadletter-queue",
    "name": "Challenge Lab : Introduction SQS DeadLetter Queue",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-introduction-sqs-deadletter-queue"
  },
  {
    "n": 47,
    "slug": "challenge-lab-automating-amazon-guardduty-setup-with-terraform",
    "name": "Challenge Lab : Introduction to Amazon GuardDuty using Terraform",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-automating-amazon-guardduty-setup-with-terraform"
  },
  {
    "n": 48,
    "slug": "challenge-lab-setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer",
    "name": "Challenge Lab : Setting up the VPC environment, launching EC2 instances, and testing reachability using the AWS Reachability Analyzer",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer"
  },
  {
    "n": 49,
    "slug": "challenge-lab-understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform",
    "name": "Challenge Lab : Understanding and Configuring Layered Security in an AWS VPC Using Terraform",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform"
  },
  {
    "n": 50,
    "slug": "challenge-lab-enable-sticky-sessions-in-application-load-balancer",
    "name": "Challenge Lab – Enable Sticky sessions in Application Load balancer",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-enable-sticky-sessions-in-application-load-balancer"
  },
  {
    "n": 51,
    "slug": "challenge-lab-allocating-elastic-ip-and-associating-it-to-ec2-instance",
    "name": "Challenge Lab- Allocating Elastic IP and Associating it to EC2 Instance",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-allocating-elastic-ip-and-associating-it-to-ec2-instance"
  },
  {
    "n": 52,
    "slug": "challenge-apigatewayresourcesmethods-api-setup-basics",
    "name": "Challenge Lab: API Gateway - Creating Resources and Methods",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-apigatewayresourcesmethods-api-setup-basics"
  },
  {
    "n": 53,
    "slug": "challenge-lab-access-amazon-sqs-using-amazon-vpc-interface-endpoint",
    "name": "Challenge Lab: Access Amazon SQS using Amazon VPC Interface Endpoint",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-access-amazon-sqs-using-amazon-vpc-interface-endpoint"
  },
  {
    "n": 54,
    "slug": "challenge-lab-analyzing-expense-data-with-amazon-athena",
    "name": "Challenge Lab: Analyzing Expense Data with Amazon Athena",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Data Analytics - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-analyzing-expense-data-with-amazon-athena"
  },
  {
    "n": 55,
    "slug": "challenge-lab-building-a-dynamic-api-with-path-and-query-string-parameters",
    "name": "Challenge Lab: Building a Dynamic API with Path and Query String Parameters",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-building-a-dynamic-api-with-path-and-query-string-parameters"
  },
  {
    "n": 56,
    "slug": "challenge-lab-cloudfront-distribution-with-ec2-s3-integration",
    "name": "Challenge Lab: CloudFront Distribution with EC2 & S3 Integration",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-cloudfront-distribution-with-ec2-s3-integration"
  },
  {
    "n": 57,
    "slug": "challenge-lab-multi-ip-ec2-deployment-with-elastic-network-interfaces",
    "name": "Challenge Lab: Create Elastic Network Interface - Multiple IPs on an EC2",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-multi-ip-ec2-deployment-with-elastic-network-interfaces"
  },
  {
    "n": 58,
    "slug": "challenge-lab-dynamodb-table-operations-using-aws-console-and-nosql-workbench",
    "name": "Challenge Lab: Create a DynamoDB table and perform various table operations using NoSQL Workbench",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-dynamodb-table-operations-using-aws-console-and-nosql-workbench"
  },
  {
    "n": 59,
    "slug": "challenge-amazoneksclustersetup-eks-basics",
    "name": "Challenge Lab: Create a cluster in Amazon EKS and install kubectl",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-amazoneksclustersetup-eks-basics"
  },
  {
    "n": 60,
    "slug": "challenge-lab-deploying-scalable-ec2-instances-using-launch-templates",
    "name": "Challenge Lab: Create and Configure Amazon EC2 Auto Scaling with Launch Templates",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-deploying-scalable-ec2-instances-using-launch-templates"
  },
  {
    "n": 61,
    "slug": "challenge-lab-building-a-dynamic-workflow-with-aws-step-functions",
    "name": "Challenge Lab: Creating a workflow using different States with AWS Step Functions",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-building-a-dynamic-workflow-with-aws-step-functions"
  },
  {
    "n": 62,
    "slug": "challenge-lab-data-protection-using-aws-key-management-service",
    "name": "Challenge Lab: Data Protection Using AWS Key Management Service",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-data-protection-using-aws-key-management-service"
  },
  {
    "n": 63,
    "slug": "challenge-lab-deploy-and-connect-to-a-redis-cluster-using-amazon-elasticache",
    "name": "Challenge Lab: Deploy and Connect to a Redis Cluster using Amazon ElastiCache",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-deploy-and-connect-to-a-redis-cluster-using-amazon-elasticache"
  },
  {
    "n": 64,
    "slug": "challenge-apigatewaycloudwatchlogs-logging-setup",
    "name": "Challenge Lab: Enabling CloudWatch Logs in API Gateway",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-apigatewaycloudwatchlogs-logging-setup"
  },
  {
    "n": 65,
    "slug": "challenge-lab-enable-developer-controlled-encryption-with-aws-kms-cmks",
    "name": "Challenge Lab: Encrypt S3 bucket, EBS Volume and AMI using AWS KMS",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-enable-developer-controlled-encryption-with-aws-kms-cmks"
  },
  {
    "n": 66,
    "slug": "challenge-lab-encrypt-an-amazon-rds-instance-using-snapshot-migration-and-kms",
    "name": "Challenge Lab: How to Encrypt an Unencrypted RDS DB Instance",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-encrypt-an-amazon-rds-instance-using-snapshot-migration-and-kms"
  },
  {
    "n": 67,
    "slug": "challenge-amazonguarddutyintroduction-threat-detection-basics",
    "name": "Challenge Lab: Introduction to Amazon GuardDuty",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-amazonguarddutyintroduction-threat-detection-basics"
  },
  {
    "n": 68,
    "slug": "challenge-lab-launch-manage-a-spot-ec2-web-server",
    "name": "Challenge Lab: Launch & Manage a Spot EC2 Web Server",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-launch-manage-a-spot-ec2-web-server"
  },
  {
    "n": 69,
    "slug": "challenge-lab-migrating-ebs-volumes-from-gp2-to-gp3",
    "name": "Challenge Lab: Migrating EBS volumes from gp2 to gp3",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-migrating-ebs-volumes-from-gp2-to-gp3"
  },
  {
    "n": 70,
    "slug": "challenge-lab-secure-secret-management-with-aws-secrets-manager-and-ecs",
    "name": "Challenge Lab: Secure Secret Management with AWS Secrets Manager and ECS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-secure-secret-management-with-aws-secrets-manager-and-ecs"
  },
  {
    "n": 71,
    "slug": "challenge-lab-set-up-a-free-vpn-server-using-openvpn-on-aws",
    "name": "Challenge Lab: Set Up a Free VPN Server Using OpenVPN on AWS",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-set-up-a-free-vpn-server-using-openvpn-on-aws"
  },
  {
    "n": 72,
    "slug": "challenge-lab-stream-and-store-vpc-flow-logs-using-kinesis-firehose-and-s3",
    "name": "Challenge Lab: Transfer data to S3 using Amazon Kinesis Firehose",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Data Analytics - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-lab-stream-and-store-vpc-flow-logs-using-kinesis-firehose-and-s3"
  },
  {
    "n": 73,
    "slug": "iam-challenge-access-control-to-usersservices",
    "name": "Challenge- IAM- Access Control to Users Services",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/iam-challenge-access-control-to-usersservices"
  },
  {
    "n": 74,
    "slug": "challenge-awsvpcnacllab-case-study-on-vpc-nacl-configuration-and-compliance-auditing",
    "name": "Challenge: AWS_VPC_NACL_Lab - Case Study on VPC, NACL Configuration, and Compliance Auditing",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-awsvpcnacllab-case-study-on-vpc-nacl-configuration-and-compliance-auditing"
  },
  {
    "n": 75,
    "slug": "challenge-amazonsesintroduction-sending-emails-with-ses",
    "name": "Challenge: Amazon_SES_Introduction - Sending Emails with SES",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "25m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-amazonsesintroduction-sending-emails-with-ses"
  },
  {
    "n": 76,
    "slug": "challenge-s3transferacceleration-comparing-data-transfer-speeds",
    "name": "Challenge: Comparing Data Transfer Speeds with S3 Transfer Acceleration",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-s3transferacceleration-comparing-data-transfer-speeds"
  },
  {
    "n": 77,
    "slug": "connect-rds-from-instance-challenge-mysql-access",
    "name": "Challenge: Connecting RDS from EC2 Instance",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 10m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/connect-rds-from-instance-challenge-mysql-access"
  },
  {
    "n": 78,
    "slug": "challenge-apigatewayintroduction-api-basics",
    "name": "Challenge: Introduction to Amazon API Gateway",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-apigatewayintroduction-api-basics"
  },
  {
    "n": 79,
    "slug": "challenge-waffirewall-web-traffic-shield",
    "name": "Challenge: WAFFirewall - Web Traffic Shield",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/challenge-waffirewall-web-traffic-shield"
  },
  {
    "n": 80,
    "slug": "comparing-data-transfer-speeds-with-s3-transfer-acceleration",
    "name": "Comparing Data Transfer Speeds with S3 Transfer Acceleration",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/comparing-data-transfer-speeds-with-s3-transfer-acceleration"
  },
  {
    "n": 81,
    "slug": "configure-email-notification-on-s3-bucket-event-amazon-sns-challenge",
    "name": "Configure Email Notification on S3 Bucket Event - Amazon SNS Challenge",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "40m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/configure-email-notification-on-s3-bucket-event-amazon-sns-challenge"
  },
  {
    "n": 82,
    "slug": "configure-nat-instance-and-stream-web-logs-to-cloudwatch-using-cloudwatch-agent",
    "name": "Configure NAT Instance and Stream Web Logs to CloudWatch Using CloudWatch Agent",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/configure-nat-instance-and-stream-web-logs-to-cloudwatch-using-cloudwatch-agent"
  },
  {
    "n": 83,
    "slug": "configure-wordpress-website-using-aws-console-challenge",
    "name": "Configure WordPress Website Using AWS Console Challenge",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/configure-wordpress-website-using-aws-console-challenge"
  },
  {
    "n": 84,
    "slug": "configuring-amazon-fsx-for-lustre-with-ec2-instances-for-shared-high-performance-storage-access",
    "name": "Configuring Amazon FSx for Lustre with EC2 Instances for Shared High-Performance Storage Access",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/configuring-amazon-fsx-for-lustre-with-ec2-instances-for-shared-high-performance-storage-access"
  },
  {
    "n": 85,
    "slug": "configuring-ebs-volume-to-ecs-task",
    "name": "Configuring EBS Volume to ECS task",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/configuring-ebs-volume-to-ecs-task"
  },
  {
    "n": 86,
    "slug": "launch-amazon-ec2-instance-launch-amazon-rds-instance-connecting-rds-from-ec2-instance",
    "name": "Connecting RDS from EC2 Instance",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "55m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/launch-amazon-ec2-instance-launch-amazon-rds-instance-connecting-rds-from-ec2-instance"
  },
  {
    "n": 87,
    "slug": "create-elastic-network-interface-multiple-ips-on-an-ec2",
    "name": "Create Elastic Network Interface - Multiple IPs on an EC2",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/create-elastic-network-interface-multiple-ips-on-an-ec2"
  },
  {
    "n": 88,
    "slug": "create-redis-cluster-using-elasticache",
    "name": "Create Redis cluster using ElastiCache",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/create-redis-cluster-using-elasticache"
  },
  {
    "n": 89,
    "slug": "create-vpc-environment-challenge",
    "name": "Create VPC Environment challenge",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/create-vpc-environment-challenge"
  },
  {
    "n": 90,
    "slug": "create-a-dynamodb-table-and-perform-various-table-operations-using-nosql-workbench",
    "name": "Create a DynamoDB table and perform various table operations using NoSQL Workbench",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/create-a-dynamodb-table-and-perform-various-table-operations-using-nosql-workbench"
  },
  {
    "n": 91,
    "slug": "create-a-cluster-in-amazon-eks-and-install-kubectl",
    "name": "Create a cluster in Amazon EKS and install kubectl",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/create-a-cluster-in-amazon-eks-and-install-kubectl"
  },
  {
    "n": 92,
    "slug": "create-a-sample-web-application-and-monitor-it-in-aws-x-ray",
    "name": "Create a sample Web Application and monitor it in AWS X-Ray",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "40m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/create-a-sample-web-application-and-monitor-it-in-aws-x-ray"
  },
  {
    "n": 93,
    "slug": "create-and-configure-amazon-ec2-auto-scaling-with-launch-templates",
    "name": "Create and Configure Amazon EC2 Auto Scaling with Launch Templates",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "55m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/create-and-configure-amazon-ec2-auto-scaling-with-launch-templates"
  },
  {
    "n": 94,
    "slug": "creating-events-in-cloudwatch-challenge",
    "name": "Creating Events in CloudWatch Challenge",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-events-in-cloudwatch-challenge"
  },
  {
    "n": 95,
    "slug": "creating-nat-gateways-in-aws",
    "name": "Creating NAT Gateways in AWS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-nat-gateways-in-aws"
  },
  {
    "n": 96,
    "slug": "creating-new-ec2-instance-using-snapshot",
    "name": "Creating New EC2 Instance using Snapshot",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-new-ec2-instance-using-snapshot"
  },
  {
    "n": 97,
    "slug": "creating-serverless-contact-forms-with-aws",
    "name": "Creating Serverless Contact Forms with AWS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-serverless-contact-forms-with-aws"
  },
  {
    "n": 98,
    "slug": "creating-a-user-pool-in-aws-cognito",
    "name": "Creating a User Pool in AWS Cognito",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-a-user-pool-in-aws-cognito"
  },
  {
    "n": 99,
    "slug": "creating-a-user-pool-in-aws-cognito-using-terraform",
    "name": "Creating a User Pool in AWS Cognito Using Terraform",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-a-user-pool-in-aws-cognito-using-terraform"
  },
  {
    "n": 100,
    "slug": "creating-a-workflow-using-different-states-with-aws-step-functions",
    "name": "Creating a workflow using different States with AWS Step Functions",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-a-workflow-using-different-states-with-aws-step-functions"
  },
  {
    "n": 101,
    "slug": "creating-an-s3-lifecycle-policy",
    "name": "Creating an S3 Lifecycle Policy",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-an-s3-lifecycle-policy"
  },
  {
    "n": 102,
    "slug": "creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket",
    "name": "Creating and Subscribing to SNS Topics, Adding SNS event for S3 bucket",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket"
  },
  {
    "n": 103,
    "slug": "creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket-challenge-bucket-monitor",
    "name": "Creating and Subscribing to SNS Topics, Adding SNS event for S3 bucket Challenge -  Bucket Monitor",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/creating-and-subscribing-to-sns-topics-adding-sns-event-for-s3-bucket-challenge-bucket-monitor"
  },
  {
    "n": 104,
    "slug": "data-integration-and-transformation-with-aws-glue",
    "name": "Data Integration and Transformation with AWS Glue",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "2h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Machine Learning - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/data-integration-and-transformation-with-aws-glue"
  },
  {
    "n": 105,
    "slug": "deploy-container-using-aws-app-runner",
    "name": "Deploy Container using AWS App Runner",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/deploy-container-using-aws-app-runner"
  },
  {
    "n": 106,
    "slug": "deploying-aws-file-gateway-on-vmware-esxi-to-enable-hybrid-cloud-storage-with-enterprise-grade-security-and-scalability",
    "name": "Deploying AWS File Gateway on VMware  ESXi to enable hybrid cloud storage with enterprise-grade security and scalability",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/deploying-aws-file-gateway-on-vmware-esxi-to-enable-hybrid-cloud-storage-with-enterprise-grade-security-and-scalability"
  },
  {
    "n": 107,
    "slug": "deploying-amazon-rds-multi-az-and-read-replica-simulate-failover",
    "name": "Deploying Amazon RDS Multi-AZ and Read Replica, Simulate Failover",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/deploying-amazon-rds-multi-az-and-read-replica-simulate-failover"
  },
  {
    "n": 108,
    "slug": "deploying-a-highly-available-web-application-and-bastion-host-in-aws",
    "name": "Deploying a Highly Available Web Application and Bastion Host in AWS",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/deploying-a-highly-available-web-application-and-bastion-host-in-aws"
  },
  {
    "n": 109,
    "slug": "deploying-a-highly-available-web-application-and-bastion-host-in-aws-challenge-bastion-setup",
    "name": "Deploying a Highly Available Web Application and Bastion Host in AWS Challenge - Bastion Setup",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/deploying-a-highly-available-web-application-and-bastion-host-in-aws-challenge-bastion-setup"
  },
  {
    "n": 110,
    "slug": "difference-between-sqs-visibility-timeout-and-delay-queue",
    "name": "Difference between SQS Visibility Timeout and Delay Queue",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/difference-between-sqs-visibility-timeout-and-delay-queue"
  },
  {
    "n": 111,
    "slug": "discover-sensitive-data-present-in-s3-bucket-using-amazon-macie",
    "name": "Discover sensitive data present in S3 bucket using Amazon Macie",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Security - Specialty",
      "AWS Certified Machine Learning - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/discover-sensitive-data-present-in-s3-bucket-using-amazon-macie"
  },
  {
    "n": 112,
    "slug": "dynamodb-global-secondary-index",
    "name": "DynamoDB & Global Secondary Index",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/dynamodb-global-secondary-index"
  },
  {
    "n": 113,
    "slug": "ebs-multi-attach",
    "name": "EBS Multi- Attach",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/ebs-multi-attach"
  },
  {
    "n": 114,
    "slug": "ec2-challenge-cloud-core-compute-quest",
    "name": "EC2  Challenge-Cloud-Core Compute Quest",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/ec2-challenge-cloud-core-compute-quest"
  },
  {
    "n": 115,
    "slug": "enable-vpc-peering-through-transit-gateway-challenge",
    "name": "Enable VPC Peering through Transit Gateway Challenge",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/enable-vpc-peering-through-transit-gateway-challenge"
  },
  {
    "n": 116,
    "slug": "enable-sticky-sessions-in-application-load-balancer",
    "name": "Enable sticky sessions in Application Load balancer",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/enable-sticky-sessions-in-application-load-balancer"
  },
  {
    "n": 117,
    "slug": "enabling-cloudwatch-logs-in-api-gateway",
    "name": "Enabling CloudWatch Logs in API Gateway",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/enabling-cloudwatch-logs-in-api-gateway"
  },
  {
    "n": 118,
    "slug": "encrypt-s3-bucket-ebs-volume-and-ami-using-aws-kms",
    "name": "Encrypt S3 bucket, EBS Volume and AMI using AWS KMS",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/encrypt-s3-bucket-ebs-volume-and-ami-using-aws-kms"
  },
  {
    "n": 119,
    "slug": "encryption-and-decryption-using-kms",
    "name": "Encryption and Decryption Using KMS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/encryption-and-decryption-using-kms"
  },
  {
    "n": 120,
    "slug": "export-amazon-rds-db-snapshot-to-s3",
    "name": "Export Amazon RDS DB Snapshot to S3",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "2h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/export-amazon-rds-db-snapshot-to-s3"
  },
  {
    "n": 121,
    "slug": "find-vulnerabilities-on-inspector2-using-lambda-scanning",
    "name": "Find vulnerabilities on Inspector2 using Lambda scanning",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/find-vulnerabilities-on-inspector2-using-lambda-scanning"
  },
  {
    "n": 122,
    "slug": "getting-started-with-amazon-elastic-container-service-using-fargate",
    "name": "Getting Started with Amazon Elastic Container Service using Fargate",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/getting-started-with-amazon-elastic-container-service-using-fargate"
  },
  {
    "n": 123,
    "slug": "hibernating-an-ec2-instance",
    "name": "Hibernating an EC2 Instance",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/hibernating-an-ec2-instance"
  },
  {
    "n": 124,
    "slug": "how-to-create-virtual-private-cloud-vpc-with-aws-cloudformation",
    "name": "How to Create Virtual Private Cloud (VPC) with AWS CloudFormation",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "55m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/how-to-create-virtual-private-cloud-vpc-with-aws-cloudformation"
  },
  {
    "n": 125,
    "slug": "how-to-encrypt-an-s3-bucket-using-aws-kms-and-monitor-the-activities-with-cloudtrail",
    "name": "How to Encrypt an S3 bucket using AWS KMS and monitor the activities with CloudTrail",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "50m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/how-to-encrypt-an-s3-bucket-using-aws-kms-and-monitor-the-activities-with-cloudtrail"
  },
  {
    "n": 126,
    "slug": "how-to-encrypt-an-unencrypted-rds-db-instance",
    "name": "How to Encrypt an Unencrypted RDS DB Instance",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 20m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/how-to-encrypt-an-unencrypted-rds-db-instance"
  },
  {
    "n": 127,
    "slug": "how-to-query-into-rds-mysql-using-aws-lambda",
    "name": "How to Query into RDS MySQL Using AWS Lambda",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/how-to-query-into-rds-mysql-using-aws-lambda"
  },
  {
    "n": 128,
    "slug": "how-to-setup-a-free-vpn-server-in-aws",
    "name": "How to setup a free VPN server in AWS",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/how-to-setup-a-free-vpn-server-in-aws"
  },
  {
    "n": 129,
    "slug": "hybrid-monitoring-system-deploymentusing-prometheus-with-grafana-on-awsand-vmware",
    "name": "Hybrid Monitoring System Deployment using Prometheus with Grafana on AWS and VMware",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/hybrid-monitoring-system-deploymentusing-prometheus-with-grafana-on-awsand-vmware"
  },
  {
    "n": 130,
    "slug": "hybrid-web-app-using-vmware-ubuntu-and-aws-rds",
    "name": "Hybrid web app using VMware Ubuntu and AWS RDS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/hybrid-web-app-using-vmware-ubuntu-and-aws-rds"
  },
  {
    "n": 131,
    "slug": "implement-data-backup-on-ubuntu-vmware-to-amazon-s3",
    "name": "Implement Data Backup on Ubuntu VMware to Amazon S3",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/implement-data-backup-on-ubuntu-vmware-to-amazon-s3"
  },
  {
    "n": 132,
    "slug": "implementing-aws-waf-with-alb-to-block-sql-injection-geo-location-and-query-string",
    "name": "Implementing AWS WAF with ALB to block SQL Injection, Geo Location and Query string",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "2h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/implementing-aws-waf-with-alb-to-block-sql-injection-geo-location-and-query-string"
  },
  {
    "n": 133,
    "slug": "implementing-vpc-peering-on-aws",
    "name": "Implementing VPC peering on AWS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/implementing-vpc-peering-on-aws"
  },
  {
    "n": 134,
    "slug": "integrating-api-gateway-with-lambda-function-challenge",
    "name": "Integrating API Gateway with Lambda Function Challenge",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/integrating-api-gateway-with-lambda-function-challenge"
  },
  {
    "n": 135,
    "slug": "introduction-sqs-deadletter-queue",
    "name": "Introduction SQS DeadLetter Queue",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-sqs-deadletter-queue"
  },
  {
    "n": 136,
    "slug": "introduction-to-aws-dynamodb",
    "name": "Introduction to AWS DynamoDB",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-aws-dynamodb"
  },
  {
    "n": 137,
    "slug": "introduction-to-aws-elastic-beanstalk",
    "name": "Introduction to AWS Elastic Beanstalk",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-aws-elastic-beanstalk"
  },
  {
    "n": 138,
    "slug": "introduction-to-aws-elastic-load-balancing",
    "name": "Introduction to AWS Elastic Load Balancing",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-aws-elastic-load-balancing"
  },
  {
    "n": 139,
    "slug": "introduction-to-aws-identity-access-management-iam",
    "name": "Introduction to AWS Identity Access Management (IAM)",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-aws-identity-access-management-iam"
  },
  {
    "n": 140,
    "slug": "introduction-to-aws-relational-database-service",
    "name": "Introduction to AWS Relational Database Service",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "50m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-aws-relational-database-service"
  },
  {
    "n": 141,
    "slug": "introduction-to-aws-step-functions",
    "name": "Introduction to AWS Step Functions",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-aws-step-functions"
  },
  {
    "n": 142,
    "slug": "introduction-to-amazon-api-gateway",
    "name": "Introduction to Amazon API Gateway",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "15m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-api-gateway"
  },
  {
    "n": 143,
    "slug": "introduction-to-amazon-aurora-challenge-aurora-connect",
    "name": "Introduction to Amazon Aurora Connect - Challenge Lab",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Database - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-aurora-challenge-aurora-connect"
  },
  {
    "n": 144,
    "slug": "introduction-to-amazon-auto-scaling",
    "name": "Introduction to Amazon Auto Scaling",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "55m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-auto-scaling"
  },
  {
    "n": 145,
    "slug": "introduction-to-amazon-cloudformation",
    "name": "Introduction to Amazon CloudFormation",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-cloudformation"
  },
  {
    "n": 146,
    "slug": "introduction-to-amazon-cloudfront",
    "name": "Introduction to Amazon CloudFront",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-cloudfront"
  },
  {
    "n": 147,
    "slug": "introduction-to-amazon-elastic-compute-cloud-ec2",
    "name": "Introduction to Amazon Elastic Compute Cloud (EC2)",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-elastic-compute-cloud-ec2"
  },
  {
    "n": 148,
    "slug": "introduction-to-amazon-elastic-container-service-ecs",
    "name": "Introduction to Amazon Elastic Container Service (ECS)",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-elastic-container-service-ecs"
  },
  {
    "n": 149,
    "slug": "introduction-to-amazon-guardduty",
    "name": "Introduction to Amazon GuardDuty",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-guardduty"
  },
  {
    "n": 150,
    "slug": "introduction-to-amazon-guardduty-using-terraform",
    "name": "Introduction to Amazon GuardDuty using Terraform",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-guardduty-using-terraform"
  },
  {
    "n": 151,
    "slug": "introduction-to-amazon-lambda",
    "name": "Introduction to Amazon Lambda",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-lambda"
  },
  {
    "n": 152,
    "slug": "introduction-to-amazon-simple-email-service-ses",
    "name": "Introduction to Amazon Simple Email Service SES",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "15m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-simple-email-service-ses"
  },
  {
    "n": 153,
    "slug": "introduction-to-amazon-simple-storage-service-s3",
    "name": "Introduction to Amazon Simple Storage Service (S3)",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-amazon-simple-storage-service-s3"
  },
  {
    "n": 154,
    "slug": "introduction-to-creating-aws-vpc-flow-logs",
    "name": "Introduction to Creating AWS VPC Flow Logs",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-creating-aws-vpc-flow-logs"
  },
  {
    "n": 155,
    "slug": "introduction-to-simple-queuing-service-sqs",
    "name": "Introduction to Simple Queuing Service (SQS)",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-simple-queuing-service-sqs"
  },
  {
    "n": 156,
    "slug": "introduction-to-simple-queuing-service-sqs-challenge-queue-configuration",
    "name": "Introduction to Simple Queuing Service (SQS) Challenge - Queue Configuration",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/introduction-to-simple-queuing-service-sqs-challenge-queue-configuration"
  },
  {
    "n": 157,
    "slug": "launch-ecs-container-challenge",
    "name": "Launch ECS Container Challenge",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/launch-ecs-container-challenge"
  },
  {
    "n": 158,
    "slug": "launch-a-spot-instance-with-amazon-ec2",
    "name": "Launch a Spot Instance with Amazon EC2",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/launch-a-spot-instance-with-amazon-ec2"
  },
  {
    "n": 159,
    "slug": "migrating-ebs-volumes-from-gp2-to-gp3",
    "name": "Migrating EBS volumes from gp2 to gp3",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "30m",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/migrating-ebs-volumes-from-gp2-to-gp3"
  },
  {
    "n": 160,
    "slug": "migrating-local-vm-ubuntu-database-to-aws-rds",
    "name": "Migrating Local VM Ubuntu Database to AWS RDS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/migrating-local-vm-ubuntu-database-to-aws-rds"
  },
  {
    "n": 161,
    "slug": "mount-elastic-file-system-efs-on-ec2",
    "name": "Mount Elastic File System (EFS) on EC2",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/mount-elastic-file-system-efs-on-ec2"
  },
  {
    "n": 162,
    "slug": "nat-gateway-aws-vpc-challenge",
    "name": "NAT gateway - AWS VPC Challenge",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/nat-gateway-aws-vpc-challenge"
  },
  {
    "n": 163,
    "slug": "peer-vpc-with-transit-gateway-and-its-components",
    "name": "Peer VPC with Transit Gateway and its components",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "1h 15m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/peer-vpc-with-transit-gateway-and-its-components"
  },
  {
    "n": 164,
    "slug": "query-vpc-flow-log-using-amazon-athena",
    "name": "Query VPC Flow log using Amazon Athena",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Data Analytics - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/query-vpc-flow-log-using-amazon-athena"
  },
  {
    "n": 165,
    "slug": "query-items-in-dynamodb-with-partiql-statements",
    "name": "Query items in DynamoDB with PartiQL Statements",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/query-items-in-dynamodb-with-partiql-statements"
  },
  {
    "n": 166,
    "slug": "querying-data-in-s3-with-amazon-athena",
    "name": "Querying Data in S3 with Amazon Athena",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Data Analytics - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/querying-data-in-s3-with-amazon-athena"
  },
  {
    "n": 167,
    "slug": "resizing-amazon-ebs-volume",
    "name": "Resizing Amazon EBS Volume",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/resizing-amazon-ebs-volume"
  },
  {
    "n": 168,
    "slug": "resizing-amazon-ebs-volume-challege-disk-scaling",
    "name": "Resizing Amazon EBS Volume Challege - Disk Scaling",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/resizing-amazon-ebs-volume-challege-disk-scaling"
  },
  {
    "n": 169,
    "slug": "s3-batch-operation",
    "name": "S3 Batch Operation",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/s3-batch-operation"
  },
  {
    "n": 170,
    "slug": "serverless-email-sender-with-amazon-simple-email-service",
    "name": "Serverless Email Sender with Amazon Simple-Email-Service",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/serverless-email-sender-with-amazon-simple-email-service"
  },
  {
    "n": 171,
    "slug": "setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer",
    "name": "Setting up the VPC environment, launching EC2 instances, and testing reachability using the AWS  Reachability Analyzer",
    "type": "Guided Labs",
    "level": "Fundamental",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Advanced Networking - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/setting-up-the-vpc-environment-launching-ec2-instances-and-testing-reachability-using-the-aws-reachability-analyzer"
  },
  {
    "n": 172,
    "slug": "setup-cross-region-replication-and-versioning-in-s3",
    "name": "Setup Cross Region Replication and Versioning in S3",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "45m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Solutions Architect - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/setup-cross-region-replication-and-versioning-in-s3"
  },
  {
    "n": 173,
    "slug": "transfer-data-to-s3-using-amazon-kinesis-firehose",
    "name": "Transfer data to S3 using Amazon Kinesis Firehose",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified Data Analytics - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/transfer-data-to-s3-using-amazon-kinesis-firehose"
  },
  {
    "n": 174,
    "slug": "troubleshooting-connectivity-issues-between-vpc-ec2-and-load-balancer",
    "name": "Troubleshooting Connectivity Issues Between VPC, EC2, and Load Balancer",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified DevOps Engineer - Professional"
    ],
    "url": "https://business.whizlabs.com/labs/lab/troubleshooting-connectivity-issues-between-vpc-ec2-and-load-balancer"
  },
  {
    "n": 175,
    "slug": "understanding-cloudfront-origin-groups",
    "name": "Understanding CloudFront Origin Groups",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h 30m",
    "certifications": [
      "AWS Certified Developer - Associate",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/understanding-cloudfront-origin-groups"
  },
  {
    "n": 176,
    "slug": "understanding-and-configuring-layered-security-in-an-aws-vpc",
    "name": "Understanding and Configuring Layered Security in an AWS VPC",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/understanding-and-configuring-layered-security-in-an-aws-vpc"
  },
  {
    "n": 177,
    "slug": "understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform",
    "name": "Understanding and Configuring Layered Security in an AWS VPC Using Terraform",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Cloud Practitioner",
      "AWS Certified Solutions Architect - Associate",
      "AWS Certified SysOps Administrator - Associate",
      "AWS Certified Solutions Architect - Professional",
      "AWS Certified Advanced Networking - Specialty",
      "AWS Certified Security - Specialty"
    ],
    "url": "https://business.whizlabs.com/labs/lab/understanding-and-configuring-layered-security-in-an-aws-vpc-using-terraform"
  },
  {
    "n": 178,
    "slug": "use-aws-secrets-manager-secret-with-amazon-ecs",
    "name": "Use AWS Secrets Manager secret with Amazon ECS",
    "type": "Guided Labs",
    "level": "Intermediate",
    "duration": "1h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/use-aws-secrets-manager-secret-with-amazon-ecs"
  },
  {
    "n": 179,
    "slug": "wokwi-iot-device-simulation-with-aws-iot-core-real-time-dashboard",
    "name": "Wokwi IoT Device Simulation with AWS IoT Core Real-Time Dashboard",
    "type": "Guided Labs",
    "level": "Advanced",
    "duration": "2h",
    "certifications": [
      "AWS Certified Solutions Architect - Associate"
    ],
    "url": "https://business.whizlabs.com/labs/lab/wokwi-iot-device-simulation-with-aws-iot-core-real-time-dashboard"
  }
]
