/**
 * Generates data/saaCertLabs.ts from the cloud-labs SAA cert markdown table.
 *
 * The lab *content* already lives in data/labsCatalog.ts (keyed by slug); this
 * file only carries the cert-level metadata that the catalog lacks — Type,
 * Certifications mapping, and the source URL — plus the slug (derived from the
 * URL's last path segment, matching lib/labs.ts `slugFromLabUrl`).
 *
 * Run: bun run scripts/compile-saa-cert-labs.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

// Source table lives in the sibling cloud-labs repo.
const SOURCE = resolve(
  import.meta.dirname,
  '../../cloud-labs/docs/cloud/cert-aws-certified-solutions-architect---associate.md',
)
const OUT = resolve(import.meta.dirname, '../data/saaCertLabs.ts')

const slugFromLabUrl = (url: string): string =>
  new URL(url).pathname.replace(/\/$/, '').split('/').pop() ?? 'lab'

const raw = readFileSync(SOURCE, 'utf-8')

const rows = raw
  .split('\n')
  // Keep only table-body rows: start with "|", and the first cell is a number.
  .filter((line) => /^\|\s*\d+\s*\|/.test(line))
  .map((line) => {
    // Split on "|", drop the leading/trailing empty cells, trim each.
    const cells = line.split('|').slice(1, -1).map((c) => c.trim())
    const [n, name, type, level, duration, certs, urlCell] = cells
    const url = urlCell.match(/\((https?:\/\/[^)]+)\)/)?.[1] ?? ''
    return {
      n: Number(n),
      slug: slugFromLabUrl(url),
      name,
      type,
      level,
      duration,
      certifications: certs
        .split(',')
        .map((c) => c.trim())
        .filter(Boolean),
      url,
    }
  })

const body = `// Auto-generated by scripts/compile-saa-cert-labs.ts — do not edit
import type { LabLevel } from '@/lib/labs'

export type SaaCertLab = {
  /** 1-based row number from the source catalog table. */
  n: number
  /** Matches the slug used in data/labsCatalog.ts (URL's last path segment). */
  slug: string
  name: string
  type: string
  level: LabLevel
  duration: string
  certifications: string[]
  url: string
}

export const saaCertLabs: SaaCertLab[] = ${JSON.stringify(rows, null, 2)}
`

writeFileSync(OUT, body)
console.log(`Wrote ${rows.length} labs to ${OUT}`)
