/**
 * Bundle scripts/labs/*.json → data/labsCatalog.ts for local next dev (no D1).
 *
 * Usage: bun run labs:compile
 */

import { readdirSync, readFileSync, writeFileSync, unlinkSync, existsSync } from 'fs'
import { join, resolve } from 'path'
import type { Lab } from '../lib/labs'
import { sanitizeLab } from '../lib/sanitize-lab'

const LABS_DIR = resolve('scripts/labs')
const OUT_LABS = resolve('data/labsCatalog.ts')
const LEGACY_OUT = resolve('data/labsWhizlabs.ts')
const OUT_ORDER = resolve('data/labsCourseOrder.ts')
const COURSE_INDEX = join(LABS_DIR, 'course-index.json')

const files = readdirSync(LABS_DIR).filter((f) => f.endsWith('.json') && f !== 'course-index.json')

const labs = files
  .map((file) => {
    const raw = readFileSync(join(LABS_DIR, file), 'utf8')
    return sanitizeLab(JSON.parse(raw) as Lab)
  })
  .sort((a, b) => a.title.localeCompare(b.title))

const labsBody = `// Auto-generated by scripts/compile-labs-from-json.ts — do not edit
import type { Lab } from '@/lib/labs'

export const labsCatalog: Lab[] = ${JSON.stringify(labs, null, 2)}
`

writeFileSync(OUT_LABS, labsBody)
if (existsSync(LEGACY_OUT)) unlinkSync(LEGACY_OUT)

const courseRaw = readFileSync(COURSE_INDEX, 'utf8')
const courseIndex = JSON.parse(courseRaw) as {
  total: number
  labs: Array<{
    index: number
    title: string
    slug: string
    category: string
    duration: string
    url?: string
  }>
}

const orderEntries = courseIndex.labs.map(({ index, title, slug, category, duration }) => ({
  index,
  title,
  slug,
  category,
  duration,
}))

const orderBody = `// Auto-generated by scripts/compile-labs-from-json.ts — do not edit
export type CourseLabEntry = {
  index: number
  title: string
  slug: string
  category: string
  duration: string
}

export const labsCourseTotal = ${courseIndex.total}

export const labsCourseOrder: CourseLabEntry[] = ${JSON.stringify(orderEntries, null, 2)}
`

writeFileSync(OUT_ORDER, orderBody)
console.log(`Compiled ${labs.length} labs → data/labsCatalog.ts`)
console.log(`Compiled ${orderEntries.length} course entries → data/labsCourseOrder.ts`)
