/**
 * Bundle scripts/labs/*.json → data/labsWhizlabs.ts for local next dev (no D1).
 *
 * Usage: bun run labs:compile
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join, resolve } from 'path'
import type { Lab } from '../lib/labs'

const LABS_DIR = resolve('scripts/labs')
const OUT = resolve('data/labsWhizlabs.ts')

const files = readdirSync(LABS_DIR).filter((f) => f.endsWith('.json') && f !== 'course-index.json')

const labs = files
  .map((file) => {
    const raw = readFileSync(join(LABS_DIR, file), 'utf8')
    return JSON.parse(raw) as Lab
  })
  .sort((a, b) => a.title.localeCompare(b.title))

const body = `// Auto-generated by scripts/compile-labs-from-json.ts — do not edit
import type { Lab } from '@/lib/labs'

export const labsWhizlabs: Lab[] = ${JSON.stringify(labs, null, 2)}
`

writeFileSync(OUT, body)
console.log(`Compiled ${labs.length} labs → data/labsWhizlabs.ts`)
