/**
 * Compact indexes + static JSON for edge routes — keeps labsCatalog + awsServices
 * out of the Cloudflare Worker bundle (free tier 3 MiB gzip limit).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { allLabsFallback } from '../lib/labs-fallback'
import { domains, serviceSlug } from '../data/awsServices'

const labsLinkIndex = allLabsFallback().map((lab) => ({
  slug: lab.slug,
  title: lab.title,
}))

const deepNotesLinkIndex = domains.flatMap((domain) =>
  domain.sections.flatMap((section) =>
    section.services.map((service) => ({
      sectionId: section.id,
      sectionTitle: section.title,
      sectionIcon: section.icon,
      shortName: service.shortName,
      searchBlob: [
        service.shortName,
        service.fullName,
        ...(service.keywords ?? []),
        service.fungsi,
        service.contohGuna ?? '',
        service.scenario ?? '',
        section.title,
      ]
        .join(' ')
        .toLowerCase(),
    })),
  ),
)

const searchIndex = domains.flatMap((domain) =>
  domain.sections.flatMap((section) =>
    section.services.map((service) => ({
      shortName: service.shortName,
      fullName: service.fullName,
      domainBadge: (domain.badge ?? '').split('·')[0].trim(),
      domainVariant: domain.variant,
      slug: serviceSlug(section.id, service.shortName),
      sectionTitle: section.title,
      sectionIcon: section.icon,
      category: section.category,
      shortLower: (service.shortName ?? '').toLowerCase(),
      fullLower: (service.fullName ?? '').toLowerCase(),
      keywordsLower: ((service.keywords ?? []).join(' ')).toLowerCase(),
      descLower: [service.fungsi ?? '', service.contohGuna ?? '', service.scenario ?? ''].join(' ').toLowerCase(),
    })),
  ),
)

const labsFallback = allLabsFallback()

mkdirSync('public/data', { recursive: true })

writeFileSync(
  'data/labsLinkIndex.ts',
  `/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */\nexport const labsLinkIndex = ${JSON.stringify(labsLinkIndex, null, 2)} as const\n`,
)

writeFileSync(
  'data/deepNotesLinkIndex.ts',
  `/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */\nexport const deepNotesLinkIndex = ${JSON.stringify(deepNotesLinkIndex, null, 2)} as const\n`,
)

writeFileSync(
  'data/searchIndex.ts',
  `/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */\nexport type SearchIndexDoc = {\n  shortName: string\n  fullName: string\n  domainBadge: string\n  domainVariant: 'd1' | 'd2' | 'd3' | 'd4'\n  slug: string\n  sectionTitle: string\n  sectionIcon: string\n  category: string\n  shortLower: string\n  fullLower: string\n  keywordsLower: string\n  descLower: string\n}\n\nexport const searchIndex: SearchIndexDoc[] = ${JSON.stringify(searchIndex, null, 2)}\n`,
)

writeFileSync('public/data/labs-fallback.json', JSON.stringify(labsFallback))

console.log(`Wrote data/labsLinkIndex.ts (${labsLinkIndex.length} labs)`)
console.log(`Wrote data/deepNotesLinkIndex.ts (${deepNotesLinkIndex.length} services)`)
console.log(`Wrote data/searchIndex.ts (${searchIndex.length} services)`)
console.log(`Wrote public/data/labs-fallback.json (${labsFallback.length} labs)`)
