/**
 * Compact indexes for AI hint/internal-links — keeps labsCatalog + awsServices
 * out of the Cloudflare Worker bundle (free tier 3 MiB limit).
 */
import { writeFileSync } from 'node:fs'
import { allLabsFallback } from '../lib/labs-fallback'
import { domains } from '../data/awsServices'

const labsLinkIndex = allLabsFallback().map((lab) => ({
  slug: lab.slug,
  title: lab.title,
}))

const deepNotesLinkIndex = domains.flatMap((domain) =>
  domain.sections.flatMap((section) =>
    section.services.map((service) => ({
      sectionId: section.id,
      sectionTitle: section.title,
      sectionIcon: section.icon,
      shortName: service.shortName,
      searchBlob: [
        service.shortName,
        service.fullName,
        ...(service.keywords ?? []),
        service.fungsi,
        service.contohGuna ?? '',
        service.scenario ?? '',
        section.title,
      ]
        .join(' ')
        .toLowerCase(),
    })),
  ),
)

writeFileSync(
  'data/labsLinkIndex.ts',
  `/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */\nexport const labsLinkIndex = ${JSON.stringify(labsLinkIndex, null, 2)} as const\n`,
)

writeFileSync(
  'data/deepNotesLinkIndex.ts',
  `/** Generated by scripts/generate-ai-link-indexes.ts — do not edit by hand. */\nexport const deepNotesLinkIndex = ${JSON.stringify(deepNotesLinkIndex, null, 2)} as const\n`,
)

console.log(`Wrote data/labsLinkIndex.ts (${labsLinkIndex.length} labs)`)
console.log(`Wrote data/deepNotesLinkIndex.ts (${deepNotesLinkIndex.length} services)`)
