/**
 * SAA-C03 library labs NOT in domain catalog or study checklist → data/labsLibraryOrder.ts
 *
 * Usage: bun run scripts/generate-labs-library-order.ts
 */

import { existsSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'
import { labsChecklistOrder } from '../data/labsChecklistOrder'
import { labsCourseOrder } from '../data/labsCourseOrder'

const LIBRARY_INDEX = resolve('scripts/labs/library-index.json')
const OUT = resolve('data/labsLibraryOrder.ts')

export type LibrarySectionId = 'guided' | 'challenge' | 'project' | 'sandbox'

export type LibraryLabEntry = {
  index: number
  title: string
  slug: string
  duration: string
  sectionId: LibrarySectionId
  externalUrl: string
}

const librarySections: Array<{ id: LibrarySectionId; label: string }> = [
  { id: 'guided', label: 'Guided labs' },
  { id: 'challenge', label: 'Challenges' },
  { id: 'project', label: 'Projects' },
  { id: 'sandbox', label: 'Sandboxes' },
]

const formatDuration = (seconds: number): string => {
  const hours = Math.floor(seconds / 3600)
  const mins = Math.floor((seconds % 3600) / 60)
  if (hours === 0) return `${mins}m`
  if (mins === 0) return `${hours}h`
  return `${hours}h ${mins}m`
}

const inferSection = (title: string, slug: string, labType: number): LibrarySectionId => {
  const haystack = `${title} ${slug}`.toLowerCase()
  if (labType === 2 || haystack.includes('challenge')) return 'challenge'
  if (labType === 3 || haystack.includes('project')) return 'project'
  if (labType === 4 || haystack.includes('sandbox')) return 'sandbox'
  return 'guided'
}

const main = (): void => {
  if (!existsSync(LIBRARY_INDEX)) {
    console.error(`Missing ${LIBRARY_INDEX} — run: bun run labs:library:discover`)
    process.exit(1)
  }

  const library = JSON.parse(readFileSync(LIBRARY_INDEX, 'utf8')) as {
    total: number
    labs: Array<{ title: string; slug: string; durationSeconds?: number; duration?: number; labType: number; url: string }>
  }

  const exclude = new Set([
    ...labsCourseOrder.map((entry) => entry.slug),
    ...labsChecklistOrder.map((entry) => entry.slug).filter(Boolean),
  ])

  const others = library.labs.filter((lab) => !exclude.has(lab.slug))
  const entries: LibraryLabEntry[] = others.map((lab, index) => {
    const durationSeconds = lab.durationSeconds ?? lab.duration ?? 0
    return {
      index: index + 1,
      title: lab.title,
      slug: lab.slug,
      duration: formatDuration(durationSeconds),
      sectionId: inferSection(lab.title, lab.slug, lab.labType),
      externalUrl: lab.url ?? `https://business.whizlabs.com/labs/${lab.slug}`,
    }
  })

  const body = `// Auto-generated by scripts/generate-labs-library-order.ts — do not edit
export type LibrarySectionId = 'guided' | 'challenge' | 'project' | 'sandbox'

export type LibraryLabEntry = {
  index: number
  title: string
  slug: string
  duration: string
  sectionId: LibrarySectionId
  externalUrl: string
}

export const librarySections: Array<{ id: LibrarySectionId; label: string }> = ${JSON.stringify(librarySections, null, 2)}

/** SAA-C03 Whizlabs library labs not in domain catalog or study checklist */
export const labsLibraryTotal = ${entries.length}

export const labsLibraryOrder: LibraryLabEntry[] = ${JSON.stringify(entries, null, 2)}
`

  writeFileSync(OUT, body)
  console.log(`Generated ${entries.length} library-only labs → ${OUT}`)
  librarySections.forEach((section) => {
    const count = entries.filter((entry) => entry.sectionId === section.id).length
    if (count > 0) console.log(`  ${section.id}: ${count}`)
  })
}

main()
