import { writeFileSync } from 'fs'

const escape = (s: string) => s.replace(/'/g, "''")

interface Q {
  id: string
  domain: 'd1' | 'd2' | 'd3' | 'd4'
  domainLabel: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  scenario: string
  options: { id: string; text: string }[]
  correctId: string
  explanation: string
  reference: string
  keywords: string[]
  screenshotUrl: string
}

const questions: Q[] = [
  {
    id: 'wz5-001', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-001.png',
    scenario: 'A manufacturing firm has a large fleet of smart devices deployed worldwide. Each device uploads hourly telemetry logs to an Amazon S3 bucket. Leadership wants comprehensive, executive-ready dashboards that show device usage trends and include forecasting (e.g., seasonality, future utilization) without first standing up a data warehouse and with minimal operational overhead. Which tool is best suited to deliver those dashboards?',
    options: [
      { id: 'a', text: 'Use S3 as a source for Amazon QuickSight and create dashboards for usage and forecast trends' },
      { id: 'b', text: 'Use S3 as a source for Amazon Redshift and create dashboards for usage and forecast trends' },
      { id: 'c', text: 'Copy data from S3 to DynamoDB. Use DynamoDB as a source for QuickSight and create dashboards' },
      { id: 'd', text: 'Copy data from S3 to Amazon RDS. Use RDS as a source for QuickSight and create dashboards' },
    ],
    correctId: 'a',
    explanation: 'Amazon QuickSight connects directly to Amazon S3 as a data source with no intermediate data warehouse. QuickSight includes ML-powered forecasting (ML Insights) for detecting seasonality and projecting future trends — no additional services required. Loading data into Redshift or RDS first adds complexity and cost that contradicts the minimal-overhead requirement.',
    reference: '',
    keywords: ['QuickSight', 'S3', 'dashboards', 'ML Insights', 'forecasting', 'IoT analytics', 'no data warehouse'],
  },
  {
    id: 'wz5-002', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-002.png',
    scenario: 'A company runs its web application on Amazon EC2 instances in an Auto Scaling group. The Operations team must capture custom, application-level metrics from every instance and visualize them aggregated at the Auto Scaling group level (with the ability to drill down to individual instances when needed). What configuration should be implemented to achieve these metrics as required?',
    options: [
      { id: 'a', text: 'Use CloudWatch metrics with detailed monitoring; aggregation occurs by default' },
      { id: 'b', text: 'Install the unified CloudWatch agent on all instances and use aggregation_dimensions to aggregate metrics across the ASG' },
      { id: 'c', text: 'Install the agent and use append-config to aggregate across the ASG' },
      { id: 'd', text: 'Use detailed monitoring and build a single CloudWatch dashboard for all instances' },
    ],
    correctId: 'b',
    explanation: 'The unified CloudWatch agent supports custom application-level metrics and the aggregation_dimensions configuration option, which lets you aggregate metrics by Auto Scaling group name while retaining per-instance visibility. Standard EC2 detailed monitoring only surfaces hypervisor-level metrics; it does not expose guest OS or application-level metrics, nor does it support aggregation by ASG.',
    reference: '',
    keywords: ['CloudWatch agent', 'aggregation_dimensions', 'Auto Scaling group', 'custom metrics', 'application metrics'],
  },
  {
    id: 'wz5-003', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-003.png',
    scenario: 'A critical web application runs on multiple Amazon EC2 instances behind a load balancer and managed by an Auto Scaling group. You need to upgrade software on one specific instance with zero user impact (no traffic during the upgrade) and, once complete, ensure that the same instance seamlessly returns to service within the Auto Scaling group. What steps should you take to complete this upgrade?',
    options: [
      { id: 'a', text: 'Hibernate the instance and upgrade offline' },
      { id: 'b', text: 'Use cooldown timers during the upgrade' },
      { id: 'c', text: 'Put the instance in Standby state, perform the upgrade, then return it to InService' },
      { id: 'd', text: 'Use lifecycle hooks; after timers expire, it re-joins' },
    ],
    correctId: 'c',
    explanation: 'The Auto Scaling group Standby feature allows you to move a specific instance out of the active pool without terminating it. While in Standby, the instance stops receiving load balancer traffic but remains in the ASG. After completing the upgrade, you return the instance to InService and it re-registers with the load balancer. This is the purpose-built mechanism for in-place maintenance of individual ASG instances.',
    reference: '',
    keywords: ['Auto Scaling', 'Standby', 'InService', 'maintenance', 'zero downtime', 'instance upgrade'],
  },
  {
    id: 'wz5-004', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-004.png',
    scenario: 'An e-commerce site runs on two EC2 instances behind an Elastic Load Balancer. During a recent incident, one instance failed and traffic collapsed onto the remaining instance, causing dramatically slower response times. Management wants to prevent a repeat of this capacity loss due to single-instance failure and expects automatic recovery when an instance becomes unhealthy. What is the best course of action?',
    options: [
      { id: 'a', text: 'Upsize to the largest instance type' },
      { id: 'b', text: 'Use CloudWatch with VPC Flow Logs to monitor instances' },
      { id: 'c', text: 'Configure ELB health checks and implement Auto Scaling' },
      { id: 'd', text: 'Replicate the two-instance setup in several Regions' },
    ],
    correctId: 'c',
    explanation: 'ELB health checks detect unhealthy instances and stop routing traffic to them. An Auto Scaling group configured to maintain a minimum instance count automatically launches replacement instances when one fails. This combination provides automatic failure detection and capacity recovery — solving both the single-instance failure concern and the slow-recovery problem.',
    reference: '',
    keywords: ['ELB health check', 'Auto Scaling', 'automatic recovery', 'high availability', 'fault tolerance'],
  },
  {
    id: 'wz5-005', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-005.png',
    scenario: 'A small third-party vendor team located on-premises needs temporary, secure access to databases hosted in a single Amazon VPC. Access must be user-authenticated, limited only to the required subnets, and cost-efficient with minimal setup/management. Which connectivity option should be deployed to meet these requirements most cost-effectively?',
    options: [
      { id: 'a', text: 'Deploy an AWS Client VPN from vendor machines to the VPC' },
      { id: 'b', text: 'Use AWS Direct Connect' },
      { id: 'c', text: 'Use AWS Managed Site-to-Site VPN to a Virtual Private Gateway' },
      { id: 'd', text: 'Use AWS Managed Site-to-Site VPN to a Transit Gateway' },
    ],
    correctId: 'a',
    explanation: 'AWS Client VPN is a managed VPN service that allows individual users to authenticate (via Active Directory, SAML, or certificates) and connect to a VPC. It supports authorization rules that restrict each user to only the specific subnets they need. Client VPN is ideal for small teams needing temporary, user-level access at low cost. Site-to-Site VPN connects entire networks, not individual users. Direct Connect is expensive and suited for persistent high-bandwidth needs.',
    reference: '',
    keywords: ['Client VPN', 'user authentication', 'VPC access', 'cost-efficient', 'third-party vendor', 'authorization rules'],
  },
  {
    id: 'wz5-006', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-006.png',
    scenario: 'Your networking team is evaluating Amazon Route 53. They need to understand its primary functions across domain management, DNS routing, traffic steering, and health awareness to support a production web presence. Which of the following are the main functions of Route 53?',
    options: [
      { id: 'a', text: 'Register domain names' },
      { id: 'b', text: 'Route internet traffic to your resources' },
      { id: 'c', text: 'Load-balance traffic among geographically distributed web servers' },
      { id: 'd', text: 'Check the health of your resources' },
      { id: 'e', text: 'All of the above' },
    ],
    correctId: 'e',
    explanation: 'Amazon Route 53 performs all four functions: (1) Domain registration — register new domains or transfer existing ones; (2) DNS routing — translate domain names to IP addresses; (3) Traffic steering — route traffic based on latency, geography, weights, or failover policies (effective load balancing across distributed servers); (4) Health checks — monitor endpoint health and route away from unhealthy resources.',
    reference: '',
    keywords: ['Route 53', 'DNS', 'domain registration', 'health checks', 'traffic routing', 'load balancing'],
  },
  {
    id: 'wz5-007', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-007.png',
    scenario: 'An online shopping platform runs microservices on Amazon ECS (EC2 launch type). The security team requires task-level security controls (e.g., security groups per task) and granular network visibility/monitoring for each task\'s traffic. Which ECS networking mode should be chosen to meet these requirements?',
    options: [
      { id: 'a', text: 'Use host networking mode' },
      { id: 'b', text: 'By default, one ENI with a primary private IP is assigned to each task' },
      { id: 'c', text: 'Use awsvpc networking mode' },
      { id: 'd', text: 'Use bridge networking mode' },
    ],
    correctId: 'c',
    explanation: 'The awsvpc networking mode gives each ECS task its own Elastic Network Interface (ENI) with a private IP address in the VPC. Because each task has its own ENI, you can apply dedicated security groups per task, use VPC Flow Logs to capture task-level traffic, and enforce granular network isolation. Host and bridge modes share the EC2 instance\'s network interface and do not support per-task security groups.',
    reference: '',
    keywords: ['ECS', 'awsvpc', 'ENI', 'task-level security group', 'network mode', 'container networking'],
  },
  {
    id: 'wz5-008', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    screenshotUrl: '/questions/wz5/wz5-008.png',
    scenario: 'A start-up plans to deploy containerized applications on Amazon ECS and needs the lowest possible latency from on-premises networks to those workloads. The solution must be highly scalable and support consistent, high CPU and memory requirements. Which deployment approach best satisfies these constraints?',
    options: [
      { id: 'a', text: 'ECS Fargate on AWS Outposts' },
      { id: 'b', text: 'ECS Fargate in Local Zones' },
      { id: 'c', text: 'ECS EC2 launch type in Local Zones' },
      { id: 'd', text: 'ECS EC2 launch type on AWS Outposts' },
    ],
    correctId: 'd',
    explanation: 'AWS Outposts brings AWS infrastructure physically on-premises, providing sub-millisecond latency to on-premises applications. AWS Fargate is NOT available on AWS Outposts — only the EC2 launch type is supported. Local Zones place AWS infrastructure in major cities but are not at your facility. Therefore, ECS with EC2 launch type on AWS Outposts provides the lowest on-premises latency with full control over CPU/memory.',
    reference: '',
    keywords: ['ECS', 'AWS Outposts', 'EC2 launch type', 'on-premises latency', 'Fargate not on Outposts', 'Local Zones'],
  },
  {
    id: 'wz5-009', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-009.png',
    scenario: 'A new application runs on an EC2 instance in a private subnet. It must access Amazon S3 and Amazon DynamoDB without the public internet. In the future, your on-premises environment will also need private access to S3. The design should be secure, cost-effective, and avoid internet traversal. What connectivity design should you implement?',
    options: [
      { id: 'a', text: 'DynamoDB via gateway endpoint; S3 via interface endpoint' },
      { id: 'b', text: 'Use a private NAT gateway' },
      { id: 'c', text: 'Use a public NAT gateway' },
      { id: 'd', text: 'Use gateway endpoints for both S3 and DynamoDB' },
    ],
    correctId: 'd',
    explanation: 'VPC gateway endpoints are free and available for both Amazon S3 and Amazon DynamoDB. They route traffic directly through the AWS network without traversing the internet, no additional charge per GB. For future on-premises access to S3, you can add a VPC interface endpoint for S3 (PrivateLink) and access it over Direct Connect or VPN. Gateway endpoints are the most cost-effective starting point for both services.',
    reference: '',
    keywords: ['VPC gateway endpoint', 'S3', 'DynamoDB', 'private access', 'no internet', 'cost-effective'],
  },
  {
    id: 'wz5-010', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-010.png',
    scenario: 'A static website named whizexample is hosted in Amazon S3. Client-side JavaScript on the site needs to make authenticated GET requests to the bucket\'s REST endpoint (example.s3.us-west-1.amazonaws.com). To permit these browser calls while maintaining security, what additional configuration is required?',
    options: [
      { id: 'a', text: 'Create CORS with Access-Control-Request-Header as GET (JSON)' },
      { id: 'b', text: 'Create CORS with Access-Control-Request-Method as GET (JSON)' },
      { id: 'c', text: 'Create CORS with Access-Control-Request-Method as GET (XML)' },
      { id: 'd', text: 'Create CORS with Access-Control-Request-Header as GET (XML)' },
    ],
    correctId: 'b',
    explanation: 'Amazon S3 CORS configuration specifies AllowedMethod (corresponding to Access-Control-Request-Method) to permit specific HTTP methods from cross-origin requests. The current S3 CORS configuration format uses JSON. The correct approach is to add a CORS rule with AllowedMethod: GET in JSON format. Using XML is the legacy format; using Access-Control-Request-Header instead of Method would be for specifying allowed request headers, not the HTTP method.',
    reference: '',
    keywords: ['S3 CORS', 'Access-Control-Request-Method', 'cross-origin', 'JSON', 'AllowedMethod', 'browser JavaScript'],
  },
  {
    id: 'wz5-011', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-011.png',
    scenario: 'The HR team stores sensitive employee data in a dedicated S3 bucket. Some developers have an IAM policy that grants broad ("full") S3 access. HR wants strict access control so that only HR personnel can access the HR bucket, even if new users are later granted "full S3 access." What access control should be implemented to meet this requirement with minimal ongoing administration?',
    options: [
      { id: 'a', text: 'Bucket policy: explicit deny for all Principals except the listed HR users/roles' },
      { id: 'b', text: 'Bucket policy: explicit deny for all users except listed users' },
      { id: 'c', text: 'Bucket policy that allows only a specific role; HR users assume that role for access' },
      { id: 'd', text: 'Bucket policy with NotPrincipal to deny all but matching users/roles' },
    ],
    correctId: 'a',
    explanation: 'An explicit Deny in an S3 bucket policy overrides any IAM Allow — including "full S3 access" policies. By adding a Deny statement for all Principals except the listed HR users/roles (using NotPrincipal with Deny), you ensure that no other IAM principal can access the bucket regardless of their IAM permissions. This requires no ongoing administration as new users with full S3 access are automatically blocked by the bucket-level deny.',
    reference: '',
    keywords: ['S3 bucket policy', 'explicit deny', 'NotPrincipal', 'least privilege', 'override IAM allow', 'sensitive data'],
  },
  {
    id: 'wz5-012', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-012.png',
    scenario: 'An online retailer uses Amazon Redshift at petabyte scale. Operations requires near real-time visibility (minute-level) into cluster performance, including query behavior and load activity, to troubleshoot hotspots and maintain SLAs. What actions should be taken to obtain this monitoring data?',
    options: [
      { id: 'a', text: 'Build custom queries and view in CloudWatch' },
      { id: 'b', text: 'Build custom queries and view in Trusted Advisor' },
      { id: 'c', text: 'Build custom queries and view in CloudTrail' },
      { id: 'd', text: 'Build custom queries and view in the Redshift console' },
    ],
    correctId: 'd',
    explanation: 'Amazon Redshift provides native performance monitoring views (STL_, STV_, SVV_ system tables/views) accessible via the Redshift console\'s Query Monitoring and Performance tabs. The console shows minute-level query execution details, workload management (WLM) queue status, and cluster load metrics. CloudWatch provides EC2/node-level metrics but lacks the query-execution granularity available in the Redshift console.',
    reference: '',
    keywords: ['Redshift', 'performance monitoring', 'console', 'query monitoring', 'STL views', 'WLM'],
  },
  {
    id: 'wz5-013', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-013.png',
    scenario: 'You created a VPC with an internet-facing Application Load Balancer (ALB) and registered two EC2 targets. However, client requests to the ALB consistently fail. Security groups appear open and targets look healthy. What is the most likely networking misconfiguration causing the failures?',
    options: [
      { id: 'a', text: 'The route table for the ALB\'s subnet lacks a route to the Internet Gateway' },
      { id: 'b', text: 'Targets are in a public subnet' },
      { id: 'c', text: 'The ALB has no Elastic IP' },
      { id: 'd', text: 'Cross-zone load balancing is disabled' },
    ],
    correctId: 'a',
    explanation: 'An internet-facing ALB must be in a public subnet — a subnet with a route to an Internet Gateway in its associated route table. If the ALB\'s subnet does not have a route to the IGW (0.0.0.0/0 → igw-xxx), the ALB cannot receive inbound traffic from the internet. ALBs use AWS-managed IPs, not Elastic IPs. Security group openness does not matter if the network route is missing.',
    reference: '',
    keywords: ['ALB', 'Internet Gateway', 'route table', 'public subnet', 'internet-facing', 'VPC networking'],
  },
  {
    id: 'wz5-014', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-014.png',
    scenario: 'Your organization plans to deploy microservices on Amazon ECS and expects occasional traffic bursts. Compute must scale automatically with no instance management, and the relational database must auto-scale capacity to meet demand without manual intervention. What architecture should you recommend?',
    options: [
      { id: 'a', text: 'ECS Fargate + DynamoDB' },
      { id: 'b', text: 'ECS Fargate + Aurora Serverless' },
      { id: 'c', text: 'ECS EC2 + Aurora Serverless' },
      { id: 'd', text: 'ECS EC2 + DynamoDB' },
    ],
    correctId: 'b',
    explanation: 'ECS Fargate provides serverless container compute that scales automatically with no EC2 instance management. Aurora Serverless v2 automatically scales database capacity (ACUs) up and down based on demand with no manual intervention, pausing when idle to minimize costs. This combination delivers a fully serverless, auto-scaling architecture for both compute and relational database tiers.',
    reference: '',
    keywords: ['ECS Fargate', 'Aurora Serverless', 'serverless', 'auto-scaling', 'no instance management', 'relational database'],
  },
  {
    id: 'wz5-015', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-015.png',
    scenario: 'A start-up operates many EC2 instances for its web application. The Operations team needs a programmatic way, from inside each instance, to retrieve the AMI ID the instance was launched from (compatible with IMDSv2). Which HTTP path should be used to obtain this value from the instance metadata service?',
    options: [
      { id: 'a', text: 'http://169.254.169.254/latest/meta-data/ami-id' },
      { id: 'b', text: 'http://169.254.169.254/latest/metadata/ami-id' },
      { id: 'c', text: 'http://169.254.169.254/latest/user-data/ami-id' },
      { id: 'd', text: 'http://169.253.169.253/latest/dynamic/ami-id' },
    ],
    correctId: 'a',
    explanation: 'The EC2 Instance Metadata Service (IMDS) is accessible at the link-local IP 169.254.169.254. Instance metadata is under the /latest/meta-data/ prefix. The correct path for the AMI ID is http://169.254.169.254/latest/meta-data/ami-id. Note the path uses "meta-data" (with hyphen), not "metadata". User-data is configuration scripts, not metadata. The address 169.253.169.253 does not exist.',
    reference: '',
    keywords: ['IMDS', 'instance metadata', '169.254.169.254', 'ami-id', 'meta-data', 'IMDSv2'],
  },
  {
    id: 'wz5-016', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    screenshotUrl: '/questions/wz5/wz5-016.png',
    scenario: 'You are the Solutions Architect for a health-insurance provider planning to onboard IoT devices for newly enrolled patients. The environment must be HIPAA-eligible, enforce in-transit encryption, and avoid the public internet for device ingress. The company already uses ELBs and wants to avoid DNS reconfiguration and issues with client IP caching on the devices. Which AWS service best addresses these requirements?',
    options: [
      { id: 'a', text: 'AWS ELB + AWS IoT + Amazon Route 53 geolocation routing with an interface endpoint for Route 53' },
      { id: 'b', text: 'AWS ELB + AWS IoT + AWS Global Accelerator (provisions two anycast static IP addresses)' },
      { id: 'c', text: 'AWS ELB + AWS IoT + Amazon Route 53 geolocation routing because Route 53 is inside the AWS backbone' },
      { id: 'd', text: 'AWS ELB + AWS IoT + AWS Global Accelerator (provisions one anycast static IP address)' },
    ],
    correctId: 'b',
    explanation: 'AWS Global Accelerator provisions two static Anycast IP addresses that remain fixed — solving the IP caching problem on IoT devices. Traffic enters the AWS global network at the nearest edge PoP, avoiding the public internet for most of the journey (addressing the no-public-internet requirement). It is HIPAA-eligible and supports in-transit encryption via TLS. Route 53 DNS changes still require propagation and IoT devices may cache the old IP.',
    reference: '',
    keywords: ['Global Accelerator', 'static IP', 'Anycast', 'HIPAA', 'IoT', 'IP caching', 'no public internet'],
  },
  {
    id: 'wz5-017', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-017.png',
    scenario: 'A fraud-detection team runs high-performance analytics on a POSIX-compliant Lustre file system and must regularly transfer datasets to Amazon S3 without sacrificing throughput or disrupting existing POSIX-based tools and workflows. Which two statements are correct in this context? (Select TWO)',
    options: [
      { id: 'a', text: 'AWS DataSync provides support for Amazon FSx for Lustre' },
      { id: 'b', text: 'Amazon FSx for Lustre integrates natively with Amazon S3' },
      { id: 'c', text: 'Amazon FSx for Windows File Server takes highly durable backups stored in S3' },
      { id: 'd', text: 'If you link FSx for Lustre to an S3 data lake, objects appear as S3 objects as soon as block storage is available' },
    ],
    correctId: 'a,b',
    explanation: 'Both A and B are correct: AWS DataSync supports FSx for Lustre as a transfer location, enabling high-speed data migration to/from FSx for Lustre. Amazon FSx for Lustre natively integrates with Amazon S3 via Data Repository Associations (DRAs), allowing you to link an S3 bucket so that objects are lazily imported and HPC-processed files can be exported back to S3 automatically. Option D is incorrect — objects are not immediately visible in S3; they must be explicitly exported.',
    reference: '',
    keywords: ['FSx for Lustre', 'S3 integration', 'DataSync', 'Data Repository Association', 'DRA', 'HPC analytics'],
  },
  {
    id: 'wz5-018', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-018.png',
    scenario: 'You are drafting DR and high-availability guidance for a system that relies on Amazon FSx for Windows File Server. Leadership wants confirmation of supported deployment models and access patterns (including multi-AZ behavior and cross-network access). Which two statements about FSx for Windows File Server are true? (Select TWO)',
    options: [
      { id: 'a', text: 'FSx for Windows offers instance store caching that can be shared across applications, VPCs, accounts, or Regions' },
      { id: 'b', text: 'FSx for Windows allows access across applications, VPCs, accounts, and Regions via VPC peering/Transit Gateway and on-premises via Direct Connect/VPN' },
      { id: 'c', text: 'FSx for Windows offers single-AZ and multi-AZ deployment options with both SSD and HDD storage options' },
      { id: 'd', text: 'Direct Connect, VPN, VPC Peering, and Transit Gateway are not supported' },
      { id: 'e', text: 'FSx for Windows is a fully POSIX-compliant filesystem' },
    ],
    correctId: 'b,c',
    explanation: 'FSx for Windows File Server supports two deployment options: Single-AZ (one AZ, SSD or HDD) and Multi-AZ (active/standby across two AZs for HA). It supports access from multiple VPCs, AWS accounts, and Regions via VPC peering or Transit Gateway, and from on-premises via Direct Connect or VPN. It is NOT POSIX-compliant (it is Windows NTFS/SMB-based). It does not use instance store caching.',
    reference: '',
    keywords: ['FSx for Windows File Server', 'multi-AZ', 'single-AZ', 'SSD', 'HDD', 'VPC peering', 'Direct Connect', 'NTFS'],
  },
  {
    id: 'wz5-019', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    screenshotUrl: '/questions/wz5/wz5-019.png',
    scenario: 'While analyzing billions of web pages, some data preprocessing pipelines are exceeding SLAs. Monitoring shows that write operations involving S3 content pre-processing cause 80% of the bottlenecks, while read operations and S3 LIST operations together account for 20%. Which two options are recommended to increase performance in this scenario? (Select TWO)',
    options: [
      { id: 'a', text: 'Migrate S3 files to Amazon RDS with provisioned IOPS' },
      { id: 'b', text: 'Use S3 Transfer Acceleration, Multipart Upload, parallelization, and well-designed key prefixes' },
      { id: 'c', text: 'Replace LIST with more LIST calls via many concurrent connections' },
      { id: 'd', text: 'Build a search/catalog index (e.g., DynamoDB or OpenSearch Service) instead of brute-force LIST scans' },
      { id: 'e', text: 'Migrate to EC2 local disks + S3 sync to reduce network latency and egress' },
    ],
    correctId: 'b,d',
    explanation: 'For the write bottleneck (80%): Use S3 Transfer Acceleration (CloudFront edge network), multipart upload for large objects, parallelization, and well-designed key prefixes (random prefix distribution across S3 partitions) to maximize write throughput. For the LIST bottleneck (20%): Replace S3 LIST operations with a DynamoDB or OpenSearch catalog/index — S3 LIST is expensive and slow at scale; a metadata catalog provides O(1) lookups instead of O(n) scans.',
    reference: '',
    keywords: ['S3 performance', 'S3 Transfer Acceleration', 'multipart upload', 'key prefix', 'DynamoDB catalog', 'LIST optimization', 'parallelization'],
  },
  {
    id: 'wz5-020', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-020.png',
    scenario: 'A global logistics company is planning to upgrade its package tracking and auditing platform. The solution must support an immutable record of transactions, offer real-time visibility into data changes, and integrate easily with existing AWS services. Which AWS service best meets these requirements?',
    options: [
      { id: 'a', text: 'Amazon Neptune' },
      { id: 'b', text: 'Amazon Aurora PostgreSQL' },
      { id: 'c', text: 'Amazon ElastiCache' },
      { id: 'd', text: 'Amazon DynamoDB' },
    ],
    correctId: 'd',
    explanation: 'Amazon DynamoDB supports both requirements: (1) DynamoDB Streams provide real-time visibility into item-level changes, enabling event-driven architectures and change data capture; (2) DynamoDB can be configured with append-only patterns for immutable transaction records. It integrates natively with Lambda, Kinesis, and other AWS services. Neptune is for graphs; Aurora is relational; ElastiCache is caching only.',
    reference: '',
    keywords: ['DynamoDB', 'DynamoDB Streams', 'immutable records', 'real-time changes', 'event-driven', 'logistics tracking'],
  },
  {
    id: 'wz5-021', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-021.png',
    scenario: 'You are analyzing dynamic scaling activity defined to process messages from an Amazon SQS queue. You are using a target tracking policy, and CloudWatch alarms are configured to invoke the scaling policy. However, you have noticed that the EC2 Auto Scaling group does not respond when the CloudWatch alarm fires. Which option may cause this?',
    options: [
      { id: 'a', text: 'The wrong CloudWatch metric was configured' },
      { id: 'b', text: 'The Auto Scaling group is in a cooldown period' },
      { id: 'c', text: 'The minimum size of the ASG is 0' },
      { id: 'd', text: 'The desired size of the ASG is 0' },
    ],
    correctId: 'b',
    explanation: 'Auto Scaling cooldown periods prevent the ASG from launching or terminating additional instances before the previous scaling activity takes effect. If the ASG is in a cooldown period when a CloudWatch alarm fires, the scaling action is blocked until the cooldown expires. This is the most common reason an ASG appears unresponsive to alarms. The cooldown gives the fleet time to stabilize before evaluating whether further scaling is needed.',
    reference: '',
    keywords: ['Auto Scaling', 'cooldown period', 'CloudWatch alarm', 'scaling blocked', 'SQS', 'target tracking'],
  },
  {
    id: 'wz5-022', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-022.png',
    scenario: 'A project has a latency-sensitive workload, with latency prioritized over availability under strict SLAs. You must design high-performance networking for their VPCs to meet the contractual SLAs. Which two statements about EC2 placement groups are correct? (Select TWO)',
    options: [
      { id: 'a', text: 'A cluster placement group is suitable for this use case as long as instances remain in a single AZ' },
      { id: 'b', text: 'A cluster placement group is appropriate because it supports high performance over Direct Connect to on-premises' },
      { id: 'c', text: 'You can move an instance from one placement group to another, but you cannot merge placement groups' },
      { id: 'd', text: 'You can migrate an instance and merge placement groups' },
      { id: 'e', text: 'A spread placement group is better here, but if there is no unique hardware available the request fails' },
    ],
    correctId: 'a,c',
    explanation: 'Cluster placement groups pack instances physically close together in a single AZ to achieve the lowest network latency and highest throughput — ideal for latency-sensitive workloads. They are constrained to one AZ. You can stop an instance, change its placement group, and restart it (moving it to another group), but placement groups themselves cannot be merged. Spread placement groups maximize fault tolerance, not performance.',
    reference: '',
    keywords: ['cluster placement group', 'low latency', 'single AZ', 'high performance networking', 'placement group rules'],
  },
  {
    id: 'wz5-023', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-023.png',
    scenario: 'You are building a solution for a security company that requires real-time monitoring and analysis of surveillance camera footage for detecting suspicious activities and intrusions. Which AWS service do you suggest for securely ingesting and streaming the visual data originating from multiple cameras dispersed across various locations?',
    options: [
      { id: 'a', text: 'Amazon Elastic Transcoder' },
      { id: 'b', text: 'Amazon Rekognition Video' },
      { id: 'c', text: 'Amazon SageMaker' },
      { id: 'd', text: 'Amazon Kinesis Video Streams' },
    ],
    correctId: 'd',
    explanation: 'Amazon Kinesis Video Streams is purpose-built for securely ingesting, storing, and streaming video from millions of devices (including cameras) to AWS for real-time and batch processing. It handles the ingestion and streaming layer. Rekognition Video analyzes video for object/activity detection but requires an ingestion service — you pair Kinesis Video Streams with Rekognition Video for the full pipeline. Elastic Transcoder is for format conversion.',
    reference: '',
    keywords: ['Kinesis Video Streams', 'video ingestion', 'surveillance', 'real-time video', 'camera streaming', 'IoT cameras'],
  },
  {
    id: 'wz5-024', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-024.png',
    scenario: 'A web application uses Amazon CloudFront to deliver its static and dynamic web content. You want to customize the error pages returned to the viewer when the origin returns 5xx errors (for example, 500 Internal Server Error), so CloudFront presents a page that you have prepared. How would you achieve this requirement in CloudFront?',
    options: [
      { id: 'a', text: 'Modify the application to store custom error pages; CloudFront caches them automatically' },
      { id: 'b', text: 'Create a second CloudFront distribution solely for error pages and chain the first to the second' },
      { id: 'c', text: 'Put static error pages in S3 and configure Custom Error Responses in the CloudFront distribution for HTTP 5xx' },
      { id: 'd', text: 'Upload custom error pages directly into CloudFront' },
    ],
    correctId: 'c',
    explanation: 'CloudFront Custom Error Responses allow you to map specific HTTP error codes (4xx and 5xx) to custom HTML pages stored in S3. You configure the error code, the response page path (pointing to your S3-hosted error page), and optionally the TTL for caching the error response. This is the native CloudFront mechanism for branded error pages with no application changes required.',
    reference: '',
    keywords: ['CloudFront', 'Custom Error Responses', '5xx', 'error page', 'S3', 'HTTP error codes'],
  },
  {
    id: 'wz5-025', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-025.png',
    scenario: 'A CloudFront distribution delivers the web content of an application. Some static files are cached in CloudFront with a TTL of 1 day. You upgrade the origin server and the configuration JSON file has been updated. However, when users access the website, the old cached file in CloudFront is returned, causing service impact. How would you resolve this problem immediately?',
    options: [
      { id: 'a', text: 'Wait 24 hours for caches to expire' },
      { id: 'b', text: 'Invalidate the object in CloudFront' },
      { id: 'c', text: 'Set the distribution\'s default TTL to 0' },
      { id: 'd', text: 'Redeploy the app with special Cache-Control headers to remove the object' },
    ],
    correctId: 'b',
    explanation: 'CloudFront invalidation removes specific objects from all edge caches immediately, forcing the next request to fetch the updated version from the origin — even before the TTL expires. You can invalidate individual files (e.g., /config.json) or use a wildcard (/*). Setting TTL to 0 affects future caches only; redeploying with Cache-Control only helps for future requests after cache expiry.',
    reference: '',
    keywords: ['CloudFront', 'invalidation', 'cache', 'TTL', 'stale content', 'immediate refresh'],
  },
  {
    id: 'wz5-026', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-026.png',
    scenario: 'You plan to migrate a Classic Load Balancer to either an Application Load Balancer or a Network Load Balancer. For the new load balancer listener, you need to define two rules that route requests based on the Host header (hostname), then route traffic to two different target groups accordingly. Which load balancer type should you choose?',
    options: [
      { id: 'a', text: 'Network Load Balancer with HTTP listener and host-based rules' },
      { id: 'b', text: 'Network Load Balancer with TCP listener and path-based routing' },
      { id: 'c', text: 'Application Load Balancer with multiple path-based rules' },
      { id: 'd', text: 'Application Load Balancer with host-based routing rules' },
    ],
    correctId: 'd',
    explanation: 'Only Application Load Balancers (ALBs) support content-based routing at Layer 7, including host-based routing (routing based on the Host header/hostname). ALB listener rules can inspect the Host header and forward to different target groups accordingly. Network Load Balancers operate at Layer 4 (TCP/UDP) and cannot inspect HTTP headers for routing decisions.',
    reference: '',
    keywords: ['ALB', 'host-based routing', 'Layer 7', 'Host header', 'listener rules', 'content-based routing'],
  },
  {
    id: 'wz5-027', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-027.png',
    scenario: 'Your team uses Amazon ECS to manage containers for several microservices. To save cost, multiple ECS tasks should run on a single container instance. When a task is launched, the host port should be dynamically chosen from the container instance\'s ephemeral port range. Which types of load balancers support dynamic port mapping with ECS?',
    options: [
      { id: 'a', text: 'Application Load Balancer or Network Load Balancer' },
      { id: 'b', text: 'Application Load Balancer only' },
      { id: 'c', text: 'Network Load Balancer only' },
      { id: 'd', text: 'Application Load Balancer or Classic Load Balancer' },
    ],
    correctId: 'a',
    explanation: 'Both Application Load Balancer (ALB) and Network Load Balancer (NLB) support dynamic port mapping with Amazon ECS. Dynamic port mapping allows the container host to assign ephemeral ports to containers, enabling multiple tasks of the same type to run on a single EC2 instance. The load balancer registers these dynamic ports as targets. Classic Load Balancer does NOT support dynamic port mapping with ECS.',
    reference: '',
    keywords: ['ECS', 'dynamic port mapping', 'ALB', 'NLB', 'ephemeral ports', 'Classic Load Balancer', 'container tasks'],
  },
  {
    id: 'wz5-028', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-028.png',
    scenario: 'You plan to manage API keys in AWS Secrets Manager. The keys need to be automatically rotated to comply with company policy. From Secrets Manager, applications must be able to get the latest version of the API credentials. How would you implement the rotation of keys?',
    options: [
      { id: 'a', text: 'Use Parameter Store because Secrets Manager cannot rotate API keys' },
      { id: 'b', text: 'Store multiple keys in one secret; Secrets Manager rotates them yearly automatically' },
      { id: 'c', text: 'Customize the rotation Lambda function to rotate the API keys in Secrets Manager' },
      { id: 'd', text: 'Create two separate secrets and alternate reads in the app' },
    ],
    correctId: 'c',
    explanation: 'AWS Secrets Manager supports automatic secret rotation via AWS Lambda. For custom API keys (not natively supported services like RDS), you write a custom rotation Lambda function that: generates the new key, updates the third-party service, and stores the new value in Secrets Manager. The rotation Lambda is invoked on a schedule or on demand. Applications always retrieve the latest AWSCURRENT version via the Secrets Manager API.',
    reference: '',
    keywords: ['Secrets Manager', 'rotation', 'Lambda', 'API keys', 'automatic rotation', 'AWSCURRENT'],
  },
  {
    id: 'wz5-029', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-029.png',
    scenario: 'Your organization stores RDS credentials in AWS Secrets Manager. To comply with security regulations, all secrets must have rotation enabled. If rotation is not enabled for any secret, the team should receive an email notification. Which method is most appropriate?',
    options: [
      { id: 'a', text: 'A setting to "enable rotation for all secrets" in Secrets Manager' },
      { id: 'b', text: 'A CloudWatch Event Rule that matches "any Secrets Manager event" and publishes to SNS' },
      { id: 'c', text: 'Amazon GuardDuty to monitor Secrets Manager rotation status' },
      { id: 'd', text: 'AWS Config rule secretsmanager-rotation-enabled-check with SNS notifications via EventBridge' },
    ],
    correctId: 'd',
    explanation: 'AWS Config provides a managed rule called secretsmanager-rotation-enabled-check that evaluates whether secrets in Secrets Manager have rotation enabled. When a secret is found non-compliant, AWS Config generates a compliance change event. You configure EventBridge (formerly CloudWatch Events) to forward Config compliance change events to SNS, which sends an email notification. This is the AWS-native compliance monitoring pattern.',
    reference: '',
    keywords: ['AWS Config', 'secretsmanager-rotation-enabled-check', 'compliance', 'SNS', 'EventBridge', 'Secrets Manager rotation'],
  },
  {
    id: 'wz5-030', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-030.png',
    scenario: 'The customer data of an application is stored in an S3 bucket. Your team would like to use Amazon Athena to analyze the data using standard SQL. However, the data in the S3 bucket is encrypted via SSE-KMS. How would you create the table in Athena for the encrypted data in S3?',
    options: [
      { id: 'a', text: 'Provide the KMS private key to Athena' },
      { id: 'b', text: 'Nothing extra is needed; Athena can read SSE-KMS encrypted data if IAM and KMS permissions allow' },
      { id: 'c', text: 'Convert SSE-KMS to SSE-S3 before creating the table' },
      { id: 'd', text: 'Disable server-side encryption before table creation' },
    ],
    correctId: 'b',
    explanation: 'Amazon Athena transparently decrypts S3 data encrypted with SSE-KMS when the Athena query\'s IAM execution role has both IAM S3 permissions and KMS Decrypt (kms:Decrypt, kms:GenerateDataKey) permissions on the relevant KMS key. No additional Athena configuration is required — just ensure the IAM role used by Athena can access both the S3 bucket and the KMS key.',
    reference: '',
    keywords: ['Athena', 'SSE-KMS', 'KMS decrypt', 'IAM permissions', 'transparent decryption', 'S3 encryption'],
  },
  {
    id: 'wz5-031', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-031.png',
    scenario: 'Your organization stores customer data in an Amazon DynamoDB table. You need to use AWS Glue to create ETL jobs to build a data warehouse. In AWS Glue, you need a component to determine the schema from DynamoDB and populate the AWS Glue Data Catalog with metadata. Which component should be used?',
    options: [
      { id: 'a', text: 'Table in AWS Glue' },
      { id: 'b', text: 'Table in Amazon Athena' },
      { id: 'c', text: 'Crawler in AWS Glue' },
      { id: 'd', text: 'Classifier in AWS Glue' },
    ],
    correctId: 'c',
    explanation: 'An AWS Glue Crawler connects to a data source (DynamoDB, S3, RDS, etc.), crawls the data, infers the schema, and populates the AWS Glue Data Catalog with table metadata. Once the catalog is populated, ETL jobs can reference these tables. A Glue Classifier helps the crawler determine data formats; a Glue Table is the metadata entry the crawler creates, not the crawling mechanism itself.',
    reference: '',
    keywords: ['AWS Glue', 'Crawler', 'Data Catalog', 'DynamoDB', 'schema inference', 'ETL', 'metadata'],
  },
  {
    id: 'wz5-032', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-032.png',
    scenario: 'You create a new AWS Organization with many accounts and want to trigger a notification whenever an administrator acts on the Organization. Which service would you use?',
    options: [
      { id: 'a', text: 'Amazon EventBridge' },
      { id: 'b', text: 'AWS Config Resources' },
      { id: 'c', text: 'AWS CloudTrail' },
      { id: 'd', text: 'Amazon CloudWatch Logs' },
    ],
    correctId: 'c',
    explanation: 'AWS CloudTrail records all AWS API calls including every action taken on an AWS Organization (CreateAccount, InviteAccountToOrganization, DeleteOrganizationalUnit, etc.). CloudTrail logs are delivered to S3 and can trigger EventBridge or CloudWatch alarms. For "trigger a notification when an admin acts on the Organization," CloudTrail is the source of the audit events, which EventBridge then routes to SNS for notifications.',
    reference: '',
    keywords: ['CloudTrail', 'AWS Organizations', 'audit', 'API calls', 'admin actions', 'notification'],
  },
  {
    id: 'wz5-033', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-033.png',
    scenario: 'Your company ingests telemetry from thousands of IoT sensors into Amazon Kinesis Data Streams using default settings. A batch export job writes the stream records to Amazon S3 every other day. When analysts review S3, portions of data are consistently missing from periods older than the previous day. Why is data missing in S3?',
    options: [
      { id: 'a', text: 'Sensors stopped working some days' },
      { id: 'b', text: 'S3 can only store data for a day' },
      { id: 'c', text: 'The default retention period of the Kinesis Data Stream is 24 hours' },
      { id: 'd', text: 'Kinesis is not meant for IoT data' },
    ],
    correctId: 'c',
    explanation: 'Amazon Kinesis Data Streams has a default data retention period of 24 hours (1 day). Records that are older than the retention period are automatically deleted from the stream. If the batch export job runs every other day (48 hours), data from more than 24 hours ago has already been purged by the time the export runs. The solution is to increase the retention period (up to 365 days) or run the export more frequently.',
    reference: '',
    keywords: ['Kinesis Data Streams', 'retention period', '24 hours', 'data expiry', 'IoT', 'batch export'],
  },
  {
    id: 'wz5-034', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-034.png',
    scenario: 'Your company uses an S3 bucket to store data for an application. Sometimes the team downloads S3 files for further analysis. As the data is very important, you need to protect against accidental deletions and restore files when needed. Which option is appropriate?',
    options: [
      { id: 'a', text: 'Enable the versioning feature in the S3 bucket' },
      { id: 'b', text: 'Modify the S3 bucket to be read-only' },
      { id: 'c', text: 'Use an S3 Lifecycle policy to transfer objects to a lower cost storage' },
      { id: 'd', text: 'Enable Server-Side Encryption with AWS KMS-Managed Keys (SSE-KMS)' },
    ],
    correctId: 'a',
    explanation: 'S3 Versioning retains all versions of every object in the bucket. When an object is deleted, S3 creates a delete marker rather than permanently removing the object — the previous version is preserved and can be restored by deleting the delete marker or retrieving the specific version. Encryption (SSE-KMS) protects data at rest but does not prevent deletion. Read-only would prevent all writes including new uploads.',
    reference: '',
    keywords: ['S3 versioning', 'accidental deletion', 'delete marker', 'restore', 'object versions', 'data protection'],
  },
  {
    id: 'wz5-035', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Hard',
    screenshotUrl: '/questions/wz5/wz5-035.png',
    scenario: 'You are working as an AWS Administrator for a software firm with a popular web application hosted on EC2 instances. You are using AWS CloudHSM for offloading SSL/TLS processing. You need to ensure proper backups are performed for data in AWS CloudHSM clusters. What does AWS CloudHSM use to create a secure and durable backup?',
    options: [
      { id: 'a', text: 'Ephemeral Backup Key (EBK) is used to encrypt data and Persistent Backup Key (PBK) is used to encrypt EBK before saving data to the Amazon S3 bucket in the same region as the AWS CloudHSM cluster' },
      { id: 'b', text: 'Data Key is used to encrypt data and Customer Managed Key (CMK) is used to encrypt Data Key before saving data to the Amazon S3 bucket in the same region as the AWS CloudHSM cluster' },
      { id: 'c', text: 'Ephemeral Backup Key (EBK) is used to encrypt data and Persistent Backup Key (PBK) is used to encrypt EBK before saving data to the Amazon S3 bucket in a different region than the AWS CloudHSM cluster' },
      { id: 'd', text: 'Data Key is used to encrypt data and Customer Managed Key (CMK) is used to encrypt Data Key before saving data to an Amazon S3 bucket in a different region than the AWS CloudHSM cluster' },
    ],
    correctId: 'a',
    explanation: 'AWS CloudHSM backups use a two-level key hierarchy: an Ephemeral Backup Key (EBK) encrypts the HSM data (using AES-256), and a Persistent Backup Key (PBK) derived from a KDF encrypts the EBK. The encrypted backup is then stored in an S3 bucket in the same AWS region as the CloudHSM cluster. To use backups across regions, you must explicitly copy them — they are not automatically stored in a different region.',
    reference: '',
    keywords: ['CloudHSM', 'EBK', 'PBK', 'backup', 'same region S3', 'Ephemeral Backup Key', 'Persistent Backup Key'],
  },
  {
    id: 'wz5-036', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-036.png',
    scenario: 'A company is planning to move its applications to the AWS Cloud. They have large SQL data sets that need to be hosted in a data store on the cloud. The data store needs to support client connections with many types of applications, including business intelligence (BI), reporting, data, and analytics tools. Which service should be considered?',
    options: [
      { id: 'a', text: 'Amazon DynamoDB' },
      { id: 'b', text: 'Amazon Redshift' },
      { id: 'c', text: 'Amazon Kinesis' },
      { id: 'd', text: 'Amazon Simple Queue Service' },
    ],
    correctId: 'b',
    explanation: 'Amazon Redshift is a fully managed, petabyte-scale data warehouse built for SQL-based analytics. It supports JDBC/ODBC connections from BI tools (Tableau, QuickSight, Power BI), reporting tools, and analytics platforms. It is purpose-built for large SQL data sets and analytical query workloads. DynamoDB is NoSQL; Kinesis is for streaming; SQS is a message queue.',
    reference: '',
    keywords: ['Redshift', 'data warehouse', 'SQL', 'BI tools', 'JDBC', 'ODBC', 'analytics', 'petabyte scale'],
  },
  {
    id: 'wz5-037', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-037.png',
    scenario: 'You are developing an application that uses the Amazon Kinesis Producer Library (KPL) to put data records to an encrypted Kinesis data stream. When your application runs, there is an "unauthorized KMS master key permission" error. How would you resolve the problem?',
    options: [
      { id: 'a', text: 'Configure the application\'s IAM role as the key administrator of the KMS key' },
      { id: 'b', text: 'In the KMS key policy, assign the permission to the application to access the key' },
      { id: 'c', text: 'Re-encrypt the Kinesis data stream with AWS/Kinesis managed key' },
      { id: 'd', text: 'Configure the KPL not to encrypt the data records for the Kinesis data stream' },
    ],
    correctId: 'b',
    explanation: 'When a Kinesis Data Stream is encrypted with a KMS customer-managed key, producers using the KPL must have kms:GenerateDataKey permission to encrypt records before sending them. This permission is granted via the KMS key policy (key resource policy), not just the IAM role policy — both must allow the principal. Adding kms:GenerateDataKey and kms:Decrypt to the KMS key policy for the application\'s principal resolves the error.',
    reference: '',
    keywords: ['KMS', 'Kinesis', 'KPL', 'key policy', 'kms:GenerateDataKey', 'unauthorized', 'encryption'],
  },
  {
    id: 'wz5-038', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-038.png',
    scenario: 'Your company plans to host its development, test, and production applications on EC2 instances in AWS. The team is worried about how access control would be given to relevant IT Admins for each of the above environments. As an architect, what would you suggest to manage the relevant accesses?',
    options: [
      { id: 'a', text: 'Add tags to the instances marking each environment, and then segregate access using IAM Policies' },
      { id: 'b', text: 'Add Userdata to the underlying instances to mark each environment' },
      { id: 'c', text: 'Add Metadata to the underlying instances to mark each environment' },
      { id: 'd', text: 'Add each environment to a separate Auto Scaling Group' },
    ],
    correctId: 'a',
    explanation: 'EC2 tags (e.g., Environment: dev/test/prod) combined with IAM Condition keys (aws:ResourceTag) in IAM policies enable attribute-based access control (ABAC). Admins are granted IAM policies that restrict access to only instances tagged with their environment. This is scalable and requires no changes to instance configuration. User data is for instance bootstrap scripts; instance metadata cannot be used for IAM-based access control.',
    reference: '',
    keywords: ['IAM tags', 'ABAC', 'attribute-based access control', 'EC2 tags', 'aws:ResourceTag', 'environment segregation'],
  },
  {
    id: 'wz5-039', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-039.png',
    scenario: 'Your order-processing application is decoupled with Amazon SQS receiving messages from the web front end. The consumers are EC2 instances behind an ELB, managed by an Auto Scaling group. You want the ASG to scale automatically based on the size of the backlog in the SQS queue so that additional workers launch when orders pile up and scale back down when the queue drains. Which CloudWatch metric should you use to measure the queue length for this scaling policy?',
    options: [
      { id: 'a', text: 'ApproximateNumberOfMessagesVisible' },
      { id: 'b', text: 'NumberOfMessagesReceived' },
      { id: 'c', text: 'NumberOfMessagesDeleted' },
      { id: 'd', text: 'ApproximateNumberOfMessagesNotVisible' },
    ],
    correctId: 'a',
    explanation: 'ApproximateNumberOfMessagesVisible is the SQS CloudWatch metric that represents the number of messages available in the queue that can be retrieved. This is the backlog metric — when it rises, the queue is backing up and more workers are needed; when it falls to zero, the queue is drained. NumberOfMessagesReceived tracks consumption rate; NotVisible tracks in-flight messages being processed.',
    reference: '',
    keywords: ['SQS', 'ApproximateNumberOfMessagesVisible', 'backlog', 'Auto Scaling', 'queue depth', 'scaling metric'],
  },
  {
    id: 'wz5-040', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-040.png',
    scenario: 'You are performing a load testing exercise on your application hosted on AWS. While testing your Amazon RDS MySQL DB instance, you notice that your application becomes non-responsive when you reach 80% CPU utilization. Your application is read-heavy. Which methods would help scale your data tier to meet the application\'s needs? (Select THREE)',
    options: [
      { id: 'a', text: 'Add Amazon RDS DB Read Replicas, and have your application direct read queries to them' },
      { id: 'b', text: 'Add your Amazon RDS DB instance to Storage Auto Scaling, and set your desired maximum storage limit' },
      { id: 'c', text: 'Use an Amazon SQS queue to throttle data going to the Amazon RDS DB instance' },
      { id: 'd', text: 'Use ElastiCache to cache common queries of your Amazon RDS DB' },
      { id: 'e', text: 'Shard your data set among multiple Amazon RDS DB instances' },
      { id: 'f', text: 'Enable Multi-AZ for your Amazon RDS DB instance' },
    ],
    correctId: 'a,d,e',
    explanation: 'For read-heavy RDS scaling: (A) Read Replicas offload read queries from the primary instance using asynchronous replication — directly reduces primary CPU utilization. (D) ElastiCache (Redis/Memcached) caches frequent query results in-memory — reduces the number of queries reaching RDS entirely. (E) Sharding distributes data across multiple RDS instances — horizontal scaling for both reads and writes. Storage Auto Scaling (B) only expands disk, not compute. SQS (C) adds latency without reducing CPU. Multi-AZ (F) is for HA/failover, not read scaling.',
    reference: '',
    keywords: ['RDS', 'Read Replica', 'ElastiCache', 'sharding', 'read-heavy', 'CPU scaling', 'data tier scaling'],
  },
  {
    id: 'wz5-041', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-041.png',
    scenario: 'A software company is developing a customer support system. Different types of support requests (billing, technical, and general inquiries) are sent to dedicated Amazon SQS queues. Each queue is polled by backend workers for processing. You need to implement a solution that receives incoming messages from the web frontend and routes them dynamically to the appropriate SQS queue using a publish/subscribe pattern. Which AWS service should you use?',
    options: [
      { id: 'a', text: 'Amazon MQ' },
      { id: 'b', text: 'Amazon Simple Notification Service (Amazon SNS)' },
      { id: 'c', text: 'Amazon Simple Queue Service (Amazon SQS)' },
      { id: 'd', text: 'AWS Step Functions' },
    ],
    correctId: 'b',
    explanation: 'Amazon SNS implements the publish/subscribe (pub/sub) pattern. The web frontend publishes messages to an SNS topic, and each SQS queue is subscribed to the topic. Using SNS message filtering, different subscription filter policies route billing, technical, and general inquiry messages to the correct SQS queue. This is the classic SNS-to-SQS fan-out pattern for message routing.',
    reference: '',
    keywords: ['SNS', 'SQS', 'pub/sub', 'fan-out', 'message filtering', 'routing', 'customer support'],
  },
  {
    id: 'wz5-042', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-042.png',
    scenario: 'You are building a Lambda function that runs periodically and processes data stored in a DynamoDB table. As the data grows fast, you need to estimate the cost of the Lambda function. Which two factors directly determine the monthly cost of Lambda? (Select TWO)',
    options: [
      { id: 'a', text: 'The programming language used by the Lambda function' },
      { id: 'b', text: 'The Lambda function handler' },
      { id: 'c', text: 'The memory allocated to the Lambda function' },
      { id: 'd', text: 'The timeout value of the Lambda function' },
      { id: 'e', text: 'The total number of requests for the Lambda function' },
    ],
    correctId: 'c,e',
    explanation: 'AWS Lambda pricing is based on two dimensions: (1) Number of requests — each invocation is billed at $0.20 per 1 million requests; (2) Duration — charged per GB-second = memory allocated (GB) × execution time (seconds). Memory allocation directly determines the GB-second rate. The timeout sets the maximum duration but actual billing is for actual execution time. Programming language and handler name have no pricing impact.',
    reference: '',
    keywords: ['Lambda pricing', 'memory', 'number of requests', 'GB-second', 'duration', 'cost'],
  },
  {
    id: 'wz5-043', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-043.png',
    scenario: 'You need a new S3 bucket to store objects using the write-once-read-many (WORM) model. After objects are saved in the bucket, they cannot be deleted or overwritten for a fixed amount of time. Which option would you select to achieve this requirement?',
    options: [
      { id: 'a', text: 'Enable the Amazon S3 Object Lock when creating the S3 bucket' },
      { id: 'b', text: 'Enable versioning for the S3 bucket' },
      { id: 'c', text: 'Modify the S3 bucket policy to only allow the read operation' },
      { id: 'd', text: 'Enable the WORM model in the S3 Access Control List (ACL) configuration' },
    ],
    correctId: 'a',
    explanation: 'Amazon S3 Object Lock implements the WORM (Write Once, Read Many) model. It prevents objects from being deleted or overwritten for a fixed retention period (Governance or Compliance mode) or indefinitely (Legal Hold). Object Lock must be enabled when the bucket is created (it cannot be enabled on an existing bucket without contacting support). S3 versioning prevents permanent deletion but doesn\'t enforce WORM immutability.',
    reference: '',
    keywords: ['S3 Object Lock', 'WORM', 'immutability', 'Compliance mode', 'Governance mode', 'retention period'],
  },
  {
    id: 'wz5-044', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-044.png',
    scenario: 'You have a lifecycle rule for an S3 bucket that archives objects to the S3 Glacier storage class 60 days after creation. The archived objects are no longer needed one year after being created. How would you configure the S3 bucket to save more cost?',
    options: [
      { id: 'a', text: 'Configure a rule in S3 Glacier to place delete markers for objects that are one year old' },
      { id: 'b', text: 'Configure the S3 lifecycle rule to expire (delete) the objects after 365 days from object creation' },
      { id: 'c', text: 'Modify the S3 lifecycle rule to clean up expired object delete markers for one year old objects' },
      { id: 'd', text: 'Modify the S3 lifecycle rule to use S3 Glacier Deep Archive which automatically deletes objects one year after creation' },
    ],
    correctId: 'b',
    explanation: 'An S3 lifecycle expiration action permanently deletes objects after a specified number of days from creation. Adding an expiration action for 365 days (in addition to the existing transition at 60 days) automatically deletes objects after one year, eliminating Glacier storage costs for objects no longer needed. Glacier itself does not have rules to delete objects — lifecycle rules are configured at the S3 level.',
    reference: '',
    keywords: ['S3 Lifecycle', 'expiration', 'delete', '365 days', 'Glacier', 'cost optimization', 'transition'],
  },
  {
    id: 'wz5-045', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-045.png',
    scenario: 'You are working for an electrical appliance company with a two-tier web application. You are using a Network Load Balancer in the front end with instance IDs for target configuration. Some clients report delays. To troubleshoot, you need to find client IP addresses with longer TLS handshake times. You have NLB access logs saved in Amazon S3. Which tool can quickly analyze many log files without visualization, in a cost-effective way?',
    options: [
      { id: 'a', text: 'Use Amazon Athena to query logs saved in Amazon S3 buckets' },
      { id: 'b', text: 'Use the Amazon S3 console to process logs' },
      { id: 'c', text: 'Export Network Load Balancer access logs to a third-party application' },
      { id: 'd', text: 'Use Amazon Athena along with Amazon QuickSight to query logs saved in Amazon S3 buckets' },
    ],
    correctId: 'a',
    explanation: 'Amazon Athena allows you to run SQL queries directly against log files stored in S3 without loading them into a database. It is serverless (pay per query), fast for ad-hoc analysis, and can query large volumes of NLB access logs with standard SQL. For analysis without visualization, Athena alone suffices. Adding QuickSight (option D) provides visualization but is unnecessary for the described requirement.',
    reference: '',
    keywords: ['Athena', 'NLB access logs', 'S3', 'SQL queries', 'serverless analytics', 'TLS troubleshooting', 'log analysis'],
  },
  {
    id: 'wz5-046', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-046.png',
    scenario: 'Multiple data science teams are working on a problem to provide insights at a global scale. In order to support a shared, low-latency storage, what would you recommend that also accomplishes cost optimization?',
    options: [
      { id: 'a', text: 'Use Amazon EC2 instance store volumes for storage' },
      { id: 'b', text: 'Use Amazon EFS for shared storage' },
      { id: 'c', text: 'Use Amazon EBS with Multi-Attach for volumes' },
      { id: 'd', text: 'Use Amazon S3 Standard storage class to store data' },
    ],
    correctId: 'd',
    explanation: 'Amazon S3 Standard provides globally accessible shared storage with low-latency HTTP access from anywhere in the world. It is highly cost-effective for large datasets (much cheaper than EFS per GB). Multiple data science teams worldwide can access S3 concurrently without any networking constraints. EFS is regional and more expensive; EC2 instance store is ephemeral and not shared; EBS Multi-Attach is AZ-local.',
    reference: '',
    keywords: ['S3 Standard', 'global shared storage', 'cost optimization', 'data science', 'concurrent access'],
  },
  {
    id: 'wz5-047', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-047.png',
    scenario: 'You are working in an IT security organization that has written an IDS agent running on an EC2 instance. Suddenly, your database stops functioning due to an overload of connections from outside the VPC. The security team requires that the DB be accessible only from the application. Which method can be used to protect the databases in the VPC against a DoS attack from outside?',
    options: [
      { id: 'a', text: 'Change the inbound rules of the Security Group to restrict inbound connections to only application ports within the Security Group' },
      { id: 'b', text: 'Change the outbound rules of the Security Group to restrict outbound connections to only application ports within the Security Group' },
      { id: 'c', text: 'Change the inbound rules of the Network ACL to deny access' },
      { id: 'd', text: 'Change the Network ACL and Security Group outbound rules to block external calls' },
    ],
    correctId: 'a',
    explanation: 'Security group inbound rules control what traffic is allowed to reach the database. By restricting inbound rules to allow connections only from the application security group (referencing the application SG ID as the source), you ensure only the application EC2 instances can connect to the database — blocking all other external connections. Security groups are stateful, so only inbound rules need to be modified.',
    reference: '',
    keywords: ['security group', 'inbound rules', 'DoS protection', 'database protection', 'security group reference', 'VPC security'],
  },
  {
    id: 'wz5-048', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-048.png',
    scenario: 'Your company has a set of 100 servers hosted on the AWS Cloud. There is a need to stream the logs from the instances for analysis purposes. From a security compliance perspective, additional logic will be executed to analyze the data for any sort of abnormal behavior. Which of the following would be used to stream the log data?',
    options: [
      { id: 'a', text: 'Amazon CloudFront' },
      { id: 'b', text: 'Amazon SQS' },
      { id: 'c', text: 'Amazon Kinesis Data Streams (KDS)' },
      { id: 'd', text: 'Amazon SES (Simple Email Service)' },
    ],
    correctId: 'c',
    explanation: 'Amazon Kinesis Data Streams (KDS) is purpose-built for real-time log streaming at scale. Multiple producers (100 servers with CloudWatch/Kinesis agents) can stream logs concurrently, and multiple consumers (analytics Lambda, security analysis applications) can process the stream simultaneously. KDS retains records for up to 365 days. SQS is for task queues, not log streaming; CloudFront is a CDN; SES is for email.',
    reference: '',
    keywords: ['Kinesis Data Streams', 'log streaming', 'real-time', '100 servers', 'security analysis', 'stream processing'],
  },
  {
    id: 'wz5-049', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-049.png',
    scenario: 'A startup company wants to launch an online learning portal on AWS using CloudFront and S3. They have different subscription models: basic content available to all members, and premium content including multiple private files. The company wants to restrict premium content without changing current links. How should a Solutions Architect design this solution?',
    options: [
      { id: 'a', text: 'Design the learning portal using CloudFront web distribution to deliver the premium private content using Signed Cookies' },
      { id: 'b', text: 'Design the learning portal using CloudFront web distribution to deliver the premium private content using Signed URLs' },
      { id: 'c', text: 'Design the learning portal using CloudFront web distribution to deliver the premium private content using S3 pre-signed URLs' },
      { id: 'd', text: 'Design the learning portal using CloudFront web distribution to deliver the premium private content using CloudFront geographic restrictions' },
    ],
    correctId: 'a',
    explanation: 'CloudFront Signed Cookies allow you to restrict access to multiple private files without changing their URLs. When a user is authenticated as a premium subscriber, you set signed cookies in their browser. All subsequent CloudFront requests include those cookies for authorization. Signed URLs work per individual file and would require URL changes. Signed Cookies are specifically designed for restricting access to multiple files while keeping URLs intact.',
    reference: '',
    keywords: ['CloudFront Signed Cookies', 'premium content', 'multiple files', 'no URL change', 'private content', 'subscription'],
  },
  {
    id: 'wz5-050', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-050.png',
    scenario: 'A small company uses EBS-backed EC2 instances. The company\'s policy is to stop the development servers over the weekend and restart them each week. The first time the servers were brought back, none of the developers was able to SSH into them. What most likely caused this?',
    options: [
      { id: 'a', text: 'The associated Elastic IP address has changed, and the SSH configurations were not updated' },
      { id: 'b', text: 'The security group for a stopped instance needs to be reassigned after start' },
      { id: 'c', text: 'The public IPv4 address has changed on server restart and the SSH configurations were not updated' },
      { id: 'd', text: 'EBS-backed EC2 instances cannot be stopped and were automatically terminated' },
    ],
    correctId: 'c',
    explanation: 'When an EC2 instance (that does not have an Elastic IP) is stopped and restarted, AWS releases the dynamic public IPv4 address and assigns a new one at restart. Developers who configured SSH with the old IP address would get connection failures. The fix is to either use Elastic IPs for static addressing or retrieve the new public IP after each restart. Security groups are preserved through stop/start cycles.',
    reference: '',
    keywords: ['EC2', 'public IPv4', 'stop start', 'IP change', 'SSH', 'Elastic IP', 'dynamic public IP'],
  },
  {
    id: 'wz5-051', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-051.png',
    scenario: 'You created an Amazon S3 bucket in us-east-1 with default settings (no versioning/Object Lock). From Asia, you delete an object using the AWS CLI and then immediately run list-objects-v2 on the bucket. What should you expect to see?',
    options: [
      { id: 'a', text: 'The object is still there' },
      { id: 'b', text: 'The object is deleted completely' },
      { id: 'c', text: 'The object may still be there or deleted, depending on whether the deletion is finished in AWS' },
      { id: 'd', text: 'The object is attached with a deletion mark' },
    ],
    correctId: 'b',
    explanation: 'Amazon S3 provides strong read-after-write consistency for all operations, including DELETEs, as of December 2020. When you delete an object, any subsequent read or list operation immediately reflects the deletion — the object will not appear in list-objects-v2. This applies globally, regardless of the requester\'s geographic location. The old "eventual consistency" behavior for overwrites and deletes no longer applies.',
    reference: '',
    keywords: ['S3 consistency', 'strong consistency', 'read-after-write', 'DELETE', 'list-objects-v2', 'eventual consistency'],
  },
  {
    id: 'wz5-052', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-052.png',
    scenario: 'An IT firm uses memory-optimized EC2 instances for application hosting and SQL-based database servers in Multi-AZ with auto-failover. Recently, they observe heavy loads on database servers, impacting user data lookup and causing slow access. Which of the following will provide a faster, scalable option to deliver data to users without impacting backend servers?',
    options: [
      { id: 'a', text: 'Use Amazon ElastiCache to cache data' },
      { id: 'b', text: 'Configure the Multi-AZ replicas to serve the read traffic' },
      { id: 'c', text: 'Use Amazon CloudFront to save recently accessed data in cache' },
      { id: 'd', text: 'Use on-host caching on memory-optimized EC2 instance' },
    ],
    correctId: 'a',
    explanation: 'Amazon ElastiCache (Redis or Memcached) provides an in-memory caching layer that serves frequently accessed database results with sub-millisecond latency. Application servers query ElastiCache first; cache misses fall through to RDS. This dramatically reduces database load for read-heavy workloads. Multi-AZ standby replicas do not serve read traffic in standard Multi-AZ (they are for failover only). CloudFront is for HTTP content, not database queries.',
    reference: '',
    keywords: ['ElastiCache', 'caching', 'database load', 'in-memory', 'Redis', 'Memcached', 'read-heavy', 'performance'],
  },
  {
    id: 'wz5-053', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-053.png',
    scenario: 'Your company has EC2 instances in a VPC and suspects some instances are consistently underutilized (low CPU and network). You want an AWS-native way to identify these instances for rightsizing or stopping. The solution should be quick to implement and low effort to operate. Which two services can help find underutilized resources? (Select TWO)',
    options: [
      { id: 'a', text: 'AWS CloudWatch' },
      { id: 'b', text: 'Amazon SNS' },
      { id: 'c', text: 'AWS Trusted Advisor' },
      { id: 'd', text: 'AWS CloudTrail' },
      { id: 'e', text: 'AWS Config' },
    ],
    correctId: 'a,c',
    explanation: 'CloudWatch provides instance-level CPU, network, and disk metrics — you can identify underutilized instances by creating dashboards or alarms on low utilization. AWS Trusted Advisor includes a "Low Utilization Amazon EC2 Instances" check that automatically identifies instances with low CPU utilization over a 14-day period and recommends rightsizing or stopping. Both are native AWS tools requiring minimal setup. CloudTrail tracks API calls; Config tracks configuration changes.',
    reference: '',
    keywords: ['CloudWatch', 'Trusted Advisor', 'underutilized EC2', 'rightsizing', 'Low Utilization check', 'cost optimization'],
  },
  {
    id: 'wz5-054', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Hard',
    screenshotUrl: '/questions/wz5/wz5-054.png',
    scenario: 'A Solutions Architect must design a fully serverless media-upload web app. Users upload files, after which the system must generate thumbnails, transcode videos, index files, validate contents, and aggregate data in near real time. The team requires a graphical console showing the end-to-end workflow and each distributed component\'s state for monitoring and troubleshooting. How should this be designed?',
    options: [
      { id: 'a', text: 'S3 static site → S3 uploads → Lambda on upload → coordinate Lambdas with SQS → store in DynamoDB' },
      { id: 'b', text: 'S3 static site → S3 uploads → Lambda on upload → coordinate Lambdas with SWF → store in DynamoDB' },
      { id: 'c', text: 'S3 static site → S3 uploads → Lambda on upload → process via Lambdas → store in DynamoDB' },
      { id: 'd', text: 'S3 static site → S3 uploads → S3 event → Lambda → coordinate with Step Functions → store in DynamoDB' },
    ],
    correctId: 'd',
    explanation: 'AWS Step Functions provides the visual workflow console showing each step\'s state (Succeeded, Running, Failed) and handles distributed Lambda coordination with automatic retries, error handling, and branching. An S3 event triggers the first Lambda, which starts a Step Functions execution orchestrating all subsequent processing steps (thumbnail, transcode, index, validate, aggregate). SQS and SWF lack the graphical console requirement; plain Lambda-to-Lambda lacks the orchestration and visualization.',
    reference: '',
    keywords: ['Step Functions', 'visual workflow', 'serverless orchestration', 'S3 event', 'Lambda', 'state machine', 'media processing'],
  },
  {
    id: 'wz5-055', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-055.png',
    scenario: 'Your team is deploying new AWS Lambda functions across multiple Regions using infrastructure-as-code. You must allow each function to emit logs to Amazon CloudWatch Logs from its very first cold start, even when the target log group doesn\'t exist yet. Which IAM actions must be granted to the Lambda execution role so the runtime can successfully write logs? (Select THREE)',
    options: [
      { id: 'a', text: 'logs:CreateLogGroup' },
      { id: 'b', text: 'logs:GetLogEvents' },
      { id: 'c', text: 'logs:CreateLogStream' },
      { id: 'd', text: 'logs:DescribeLogStreams' },
      { id: 'e', text: 'logs:PutLogEvents' },
    ],
    correctId: 'a,c,e',
    explanation: 'Lambda requires three CloudWatch Logs permissions: (1) logs:CreateLogGroup — to create the /aws/lambda/{function-name} log group if it doesn\'t exist; (2) logs:CreateLogStream — to create a new log stream for each function instance/invocation; (3) logs:PutLogEvents — to write log records to the stream. logs:GetLogEvents is for reading logs (not needed by the function). logs:DescribeLogStreams is for listing streams.',
    reference: '',
    keywords: ['Lambda', 'CloudWatch Logs', 'CreateLogGroup', 'CreateLogStream', 'PutLogEvents', 'execution role', 'IAM permissions'],
  },
  {
    id: 'wz5-056', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-056.png',
    scenario: 'An organization runs a production serverless microservices application on AWS: Amazon API Gateway + AWS Lambda, Amazon SNS fan-out, and Amazon SQS worker queues. The operations team needs end-to-end request tracing, a service map to visualize dependencies, quick root-cause debugging for latency/errors across managed services, and automatic anomaly detection with notifications. What is the best fit?',
    options: [
      { id: 'a', text: 'CloudWatch dashboards and alarms' },
      { id: 'b', text: 'Amazon EventBridge rule to trigger a Lambda and notify' },
      { id: 'c', text: 'Use AWS X-Ray to analyze and debug, and enable X-Ray Insights notifications' },
      { id: 'd', text: 'Use a third-party tool' },
    ],
    correctId: 'c',
    explanation: 'AWS X-Ray provides end-to-end distributed tracing across Lambda, API Gateway, SQS, and SNS — generating a visual service map showing dependencies and latency between services. X-Ray Insights automatically detects anomalies (latency spikes, error rate increases) and sends notifications via SNS or EventBridge. This directly addresses all four requirements: tracing, service map, root-cause debugging, and anomaly detection with notifications.',
    reference: '',
    keywords: ['X-Ray', 'distributed tracing', 'service map', 'X-Ray Insights', 'anomaly detection', 'serverless debugging'],
  },
  {
    id: 'wz5-057', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-057.png',
    scenario: 'A multinational airline\'s baggage tracking system streams GPS coordinate updates from baggage carts worldwide to AWS. The data is bursty and must be reliably captured and consumed in near real-time by multiple downstream services. Which AWS service best meets this requirement?',
    options: [
      { id: 'a', text: 'Amazon Data Firehose' },
      { id: 'b', text: 'AWS IoT Core' },
      { id: 'c', text: 'Verify job dependencies across batch jobs to ensure resources are available' },
      { id: 'd', text: 'Amazon Kinesis Data Streams' },
    ],
    correctId: 'd',
    explanation: 'Amazon Kinesis Data Streams supports multiple concurrent consumers reading the same stream (fan-out) — meeting the "multiple downstream services" requirement. It handles bursty data ingestion with configurable shards for scalability and provides near real-time (sub-second) data availability. Firehose is for delivery to destinations (S3, Redshift) but doesn\'t support multiple independent consumers on the same stream in the same way.',
    reference: '',
    keywords: ['Kinesis Data Streams', 'multiple consumers', 'fan-out', 'real-time', 'GPS streaming', 'IoT', 'bursty data'],
  },
  {
    id: 'wz5-058', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-058.png',
    scenario: 'A non-profit wants to turn a large library of scanned PDFs and images of educational materials into natural-sounding audiobooks for visually impaired learners. The solution should extract text reliably (including from forms/handwriting) and generate high-quality, human-like speech in multiple voices. Which two AWS services achieve this goal? (Select TWO)',
    options: [
      { id: 'a', text: 'Amazon Textract' },
      { id: 'b', text: 'Amazon Comprehend' },
      { id: 'c', text: 'Amazon Polly' },
      { id: 'd', text: 'Amazon Lex' },
      { id: 'e', text: 'Amazon Kendra' },
    ],
    correctId: 'a,c',
    explanation: 'Amazon Textract extracts text and data from scanned PDFs, images, forms, and tables (including handwritten content) using machine learning — much more accurate than simple OCR. Amazon Polly converts the extracted text to lifelike speech using neural text-to-speech in multiple voices and languages. Together: Textract (document → text) + Polly (text → audio) creates the audiobook pipeline. Comprehend is for NLP/sentiment; Lex is for chatbots; Kendra is for enterprise search.',
    reference: '',
    keywords: ['Textract', 'Polly', 'text-to-speech', 'OCR', 'audiobook', 'PDF extraction', 'handwriting', 'neural TTS'],
  },
  {
    id: 'wz5-059', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    screenshotUrl: '/questions/wz5/wz5-059.png',
    scenario: 'Your single-page web application at https://app.example.com lets authenticated users upload large videos directly to an Amazon S3 bucket. Security requires SSE-KMS for every upload, and the platform team must immediately record both the object version ID and the encryption algorithm actually applied in object metadata, without making extra API calls after the PUT completes. How should you design this upload so the browser can capture these values straight from the response?',
    options: [
      { id: 'a', text: 'Enable S3 server access logging and parse the logs to obtain version IDs and encryption details after each upload' },
      { id: 'b', text: 'Enable S3 bucket versioning and perform PUT uploads with x-amz-server-side-encryption: aws:kms header; read x-amz-version-id and x-amz-server-side-encryption from the PUT response headers and persist them' },
      { id: 'c', text: 'Use S3 Inventory (daily) with "include versions" enabled to obtain object version and encryption details asynchronously' },
      { id: 'd', text: 'Add a bucket policy that denies unencrypted PUTs and rely on the object ETag to uniquely track versions for auditing' },
    ],
    correctId: 'b',
    explanation: 'When S3 Versioning is enabled and an object is PUT with SSE-KMS (x-amz-server-side-encryption: aws:kms), the PUT response headers include x-amz-version-id (the assigned version ID) and x-amz-server-side-encryption (the encryption algorithm applied). The browser can extract these headers immediately from the PUT response without any additional API calls. S3 access logs and Inventory are asynchronous and do not provide immediate capture.',
    reference: '',
    keywords: ['S3 versioning', 'SSE-KMS', 'PUT response headers', 'x-amz-version-id', 'x-amz-server-side-encryption', 'direct upload'],
  },
  {
    id: 'wz5-060', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Hard',
    screenshotUrl: '/questions/wz5/wz5-060.png',
    scenario: 'You are designing a serverless text-to-speech pipeline for a media firm. Large text files in Amazon S3 must be converted to audio with minimal operations, pay-per-request scaling, and clear prioritization: critical jobs must complete quickly while non-critical jobs can run off-peak at lower cost. The solution should chunk inputs, invoke Amazon Polly asynchronously so audio is written directly to S3, and send a notification on completion. Which architecture best meets these goals?',
    options: [
      { id: 'a', text: 'Configure AWS Batch with two job queues (critical on On-Demand, non-critical on Spot) and run containerized workers that call Polly' },
      { id: 'b', text: 'Use S3 event (or manifest) → Step Functions (Distributed Map) → Polly StartSpeechSynthesisTask → S3, with two entry points (High/Low via separate SQS queues); higher Lambda reserved concurrency for High priority, and SNS for completion notification' },
      { id: 'c', text: 'Use ECS Fargate/Fargate Spot services consuming from SQS; workers call Polly synchronous SynthesizeSpeech; scale services with target tracking' },
      { id: 'd', text: 'Use Amazon Lex bots integrated with S3 to read documents and speak them; manage priorities with separate bots' },
    ],
    correctId: 'b',
    explanation: 'The optimal architecture: Step Functions Distributed Map parallelizes chunked text processing; Polly\'s StartSpeechSynthesisTask writes audio asynchronously directly to S3; separate SQS queues (critical/non-critical) with different Lambda concurrency settings manage priority; SNS sends completion notifications. This is fully serverless, pay-per-request, and handles both chunking and priority without managing infrastructure.',
    reference: '',
    keywords: ['Step Functions', 'Distributed Map', 'Polly', 'StartSpeechSynthesisTask', 'SQS priority', 'SNS', 'serverless pipeline'],
  },
  {
    id: 'wz5-061', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-061.png',
    scenario: 'You are a solutions architect. Your organization is building an application hosted on-premises, but wants to keep the data at rest in AWS. All objects/files must be accessed only through the application, with a single exception: Administrators must be able to access the same objects/files directly via the Amazon S3 console/API, bypassing the application. What solution would you provide?',
    options: [
      { id: 'a', text: 'Cached Volume Gateway' },
      { id: 'b', text: 'Stored Volume Gateway' },
      { id: 'c', text: 'File Gateway' },
      { id: 'd', text: 'Tape Gateway' },
    ],
    correctId: 'c',
    explanation: 'AWS Storage Gateway File Gateway stores files as objects in Amazon S3. The on-premises application accesses files through File Gateway using NFS or SMB protocols. Critically, since data is stored natively in S3 as objects, administrators can also access the files directly via the S3 console or API — satisfying the dual-access requirement. Stored Volume Gateway stores data locally and backs up to S3 as EBS snapshots (not directly accessible as S3 objects).',
    reference: '',
    keywords: ['Storage Gateway', 'File Gateway', 'S3 objects', 'dual access', 'on-premises application', 'S3 console access'],
  },
  {
    id: 'wz5-062', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-062.png',
    scenario: 'You operate EC2 instances in us-east-1a and must launch a new EC2 instance in us-east-1c. An existing instance has a production EBS io2 data volume encrypted with a customer-managed KMS key. You require immediate, full I/O performance on access after the move. Using only supported AWS mechanisms, what is the correct way to move the volume\'s data to an instance in the other AZ?',
    options: [
      { id: 'a', text: 'Detach the volume and attach it to an EC2 instance in another AZ' },
      { id: 'b', text: 'Create a new volume in the other AZ and specify the current volume as the source' },
      { id: 'c', text: 'Create a snapshot of the volume, then create a new volume from the snapshot in the other AZ' },
      { id: 'd', text: 'Create a new volume in the AZ and do a disk copy of contents' },
    ],
    correctId: 'c',
    explanation: 'Amazon EBS volumes are AZ-specific and cannot be directly moved to another AZ. The correct procedure is: (1) Create a snapshot of the volume (snapshots are region-level, not AZ-specific); (2) Create a new EBS volume from the snapshot in us-east-1c. The new volume inherits the KMS encryption. EBS Multi-Attach is not cross-AZ; Elastic Volumes cannot change the AZ of a volume.',
    reference: '',
    keywords: ['EBS', 'snapshot', 'cross-AZ', 'volume migration', 'AZ-specific', 'KMS encrypted', 'io2'],
  },
  {
    id: 'wz5-063', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Easy',
    screenshotUrl: '/questions/wz5/wz5-063.png',
    scenario: 'Your organization plans to upload a large number of files to AWS. As soon as each upload completes, those files must be immediately available for download to users in different geographic regions (no wait for propagation). The team asks whether Amazon S3 is suitable for this requirement. What do you suggest?',
    options: [
      { id: 'a', text: 'S3 is not suitable for immediate downloads because AWS provides eventual consistency for new objects' },
      { id: 'b', text: 'EFS is not suitable for immediate downloads because AWS provides eventual consistency for new objects' },
      { id: 'c', text: 'EFS is suitable for immediate downloads because AWS provides eventual consistency for new objects' },
      { id: 'd', text: 'S3 is suitable for immediate downloads because AWS provides strong read-after-write consistency for new objects' },
    ],
    correctId: 'd',
    explanation: 'Since December 2020, Amazon S3 provides strong read-after-write consistency for all S3 GET, PUT, and LIST operations. As soon as a PUT completes successfully, any subsequent GET or LIST request immediately reflects the new object — from any geographic location. The old eventual consistency model for new objects no longer applies. S3 is therefore fully suitable for the described requirement.',
    reference: '',
    keywords: ['S3 consistency', 'read-after-write', 'strong consistency', 'December 2020', 'immediate availability', 'upload download'],
  },
  {
    id: 'wz5-064', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-064.png',
    scenario: 'Your organization deployed an application with an Auto Scaling group in two Availability Zones (AZ-1 with up to 10 instances and AZ-2 with up to 20). After a scaling event in AZ-1, user load increases and you see rapid scaling events plus a hot spot in AZ-1. Which deployment strategy ensures that the additional user load is distributed across both Availability Zones while quickly reaching a balanced state without incurring additional scaling costs?',
    options: [
      { id: 'a', text: 'Use simple scaling policy for the Auto Scaling group' },
      { id: 'b', text: 'Use step scaling policy and enable predictive scaling' },
      { id: 'c', text: 'Use a target tracking policy based on CPU and enable capacity redistribution across AZs' },
      { id: 'd', text: 'Use a scheduled scaling policy for both AZs to align with the expected traffic pattern' },
    ],
    correctId: 'c',
    explanation: 'Target tracking scaling policies automatically adjust capacity to maintain a target utilization (e.g., 60% CPU). When combined with Auto Scaling\'s capacity rebalancing feature, the group redistributes instances across AZs when an imbalance is detected — moving excess capacity from the hot AZ to the underloaded AZ without launching additional instances (no extra cost). This directly resolves the AZ hot spot without over-provisioning.',
    reference: '',
    keywords: ['Auto Scaling', 'target tracking', 'capacity rebalancing', 'AZ imbalance', 'hot spot', 'distribution'],
  },
  {
    id: 'wz5-065', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz5/wz5-065.png',
    scenario: 'A media company runs a multi-Region active-passive architecture fronted by Route 53. In us-east-1, RDS hosts the primary DB. A read replica exists in us-west-2. If us-east-1 fails, which is the most suitable and easy approach for the application to recover?',
    options: [
      { id: 'a', text: 'Update the CNAME for the primary DB instance in us-east-1' },
      { id: 'b', text: 'Update the CNAME for the read replica in us-west-2 after promoting it to a standalone DB' },
      { id: 'c', text: 'Update the RDS DNS Name to point to the us-west-2 instance' },
      { id: 'd', text: 'Switch from Active-Passive to Active-Active and use a multi-master DB' },
    ],
    correctId: 'b',
    explanation: 'When the primary RDS region fails: (1) Promote the Read Replica in us-west-2 to a standalone writable DB instance (takes a few minutes); (2) Update the application\'s database CNAME in Route 53 to point to the promoted instance\'s endpoint. This is the standard cross-region RDS disaster recovery procedure. The promoted instance becomes independent and fully writable. Updating a CNAME for the failed us-east-1 instance does nothing since the region is down.',
    reference: '',
    keywords: ['RDS', 'Read Replica', 'promote', 'cross-region DR', 'CNAME', 'failover', 'active-passive'],
  },
]

const rows = questions.map((q, i) => {
  const options = escape(JSON.stringify(q.options))
  const expl = escape(JSON.stringify({ correct: q.explanation, incorrects: {} }))
  const keywords = escape(JSON.stringify(q.keywords))
  const reference = q.reference ? `'${escape(q.reference)}'` : 'NULL'
  const pageNumber = i + 1
  const screenshotUrl = `'/questions/wz5/${escape(q.id)}.png'`
  return `INSERT OR IGNORE INTO questions (id, domain, domain_label, difficulty, scenario, options, correct_id, explanation, reference, keywords, source, page_number, screenshot_url) VALUES ('${escape(q.id)}', '${q.domain}', '${escape(q.domainLabel)}', '${q.difficulty}', '${escape(q.scenario)}', '${options}', '${escape(q.correctId)}', '${expl}', ${reference}, '${keywords}', 'core', ${pageNumber}, ${screenshotUrl});`
})

writeFileSync('scripts/wz5.sql', rows.join('\n'))
console.log(`Generated ${rows.length} INSERT statements → scripts/wz5.sql`)
