import { writeFileSync } from 'fs'

const escape = (s: string) => s.replace(/'/g, "''")

interface Q {
  id: string
  domain: 'd1' | 'd2' | 'd3' | 'd4'
  domainLabel: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  scenario: string
  options: { id: string; text: string }[]
  correctId: string
  explanation: string
  reference: string
  keywords: string[]
  screenshotUrl: string
}

const questions: Q[] = [
  {
    id: 'wz2-001', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-001.png',
    scenario: 'A global beverage company hosts its web application on AWS. To promote a new beverage, the firm wants to create a distinctive voice using Amazon Polly to market the product to a broad audience. Which Amazon Polly feature should they use?',
    options: [
      { id: 'a', text: 'Create custom Lexicons with Amazon Polly' },
      { id: 'b', text: 'Use a custom SSML tag with Amazon Polly' },
      { id: 'c', text: 'Build a Brand Voice using Amazon Polly' },
      { id: 'd', text: 'Use a Newscaster Speaking Style with Amazon Polly' },
    ],
    correctId: 'c',
    explanation: 'Amazon Polly Brand Voice lets you work with AWS to build a custom voice for your brand using a neural text-to-speech voice. It allows companies to create a distinctive, branded voice that differentiates their product.',
    reference: '',
    keywords: ['Amazon Polly', 'Brand Voice', 'neural TTS', 'custom voice', 'SSML', 'Lexicons'],
  },
  {
    id: 'wz2-002', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-002.png',
    scenario: 'An airline collects large volumes of customer feedback in text files labelled with phrases such as "Ticket returns" and "Flight complaints". These files must be classified and tagged for analysis. The team plans to use Amazon Comprehend and needs advice on how to store the files for processing and where to save the results. How should they design the solution?',
    options: [
      { id: 'a', text: 'Store the files in Amazon EFS volumes. Use Amazon Comprehend to read data from EFS and write results to Amazon Redshift' },
      { id: 'b', text: 'Store the files in Amazon EBS volumes. Use Amazon Comprehend to read data from EBS and write results to Amazon S3' },
      { id: 'c', text: 'Store the files in Amazon Redshift. Use Amazon Comprehend to read data from Redshift and write results to Amazon S3' },
      { id: 'd', text: 'Store the files in an Amazon S3 bucket. Use Amazon Comprehend to read the data from S3 and write results to Amazon Redshift' },
    ],
    correctId: 'd',
    explanation: 'Amazon Comprehend natively integrates with Amazon S3 as its input data source. It reads documents from S3, performs NLP analysis, and can write results to S3 or Redshift. EFS and EBS are not supported as direct Comprehend input sources.',
    reference: '',
    keywords: ['Amazon Comprehend', 'S3', 'NLP', 'text classification', 'EFS', 'EBS', 'Redshift'],
  },
  {
    id: 'wz2-003', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-003.png',
    scenario: 'A stock brokerage runs a trading application on Amazon ECS. They want to embed a virtual agent in the app to provide conversational assistance and real-time, personalized stock recommendations to premium customers. Which AWS service should be integrated?',
    options: [
      { id: 'a', text: 'Amazon Lex' },
      { id: 'b', text: 'Amazon Translate' },
      { id: 'c', text: 'Amazon Transcribe' },
      { id: 'd', text: 'Amazon Personalize' },
    ],
    correctId: 'a',
    explanation: 'Amazon Lex is AWS\'s service for building conversational interfaces (virtual agents/chatbots). It provides AI-powered conversational assistance and can be integrated with other services for personalized recommendations. Lex is the correct choice for embedding a virtual agent with conversational capabilities.',
    reference: '',
    keywords: ['Amazon Lex', 'chatbot', 'virtual agent', 'conversational AI', 'ECS', 'Amazon Personalize', 'Amazon Transcribe'],
  },
  {
    id: 'wz2-004', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-004.png',
    scenario: 'A company runs a website on Amazon EC2 in the US West (N. California) Region and distributes content via Amazon CloudFront. They want to use a third-party SSL/TLS certificate for HTTPS and monitor its expiration. Where should the certificate be imported?',
    options: [
      { id: 'a', text: 'Import the certificate into AWS Certificate Manager (ACM) in the US East (N. Virginia) Region and use it with CloudFront' },
      { id: 'b', text: 'Import the certificate into ACM in the US West (N. California) Region and use it with CloudFront' },
      { id: 'c', text: 'Import the certificate into IAM Certificate Manager in the US East (N. Virginia) Region and use it with CloudFront' },
      { id: 'd', text: 'Import the certificate into IAM Certificate Manager in the US West (N. California) Region and use it with CloudFront' },
    ],
    correctId: 'a',
    explanation: 'CloudFront requires SSL/TLS certificates to be stored in AWS Certificate Manager (ACM) in the US East (N. Virginia) us-east-1 region, regardless of where your origin resources are located. This is a hard requirement for CloudFront distributions.',
    reference: '',
    keywords: ['CloudFront', 'ACM', 'SSL', 'TLS', 'certificate', 'us-east-1', 'N. Virginia'],
  },
  {
    id: 'wz2-005', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-005.png',
    scenario: 'A development team uses an Amazon Aurora cluster with one primary instance and five Aurora replicas. During testing, the primary instance becomes over-utilized by read requests. How should the application be modified to improve performance?',
    options: [
      { id: 'a', text: 'Point the application to the Aurora custom endpoint' },
      { id: 'b', text: 'Point the application to the cluster endpoint' },
      { id: 'c', text: 'Point read queries to the reader endpoint' },
      { id: 'd', text: 'Point the application to the instance endpoint' },
    ],
    correctId: 'c',
    explanation: 'The Aurora reader endpoint automatically load-balances read traffic across all available Aurora Replicas. By directing read queries to the reader endpoint, the primary instance is relieved of read load, improving overall performance.',
    reference: '',
    keywords: ['Aurora', 'reader endpoint', 'read replica', 'cluster endpoint', 'load balancing', 'custom endpoint'],
  },
  {
    id: 'wz2-006', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-006.png',
    scenario: 'A gaming company collects and stores massive volumes of clickstream data ranging from terabytes to petabytes in a centralized Amazon S3 bucket. This data needs to be analysed for business insights, and all analytics workloads are performed using Amazon Redshift, which is deployed securely inside a private subnet in a VPC. The company wants to run complex analytics queries on the S3 data directly, without copying or transforming it into Amazon Redshift. Security and cost efficiency are both critical requirements. As a Solutions Architect, which solution should you recommend?',
    options: [
      { id: 'a', text: 'Use a VPC endpoint to securely connect Redshift with the S3 bucket, and use Amazon Athena to run the queries' },
      { id: 'b', text: 'Use a NAT Gateway to allow Redshift to access the internet and query the S3 bucket using Redshift Spectrum' },
      { id: 'c', text: 'Create a VPC endpoint between Redshift and S3, and use Amazon Redshift Spectrum to run the queries' },
      { id: 'd', text: 'Set up a Site-to-Site VPN connection between Redshift and S3, and use Redshift Spectrum to run the queries' },
    ],
    correctId: 'c',
    explanation: 'Redshift Spectrum allows querying data directly in S3 without loading it into Redshift. A VPC Gateway endpoint for S3 keeps traffic private within AWS network (no NAT Gateway needed), satisfying both security and cost efficiency requirements.',
    reference: '',
    keywords: ['Redshift Spectrum', 'S3', 'VPC endpoint', 'private subnet', 'clickstream', 'NAT Gateway', 'Amazon Athena'],
  },
  {
    id: 'wz2-007', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-007.png',
    scenario: 'A pharmaceutical research team stores sensitive data in Amazon S3. They want to encrypt the data at rest with their own key without writing encryption/decryption code, and will keep the secret key themselves. Which option meets these requirements?',
    options: [
      { id: 'a', text: 'Server-side encryption with customer-provided keys (SSE-C)' },
      { id: 'b', text: 'Server-side encryption with S3-managed keys (SSE-S3)' },
      { id: 'c', text: 'Server-side encryption with KMS keys stored in AWS KMS (SSE-KMS)' },
      { id: 'd', text: 'Client-side encryption' },
    ],
    correctId: 'a',
    explanation: 'SSE-C allows customers to provide their own encryption keys to S3. AWS performs the encryption/decryption server-side (so no coding required), and the customer retains and manages the key. The key is never stored by AWS.',
    reference: '',
    keywords: ['SSE-C', 'SSE-S3', 'SSE-KMS', 'S3 encryption', 'customer-provided key', 'server-side encryption'],
  },
  {
    id: 'wz2-008', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-008.png',
    scenario: 'An online retailer stores terabytes to petabytes of customer data in Amazon S3 and wants to extract business insights. They need to run complex SQL queries on the data and create a visualization dashboard for management review. The solution should be quick to deploy and cost-effective. Which approach is best?',
    options: [
      { id: 'a', text: 'Use Amazon Redshift Spectrum to query the S3 data and send results to Amazon Managed Service for Apache Flink for dashboard creation' },
      { id: 'b', text: 'Use Amazon Redshift to query the S3 data and build a custom web-based dashboard for visualization' },
      { id: 'c', text: 'Use Amazon EMR to query the S3 data and visualize it with Amazon QuickSight' },
      { id: 'd', text: 'Use Amazon Athena to query the S3 data and visualize it with Amazon QuickSight' },
    ],
    correctId: 'd',
    explanation: 'Amazon Athena is serverless and queries S3 directly with no infrastructure to set up — quick to deploy and pay-per-query. Amazon QuickSight is AWS\'s BI visualization service that integrates natively with Athena. Together they provide a cost-effective, fast-to-deploy analytics + visualization solution.',
    reference: '',
    keywords: ['Amazon Athena', 'QuickSight', 'S3', 'serverless', 'SQL', 'BI', 'visualization', 'Redshift Spectrum', 'EMR'],
  },
  {
    id: 'wz2-009', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-009.png',
    scenario: 'A company archives large volumes of data using Amazon S3 Glacier storage classes. The data is occasionally retrieved at unpredictable times, leading to high retrieval charges. Minimizing expenses is a priority. Which strategy should be adopted?',
    options: [
      { id: 'a', text: 'Use S3 Glacier Instant Retrieval for all archived data to ensure fast access without retrieval charges' },
      { id: 'b', text: 'Transition infrequently accessed data to S3 Glacier Deep Archive and schedule bulk retrievals to minimize costs' },
      { id: 'c', text: 'Use S3 lifecycle policies to move data to S3 Glacier Flexible Retrieval and keep retrievals within the free retrieval quota' },
      { id: 'd', text: 'Set up a retrieval policy with no limits so all data is accessible anytime, regardless of cost' },
    ],
    correctId: 'c',
    explanation: 'S3 Glacier Flexible Retrieval includes a free tier of 10 GB of data retrievals per month (bulk). Using lifecycle policies to transition data to this class and managing retrievals within the free tier quota effectively minimizes costs for infrequently accessed archival data.',
    reference: '',
    keywords: ['S3 Glacier Flexible Retrieval', 'S3 lifecycle policy', 'S3 Glacier Instant Retrieval', 'S3 Glacier Deep Archive', 'retrieval cost'],
  },
  {
    id: 'wz2-010', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-010.png',
    scenario: 'A gaming company is launching a new application for web and mobile platforms. They want to expose a single GraphQL API to securely query or update data across multiple databases, microservices and other APIs. Some parts of the data require real-time updates. The company prefers a serverless implementation. Which AWS service should they use?',
    options: [
      { id: 'a', text: 'Amazon Data Firehose' },
      { id: 'b', text: 'Amazon Neptune' },
      { id: 'c', text: 'Amazon API Gateway' },
      { id: 'd', text: 'AWS AppSync' },
    ],
    correctId: 'd',
    explanation: 'AWS AppSync is a fully managed GraphQL service that supports real-time data subscriptions, connects to multiple data sources (DynamoDB, RDS, Lambda, HTTP APIs), and is serverless. It is purpose-built for exactly this use case.',
    reference: '',
    keywords: ['AWS AppSync', 'GraphQL', 'real-time', 'serverless', 'API Gateway', 'DynamoDB', 'subscriptions'],
  },
  {
    id: 'wz2-011', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-011.png',
    scenario: 'A weather forecasting company must store scientific data in a high-performance, POSIX-compliant file system that can serve thousands of simultaneous clients, delivering millions of IOPS with sub-millisecond latency. The workload is short-term and processing-heavy, so the file system should provide burst throughput and be cost-optimized for temporary use. Which file system configuration should you choose?',
    options: [
      { id: 'a', text: 'FSx for Lustre with Deployment Type as Persistent file system' },
      { id: 'b', text: 'FSx for Lustre with Deployment Type as Scratch file system' },
      { id: 'c', text: 'Amazon Elastic File System (EFS)' },
      { id: 'd', text: 'FSx for Windows File Server' },
    ],
    correctId: 'b',
    explanation: 'FSx for Lustre Scratch file systems are designed for temporary, short-term processing workloads. They provide high burst throughput and are more cost-effective than Persistent file systems. Persistent is for long-term, highly available workloads. Lustre delivers millions of IOPS with sub-millisecond latency for HPC workloads.',
    reference: '',
    keywords: ['FSx for Lustre', 'Scratch file system', 'HPC', 'POSIX', 'high IOPS', 'EFS', 'FSx for Windows'],
  },
  {
    id: 'wz2-012', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-012.png',
    scenario: 'A VPC has a primary CIDR block of 20.0.0.0/16. You associate a new secondary IPv4 CIDR block, 30.0.0.0/20, with this VPC. Which entry correctly appears in the route table to enable routing within the VPC?',
    options: [
      { id: 'a', text: 'A route to a peered VPC with destination 30.0.0.0/20 and target pcx-xxxxx' },
      { id: 'b', text: 'A VPN connection route with destination 30.0.0.0/20 and target vgw-xxxxx' },
      { id: 'c', text: 'A Direct Connect route with destination 30.0.0.0/20 and target vgw-xxxxx' },
      { id: 'd', text: 'A route to destination 30.0.0.0/20 with target local' },
    ],
    correctId: 'd',
    explanation: 'When you add a secondary CIDR block to a VPC, AWS automatically adds a route with the destination as the CIDR block and the target as "local" to every route table associated with the VPC. This enables local routing within the VPC for the new CIDR range.',
    reference: '',
    keywords: ['VPC', 'CIDR', 'route table', 'secondary CIDR', 'local route', 'VPC peering', 'Direct Connect'],
  },
  {
    id: 'wz2-013', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-013.png',
    scenario: 'A healthcare organization must retain large volumes of laboratory records for five years to comply with regulations. The data will rarely be accessed, no more than once per quarter, but when it is accessed, it must be available within milliseconds. Which Amazon S3 storage class should the organization choose?',
    options: [
      { id: 'a', text: 'S3 Glacier Flexible Retrieval' },
      { id: 'b', text: 'S3 Glacier Deep Archive' },
      { id: 'c', text: 'S3 Glacier Instant Retrieval' },
      { id: 'd', text: 'S3 Standard-Infrequent Access' },
    ],
    correctId: 'c',
    explanation: 'S3 Glacier Instant Retrieval delivers millisecond retrieval times for archive data accessed once per quarter. S3 Standard-IA costs more per GB. Deep Archive and Flexible Retrieval have retrieval times of hours, not milliseconds. Instant Retrieval is the only Glacier class with millisecond access.',
    reference: '',
    keywords: ['S3 Glacier Instant Retrieval', 'millisecond retrieval', 'S3 Glacier Deep Archive', 'S3 Glacier Flexible Retrieval', 'S3 Standard-IA'],
  },
  {
    id: 'wz2-014', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-014.png',
    scenario: 'A retail company stores all logs in an Amazon S3 bucket. Bucket access is restricted via Service Control Policies (SCPs) to only the Admin account. An external audit firm needs immediate access to this bucket from its own AWS account. The solution must be secure, easy to manage, and avoid sharing credentials. How should the company grant access to the audit firm?',
    options: [
      { id: 'a', text: 'Create a common IAM user in the retail account with AmazonS3FullAccess and share the user credentials with the audit firm' },
      { id: 'b', text: 'Add permissions for the audit firm in an IAM policy, in the SCP, and in the bucket policy' },
      { id: 'c', text: 'Modify the SCP to allow S3 access for the audit firm\'s account in the same way as the Admin account' },
      { id: 'd', text: 'Attach a bucket policy granting the audit firm\'s AWS account read/write permissions and require HTTPS (aws:SecureTransport) for access' },
    ],
    correctId: 'd',
    explanation: 'SCPs only restrict accounts within the AWS Organization — they don\'t apply to external AWS accounts. A bucket policy can grant cross-account access directly to the external audit firm\'s AWS account. Requiring aws:SecureTransport adds security. No credential sharing is needed as the audit firm uses their own AWS credentials.',
    reference: '',
    keywords: ['S3 bucket policy', 'SCP', 'cross-account', 'aws:SecureTransport', 'IAM', 'AWS Organizations'],
  },
  {
    id: 'wz2-015', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-015.png',
    scenario: 'A customer needs a file system that supports NFS v4.1, automatically grows and shrinks as files are added or removed, and requires no servers to manage. File access will be random and infrequent, and the customer wants to minimize cost by automatically moving cold files to a lower-cost tier. Which solution best fits these requirements?',
    options: [
      { id: 'a', text: 'Use Amazon S3' },
      { id: 'b', text: 'Use Amazon S3 Glacier' },
      { id: 'c', text: 'Use Amazon Elastic File System (EFS) with lifecycle management' },
      { id: 'd', text: 'Use Amazon FSx for Lustre' },
    ],
    correctId: 'c',
    explanation: 'Amazon EFS supports NFS v4.1, is fully serverless (no servers to manage), automatically grows and shrinks, and has lifecycle management that moves infrequently accessed files to EFS Infrequent Access (IA) storage class automatically — significantly reducing costs.',
    reference: '',
    keywords: ['EFS', 'NFS v4.1', 'lifecycle management', 'serverless', 'EFS Infrequent Access', 'FSx for Lustre', 'S3'],
  },
  {
    id: 'wz2-016', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-016.png',
    scenario: 'A VPC with CIDR 10.10.0.0/16 contains 100 subnets. One application runs 50 EC2 instances in subnet 10.10.55.0/24, and the team reports intermittent outbound connection failures for roughly 30 instances each day. You need to troubleshoot the problem while minimizing configuration changes and log volume. What is the best course of action?',
    options: [
      { id: 'a', text: 'Create a VPC Flow Log for the entire VPC and filter the logs in CloudWatch Logs' },
      { id: 'b', text: 'Create flow logs for each EC2 instance\'s network interface one by one and investigate' },
      { id: 'c', text: 'Create a flow log for subnet 10.10.55.0/24' },
      { id: 'd', text: 'None of the above' },
    ],
    correctId: 'c',
    explanation: 'Creating a flow log at the subnet level (10.10.55.0/24) captures traffic for only the affected subnet, minimizing log volume compared to VPC-wide logging. It avoids the overhead of creating individual ENI flow logs for 50 instances.',
    reference: '',
    keywords: ['VPC Flow Logs', 'subnet flow log', 'CloudWatch Logs', 'EC2', 'network troubleshooting', 'ENI'],
  },
  {
    id: 'wz2-017', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-017.png',
    scenario: 'A start-up\'s DevOps team is slow to detect and investigate issues. Sensitive data such as configuration variables, product keys and AMI IDs are hard-coded in application code. The CIO asks for a solution to speed up failure analysis and store secrets securely without requiring automated rotation. Cost efficiency is important. Which options should you take? (Select TWO.)',
    options: [
      { id: 'a', text: 'Use AWS Systems Manager Application Manager to monitor resources and accelerate troubleshooting' },
      { id: 'b', text: 'Use AWS AppSync for quick failure analysis' },
      { id: 'c', text: 'Store all secrets in AWS Secrets Manager and update the code' },
      { id: 'd', text: 'Store all secrets in AWS Systems Manager Parameter Store and update the code' },
      { id: 'e', text: 'Store all secrets in a private Amazon S3 bucket' },
    ],
    correctId: 'a,d',
    explanation: 'A) AWS Systems Manager Application Manager provides a unified view of application resources, helps accelerate troubleshooting by showing resource health and operational data. D) SSM Parameter Store securely stores secrets (including SecureString type with KMS encryption) at lower cost than Secrets Manager, and does not require automated rotation — matching the requirement. Secrets Manager (C) is more expensive and is designed for automatic rotation.',
    reference: '',
    keywords: ['Systems Manager Application Manager', 'SSM Parameter Store', 'Secrets Manager', 'SecureString', 'cost efficiency', 'troubleshooting'],
  },
  {
    id: 'wz2-018', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-018.png',
    scenario: 'A banking organization has RDS database instances in private subnets across multiple Availability Zones. To allow the databases to access the internet for patch downloads, the company uses a single NAT gateway deployed in one AZ. Users occasionally experience lost database connections even though RDS instances remain healthy. How should you redesign the network to eliminate these interruptions?',
    options: [
      { id: 'a', text: 'Create a NAT gateway in each Availability Zone and update route tables so that each subnet uses the NAT gateway in its own AZ' },
      { id: 'b', text: 'Update IAM policies to ensure the database instances have correct permissions' },
      { id: 'c', text: 'Increase network bandwidth by upgrading the internet connection' },
      { id: 'd', text: 'Remove the NAT gateway and use VPC peering' },
    ],
    correctId: 'a',
    explanation: 'A single NAT gateway is a single point of failure. When that AZ experiences issues, all database instances in other AZs lose internet connectivity through that NAT gateway, causing connection failures. The solution is to deploy a NAT gateway in each AZ and configure route tables so each subnet routes outbound traffic through its local AZ\'s NAT gateway.',
    reference: '',
    keywords: ['NAT Gateway', 'Availability Zone', 'route table', 'RDS', 'single point of failure', 'high availability'],
  },
  {
    id: 'wz2-019', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-019.png',
    scenario: 'An online advertising company wants to build a recommendation engine that understands customers\' interests, social connections and purchase history to suggest new products. They require a fully managed, highly durable database that stores billions of relationships and supports graph queries with low latency. Which service should they choose?',
    options: [
      { id: 'a', text: 'Amazon DocumentDB' },
      { id: 'b', text: 'Amazon DynamoDB' },
      { id: 'c', text: 'Amazon Aurora' },
      { id: 'd', text: 'Amazon Neptune' },
    ],
    correctId: 'd',
    explanation: 'Amazon Neptune is a fully managed graph database service purpose-built for storing and querying highly connected data. It stores billions of relationships and delivers millisecond query latency. It is ideal for recommendation engines, social networks, and fraud detection use cases.',
    reference: '',
    keywords: ['Amazon Neptune', 'graph database', 'recommendation engine', 'social graph', 'DocumentDB', 'DynamoDB', 'Aurora'],
  },
  {
    id: 'wz2-020', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-020.png',
    scenario: 'A customer wants to migrate an on-premises MongoDB deployment to AWS. They need a fully managed, MongoDB-compatible database engine that minimizes operational overhead and does not require application code changes. Which AWS service is the best choice?',
    options: [
      { id: 'a', text: 'Amazon DocumentDB' },
      { id: 'b', text: 'Amazon DynamoDB' },
      { id: 'c', text: 'Amazon Keyspaces' },
      { id: 'd', text: 'Amazon Neptune' },
    ],
    correctId: 'a',
    explanation: 'Amazon DocumentDB (with MongoDB compatibility) implements the MongoDB API, allowing existing MongoDB applications to work without code changes. It is fully managed, eliminating operational overhead for patching, backups, and scaling.',
    reference: '',
    keywords: ['Amazon DocumentDB', 'MongoDB', 'migration', 'DynamoDB', 'Amazon Keyspaces', 'fully managed'],
  },
  {
    id: 'wz2-021', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-021.png',
    scenario: 'You are an engineer in the FinOps department. A multi-account AWS environment is managed via AWS Control Tower. You must ensure that all accounts under OU=development are restricted from creating resources outside the Ireland region (eu-west-1). Where should the deny-all-except-eu-west-1 policy be applied?',
    options: [
      { id: 'a', text: 'Add the policy to a Permissions Boundary on the developer IAM role' },
      { id: 'b', text: 'Add the policy as a Service Control Policy (SCP) and attach it to the OU=development' },
      { id: 'c', text: 'Add the policy as an SCP and attach it to the root OU' },
      { id: 'd', text: 'Add the policy as a managed policy on the role' },
    ],
    correctId: 'b',
    explanation: 'SCPs attached to an OU apply to all accounts within that OU. Attaching to OU=development restricts only development accounts without affecting other OUs. Attaching to the root OU (option C) would affect ALL accounts including production. Permissions boundaries and IAM managed policies apply per-role, not per-account.',
    reference: '',
    keywords: ['SCP', 'AWS Control Tower', 'AWS Organizations', 'OU', 'region restriction', 'permissions boundary'],
  },
  {
    id: 'wz2-022', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-022.png',
    scenario: 'You\'re transferring a 12 TB file from your on-premises environment to Amazon S3 using AWS Snowball Edge and the AWS CLI. The transfer fails with a validation error. What is the most likely cause?',
    options: [
      { id: 'a', text: 'The maximum file size supported by the AWS CLI is 150 GB' },
      { id: 'b', text: 'The maximum file size supported by the AWS CLI is 5 TB' },
      { id: 'c', text: 'The IAM role used lacks permission to transfer files larger than 5 TB' },
      { id: 'd', text: 'Amazon S3 supports files larger than 10 TB' },
    ],
    correctId: 'b',
    explanation: 'Amazon S3 has a maximum object size of 5 TB. The AWS CLI cannot upload a single object larger than 5 TB to S3. For files larger than 5 TB with Snowball Edge, you must split the file into chunks or use the Snowball Edge client instead of the AWS CLI.',
    reference: '',
    keywords: ['Snowball Edge', 'S3', 'object size limit', '5 TB', 'AWS CLI', 'file transfer'],
  },
  {
    id: 'wz2-023', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-023.png',
    scenario: 'You\'re a research scientist planning to use Amazon Comprehend to analyze content from emails. You are concerned about ownership of the data processed by the service. Who retains ownership of the content?',
    options: [
      { id: 'a', text: 'Customer' },
      { id: 'b', text: 'AWS' },
      { id: 'c', text: 'A third-party company' },
      { id: 'd', text: 'Both AWS and the customer' },
    ],
    correctId: 'a',
    explanation: 'Per AWS\'s data ownership policy, customers retain full ownership of their content. AWS processes it as a service but does not claim ownership. This is a fundamental principle of the AWS Shared Responsibility Model — AWS does not use customer data for its own purposes.',
    reference: '',
    keywords: ['Amazon Comprehend', 'data ownership', 'Shared Responsibility Model', 'customer data', 'privacy'],
  },
  {
    id: 'wz2-024', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-024.png',
    scenario: 'You are a DevOps engineer managing Linux-based container workloads on-premises. You want to integrate these workloads into Amazon ECS using ECS Anywhere. Which components must be installed on your Linux servers?',
    options: [
      { id: 'a', text: 'AWS Systems Manager Agent, Amazon ECS container agent, and Docker' },
      { id: 'b', text: 'AWS Systems Manager Agent and Docker' },
      { id: 'c', text: 'Amazon ECS container agent and Docker' },
      { id: 'd', text: 'Amazon CloudWatch Agent, ECS container agent, and Docker' },
    ],
    correctId: 'a',
    explanation: 'ECS Anywhere requires three components on external instances: (1) AWS Systems Manager Agent for secure communication with AWS, (2) Amazon ECS container agent for task management, and (3) Docker as the container runtime. All three are mandatory.',
    reference: '',
    keywords: ['ECS Anywhere', 'SSM Agent', 'ECS container agent', 'Docker', 'on-premises', 'hybrid'],
  },
  {
    id: 'wz2-025', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-025.png',
    scenario: 'You\'re running Kubernetes workloads on bare-metal nodes in your on-premises data center due to compliance. You want an AWS-managed service to manage Kubernetes across multiple on-prem clusters without virtualization. What\'s the best fit?',
    options: [
      { id: 'a', text: 'Use Amazon ECS Anywhere' },
      { id: 'b', text: 'Move workloads to Amazon EKS' },
      { id: 'c', text: 'Deploy Amazon EKS Anywhere on bare-metal nodes' },
      { id: 'd', text: 'Create a VMware vSphere cluster and integrate with EKS Anywhere' },
    ],
    correctId: 'c',
    explanation: 'Amazon EKS Anywhere allows you to create and manage Kubernetes clusters on your own infrastructure, including bare-metal servers. It provides the same EKS cluster management experience on-premises without requiring virtualization.',
    reference: '',
    keywords: ['EKS Anywhere', 'bare-metal', 'Kubernetes', 'on-premises', 'ECS Anywhere', 'VMware', 'no virtualization'],
  },
  {
    id: 'wz2-026', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-026.png',
    scenario: 'A global manufacturing company is containerizing legacy apps. Due to regulations, some workloads must stay on-prem. They want to manage these applications centrally across on-prem and AWS. Which AWS service enables container management across both environments?',
    options: [
      { id: 'a', text: 'Amazon EKS with Systems Manager agent' },
      { id: 'b', text: 'Amazon ECS Anywhere with Systems Manager agent' },
      { id: 'c', text: 'Amazon Elastic Container Registry with Docker' },
      { id: 'd', text: 'Amazon EKS Distro with Docker' },
    ],
    correctId: 'b',
    explanation: 'Amazon ECS Anywhere extends ECS to manage containerized applications running on on-premises servers, edge locations, and AWS — all from a single control plane using the Systems Manager agent for secure communication.',
    reference: '',
    keywords: ['ECS Anywhere', 'SSM Agent', 'hybrid', 'on-premises', 'ECR', 'EKS', 'container management'],
  },
  {
    id: 'wz2-027', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-027.png',
    scenario: 'You\'re responsible for a microservices-based application running on an Amazon ECS cluster. Users report high latency. You want to analyze how different service components communicate with each other and pinpoint latency bottlenecks. Which AWS service should you use?',
    options: [
      { id: 'a', text: 'Amazon CloudWatch' },
      { id: 'b', text: 'AWS X-Ray' },
      { id: 'c', text: 'Amazon EventBridge' },
      { id: 'd', text: 'Amazon CloudTrail' },
    ],
    correctId: 'b',
    explanation: 'AWS X-Ray provides distributed tracing for applications, showing how requests flow through microservices, where latency occurs, and which service components are causing bottlenecks. It creates a service map showing inter-service communication and performance metrics.',
    reference: '',
    keywords: ['AWS X-Ray', 'distributed tracing', 'ECS', 'microservices', 'latency', 'service map', 'CloudWatch'],
  },
  {
    id: 'wz2-028', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-028.png',
    scenario: 'Your company wants to manage Kubernetes clusters in both on-prem and AWS environments with a consistent operational model. Which service best fits?',
    options: [
      { id: 'a', text: 'Amazon ECS Anywhere' },
      { id: 'b', text: 'Amazon EKS' },
      { id: 'c', text: 'Amazon EKS Anywhere' },
      { id: 'd', text: 'Amazon EKS Distro with CloudFormation' },
    ],
    correctId: 'c',
    explanation: 'Amazon EKS Anywhere provides a consistent Kubernetes operational model for both on-premises and AWS environments. It uses the same EKS tools and APIs on-prem as in the cloud, giving teams a single, consistent operational experience.',
    reference: '',
    keywords: ['EKS Anywhere', 'Kubernetes', 'hybrid', 'on-premises', 'ECS Anywhere', 'EKS Distro', 'consistent operations'],
  },
  {
    id: 'wz2-029', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-029.png',
    scenario: 'You\'re a Cloud Database Administrator enabling IAM authentication for Aurora MySQL. Which command is correct to configure AWSAuthenticationPlugin?',
    options: [
      { id: 'a', text: "CREATE USER iam_db_user IDENTIFIED WITH AWSAuthenticationPlugin;" },
      { id: 'b', text: 'CREATE USER iam_db_user_plugin;' },
      { id: 'c', text: 'Rename IAM iam_db_user as a Database user' },
      { id: 'd', text: "CREATE USER iam_db_user IDENTIFIED WITH AWSAuthenticationPlugin AS 'RDS';" },
    ],
    correctId: 'd',
    explanation: "Per AWS documentation, the correct syntax for creating an IAM-authenticated Aurora MySQL user is: CREATE USER 'username' IDENTIFIED WITH AWSAuthenticationPlugin AS 'RDS'; The AS 'RDS' clause specifies the authentication method and is required. Without it, the plugin configuration is incomplete.",
    reference: '',
    keywords: ['Aurora MySQL', 'IAM authentication', 'AWSAuthenticationPlugin', 'RDS', 'database user', 'IAM DB auth'],
  },
  {
    id: 'wz2-030', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-030.png',
    scenario: 'You\'re using AWS DataSync to transfer over 8 TB from on-premises to Amazon S3. Some files were skipped. What are possible causes? (Select TWO)',
    options: [
      { id: 'a', text: 'The source file was locked' },
      { id: 'b', text: 'The source file was modified during transfer' },
      { id: 'c', text: 'The source file\'s owner was changed during the VERIFYING phase' },
      { id: 'd', text: 'The source file\'s permissions changed during VERIFYING and couldn\'t be read' },
    ],
    correctId: 'a,b',
    explanation: 'DataSync skips files that are locked by another process (cannot be opened for reading) or files that are modified during the transfer (DataSync detects the change and marks the file as skipped to maintain data consistency). Files changed during the VERIFYING phase related to ownership or permissions are different failure modes.',
    reference: '',
    keywords: ['AWS DataSync', 'S3', 'file transfer', 'skipped files', 'file lock', 'VERIFYING phase'],
  },
  {
    id: 'wz2-031', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-031.png',
    scenario: 'A transportation company operates a fleet of delivery trucks with onboard cameras to monitor road conditions and driver behavior. They need a solution to stream and analyze video data in real time. Which AWS service would be most suitable?',
    options: [
      { id: 'a', text: 'AWS IoT Core' },
      { id: 'b', text: 'Amazon Kinesis Video Streams' },
      { id: 'c', text: 'Amazon Kinesis Data Streams' },
      { id: 'd', text: 'Amazon Elastic Transcoder' },
    ],
    correctId: 'b',
    explanation: 'Amazon Kinesis Video Streams is purpose-built for securely ingesting, processing, and storing video streams from connected devices such as cameras. It enables real-time and batch video processing and integrates with ML services for analysis.',
    reference: '',
    keywords: ['Kinesis Video Streams', 'IoT Core', 'video streaming', 'real-time', 'cameras', 'Kinesis Data Streams'],
  },
  {
    id: 'wz2-032', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-032.png',
    scenario: 'You need to reduce compute costs across Amazon EC2, AWS Fargate, and AWS Lambda. You want a flexible pricing model where you can commit to a compute spend rate (e.g., $10/hour) and receive reduced rates. Which AWS service should you use?',
    options: [
      { id: 'a', text: 'AWS Savings Plans' },
      { id: 'b', text: 'AWS Reserved Instances' },
      { id: 'c', text: 'AWS Dedicated Hosts' },
      { id: 'd', text: 'AWS Spot Instances' },
    ],
    correctId: 'a',
    explanation: 'Compute Savings Plans provide flexible discounts across EC2, Fargate, and Lambda. You commit to a consistent compute spend ($/hour) and receive up to 66% savings. Reserved Instances are specific to EC2 only. Savings Plans are the only option covering all three services.',
    reference: '',
    keywords: ['Savings Plans', 'Reserved Instances', 'EC2', 'Fargate', 'Lambda', 'Spot Instances', 'cost optimization'],
  },
  {
    id: 'wz2-033', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-033.png',
    scenario: 'Your company delivers analytics via an Angular SPA using API Gateway REST endpoints. You must log all requests and responses including payloads to troubleshoot latency and ensure campaign separation. What AWS logging option should you use?',
    options: [
      { id: 'a', text: 'Use CloudWatch access logging' },
      { id: 'b', text: 'Use CloudWatch execution logging' },
      { id: 'c', text: 'Use CloudTrail logging' },
      { id: 'd', text: 'Use CloudTrail execution logging' },
    ],
    correctId: 'b',
    explanation: 'API Gateway execution logging in CloudWatch logs detailed information including request/response payloads, Lambda integration errors, and full execution traces. Access logging only records who called the API (no payloads). CloudTrail logs API management events, not request/response payloads.',
    reference: '',
    keywords: ['API Gateway', 'execution logging', 'CloudWatch', 'access logging', 'CloudTrail', 'request payload', 'response payload'],
  },
  {
    id: 'wz2-034', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-034.png',
    scenario: 'Your media company provides stock images and videos for sale. Users can access content via URLs, but you must restrict access only to those who purchased the item without changing the original URL for each access. What should you use?',
    options: [
      { id: 'a', text: 'Use CloudFront signed URLs' },
      { id: 'b', text: 'Use S3 Pre-signed URLs' },
      { id: 'c', text: 'Use CloudFront signed cookies' },
      { id: 'd', text: 'Use S3 signed cookies' },
    ],
    correctId: 'c',
    explanation: 'CloudFront signed cookies allow you to restrict access to multiple files without changing the URLs. When a user purchases content, you set a signed cookie granting them access to all purchased items. Signed URLs are per-object and change the URL. Signed cookies are ideal when users access multiple objects with a single authorization.',
    reference: '',
    keywords: ['CloudFront signed cookies', 'CloudFront signed URLs', 'S3 pre-signed URLs', 'content restriction', 'access control'],
  },
  {
    id: 'wz2-035', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-035.png',
    scenario: 'You operate EC2 workloads in a VPC. A workload on one subnet uses a Transit Gateway in another subnet with different NACLs. Which statement is true regarding NACL rules for traffic from EC2 instances to the transit gateway?',
    options: [
      { id: 'a', text: 'Outbound rules use the source IP address' },
      { id: 'b', text: 'Outbound rules use the destination IP address' },
      { id: 'c', text: 'Outbound rules are not evaluated for the transit gateway subnet' },
      { id: 'd', text: 'Inbound rules use the destination IP address' },
    ],
    correctId: 'b',
    explanation: 'For NACLs, outbound rules on the source subnet evaluate traffic based on the destination IP address (where the traffic is going). When EC2 instances send traffic toward the Transit Gateway, the outbound NACL rules on the EC2 subnet use the destination IP to evaluate the traffic.',
    reference: '',
    keywords: ['NACL', 'Transit Gateway', 'EC2', 'VPC', 'outbound rules', 'destination IP', 'network ACL'],
  },
  {
    id: 'wz2-036', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-036.png',
    scenario: 'Account A stores unencrypted manual RDS snapshots in us-east-1 and needs to share them with specific other AWS accounts in the same region. How should this be done?',
    options: [
      { id: 'a', text: 'Share as private visibility; other accounts restore directly from the snapshot' },
      { id: 'b', text: 'Share as public visibility; other accounts restore directly' },
      { id: 'c', text: 'Share as private visibility; other accounts create a copy first, then restore' },
      { id: 'd', text: 'Share as public visibility; other accounts create a copy first, then restore' },
    ],
    correctId: 'a',
    explanation: 'For unencrypted RDS snapshots, you share them by setting visibility to private and specifying the target account IDs. The target accounts can then directly restore a DB instance from the shared snapshot without needing to copy it first (copying first is required only for encrypted snapshots with KMS keys).',
    reference: '',
    keywords: ['RDS snapshot', 'cross-account', 'unencrypted snapshot', 'snapshot sharing', 'KMS', 'restore'],
  },
  {
    id: 'wz2-037', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-037.png',
    scenario: 'A company uses Amazon Aurora and wants to protect against disk failure while avoiding data loss and reducing restoration overhead. What should they implement?',
    options: [
      { id: 'a', text: 'Aurora Replicas in different regions; crash recovery feature' },
      { id: 'b', text: 'Aurora Replicas in different AZs; storage auto-repair feature' },
      { id: 'c', text: 'Aurora Replicas in different regions; Survivable page cache feature' },
      { id: 'd', text: 'Aurora Replicas in different AZs; crash recovery feature' },
    ],
    correctId: 'b',
    explanation: 'Aurora stores data across multiple AZs and has a storage auto-repair feature: when a disk segment fails, Aurora automatically repairs the data using other segments in the distributed storage without data loss. Aurora Replicas in different AZs provide availability. Regions are not needed for disk failure protection.',
    reference: '',
    keywords: ['Aurora', 'storage auto-repair', 'disk failure', 'Aurora Replicas', 'Availability Zone', 'high availability'],
  },
  {
    id: 'wz2-038', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-038.png',
    scenario: 'A financial institution wants to implement disaster recovery for a web app with a target RTO/RPO of 20 minutes and limited budget. What is the best option?',
    options: [
      { id: 'a', text: 'Multi-site Active/Active' },
      { id: 'b', text: 'Warm Standby' },
      { id: 'c', text: 'Backup and Restore' },
      { id: 'd', text: 'Pilot Light' },
    ],
    correctId: 'd',
    explanation: 'Pilot Light maintains a minimal version of the core system running in the recovery region (like a pilot light on a gas heater). It can achieve 20-minute RTO at lower cost than Warm Standby (which keeps more resources running). Backup and Restore takes hours. Multi-site Active/Active is the most expensive. Pilot Light balances cost and RTO for the 20-minute target.',
    reference: '',
    keywords: ['Pilot Light', 'Warm Standby', 'disaster recovery', 'RTO', 'RPO', 'Multi-site Active/Active', 'Backup and Restore'],
  },
  {
    id: 'wz2-039', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-039.png',
    scenario: 'An app deployed in multiple regions must use Route 53 to ensure automatic failover to healthy resources during disaster. What should you use?',
    options: [
      { id: 'a', text: 'Weighted routing with manual failover' },
      { id: 'b', text: 'Public hosted zones with manual record updates' },
      { id: 'c', text: 'Private hosted zones with manual record updates' },
      { id: 'd', text: 'Health checks and failover routing policy' },
    ],
    correctId: 'd',
    explanation: 'Route 53 health checks continuously monitor endpoint health and, combined with failover routing policy, automatically route traffic to healthy resources when the primary endpoint becomes unhealthy. This eliminates manual intervention during disasters.',
    reference: '',
    keywords: ['Route 53', 'health checks', 'failover routing', 'disaster recovery', 'multi-region', 'automatic failover'],
  },
  {
    id: 'wz2-040', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-040.png',
    scenario: 'An e-commerce company has localized websites in different AWS Regions. The Japanese site is hosted in Tokyo. You must ensure users are routed to the correct regional version based on their geographical location using Route 53. Which routing policy should you use?',
    options: [
      { id: 'a', text: 'Weighted Routing Policy' },
      { id: 'b', text: 'Geoproximity Routing Policy' },
      { id: 'c', text: 'Geolocation Routing Policy' },
      { id: 'd', text: 'Multivalue Answer Routing Policy' },
    ],
    correctId: 'c',
    explanation: 'Geolocation routing routes traffic based on the geographic location of the user (country or continent). This ensures Japanese users go to the Tokyo region, US users to a US region, etc. Geoproximity routing considers physical distance and can be biased, but Geolocation provides deterministic country-to-region mapping.',
    reference: '',
    keywords: ['Route 53', 'Geolocation routing', 'Geoproximity routing', 'Weighted routing', 'multi-region', 'Japan'],
  },
  {
    id: 'wz2-041', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-041.png',
    scenario: 'A research department stores a public dataset in S3. External researchers need to download files regularly. The department wants to pay for storage but not for other organizations\' GET requests or network-transfer costs. Which solution meets this requirement?',
    options: [
      { id: 'a', text: 'Migrate the data to Amazon EFS and mount read-only for external users' },
      { id: 'b', text: 'Enable Requester Pays on the S3 bucket' },
      { id: 'c', text: 'Use S3 Transfer Acceleration to offload costs to CloudFront' },
      { id: 'd', text: 'Configure AWS DataSync so requesters pay for data transfer' },
    ],
    correctId: 'b',
    explanation: 'S3 Requester Pays buckets shift the cost of data requests and data transfer to the requester (downloader). The bucket owner only pays for storage. External researchers must be authenticated AWS users to use Requester Pays buckets.',
    reference: '',
    keywords: ['S3 Requester Pays', 'S3', 'data transfer cost', 'EFS', 'S3 Transfer Acceleration', 'DataSync'],
  },
  {
    id: 'wz2-042', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-042.png',
    scenario: 'A manufacturing company wants to stream live video from hundreds of factory cameras to detect production line anomalies in real time. The solution must support real-time video ingestion, automatic scaling, durable storage, and encryption at rest. Which AWS service should be used?',
    options: [
      { id: 'a', text: 'Amazon Kinesis Data Streams' },
      { id: 'b', text: 'Amazon Kinesis Video Streams' },
      { id: 'c', text: 'Amazon Data Firehose' },
      { id: 'd', text: 'Amazon QuickSight' },
    ],
    correctId: 'b',
    explanation: 'Amazon Kinesis Video Streams is designed for secure, real-time video ingestion from cameras and other video-producing devices. It automatically scales, provides durable storage, and supports encryption at rest. Kinesis Data Streams handles data records, not video streams.',
    reference: '',
    keywords: ['Kinesis Video Streams', 'Kinesis Data Streams', 'real-time video', 'factory cameras', 'Data Firehose', 'encryption at rest'],
  },
  {
    id: 'wz2-043', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-043.png',
    scenario: 'A company requires sensitive files to be encrypted before being uploaded to Amazon S3. Security policy mandates client-side encryption, and AWS must manage the encryption keys securely. What is the most suitable solution?',
    options: [
      { id: 'a', text: 'Enable SSE-S3' },
      { id: 'b', text: 'Use client-side encryption with AWS KMS and a customer-managed CMK' },
      { id: 'c', text: 'Enable S3 Object Lock' },
      { id: 'd', text: 'Use a customer-managed key stored in application code' },
    ],
    correctId: 'b',
    explanation: 'Client-side encryption with AWS KMS means the data is encrypted on the client before upload to S3 (satisfying the client-side encryption requirement), while AWS KMS manages and protects the encryption keys (satisfying the secure key management requirement). The AWS SDK provides client-side encryption utilities.',
    reference: '',
    keywords: ['client-side encryption', 'KMS', 'CMK', 'S3', 'SSE-S3', 'S3 Object Lock', 'AWS SDK'],
  },
  {
    id: 'wz2-044', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-044.png',
    scenario: 'A security engineer needs to assess Amazon EC2 instances for unintended open ports, missing patches, and vulnerabilities. The solution must provide continuous monitoring and automate findings for remediation. Which service should the engineer use?',
    options: [
      { id: 'a', text: 'Amazon GuardDuty' },
      { id: 'b', text: 'Amazon Inspector' },
      { id: 'c', text: 'Amazon Detective' },
      { id: 'd', text: 'AWS Artifact' },
    ],
    correctId: 'b',
    explanation: 'Amazon Inspector automatically discovers and scans EC2 instances for software vulnerabilities (CVEs), unintended network exposure (open ports), and missing patches. It provides continuous monitoring and generates findings that can trigger automated remediation via EventBridge.',
    reference: '',
    keywords: ['Amazon Inspector', 'GuardDuty', 'EC2', 'vulnerability scanning', 'open ports', 'CVE', 'EventBridge'],
  },
  {
    id: 'wz2-045', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-045.png',
    scenario: 'An application uses 50 different Application Load Balancers, each handling traffic for a different microservice on Amazon ECS. The company wants to reduce costs by consolidating without affecting functionality. What is the best solution?',
    options: [
      { id: 'a', text: 'Replace ALBs with a single Network Load Balancer' },
      { id: 'b', text: 'Configure a single ALB with host-based or path-based routing' },
      { id: 'c', text: 'Disable access logs on ALBs to reduce storage costs' },
      { id: 'd', text: 'Replace all ECS services with AWS Lambda functions' },
    ],
    correctId: 'b',
    explanation: 'A single ALB supports multiple listener rules using host-based routing (e.g., service1.example.com → Target Group 1) or path-based routing (/service1/* → Target Group 1). This consolidates 50 ALBs into one, significantly reducing ALB costs while maintaining full routing functionality.',
    reference: '',
    keywords: ['ALB', 'path-based routing', 'host-based routing', 'ECS', 'NLB', 'cost optimization', 'listener rules'],
  },
  {
    id: 'wz2-046', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-046.png',
    scenario: 'A security engineer configured CloudTrail to deliver logs from multiple member accounts to a centralized S3 bucket in the management account. The S3 bucket is encrypted with a customer-managed KMS key. CloudTrail logs are not being delivered from member accounts. What is the most likely cause?',
    options: [
      { id: 'a', text: 'Each member account must create its own KMS key' },
      { id: 'b', text: 'The S3 bucket policy is missing permissions for CloudTrail' },
      { id: 'c', text: 'The KMS key policy does not allow CloudTrail from member accounts to use the key' },
      { id: 'd', text: 'CloudTrail trails must use SSE-S3 instead of SSE-KMS' },
    ],
    correctId: 'c',
    explanation: 'When S3 is encrypted with a customer-managed KMS key, CloudTrail in member accounts must have permission to use that key to encrypt the log files. The KMS key policy in the management account must explicitly grant CloudTrail service principal from each member account (or the organization) permission to GenerateDataKey and Decrypt.',
    reference: '',
    keywords: ['CloudTrail', 'KMS', 'S3', 'multi-account', 'key policy', 'GenerateDataKey', 'management account'],
  },
  {
    id: 'wz2-047', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-047.png',
    scenario: 'A genomics company is running HPC workloads that require parallel access to shared datasets with very low latency and very high throughput. Which storage solution should they use?',
    options: [
      { id: 'a', text: 'Amazon FSx for NetApp ONTAP' },
      { id: 'b', text: 'Amazon FSx for Lustre' },
      { id: 'c', text: 'Amazon FSx for Windows File Server' },
      { id: 'd', text: 'Amazon FSx for OpenZFS' },
    ],
    correctId: 'b',
    explanation: 'Amazon FSx for Lustre is purpose-built for HPC workloads. It provides sub-millisecond latency, hundreds of GB/s throughput, and millions of IOPS for parallel access to shared data. It natively integrates with S3 and is the industry standard for genomics, financial modeling, and media processing.',
    reference: '',
    keywords: ['FSx for Lustre', 'HPC', 'genomics', 'FSx for NetApp ONTAP', 'FSx for OpenZFS', 'high throughput', 'parallel access'],
  },
  {
    id: 'wz2-048', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-048.png',
    scenario: 'A media company serves static content using Amazon CloudFront. They notice increasing data transfer costs from CloudFront back to origin. How can they minimize these origin fetch costs?',
    options: [
      { id: 'a', text: 'Migrate the origin to an on-premises server' },
      { id: 'b', text: 'Enable Requester Pays on the S3 bucket' },
      { id: 'c', text: 'Use an S3 bucket in the same Region as the CloudFront origin with an AWS origin type' },
      { id: 'd', text: 'Decrease the CloudFront TTL values' },
    ],
    correctId: 'c',
    explanation: 'Data transfer from Amazon S3 to CloudFront is free when both are in the same AWS region and S3 is configured as an AWS origin (not a custom origin). Decreasing TTL would increase origin fetches, raising costs. Using S3 as origin in the same region eliminates the per-GB data transfer charge.',
    reference: '',
    keywords: ['CloudFront', 'S3', 'data transfer cost', 'origin fetch', 'S3 Requester Pays', 'TTL', 'static content'],
  },
  {
    id: 'wz2-049', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-049.png',
    scenario: 'An IoT analytics application processes hundreds of thousands of sensor readings per second. The company needs a serverless time-series database to efficiently store, query, and aggregate this data. Which AWS service is the best fit?',
    options: [
      { id: 'a', text: 'Amazon DynamoDB' },
      { id: 'b', text: 'Amazon Neptune' },
      { id: 'c', text: 'Amazon Timestream' },
      { id: 'd', text: 'Amazon DocumentDB' },
    ],
    correctId: 'c',
    explanation: 'Amazon Timestream is a serverless, purpose-built time-series database for IoT and operational data. It automatically scales to handle trillions of events per day, includes built-in time-series analytics functions, and automatically moves data between in-memory and magnetic tiers for cost optimization.',
    reference: '',
    keywords: ['Amazon Timestream', 'IoT', 'time-series', 'serverless', 'DynamoDB', 'Neptune', 'sensor data'],
  },
  {
    id: 'wz2-050', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-050.png',
    scenario: 'A company wants to use Amazon DocumentDB for mission-critical documents requiring high availability and durability. What storage mechanism does Amazon DocumentDB use?',
    options: [
      { id: 'a', text: 'A single EBS volume with snapshots to S3' },
      { id: 'b', text: 'Each 10 GB of data is replicated six ways across three Availability Zones' },
      { id: 'c', text: 'Data is stored only in the primary instance and asynchronously copied' },
      { id: 'd', text: 'DocumentDB stores data in DynamoDB and replicates to global tables' },
    ],
    correctId: 'b',
    explanation: 'Like Amazon Aurora, DocumentDB uses a distributed storage system that automatically replicates each 10 GB chunk of data six times across three Availability Zones. This provides high durability (designed for 99.999999999% durability) and eliminates single points of failure in storage.',
    reference: '',
    keywords: ['Amazon DocumentDB', 'replication', 'Availability Zones', 'high durability', 'distributed storage', 'EBS', 'DynamoDB'],
  },
  {
    id: 'wz2-051', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-051.png',
    scenario: 'A developer tries to launch an EC2 instance from a custom AMI shared from another account. The AMI is encrypted with a customer-managed KMS key. The instance fails to boot with KMS decryption errors. What is the most likely cause?',
    options: [
      { id: 'a', text: 'The AMI was created in a different AWS Region' },
      { id: 'b', text: 'The instance type is not compatible with encrypted volumes' },
      { id: 'c', text: 'The KMS key policy does not allow decryption by the destination account' },
      { id: 'd', text: 'The source account has not enabled fast snapshot restore' },
    ],
    correctId: 'c',
    explanation: 'When an AMI encrypted with a customer-managed KMS key is shared across accounts, the destination account must be granted permission to use the KMS key. The key policy in the source account must allow the destination account\'s IAM principals to use the key for decryption. Without this permission, EBS volumes cannot be decrypted at boot time.',
    reference: '',
    keywords: ['AMI', 'KMS', 'cross-account', 'EBS encryption', 'key policy', 'decryption', 'EC2'],
  },
  {
    id: 'wz2-052', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-052.png',
    scenario: 'A startup runs a legacy web app on a single EC2 instance in a private subnet. The CTO wants HA failover across AZs without using a load balancer. What should the team do?',
    options: [
      { id: 'a', text: 'Use Amazon Route 53 latency routing between AZs' },
      { id: 'b', text: 'Use an Elastic IP and assign it manually in case of failure' },
      { id: 'c', text: 'Attach a secondary Elastic Network Interface (ENI) and move it to a standby instance upon failure' },
      { id: 'd', text: 'Use an Auto Scaling group with minimum size of one and health checks' },
    ],
    correctId: 'c',
    explanation: 'Moving a secondary ENI (with its private IP address) from a failed instance to a standby instance in another AZ provides seamless failover while preserving the private IP address. This is a well-known HA pattern that doesn\'t require a load balancer and is more reliable than manual Elastic IP reassignment.',
    reference: '',
    keywords: ['ENI', 'Elastic Network Interface', 'failover', 'Elastic IP', 'Route 53', 'Auto Scaling', 'high availability'],
  },
  {
    id: 'wz2-053', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-053.png',
    scenario: 'An administrator added a new EBS volume to an EC2 instance for data migration. After rebooting, the instance failed to start correctly; the OS tried to mount the wrong volume as the root device. What is the most likely cause?',
    options: [
      { id: 'a', text: 'The data volume was attached as /dev/sda1' },
      { id: 'b', text: 'The data volume had a duplicate filesystem label' },
      { id: 'c', text: 'The instance uses the wrong boot AMI' },
      { id: 'd', text: 'The instance lacks permission to use the additional volume' },
    ],
    correctId: 'a',
    explanation: '/dev/sda1 is the conventional root device name for EC2 instances. If a data volume is accidentally attached as /dev/sda1, it conflicts with the root EBS volume, causing the OS to attempt booting from the wrong device and failing to start correctly.',
    reference: '',
    keywords: ['EBS', 'EC2', '/dev/sda1', 'root device', 'boot failure', 'volume attachment'],
  },
  {
    id: 'wz2-054', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-054.png',
    scenario: 'A start-up uses a JSON-based database for content management and wants to rehost it to AWS from on-premises. They need millions of requests/second with low latency, flexible schema to store any type of user data from multiple sources, and ability to process data stored in different formats. Which database should be selected?',
    options: [
      { id: 'a', text: 'Amazon DocumentDB (with MongoDB compatibility)' },
      { id: 'b', text: 'Amazon Neptune' },
      { id: 'c', text: 'Amazon Timestream' },
      { id: 'd', text: 'Amazon Keyspaces' },
    ],
    correctId: 'a',
    explanation: 'Amazon DocumentDB is a fully managed JSON document database that supports flexible schemas, handles millions of requests/second with low latency, and is compatible with MongoDB. It is purpose-built for content management and catalog use cases where data comes in different formats and structures.',
    reference: '',
    keywords: ['Amazon DocumentDB', 'JSON', 'flexible schema', 'content management', 'Neptune', 'Timestream', 'Keyspaces'],
  },
  {
    id: 'wz2-055', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-055.png',
    scenario: 'A company needs to monitor disk space, memory, and logs from EC2 instances and on-premises Linux servers. They want a consistent monitoring solution that sends metrics and logs to Amazon CloudWatch. What should they use?',
    options: [
      { id: 'a', text: 'AWS Config' },
      { id: 'b', text: 'CloudWatch Agent in unified mode' },
      { id: 'c', text: 'AWS Systems Manager Session Manager' },
      { id: 'd', text: 'CloudWatch basic monitoring' },
    ],
    correctId: 'b',
    explanation: 'The CloudWatch Agent (in unified mode) collects custom metrics such as memory utilization and disk space (not available in basic monitoring), as well as application and system logs, from both EC2 instances AND on-premises servers. It provides a single, consistent monitoring solution for hybrid environments.',
    reference: '',
    keywords: ['CloudWatch Agent', 'unified mode', 'EC2', 'on-premises', 'memory metrics', 'disk metrics', 'hybrid monitoring'],
  },
  {
    id: 'wz2-056', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-056.png',
    scenario: 'A company needs to allow EC2 instances in a private subnet to access Amazon S3 without traversing the internet. No internet gateway or NAT gateway should be used. Which option meets this requirement?',
    options: [
      { id: 'a', text: 'Create a VPC peering connection between S3 and the VPC' },
      { id: 'b', text: 'Use a Gateway VPC endpoint for Amazon S3' },
      { id: 'c', text: 'Route traffic to S3 through a NAT gateway' },
      { id: 'd', text: 'Configure a public IP on the EC2 instance' },
    ],
    correctId: 'b',
    explanation: 'A Gateway VPC endpoint for Amazon S3 provides private connectivity from within a VPC to S3 without requiring an internet gateway, NAT gateway, or VPN connection. Traffic stays within the AWS network. It is free to create and use.',
    reference: '',
    keywords: ['VPC Gateway endpoint', 'S3', 'private subnet', 'no internet', 'NAT Gateway', 'VPC peering'],
  },
  {
    id: 'wz2-057', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-057.png',
    scenario: 'A company needs to allow an AWS Lambda function to retrieve messages from an Amazon SQS queue. What is the MOST secure way to grant this access?',
    options: [
      { id: 'a', text: 'Attach an inline policy to the SQS queue' },
      { id: 'b', text: 'Create a resource-based policy on the Lambda function' },
      { id: 'c', text: 'Attach an IAM role to the Lambda function with permissions to read from SQS' },
      { id: 'd', text: 'Create a service control policy' },
    ],
    correctId: 'c',
    explanation: 'The most secure AWS best practice is to attach an IAM execution role to the Lambda function with the minimum necessary permissions (e.g., sqs:ReceiveMessage, sqs:DeleteMessage). IAM roles use temporary credentials with no long-term secrets to manage, unlike access keys.',
    reference: '',
    keywords: ['Lambda', 'SQS', 'IAM role', 'execution role', 'resource-based policy', 'SCP', 'least privilege'],
  },
  {
    id: 'wz2-058', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-058.png',
    scenario: 'A solutions architect needs to create a shared file system for multiple EC2 instances running a Linux-based application. The file system must scale automatically and support concurrent access across multiple Availability Zones. What is the best solution?',
    options: [
      { id: 'a', text: 'Amazon EBS' },
      { id: 'b', text: 'Amazon EFS' },
      { id: 'c', text: 'Amazon FSx for Windows File Server' },
      { id: 'd', text: 'Amazon S3 with Transfer Acceleration' },
    ],
    correctId: 'b',
    explanation: 'Amazon EFS is a fully managed NFS file system that supports concurrent access from thousands of EC2 instances across multiple AZs, automatically scales storage capacity up and down, and is ideal for Linux-based shared workloads.',
    reference: '',
    keywords: ['EFS', 'EBS', 'shared file system', 'Linux', 'multi-AZ', 'FSx for Windows', 'auto-scaling'],
  },
  {
    id: 'wz2-059', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-059.png',
    scenario: 'A company has a REST API in API Gateway with EC2 backend. The security team wants to restrict access so only API Gateway can invoke the backend. What is the recommended solution?',
    options: [
      { id: 'a', text: 'Use a security group to allow only API Gateway\'s public IPs' },
      { id: 'b', text: 'Configure a resource policy on the EC2 instance' },
      { id: 'c', text: 'Use a VPC endpoint and private integration with API Gateway' },
      { id: 'd', text: 'Attach an IAM policy to the EC2 instance' },
    ],
    correctId: 'c',
    explanation: 'Using a VPC endpoint with private integration in API Gateway routes traffic from API Gateway through a private Network Load Balancer to the EC2 backend within the VPC. The EC2 security group can then allow traffic only from the NLB, ensuring only API Gateway can reach the backend without exposing it to the internet.',
    reference: '',
    keywords: ['API Gateway', 'VPC endpoint', 'private integration', 'NLB', 'EC2', 'security group', 'REST API'],
  },
  {
    id: 'wz2-060', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-060.png',
    scenario: 'A technology firm uses EBS volumes for project files. Completed projects need long-term, rarely accessed storage for compliance. The operations team needs a cost-efficient solution for EBS snapshots with minimal administrative effort. Which solution would you recommend?',
    options: [
      { id: 'a', text: 'Store the snapshots by creating EBS snapshots and moving them to the Amazon EBS Snapshots Archive' },
      { id: 'b', text: 'Create incremental snapshots using AWS Lambda and store them in S3 Glacier' },
      { id: 'c', text: 'Use third-party low-cost, long-term storage' },
      { id: 'd', text: 'Store the snapshots in the standard EBS snapshot tier' },
    ],
    correctId: 'a',
    explanation: 'Amazon EBS Snapshots Archive is a low-cost storage tier for archiving EBS snapshots that you don\'t need frequent access to. It costs up to 75% less than the standard snapshot tier, has minimal administrative overhead (just change the storage tier), and is fully managed by AWS.',
    reference: '',
    keywords: ['EBS Snapshots Archive', 'EBS', 'S3 Glacier', 'cost optimization', 'long-term storage', 'compliance'],
  },
  {
    id: 'wz2-061', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-061.png',
    scenario: 'A company is deploying a new web application that must be available globally with low latency. The backend is on EC2 behind an ALB. The solution should improve performance for international users. What should the architect do?',
    options: [
      { id: 'a', text: 'Deploy multiple ALBs in different Regions' },
      { id: 'b', text: 'Use AWS Global Accelerator in front of the ALB' },
      { id: 'c', text: 'Enable S3 Transfer Acceleration for dynamic content' },
      { id: 'd', text: 'Place the ALB behind a Network Load Balancer' },
    ],
    correctId: 'b',
    explanation: 'AWS Global Accelerator uses the AWS global network to route user traffic from the nearest edge location to the ALB, significantly reducing latency for international users. It provides static anycast IP addresses and automatically routes to the optimal endpoint, improving availability and performance globally.',
    reference: '',
    keywords: ['AWS Global Accelerator', 'ALB', 'global performance', 'anycast IP', 'NLB', 'S3 Transfer Acceleration'],
  },
  {
    id: 'wz2-062', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-062.png',
    scenario: 'A company hosts a mobile backend on API Gateway and Lambda. Mobile users need to securely upload images directly to a specific S3 bucket. How should the solution be designed?',
    options: [
      { id: 'a', text: 'Allow public write access on the S3 bucket' },
      { id: 'b', text: 'Use API Gateway to upload files directly to S3' },
      { id: 'c', text: 'Generate pre-signed URLs in Lambda and return them to the client' },
      { id: 'd', text: 'Create an IAM role and share credentials with the mobile app' },
    ],
    correctId: 'c',
    explanation: 'Lambda generates S3 pre-signed URLs with time-limited permissions for the specific bucket and object. The mobile client uses the pre-signed URL to upload directly to S3, bypassing API Gateway/Lambda for the upload itself. This is secure (no credential sharing), scalable, and offloads upload traffic from Lambda.',
    reference: '',
    keywords: ['S3 pre-signed URL', 'Lambda', 'API Gateway', 'mobile upload', 'S3', 'IAM', 'direct upload'],
  },
  {
    id: 'wz2-063', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-063.png',
    scenario: 'A company uses AWS CloudFormation to manage infrastructure. The team needs to ensure specific stack resources cannot be accidentally deleted during updates. What should they use?',
    options: [
      { id: 'a', text: 'Enable CloudFormation drift detection' },
      { id: 'b', text: 'Set a DeletionPolicy attribute for critical resources' },
      { id: 'c', text: 'Lock the stack using AWS Config' },
      { id: 'd', text: 'Use AWS Budgets to track stack changes' },
    ],
    correctId: 'b',
    explanation: 'The CloudFormation DeletionPolicy attribute controls what happens to a resource when the stack is deleted or when the resource is removed from the stack. Setting DeletionPolicy to Retain preserves the resource even if the CloudFormation stack is deleted or the resource is removed during updates.',
    reference: '',
    keywords: ['CloudFormation', 'DeletionPolicy', 'Retain', 'drift detection', 'AWS Config', 'stack protection'],
  },
  {
    id: 'wz2-064', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-064.png',
    scenario: 'A company is moving sensitive data to Amazon S3. Compliance requires encryption with a customer-managed key (CMK), and access must be audited and limited by IAM policies. What is the most secure and auditable encryption option?',
    options: [
      { id: 'a', text: 'SSE-S3' },
      { id: 'b', text: 'SSE-KMS with AWS-managed keys' },
      { id: 'c', text: 'SSE-KMS with customer-managed keys (CMK)' },
      { id: 'd', text: 'Client-side encryption with self-managed keys' },
    ],
    correctId: 'c',
    explanation: 'SSE-KMS with a customer-managed CMK provides: (1) full control over key policy and rotation, (2) CloudTrail audit logs for every KMS API call showing who accessed what data and when, (3) IAM policy integration to restrict key usage, and (4) key deletion capability. AWS-managed keys (option B) don\'t allow custom key policies.',
    reference: '',
    keywords: ['SSE-KMS', 'CMK', 'S3 encryption', 'CloudTrail', 'audit', 'IAM', 'SSE-S3', 'customer-managed key'],
  },
  {
    id: 'wz2-065', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    screenshotUrl: '/questions/wz2/wz2-065.png',
    scenario: 'A company stores millions of objects in S3. Many objects are not accessed for months, but when needed, must be retrieved within a few hours. What is the most cost-effective storage class?',
    options: [
      { id: 'a', text: 'S3 Standard' },
      { id: 'b', text: 'S3 One Zone-IA' },
      { id: 'c', text: 'S3 Intelligent-Tiering' },
      { id: 'd', text: 'S3 Glacier Flexible Retrieval' },
    ],
    correctId: 'd',
    explanation: 'S3 Glacier Flexible Retrieval (formerly S3 Glacier) offers the lowest per-GB storage cost for data that is infrequently accessed and can tolerate retrieval times of minutes to hours (standard: 3-5 hours). For data not accessed for months with a few-hour retrieval requirement, Glacier Flexible Retrieval is significantly cheaper than Standard, One Zone-IA, or Intelligent-Tiering.',
    reference: '',
    keywords: ['S3 Glacier Flexible Retrieval', 'S3 Standard', 'S3 One Zone-IA', 'S3 Intelligent-Tiering', 'cost optimization', 'retrieval time'],
  },
]

const rows = questions.map((q, i) => {
  const options = escape(JSON.stringify(q.options))
  const expl = escape(JSON.stringify({ correct: q.explanation, incorrects: {} }))
  const keywords = escape(JSON.stringify(q.keywords))
  const reference = q.reference ? `'${escape(q.reference)}'` : 'NULL'
  const pageNumber = i + 1
  const screenshotUrl = `'/questions/wz2/${escape(q.id)}.png'`
  return `INSERT OR IGNORE INTO questions (id, domain, domain_label, difficulty, scenario, options, correct_id, explanation, reference, keywords, source, page_number, screenshot_url) VALUES ('${escape(q.id)}', '${q.domain}', '${escape(q.domainLabel)}', '${q.difficulty}', '${escape(q.scenario)}', '${options}', '${escape(q.correctId)}', '${expl}', ${reference}, '${keywords}', 'core', ${pageNumber}, ${screenshotUrl});`
})

writeFileSync('scripts/wz2.sql', rows.join('\n'))
console.log(`Generated ${rows.length} INSERT statements → scripts/wz2.sql`)
