import { writeFileSync } from 'fs'

const escape = (s: string) => s.replace(/'/g, "''")

interface Q {
  id: string
  domain: 'd1' | 'd2' | 'd3' | 'd4'
  domainLabel: string
  difficulty: 'Easy' | 'Medium' | 'Hard'
  scenario: string
  options: { id: string; text: string }[]
  correctId: string
  explanation: string
  reference: string
  keywords: string[]
}

const questions: Q[] = [
  {
    id: 'wz6-001', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'You work as a solutions architect for a consulting firm that deploys standardized multi-tier environments (VPC, subnets, security groups, EC2, RDS, IAM roles) across many client AWS accounts. The platform team requires template-driven, version-controlled deployments with the ability to review change sets and roll back safely, while maintaining full control over the underlying infrastructure resources. Which of the following services best fits this requirement?',
    options: [
      { id: 'a', text: 'AWS Elastic Beanstalk' },
      { id: 'b', text: 'Custom AMI' },
      { id: 'c', text: 'AWS CloudFormation' },
      { id: 'd', text: 'EBS Snapshots' },
    ],
    correctId: 'c',
    explanation: 'AWS CloudFormation provides infrastructure-as-code with template-driven, version-controlled deployments. It supports change sets (preview changes before applying), stack rollbacks on failure, and drift detection. You retain full control over every AWS resource created. Elastic Beanstalk abstracts infrastructure away (opinionated PaaS); AMIs capture OS state only; EBS Snapshots are storage backups.',
    reference: '',
    keywords: ['CloudFormation', 'IaC', 'change sets', 'rollback', 'version control', 'stack', 'template-driven'],
  },
  {
    id: 'wz6-002', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'Your company runs an automobile resale platform on EC2 instances in an Auto Scaling group. At boot, each instance must programmatically discover its own private and public IP addresses to register with an internal service registry. Which is the correct AWS-native method?',
    options: [
      { id: 'a', text: 'Use ipconfig/ifconfig on the instance' },
      { id: 'b', text: 'Use AWS CloudTrail' },
      { id: 'c', text: 'Use curl to query instance metadata at 169.254.169.254/latest/meta-data/' },
      { id: 'd', text: 'Use curl to query user data at 169.254.169.254/latest/user-data/' },
    ],
    correctId: 'c',
    explanation: 'The EC2 Instance Metadata Service (IMDS) at 169.254.169.254/latest/meta-data/ exposes the instance\'s private-ipv4, public-ipv4, local-hostname, and public-hostname at runtime. This is the AWS-native, portable method — works identically in any ASG-launched instance. User data (option D) contains bootstrap scripts you provide at launch. CloudTrail records API calls, not runtime instance info.',
    reference: '',
    keywords: ['IMDS', 'instance metadata', '169.254.169.254', 'private IP', 'public IP', 'Auto Scaling', 'bootstrap'],
  },
  {
    id: 'wz6-003', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'You are designing a CloudFormation template that provisions an Application Load Balancer in front of two EC2 instances. After stack creation, the operations team wants CloudFormation to return the ALB\'s DNS name so it can be used by downstream automation. Which template section should you use?',
    options: [
      { id: 'a', text: 'Resources' },
      { id: 'b', text: 'Parameters' },
      { id: 'c', text: 'Outputs' },
      { id: 'd', text: 'Mappings' },
    ],
    correctId: 'c',
    explanation: 'The Outputs section of a CloudFormation template declares values that are returned after stack creation. You can reference resource attributes (e.g., !GetAtt ALB.DNSName) in Outputs so they are visible in the console, accessible via AWS CLI/API, and importable by other stacks. Parameters = inputs. Resources = what to create. Mappings = static lookup tables.',
    reference: '',
    keywords: ['CloudFormation', 'Outputs', 'ALB DNS name', 'GetAtt', 'stack outputs', 'cross-stack reference'],
  },
  {
    id: 'wz6-004', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    scenario: 'Your company must enforce encryption at rest for all customer data stored on EBS-backed EC2 instances and in Amazon S3. Security wants a guardrail that applies to all new volumes and objects without changing applications, with the option to use AWS KMS for centralised key control and audit. Which actions satisfy the at-rest encryption requirement? (Select TWO)',
    options: [
      { id: 'a', text: 'Enable SSL/TLS for EBS volumes' },
      { id: 'b', text: 'Enable EBS encryption' },
      { id: 'c', text: 'Ensure clients use HTTPS for S3' },
      { id: 'd', text: 'Enable S3 server-side encryption' },
    ],
    correctId: 'b,d',
    explanation: 'EBS encryption (B) encrypts volumes at rest using AES-256 with AWS KMS; you can set an account-level default so all new volumes are automatically encrypted. S3 server-side encryption (D) (SSE-S3 or SSE-KMS) encrypts objects at rest on write. Both options apply transparently without application changes. SSL/TLS and HTTPS protect data in transit — not at rest.',
    reference: '',
    keywords: ['EBS encryption', 'S3 SSE', 'KMS', 'at-rest encryption', 'default encryption', 'data protection'],
  },
  {
    id: 'wz6-005', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    scenario: 'Your network team must bring up an AWS Site-to-Site VPN from the on-premises data center to a single VPC (no Transit Gateway). The tunnels must terminate on AWS-managed endpoints and come up over the public internet using IPsec. Which prerequisites are required before you can create a successful VPN connection? (Select TWO)',
    options: [
      { id: 'a', text: 'Route the main route table through a NAT instance' },
      { id: 'b', text: 'A public, internet-routable IP address on the customer gateway (or the NAT device fronting it)' },
      { id: 'c', text: 'A Virtual Private Gateway (VGW) attached to the target VPC' },
      { id: 'd', text: 'An Elastic IP on the virtual private gateway' },
    ],
    correctId: 'b,c',
    explanation: 'Two prerequisites for Site-to-Site VPN: (B) The Customer Gateway must have a static, publicly routable IP address (or a NAT device with a public IP in front of the on-premises router) — this is what AWS tunnels terminate against. (C) A Virtual Private Gateway (VGW) must be created and attached to the target VPC — this is the AWS-side VPN endpoint. VGWs do not need Elastic IPs; they have AWS-managed IPs. NAT instances are for outbound internet, not VPN.',
    reference: '',
    keywords: ['Site-to-Site VPN', 'Virtual Private Gateway', 'Customer Gateway', 'public IP', 'IPsec', 'VPN prerequisites'],
  },
  {
    id: 'wz6-006', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    scenario: 'A c5.large EC2 instance with a single 300-GB gp2/gp3 EBS volume hosts a write-intensive relational database. CloudWatch shows rising VolumeQueueLength and throughput hitting the instance\'s EBS bandwidth ceiling. You need to reduce I/O latency without changing database engines. Which changes will improve storage performance? (Select TWO)',
    options: [
      { id: 'a', text: 'Use a larger EC2 instance type' },
      { id: 'b', text: 'Enable Multi-AZ on the DB' },
      { id: 'c', text: 'Move to Provisioned IOPS (io1/io2)' },
      { id: 'd', text: 'Put the DB behind an ELB' },
    ],
    correctId: 'a,c',
    explanation: 'Two improvements: (A) Larger instance type — EBS bandwidth limits are per-instance-type. c5.large has ~600 MB/s EBS throughput; c5.4xlarge has ~4,750 MB/s. Upsizing the instance raises the bandwidth ceiling. (C) Provisioned IOPS (io1/io2) — delivers guaranteed IOPS with sub-millisecond latency for I/O-intensive workloads, unlike gp2/gp3 which burst. Multi-AZ adds a standby for HA but does not improve write throughput. ELBs route HTTP traffic, not database storage I/O.',
    reference: '',
    keywords: ['EBS', 'io1', 'io2', 'Provisioned IOPS', 'EBS bandwidth', 'instance type', 'VolumeQueueLength', 'storage performance'],
  },
  {
    id: 'wz6-007', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'Your company operates several Amazon RDS DB instances (production and staging) across multiple AZs. To reduce monthly spend, leadership asks you to disable automated backups on non-critical instances as snapshot storage is growing. The DBA notes they sometimes need to recover after accidental changes. If you set the backup retention period to 0 (disabling automated backups), what capability do you lose?',
    options: [
      { id: 'a', text: 'Nothing, you are actually saving resources on AWS' },
      { id: 'b', text: 'You are disabling the point-in-time recovery' },
      { id: 'c', text: 'Nothing really, you can still take manual backups' },
      { id: 'd', text: 'You cannot disable automated backups in RDS' },
    ],
    correctId: 'b',
    explanation: 'Setting the RDS backup retention period to 0 disables automated backups and completely removes the ability to perform point-in-time recovery (PITR). PITR allows restoring the database to any second within the retention window using transaction logs. Manual snapshots remain available but only capture the moment they were taken — they cannot restore to an arbitrary time between snapshots. So accidental data changes cannot be rolled back precisely without PITR.',
    reference: '',
    keywords: ['RDS', 'backup retention', 'point-in-time recovery', 'PITR', 'automated backups', 'restore'],
  },
  {
    id: 'wz6-008', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    scenario: 'Your Windows fleet on AWS must continue authenticating against your existing on-premises Active Directory without replicating domain controllers into AWS. Engineers should log in to Windows instances with their corporate AD accounts. What\'s the best approach?',
    options: [
      { id: 'a', text: 'Use AWS Directory Service AD Connector' },
      { id: 'b', text: 'Use AWS Directory Service Simple AD' },
      { id: 'c', text: 'Deploy new domain controllers on EC2 in AWS' },
      { id: 'd', text: 'Use an IAM-based VPC endpoint for RDP' },
    ],
    correctId: 'a',
    explanation: 'AWS Directory Service AD Connector is a proxy that forwards authentication requests to your existing on-premises Active Directory over Direct Connect or VPN — without caching credentials or replicating domain controllers. EC2 instances domain-join via AD Connector and users log in with their corporate AD credentials. Simple AD is a standalone LDAP/Kerberos service that creates a new directory (not a proxy to existing AD). Deploying domain controllers on EC2 is possible but requires replication and management overhead.',
    reference: '',
    keywords: ['AD Connector', 'Active Directory', 'on-premises AD', 'Windows authentication', 'proxy', 'directory service'],
  },
  {
    id: 'wz6-009', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'Your e-commerce application stores user preferences as ~20 KB key-value items and needs millisecond-latency reads/writes at internet scale with seamless horizontal scaling. Which data store is the best fit?',
    options: [
      { id: 'a', text: 'Amazon RDS' },
      { id: 'b', text: 'Amazon DynamoDB' },
      { id: 'c', text: 'Amazon S3 Glacier' },
      { id: 'd', text: 'Amazon Redshift' },
    ],
    correctId: 'b',
    explanation: 'Amazon DynamoDB is a fully managed NoSQL key-value store delivering single-digit millisecond latency at any scale. It horizontally scales seamlessly by adding partitions. Item size limit is 400 KB — well above the 20 KB requirement. RDS is relational and harder to scale horizontally for KV patterns. S3 Glacier is for archival storage. Redshift is a data warehouse for analytical queries, not OLTP key-value access.',
    reference: '',
    keywords: ['DynamoDB', 'key-value', 'millisecond latency', 'horizontal scaling', 'NoSQL', 'internet scale'],
  },
  {
    id: 'wz6-010', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'You serve static assets (images/CSS/JS) from a private Amazon S3 bucket to a global audience. You must minimize latency, keep the bucket non-public, and improve resilience at the edge (DDoS protection, controlled access, and graceful origin failover) without adding heavy ops overhead. Which design best achieves this?',
    options: [
      { id: 'a', text: 'Cross-Region replication with RDS read replicas' },
      { id: 'b', text: 'Route 53 latency-based routing directly to S3' },
      { id: 'c', text: 'Network Load Balancer in front of S3 static website hosting' },
      { id: 'd', text: 'CloudFront distribution with S3 as the origin' },
    ],
    correctId: 'd',
    explanation: 'CloudFront + S3 is the canonical solution: CloudFront caches assets at 400+ edge PoPs for low global latency. The S3 bucket stays private — CloudFront accesses it via Origin Access Control (OAC). CloudFront includes AWS Shield Standard (DDoS protection) and supports origin failover (configure a secondary origin). NLB does not cache content or provide DDoS protection. Route 53 latency routing sends users to the bucket but does not cache or protect it.',
    reference: '',
    keywords: ['CloudFront', 'S3 private', 'OAC', 'edge caching', 'DDoS protection', 'origin failover', 'static assets'],
  },
  {
    id: 'wz6-011', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    scenario: 'Two AWS accounts (Prod and Analytics) have VPCs VPC-A and VPC-B connected via VPC peering. EC2 instances in VPC-A must access Amazon S3 without traversing the public internet, and Security requires data-exfiltration controls so that requests are allowed only through the approved private path even if internet routes exist. What should you implement?',
    options: [
      { id: 'a', text: 'A NAT Gateway in VPC-A' },
      { id: 'b', text: 'Create an S3 Gateway VPC Endpoint in VPC-A and apply a bucket policy that allows access only via that endpoint' },
      { id: 'c', text: 'Create the S3 Gateway Endpoint in VPC-B and rely on peering' },
      { id: 'd', text: 'Put S3 behind an NLB and target it from the peered VPC' },
    ],
    correctId: 'b',
    explanation: 'An S3 Gateway VPC Endpoint in VPC-A routes all S3 traffic through the AWS private network (no internet). Adding a bucket policy condition of "aws:SourceVpce": "<endpoint-id>" ensures requests are ONLY accepted through that endpoint — blocking all other access paths (including IAM users who might accidentally use public routes). Gateway endpoints are free and work with route table entries. VPC peering does not extend endpoints; the endpoint must be in the consuming VPC.',
    reference: '',
    keywords: ['S3 Gateway endpoint', 'VPC endpoint policy', 'aws:SourceVpce', 'data exfiltration', 'private S3 access', 'bucket policy'],
  },
  {
    id: 'wz6-012', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'A legacy on-prem analytics engine runs long-running, CPU-intensive batch jobs. The team wants to migrate to AWS with minimal operations, elastic scaling, job queues, retries, and cost control (including Spot). Which service is the best fit?',
    options: [
      { id: 'a', text: 'Amazon EC2 with Auto Scaling and cron' },
      { id: 'b', text: 'AWS Lambda with reserved concurrency' },
      { id: 'c', text: 'AWS Batch with managed compute environments' },
      { id: 'd', text: 'Amazon ECS with Fargate on a schedule' },
    ],
    correctId: 'c',
    explanation: 'AWS Batch is purpose-built for batch computing. It provides job queues, priority-based scheduling, retries, and managed compute environments that spin up EC2 (On-Demand or Spot) on demand and scale to zero when idle. You submit jobs; Batch handles provisioning and orchestration. Lambda has a 15-minute timeout — unsuitable for long-running CPU-intensive jobs. EC2 + cron requires self-managed scheduling and retry logic.',
    reference: '',
    keywords: ['AWS Batch', 'batch jobs', 'managed compute', 'Spot Instances', 'job queue', 'elastic scaling', 'HPC migration'],
  },
  {
    id: 'wz6-013', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    scenario: 'You host a web app on EC2 in a custom VPC. Only HTTP (80) and HTTPS (443) from the internet should reach the instances; all other inbound access must be blocked. What should you configure?',
    options: [
      { id: 'a', text: 'Add an outbound rule for ports 80/443 in the security group' },
      { id: 'b', text: 'Add NACL rules for 80/443 to the subnet only' },
      { id: 'c', text: 'Add a security group rule for SSH (22) from 0.0.0.0/0' },
      { id: 'd', text: 'Add security group inbound rules for HTTP (80) and HTTPS (443)' },
    ],
    correctId: 'd',
    explanation: 'Security group inbound rules control what traffic is allowed INTO your instances. Adding inbound rules for TCP 80 (HTTP) and TCP 443 (HTTPS) from 0.0.0.0/0 permits web traffic while implicitly denying everything else (security groups are deny-by-default for inbound). Outbound rules control traffic leaving the instance — not relevant here. SSH (22) would add unwanted access. NACLs at the subnet level are optional and stateless; security groups are the primary instance-level control.',
    reference: '',
    keywords: ['security group', 'inbound rules', 'HTTP 80', 'HTTPS 443', 'deny by default', 'web traffic'],
  },
  {
    id: 'wz6-014', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Easy',
    scenario: 'A Java orders microservice behind an ALB intermittently saturates an Aurora writer during sale spikes. You need to decouple HTTP producers from database writers, buffer burst traffic, and ensure durable, retriable processing with the option to handle poison messages safely. What should you add?',
    options: [
      { id: 'a', text: 'Use Auto Scaling cooldowns' },
      { id: 'b', text: 'Use Amazon SQS between the app and worker consumers' },
      { id: 'c', text: 'Use a second ALB in front of the database' },
      { id: 'd', text: 'Use ElastiCache read replicas' },
    ],
    correctId: 'b',
    explanation: 'Amazon SQS decouples producers from consumers. Burst order messages queue in SQS while worker consumers process them at a rate Aurora can handle. SQS provides durable storage (messages survive until processed), automatic retries on failure, and a Dead Letter Queue (DLQ) for poison messages that fail repeatedly. ALBs route HTTP traffic; they do not buffer or queue. ElastiCache is for caching reads, not write buffering.',
    reference: '',
    keywords: ['SQS', 'decoupling', 'message queue', 'burst buffer', 'Dead Letter Queue', 'DLQ', 'Aurora write protection'],
  },
  {
    id: 'wz6-015', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    scenario: 'A fintech team runs Amazon Aurora MySQL-Compatible (8.0) for OLTP. They must kick off downstream processing whenever specific rows are inserted or updated, with reliable delivery, loose coupling, and near real-time execution, without standing up pollers or heavy ops. Which solutions satisfy the requirement? (Select TWO)',
    options: [
      { id: 'a', text: 'Create a DB trigger that invokes AWS Lambda via the Aurora MySQL Integration' },
      { id: 'b', text: 'Use Aurora cross-Region replicas to run code in a DR Region' },
      { id: 'c', text: 'Publish events to Amazon SQS, then invoke Lambda from SQS' },
      { id: 'd', text: 'Run a cron on an EC2 instance to poll and invoke Lambda' },
    ],
    correctId: 'a,c',
    explanation: 'Two valid approaches: (A) Aurora MySQL natively supports calling Lambda functions from stored procedures/triggers via aws_lambda.invoke() — enables DB-triggered, near-real-time Lambda invocations without polling. (C) Application code publishes events to SQS on insert/update; Lambda uses SQS event source mapping to process messages with automatic retries and DLQ support. Both avoid polling. Option B (cross-region replicas) runs read queries, not downstream processing. Option D (EC2 cron) requires polling and adds ops overhead.',
    reference: '',
    keywords: ['Aurora Lambda integration', 'SQS event source mapping', 'event-driven', 'DB trigger', 'near real-time', 'no polling'],
  },
  {
    id: 'wz6-016', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    scenario: 'Your company is designing a three-tier application on AWS: web servers on EC2, an Amazon RDS MySQL backend, and a load balancer for traffic distribution. Security requires that all data at rest in the database be encrypted with minimal operational effort and centralized key control. Which actions meet this requirement? (Select TWO)',
    options: [
      { id: 'a', text: 'Encrypt the underlying EBS volumes for the database' },
      { id: 'b', text: 'Use the Encryption feature for RDS' },
      { id: 'c', text: 'Use S3 server-side encryption' },
      { id: 'd', text: 'Use AWS Key Management Service' },
    ],
    correctId: 'b,d',
    explanation: 'RDS encryption (B) enables transparent, at-rest encryption of the DB instance, automated backups, read replicas, and snapshots using AES-256 — zero application changes. AWS KMS (D) provides the centralized key management and auditing required. RDS uses KMS as the key store; you specify which CMK to use. Enabling EBS encryption separately is unnecessary when RDS encryption is on (it handles the storage layer). S3 SSE is for S3 objects, not RDS data.',
    reference: '',
    keywords: ['RDS encryption', 'KMS', 'CMK', 'at-rest encryption', 'centralized key control', 'transparent encryption'],
  },
  {
    id: 'wz6-017', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'A global IT firm must process genomics datasets at petabyte scale with elastic compute, low operational overhead, and pay-as-you-go storage. They want to use Apache Spark and avoid building on-prem clusters. Which solution best fits?',
    options: [
      { id: 'a', text: 'Use Amazon EMR with Apache Spark & data stored in Amazon S3 bucket' },
      { id: 'b', text: 'Use Apache Spark deployed at on-premise servers with data stored in Amazon S3 bucket' },
      { id: 'c', text: 'Use Amazon EMR with Apache Spark & data stored in Amazon EC2 instance store' },
      { id: 'd', text: 'Use Apache Spark deployed at on-premise servers with data stored in Amazon EC2 instance store' },
    ],
    correctId: 'a',
    explanation: 'Amazon EMR (Elastic MapReduce) provides fully managed Apache Spark clusters that scale elastically — spin up hundreds of nodes, process data, then terminate. Data stored in S3 (not instance store) provides durable, unlimited, pay-per-GB storage that persists after cluster termination, enabling cost separation between compute and storage. EC2 instance store is ephemeral and lost on termination. On-premises Spark requires capital investment and maintenance.',
    reference: '',
    keywords: ['EMR', 'Apache Spark', 'S3', 'elastic compute', 'petabyte', 'genomics', 'managed cluster'],
  },
  {
    id: 'wz6-018', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'Your team\'s application uses an Amazon DynamoDB table in Provisioned capacity mode. Traffic spikes unpredictably, causing ProvisionedThroughputExceededException during peaks and under-utilization off-peak. Finance requires you to stay on Provisioned (to keep a firm spend ceiling), but you want a one-time change that fixes the issue and auto-handles future bursts. What should you do?',
    options: [
      { id: 'a', text: 'Add an Elastic Load Balancer in front of the DynamoDB table' },
      { id: 'b', text: 'Change the Read Capacity for the table to 20' },
      { id: 'c', text: 'Change the Write capacity for the table to offset the Read capacity' },
      { id: 'd', text: 'Enable Autoscaling for the underlying DynamoDB table' },
    ],
    correctId: 'd',
    explanation: 'DynamoDB Auto Scaling (Application Auto Scaling) dynamically adjusts provisioned read and write capacity in response to actual traffic within your defined min/max bounds — staying within Provisioned mode (no switch to On-Demand required). It scales up during spikes and down during idle periods automatically. This is a one-time configuration change. Hard-coding capacity to 20 (option B) doesn\'t adapt to varying traffic. ELBs do not front DynamoDB.',
    reference: '',
    keywords: ['DynamoDB', 'auto scaling', 'Provisioned mode', 'ProvisionedThroughputExceededException', 'Application Auto Scaling', 'capacity'],
  },
  {
    id: 'wz6-019', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    scenario: 'A serverless API uses AWS Lambda functions in dev/test/prod to connect to an Amazon Aurora database. Security requires that credentials be encrypted at rest, retrieved securely at runtime, rotated automatically without downtime, and that access be auditable across environments. What\'s the best approach?',
    options: [
      { id: 'a', text: 'Hardcode the database credentials in GitHub for different environments of the Lambda function' },
      { id: 'b', text: 'Create a Lambda function for each environment and ensure each has a different programming language' },
      { id: 'c', text: 'Store the database credentials in AWS Secrets Manager' },
      { id: 'd', text: 'Store the database credentials in a Lambda tag' },
    ],
    correctId: 'c',
    explanation: 'AWS Secrets Manager stores credentials encrypted at rest (KMS), retrieves them securely at runtime via API (no plaintext in code), supports automatic rotation for Aurora/RDS without application downtime, and logs every API call to CloudTrail for auditing. Lambda functions retrieve the secret by name at runtime — supporting multiple environments with separate secrets or staging suffixes. Hardcoding in GitHub is a critical security vulnerability. Lambda tags are not for secrets.',
    reference: '',
    keywords: ['Secrets Manager', 'automatic rotation', 'Aurora credentials', 'Lambda', 'encrypted at rest', 'audit', 'CloudTrail'],
  },
  {
    id: 'wz6-020', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'A telecom has nationwide radio devices sending near-real-time telemetry. They want scalable ingestion, durable storage in a data lake, and SQL analytics with minimal ops. Which design fits?',
    options: [
      { id: 'a', text: 'Create an Amazon Kinesis Streams, save compressed data in Amazon EC2 and then copy data to Amazon Redshift' },
      { id: 'b', text: 'Create an Amazon Data Firehose Delivery Stream, save compressed data in the Amazon S3 bucket and then copy data to Amazon Redshift' },
      { id: 'c', text: 'Create an Amazon Data Firehose Delivery Stream, save compressed data in Amazon EC2 and then copy data to Amazon Redshift' },
      { id: 'd', text: 'Create an Amazon Kinesis Streams, save compressed data in the Amazon S3 bucket and then copy data to Amazon Redshift' },
    ],
    correctId: 'b',
    explanation: 'Amazon Data Firehose (formerly Kinesis Data Firehose) is the minimal-ops streaming ingestion service — it automatically buffers, batches, compresses, and delivers data directly to S3 (data lake), Redshift, or OpenSearch with no consumer code. Data in S3 forms the durable data lake; Redshift COPY from S3 enables SQL analytics. Kinesis Data Streams requires writing consumer code. EC2 as an intermediate storage is not durable and adds operational overhead.',
    reference: '',
    keywords: ['Kinesis Data Firehose', 'S3 data lake', 'Redshift', 'telemetry', 'minimal ops', 'streaming ingestion', 'COPY command'],
  },
  {
    id: 'wz6-021', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'Your e-commerce app runs on EC2 in an Auto Scaling group. Usage spikes every day from 7–9 AM (predictable pattern), causing cold starts and latency for early users. You want more capacity before the spike. What should you do?',
    options: [
      { id: 'a', text: 'Ensure that a Simple scaling policy is added to the Auto Scaling group' },
      { id: 'b', text: 'Ensure that a Step scaling policy is added to the Auto Scaling group' },
      { id: 'c', text: 'Ensure that a Scheduled scaling policy is added to the Auto Scaling group' },
      { id: 'd', text: 'Ensure that a Static scaling policy is added to the Auto Scaling group' },
    ],
    correctId: 'c',
    explanation: 'Scheduled scaling pre-emptively adjusts capacity at a specific time and date (or recurring cron schedule). For a predictable daily spike at 7 AM, you configure a scheduled action to scale out before the spike and another to scale in after. This avoids cold starts entirely. Simple and Step scaling are reactive — they respond after CloudWatch alarms fire (already too late for the spike\'s first minute). "Static scaling policy" does not exist in Auto Scaling.',
    reference: '',
    keywords: ['scheduled scaling', 'Auto Scaling', 'predictable traffic', 'pre-emptive', 'cron', 'capacity planning'],
  },
  {
    id: 'wz6-022', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Medium',
    scenario: 'Your company has an existing Amazon Redshift cluster that must meet a new compliance control to encrypt data at rest. What should you do?',
    options: [
      { id: 'a', text: 'Enable the encryption feature for the cluster' },
      { id: 'b', text: 'Enable encryption for the underlying EBS volumes' },
      { id: 'c', text: 'Use SSL certificates to encrypt the data at rest' },
      { id: 'd', text: 'Create a new cluster with encryption enabled, and then migrate the data over to the new cluster' },
    ],
    correctId: 'a',
    explanation: 'AWS supports enabling encryption on an existing Amazon Redshift cluster in-place via the console Modify option or the modify-cluster CLI command. AWS creates an encrypted snapshot and restores it as an encrypted cluster. Redshift is not EBS-backed — option B is inapplicable. SSL certificates protect data in transit, not at rest. Creating a new cluster (D) was the old approach before in-place encryption was supported.',
    reference: 'https://docs.aws.amazon.com/redshift/latest/mgmt/changing-cluster-encryption.html',
    keywords: ['Redshift', 'encryption at rest', 'modify cluster', 'KMS', 'compliance', 'in-place encryption'],
  },
  {
    id: 'wz6-023', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'A fintech startup needs Kubernetes for portability but does not want to manage worker nodes. It requires fast scale-out without capacity pre-warming, strong per-pod isolation, and deep AWS integrations (e.g., EKS Pod Identity/IRSA, ALB Ingress, CloudWatch, and EFS/EBS CSI). What do you recommend?',
    options: [
      { id: 'a', text: 'Use Amazon Elastic Kubernetes Service with Amazon EC2 worker nodes' },
      { id: 'b', text: 'Use Amazon Elastic Container Service with AWS Fargate launch type' },
      { id: 'c', text: 'Use Amazon Elastic Container Service with Amazon EC2 launch type' },
      { id: 'd', text: 'Use Amazon Elastic Kubernetes Service with AWS Fargate launch type' },
    ],
    correctId: 'd',
    explanation: 'EKS with Fargate satisfies all requirements: Kubernetes API (portability); serverless nodes (no worker node management); per-pod isolation (each pod runs in its own Fargate micro-VM); fast scale-out (Fargate provisions on demand); and full AWS integrations (IRSA/Pod Identity, ALB Ingress Controller, CloudWatch Container Insights, EFS/EBS CSI drivers). ECS does not provide Kubernetes compatibility. EKS with EC2 nodes requires managing and patching node groups.',
    reference: '',
    keywords: ['EKS', 'Fargate', 'Kubernetes', 'serverless nodes', 'IRSA', 'ALB Ingress', 'per-pod isolation', 'portability'],
  },
  {
    id: 'wz6-024', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'A popular English podcast wants to expand globally with multilingual text versions. They need automatic transcription of audio and automatic translation of that text into multiple languages. Which services should they use? (Select TWO)',
    options: [
      { id: 'a', text: 'Amazon Kendra' },
      { id: 'b', text: 'Amazon Rekognition' },
      { id: 'c', text: 'Amazon Lex' },
      { id: 'd', text: 'Amazon Transcribe' },
      { id: 'e', text: 'Amazon Translate' },
    ],
    correctId: 'd,e',
    explanation: 'Amazon Transcribe converts audio/speech to text (ASR — Automatic Speech Recognition). Amazon Translate then translates that text into any of 75+ supported languages using neural machine translation. Together they form a transcription + localization pipeline. Kendra is enterprise search; Rekognition is image/video analysis; Lex is a conversational chatbot builder.',
    reference: '',
    keywords: ['Transcribe', 'Translate', 'speech-to-text', 'multilingual', 'podcast', 'ASR', 'NMT'],
  },
  {
    id: 'wz6-025', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'In your VPC (10.0.0.0/16), you must add a new private subnet that supports at least 20 EC2 instances right away, accounting for AWS\'s standard five reserved IPs per subnet. Which IPv4 CIDR block should you assign to the subnet?',
    options: [
      { id: 'a', text: '10.0.0.0/27' },
      { id: 'b', text: '10.0.0.0/26' },
      { id: 'c', text: '10.0.0.0/29' },
      { id: 'd', text: '10.0.0.0/30' },
    ],
    correctId: 'b',
    explanation: '/26 = 64 total IPs − 5 AWS reserved = 59 usable EC2 IPs. /27 = 32 − 5 = 27 usable (just enough, but /26 provides better capacity headroom for at least 20 instances). /29 = 8 − 5 = 3 usable (not enough). /30 = 4 − 5 = insufficient. The recommended choice is /26 (59 usable) which comfortably supports 20+ instances with room to grow.',
    reference: '',
    keywords: ['CIDR', 'subnet sizing', '/26', '5 reserved IPs', 'usable IPs', 'VPC subnet'],
  },
  {
    id: 'wz6-026', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'A marketplace needs to automatically block NSFW images at upload time for product listings. The team wants an API-based, pre-trained solution that flags categories such as nudity, violence, or hate symbols with confidence scores, no custom model training, and should also support extension to video moderation later. Which AWS service best fits?',
    options: [
      { id: 'a', text: 'Amazon Rekognition' },
      { id: 'b', text: 'Amazon Comprehend' },
      { id: 'c', text: 'Amazon SageMaker' },
      { id: 'd', text: 'Amazon Kendra' },
    ],
    correctId: 'a',
    explanation: 'Amazon Rekognition provides a Content Moderation API that detects unsafe or inappropriate content in images and videos (nudity, explicit content, violence, hate symbols) with confidence scores — no model training required. It also supports real-time video moderation via Kinesis Video Streams. Comprehend is for NLP text analysis. SageMaker is for custom ML model training. Kendra is enterprise document search.',
    reference: '',
    keywords: ['Rekognition', 'content moderation', 'NSFW', 'image moderation', 'video moderation', 'confidence score', 'no training'],
  },
  {
    id: 'wz6-027', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Hard',
    scenario: 'A company hosts two public websites, example.com and brand.co on the same Application Load Balancer (ALB). Each domain has its own ACM-issued TLS certificate. They want the most cost-effective way to present the correct certificate for each request without adding another ALB and without having to reissue a combined certificate whenever domains change. What should they do?',
    options: [
      { id: 'a', text: 'Launch an additional TLS-enabled ALB fronting Amazon EC2 instances with different certificates for each domain' },
      { id: 'b', text: 'Use a wildcard certificate on the ALB that covers both domains' },
      { id: 'c', text: 'Use a single certificate with Subject Alternative Name (SAN) that includes both domains' },
      { id: 'd', text: 'Use multiple TLS certificates on the ALB listener via SNI (Server Name Indication)' },
    ],
    correctId: 'd',
    explanation: 'ALB HTTPS listeners support multiple TLS certificates per listener via Server Name Indication (SNI). The ALB selects the correct certificate based on the hostname in the TLS ClientHello. Each domain keeps its own independently managed ACM certificate — adding or rotating one doesn\'t require touching the other. A wildcard cert (B) only covers subdomains of a single apex domain; it cannot cover two different apex domains. A SAN cert (C) must be reissued whenever domains change.',
    reference: '',
    keywords: ['ALB', 'SNI', 'multiple TLS certificates', 'HTTPS listener', 'Server Name Indication', 'ACM', 'cost-effective'],
  },
  {
    id: 'wz6-028', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'A company is building active-active across two Regions and wants to explicitly split traffic between them (e.g., 50/50) for blue/green or phased rollout. Which Route 53 policy should they use?',
    options: [
      { id: 'a', text: 'Simple Routing' },
      { id: 'b', text: 'Failover Routing' },
      { id: 'c', text: 'Latency Routing' },
      { id: 'd', text: 'Weighted Routing' },
    ],
    correctId: 'd',
    explanation: 'Route 53 Weighted Routing lets you assign numeric weights to multiple records pointing to different endpoints. AWS distributes traffic proportionally — e.g., weight 50/50 sends half to each region, or 90/10 for a canary deployment. Simple routing returns one value. Failover routing routes only to a secondary when the primary fails (not gradual split). Latency routing sends users to the lowest-latency region — not an explicit percentage split.',
    reference: '',
    keywords: ['Route 53', 'weighted routing', 'blue/green', 'traffic split', 'active-active', 'phased rollout', 'canary'],
  },
  {
    id: 'wz6-029', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    scenario: 'A media firm uses S3 for video uploads via Multipart Upload. Some uploads never complete, and these orphaned parts are accruing storage cost. How can they minimize charges?',
    options: [
      { id: 'a', text: 'Reporters need to compress video files locally before uploading to Amazon S3 bucket' },
      { id: 'b', text: 'Reporters need to upload videos to Amazon S3 Glacier to save additional charges' },
      { id: 'c', text: 'Create a Lifecycle Policy to move all incomplete Multipart uploads to Amazon S3 Glacier after weeks\' time from initiation' },
      { id: 'd', text: 'Create a Lifecycle Policy to delete all incomplete Multipart uploads after weeks\' time from initiation' },
    ],
    correctId: 'd',
    explanation: 'S3 Lifecycle rules support an AbortIncompleteMultipartUpload action that automatically deletes incomplete multipart uploads after a configured number of days from initiation. This removes all orphaned parts and stops storage charges. Moving incomplete parts to Glacier (option C) still incurs storage costs. Compression or changing storage class does not address the orphaned-parts problem.',
    reference: '',
    keywords: ['S3 Lifecycle', 'incomplete multipart upload', 'AbortIncompleteMultipartUpload', 'orphaned parts', 'cost optimization', 'storage charges'],
  },
  {
    id: 'wz6-030', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Hard',
    scenario: 'A media platform serves static assets from Amazon S3 through Amazon CloudFront. Security requires blocking direct S3 access, supporting SSE-KMS, and minimizing operational overhead. What\'s the recommended way to allow CloudFront to fetch the S3 objects while keeping the bucket private?',
    options: [
      { id: 'a', text: 'Configure CloudFront Origin Access Control (OAC) for the S3 origin and update the bucket policy to allow only the OAC; keep the bucket public access blocked' },
      { id: 'b', text: 'Use Origin Access Identity (OAI) with the S3 website endpoint for the origin' },
      { id: 'c', text: 'Keep the bucket public and rely on CloudFront signed URLs to protect objects' },
      { id: 'd', text: 'Add an S3 bucket policy that allowlists CloudFront IP ranges only' },
    ],
    correctId: 'a',
    explanation: 'Origin Access Control (OAC) is the recommended replacement for OAI. OAC supports SSE-KMS encrypted S3 buckets (OAI does not), uses SigV4 request signing, and works with S3 object ownership controls. You attach the OAC to the CloudFront distribution and add a bucket policy granting only that OAC principal access — bucket stays fully private. CloudFront IP allowlisting is fragile as IPs change. Signed URLs require application-side URL generation.',
    reference: '',
    keywords: ['CloudFront OAC', 'Origin Access Control', 'SSE-KMS', 'private S3', 'bucket policy', 'OAI replacement'],
  },
  {
    id: 'wz6-031', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Easy',
    scenario: 'Your platform team is standardizing on Amazon ECS to orchestrate containerized services that run a mix of critical (customer-facing APIs, payment processors) and non-critical (report generation, batch ETL, cache warmers) workloads. Finance wants significant cost savings, but SREs insist that critical services must not be interrupted. What is the most cost-effective compute strategy the team should adopt?',
    options: [
      { id: 'a', text: 'Use ECS orchestration and Spot Instances for processing critical data and On-Demand for the non-critical data' },
      { id: 'b', text: 'Use ECS orchestration and On-Demand Instances for processing critical data and Spot Instances for the non-critical data' },
      { id: 'c', text: 'Use ECS orchestration and Spot Instances for both the processing of critical data and non-critical data' },
      { id: 'd', text: 'Use ECS orchestration and On-Demand Instances for both the processing of critical data and non-critical data' },
    ],
    correctId: 'b',
    explanation: 'The optimal strategy is: On-Demand for critical workloads (guaranteed availability, no interruption) and Spot Instances for non-critical workloads (up to 90% cost savings, tolerable interruption). Critical customer-facing APIs and payment processors must never be interrupted — On-Demand provides this guarantee. Batch ETL and cache warmers can handle interruption and restart gracefully — Spot is ideal. Using Spot for critical services (A or C) risks outages.',
    reference: '',
    keywords: ['Spot Instances', 'On-Demand', 'ECS', 'cost optimization', 'critical workloads', 'non-critical', 'interruption tolerance'],
  },
  {
    id: 'wz6-032', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    scenario: 'Your company has recently adopted Amazon API Gateway to front internal microservices. A new single-page web app is hosted at https://app.partner-example while your API endpoint is https://api-example. When the SPA calls the API from the browser, the requests are blocked by the browser\'s same-origin policy. You must allow the browser to call your API securely from the other domain without proxying traffic through a server you manage. Which API Gateway feature should you use?',
    options: [
      { id: 'a', text: 'API Stages' },
      { id: 'b', text: 'API Deployment' },
      { id: 'c', text: 'API CORS' },
      { id: 'd', text: 'API Access' },
    ],
    correctId: 'c',
    explanation: 'API Gateway has native CORS (Cross-Origin Resource Sharing) configuration. Enabling CORS on a resource adds the required Access-Control-Allow-Origin, Access-Control-Allow-Methods, and Access-Control-Allow-Headers response headers. For REST APIs, API Gateway automatically creates the OPTIONS preflight method handler. This tells browsers to allow cross-origin requests from the specified domain without routing traffic through a proxy server.',
    reference: '',
    keywords: ['API Gateway', 'CORS', 'cross-origin', 'same-origin policy', 'SPA', 'OPTIONS preflight', 'Access-Control-Allow-Origin'],
  },
  {
    id: 'wz6-033', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'You use an Auto Scaling group (ASG) to keep a fleet of web servers responsive during traffic spikes. After scaling out, your group sometimes immediately scales again before the new instances finish bootstrapping, causing churn. You want the ASG to wait for the most recent scaling activity to stabilize before taking another scaling action. What should you change?',
    options: [
      { id: 'a', text: 'Modify the instance user data to add a custom timeout' },
      { id: 'b', text: 'Increase the Auto Scaling cooldown timer value' },
      { id: 'c', text: 'Enable Auto Scaling cross-zone load balancing' },
      { id: 'd', text: 'Disable CloudWatch alarms until instances stabilize' },
    ],
    correctId: 'b',
    explanation: 'The Auto Scaling cooldown period (default 300 seconds) prevents the ASG from launching or terminating additional instances before the previous scaling activity has taken effect. Increasing the cooldown timer gives newly launched instances sufficient time to finish bootstrapping and join the load balancer before the ASG evaluates whether more scaling is needed. User data timeouts don\'t affect ASG scaling decisions.',
    reference: '',
    keywords: ['Auto Scaling', 'cooldown', 'scaling churn', 'bootstrap time', 'stabilization', 'scaling timer'],
  },
  {
    id: 'wz6-034', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'A startup wants "push-button" deployments for a LAMP web app. The CIO asks for an AWS-managed service that can provision a load-balanced, Auto Scaling environment; deploy the app; pull the latest artifacts from S3 during provisioning; and let the team do blue/green cutover deployments. Which service best meets these requirements with minimal ops?',
    options: [
      { id: 'a', text: 'AWS Elastic Beanstalk' },
      { id: 'b', text: 'Amazon CloudFront' },
      { id: 'c', text: 'AWS CodePipeline' },
      { id: 'd', text: 'AWS DevOps' },
    ],
    correctId: 'a',
    explanation: 'AWS Elastic Beanstalk handles provisioning (EC2, ALB, ASG, RDS optional), deployment, capacity scaling, and health monitoring automatically. You upload your app or point it to S3, and Beanstalk creates and manages the entire environment. It supports blue/green deployment by creating a clone environment and doing a URL swap (CNAME swap). CodePipeline is a CI/CD orchestrator, not an application platform. CloudFront is a CDN.',
    reference: '',
    keywords: ['Elastic Beanstalk', 'LAMP', 'PaaS', 'blue/green', 'CNAME swap', 'managed deployment', 'Auto Scaling'],
  },
  {
    id: 'wz6-035', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'An ingestion service writes a high volume of items to a DynamoDB table in Region A. A secondary application must fetch only new or changed items every 2 hours and run downstream processing (enrichment, notifications). The team wants a design that avoids scanning the entire table, preserves ordering, and reliably delivers only the changes since the last run. What should you implement?',
    options: [
      { id: 'a', text: 'Insert a timestamp for each record and then scan the entire table for the timestamp as per the last 2 hours' },
      { id: 'b', text: 'Create another DynamoDB table with the records modified in the last 2 hours' },
      { id: 'c', text: 'Use DynamoDB Streams to monitor the changes in the DynamoDB table' },
      { id: 'd', text: 'Transfer records to S3 which were modified in the last 2 hours' },
    ],
    correctId: 'c',
    explanation: 'DynamoDB Streams captures a time-ordered log of all item-level changes (INSERT, MODIFY, REMOVE) with a 24-hour retention window. The secondary application reads from the stream to get exactly the changed items since the last read position — no table scans, ordering preserved, no missed updates. You can also trigger Lambda from the stream for real-time processing. Scanning the full table (option A) is expensive and slow at scale.',
    reference: '',
    keywords: ['DynamoDB Streams', 'change data capture', 'CDC', 'item changes', 'time-ordered', 'no full scan', 'event-driven'],
  },
  {
    id: 'wz6-036', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'Your collaboration platform runs on EC2 with an Amazon RDS for MySQL 8.0 backend. During traffic spikes you see "Too many connections" errors. The team plans to add Amazon RDS Proxy to pool connections, but for an immediate, safe fix you must raise MySQL\'s max_connections following RDS best practices (no host access). What\'s the correct way to do this in RDS?',
    options: [
      { id: 'a', text: 'SSH to the RDS host and edit /etc/mysql/my.cnf' },
      { id: 'b', text: 'Create a new custom DB parameter group, set max_connections, and attach it to the instance' },
      { id: 'c', text: 'Create/attach an option group and change the setting there' },
      { id: 'd', text: 'Edit the default parameter group attached to the DB instance' },
    ],
    correctId: 'b',
    explanation: 'RDS is a managed service — you have no SSH/OS access to the host. Database engine parameters are managed via DB Parameter Groups. You cannot edit the default parameter group (it is shared and read-only); you must create a custom parameter group, set max_connections to the desired value, and attach it to the DB instance (apply on next maintenance or immediately with a reboot). Option groups configure optional engine features (e.g., Oracle TDE, MySQL memcached), not connection limits.',
    reference: '',
    keywords: ['RDS', 'DB parameter group', 'max_connections', 'custom parameter group', 'no SSH', 'connection pooling', 'Too many connections'],
  },
  {
    id: 'wz6-037', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    scenario: 'Several EC2 instances in private subnets (no public IPs) must read/write to an S3 bucket. Security requires the traffic must not traverse the public internet, and costs should be minimized. What should you add?',
    options: [
      { id: 'a', text: 'S3 Gateway VPC endpoint' },
      { id: 'b', text: 'S3 Interface endpoint (AWS PrivateLink)' },
      { id: 'c', text: 'NAT Gateway' },
      { id: 'd', text: 'Internet Gateway' },
    ],
    correctId: 'a',
    explanation: 'S3 Gateway VPC endpoints are free — no hourly charge, no data processing fee. They route S3 traffic through the AWS private network via route table entries in the subnet. Internet traffic never leaves AWS. S3 Interface endpoints (PrivateLink) also provide private access but cost ~$0.01/hour + data processing fees — significantly more expensive. NAT Gateway routes to the public internet. Internet Gateway requires public IPs.',
    reference: '',
    keywords: ['S3 Gateway endpoint', 'private S3 access', 'no internet', 'free', 'VPC endpoint', 'cost-effective'],
  },
  {
    id: 'wz6-038', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'You\'re designing a big-data analytics app that writes many small and large objects to Amazon S3 and then immediately needs to read or list those objects. Is S3 suitable for this access pattern?',
    options: [
      { id: 'a', text: 'No, S3 uses eventual consistency' },
      { id: 'b', text: 'Yes, S3 provides strong read-after-write and list consistency automatically' },
      { id: 'c', text: 'No, S3 isn\'t suitable for big-data workloads' },
      { id: 'd', text: 'No, S3 is not cost-effective for storing large amounts of data' },
    ],
    correctId: 'b',
    explanation: 'Since December 2020, Amazon S3 provides strong read-after-write consistency for all operations — GET, PUT, DELETE, and LIST — at no additional cost and with no configuration required. After a successful PUT, any subsequent GET or LIST immediately reflects the new object. The old eventual consistency model no longer applies. S3 is widely used for big-data analytics (EMR, Athena, Glue) and is highly cost-effective at scale.',
    reference: '',
    keywords: ['S3 consistency', 'read-after-write', 'strong consistency', 'LIST consistency', 'December 2020', 'big-data'],
  },
  {
    id: 'wz6-039', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'You created a VPC, attached an Internet Gateway, and launched an instance that received a public IP. However, the instance still cannot reach the internet. The route table for the instance\'s subnet currently has only local routes. What change is required?',
    options: [
      { id: 'a', text: 'Add a route 0.0.0.0/0 → Internet Gateway in the subnet\'s route table' },
      { id: 'b', text: 'Change the CIDR 10.0.0.0/16 to target the Internet Gateway' },
      { id: 'c', text: 'Add a route 10.0.0/16 → Internet Gateway' },
      { id: 'd', text: 'Add a route 0.0.0.0/16 → Internet Gateway' },
    ],
    correctId: 'a',
    explanation: 'A public subnet requires a route that sends all non-local traffic (destination 0.0.0.0/0 for IPv4) to the Internet Gateway. Without this route, the subnet is effectively private — the instance has a public IP but no path to send packets to the internet. The local route covers VPC-internal traffic only. The route target must be the Internet Gateway ID (igw-xxx).',
    reference: '',
    keywords: ['route table', 'Internet Gateway', '0.0.0.0/0', 'public subnet', 'default route', 'VPC networking'],
  },
  {
    id: 'wz6-040', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'You\'re rolling out a new version of an ALB + Auto Scaling + EC2 web tier behind Amazon Route 53. You want a DNS-level blue/green (canary) deployment, starting with 10% of traffic to "green", then gradually increasing to 50% and finally 100%, while using health checks to fall back if needed. Which Route 53 routing policy should you choose?',
    options: [
      { id: 'a', text: 'Simple' },
      { id: 'b', text: 'Multivalue Answer' },
      { id: 'c', text: 'Latency' },
      { id: 'd', text: 'Weighted' },
    ],
    correctId: 'd',
    explanation: 'Route 53 Weighted routing assigns relative weights to records for the same name — e.g., blue=90/green=10 for 10% canary traffic. You increment the green weight gradually while health checks monitor the endpoints and automatically exclude unhealthy targets. This is the standard pattern for DNS-level blue/green and canary deployments. Latency routing routes by lowest latency, not percentage. Multivalue returns multiple values but doesn\'t support controlled weighting.',
    reference: '',
    keywords: ['Route 53', 'weighted routing', 'blue/green', 'canary deployment', 'health check', 'DNS', 'traffic split'],
  },
  {
    id: 'wz6-041', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'A company is planning to deploy an application in AWS. This application runs on a single EC2 instance that continuously processes large log files, requiring up to ~500 MB/s of sustained read/write throughput. The team wants the most cost-effective Amazon EBS volume type that still meets this high-throughput, sequential I/O pattern. Which option should they choose?',
    options: [
      { id: 'a', text: 'General Purpose SSD volumes' },
      { id: 'b', text: 'Provisioned IOPS SSD volumes' },
      { id: 'c', text: 'Throughput Optimized HDD volumes' },
      { id: 'd', text: 'Cold HDD volumes' },
    ],
    correctId: 'c',
    explanation: 'Throughput Optimized HDD (st1) is optimized for large, sequential I/O workloads — log processing, big data, data warehousing. It delivers up to 500 MB/s throughput at much lower cost per GB than SSD options. It is designed for sustained high-throughput sequential access, making it ideal for continuously processing large log files. gp3/gp2 are general-purpose SSD; io1/io2 are high-IOPS SSD (more expensive, suited for random I/O). Cold HDD (sc1) has lower throughput limits.',
    reference: '',
    keywords: ['EBS', 'Throughput Optimized HDD', 'st1', '500 MB/s', 'sequential I/O', 'log processing', 'cost-effective throughput'],
  },
  {
    id: 'wz6-042', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    scenario: 'There are two logical folders, A and B, in the same S3 bucket. Folder A contains frequently accessed objects; Folder B contains infrequently accessed, non-critical objects that still require millisecond retrieval when needed. You plan to use different storage classes per object to reduce cost. Which combination fits best?',
    options: [
      { id: 'a', text: 'Standard for folder A and S3 Glacier Instant Retrieval for folder B' },
      { id: 'b', text: 'Intelligent-Tiering for folder A and Reduced Redundancy for folder B' },
      { id: 'c', text: 'Standard for folder A and One Zone-IA for folder B' },
      { id: 'd', text: 'Two S3 buckets are required as an S3 bucket cannot have two storage classes simultaneously' },
    ],
    correctId: 'c',
    explanation: 'S3 Standard for folder A (frequently accessed — lowest latency, highest availability). S3 One Zone-IA for folder B (infrequently accessed, non-critical — millisecond retrieval, ~20% cheaper than Standard-IA because it uses one AZ). The "non-critical" qualifier makes One Zone-IA appropriate (data loss in an AZ event is acceptable). Glacier Instant Retrieval costs less but has a 90-day minimum storage duration. Reduced Redundancy is a deprecated class. A single bucket can hold objects with different storage classes.',
    reference: '',
    keywords: ['S3 Standard', 'One Zone-IA', 'storage class', 'infrequently accessed', 'millisecond retrieval', 'non-critical', 'cost optimization'],
  },
  {
    id: 'wz6-043', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'You are developing a new mobile application expected to serve thousands of customers. You need to store user preferences (non-relational, ~30 KB per item) in AWS with a design that is cost-effective, highly available, scalable, and secure. Which option is most suitable?',
    options: [
      { id: 'a', text: 'Create a new Amazon RDS instance and store the user data there' },
      { id: 'b', text: 'Create an Amazon DynamoDB table with the required Read and Write capacity and use it as the data layer' },
      { id: 'c', text: 'Use Amazon Glacier to store the user data' },
      { id: 'd', text: 'Use an Amazon Redshift cluster for managing the user preferences' },
    ],
    correctId: 'b',
    explanation: 'DynamoDB is purpose-built for mobile app backends: managed key-value/document store with single-digit millisecond latency, automatic multi-AZ replication (HA), seamless horizontal scaling, and built-in security (IAM, encryption at rest). Item size limit is 400 KB — fits 30 KB items. It requires no schema changes as preferences evolve. RDS is over-engineered for simple KV preferences. Glacier is archival storage. Redshift is a data warehouse.',
    reference: '',
    keywords: ['DynamoDB', 'mobile backend', 'user preferences', 'NoSQL', 'highly available', 'scalable', 'key-value'],
  },
  {
    id: 'wz6-044', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    scenario: 'Instances in the private subnets of your VPC must access sensitive documents in Amazon S3. Due to confidentiality, the traffic must not traverse the public internet, and instances must remain without public IPs. What should you implement?',
    options: [
      { id: 'a', text: 'Consider using a VPC Endpoint' },
      { id: 'b', text: 'Consider using an EC2 Endpoint' },
      { id: 'c', text: 'Move the instances to a public subnet' },
      { id: 'd', text: 'Create a VPN connection and access the S3 resources from the EC2 instance' },
    ],
    correctId: 'a',
    explanation: 'A VPC Endpoint (specifically an S3 Gateway Endpoint) creates a private route from your VPC to S3 within the AWS network — traffic never leaves AWS. Instances in private subnets with no public IPs can access S3 directly. Moving to a public subnet adds internet exposure. VPN connects to on-premises networks, not to S3. "EC2 Endpoint" is not a real AWS service.',
    reference: '',
    keywords: ['VPC endpoint', 'S3 private access', 'no internet', 'private subnet', 'Gateway endpoint', 'confidential'],
  },
  {
    id: 'wz6-045', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'A company currently hosts its application in us-east-1 and is duplicating the stack in eu-west-1. They want users in both Regions to experience the lowest possible latency automatically using a single DNS name. What should they configure?',
    options: [
      { id: 'a', text: 'Create an Elastic Load Balancer setup to route traffic to both locations' },
      { id: 'b', text: 'Create a weighted Route 53 policy to route the policy based on the weightage for each location' },
      { id: 'c', text: 'Create an Auto Scaling group to route traffic to both locations' },
      { id: 'd', text: 'Create a latency-based Route 53 policy to route the traffic based on the location' },
    ],
    correctId: 'd',
    explanation: 'Route 53 Latency-Based Routing measures latency from the user to each AWS Region and routes DNS queries to the region with the lowest latency. Users in Europe are routed to eu-west-1; users in the US to us-east-1 — automatically with no manual configuration. Weighted routing splits traffic by percentage regardless of user location. ELB operates within a Region, not across Regions. Auto Scaling groups do not route DNS traffic.',
    reference: '',
    keywords: ['Route 53', 'latency-based routing', 'multi-region', 'lowest latency', 'global users', 'DNS routing'],
  },
  {
    id: 'wz6-046', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'Your development team plans to run both web and application servers on Amazon EC2. They want a fully automated bootstrap so that every new instance (from any AMI or Auto Scaling Group) always downloads and installs the latest versions of the web/app packages at launch, no manual steps. Which approach best fits this requirement?',
    options: [
      { id: 'a', text: 'Ask the Development team to create scripts which can be added to the User Data section when the instance is launched' },
      { id: 'b', text: 'Ask the Development team to create scripts which can be added to the Meta Data section when the instance is launched' },
      { id: 'c', text: 'Use Auto Scaling Groups to install the Web and Application servers when the instances are launched' },
      { id: 'd', text: 'Use EC2Config to install the Web and Application servers when the instances are launched' },
    ],
    correctId: 'a',
    explanation: 'EC2 User Data runs shell scripts (Linux) or PowerShell (Windows) automatically at first boot, before the instance becomes available. Placing the installation script in User Data ensures every instance — regardless of which AMI it launched from — downloads and installs the latest packages at launch. Meta Data is read-only instance information (IP, AMI-ID, etc.) — you cannot write scripts there. Auto Scaling Groups manage capacity but do not execute installation scripts.',
    reference: '',
    keywords: ['EC2 User Data', 'bootstrap', 'auto install', 'startup script', 'launch time', 'Auto Scaling', 'latest packages'],
  },
  {
    id: 'wz6-047', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'A company website will launch soon, and traffic may surge in the first weeks. You want a simple, robust DNS failover so that if the primary application stack becomes unhealthy/overloaded, users are automatically served a static fallback site (status page/limited content) without manual intervention. How can you set this up?',
    options: [
      { id: 'a', text: 'Duplicate the exact application architecture in another region and configure DNS Weight-based routing' },
      { id: 'b', text: 'Enable failover to an on-premises data center to the application hosted there' },
      { id: 'c', text: 'Use Amazon Route 53 with the failover routing policy to fail over to an S3 static website or CloudFront distribution' },
      { id: 'd', text: 'Add more servers in case the application fails' },
    ],
    correctId: 'c',
    explanation: 'Route 53 Failover Routing uses health checks on the primary record. If the primary (application stack) becomes unhealthy, Route 53 automatically routes DNS queries to the secondary (S3 static website or CloudFront distribution). S3 static hosting has no servers to fail and handles virtually unlimited traffic — ideal as a fallback/maintenance page. This requires no manual intervention. Weighted routing always splits traffic — it doesn\'t exclusively serve the static site on failure.',
    reference: '',
    keywords: ['Route 53', 'failover routing', 'health check', 'S3 static website', 'DNS failover', 'automatic', 'fallback'],
  },
  {
    id: 'wz6-048', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Medium',
    scenario: 'Your company runs a fleet of web servers on Reserved EC2 Instances with EBS-backed root volumes. CPU utilization is a steady 80%, and traffic is distributed by an Elastic Load Balancer. The company also operates Amazon RDS for MySQL in both development and production, each configured for Multi-AZ. Leadership has asked you to reduce cost without impacting availability of mission-critical systems (i.e., production). What is the most appropriate recommendation?',
    options: [
      { id: 'a', text: 'Consider using On-Demand Instances instead of Reserved EC2 Instances' },
      { id: 'b', text: 'Consider not using Multi-AZ RDS in the development environment' },
      { id: 'c', text: 'Consider using Spot Instances instead of Reserved EC2 Instances' },
      { id: 'd', text: 'Consider removing the Elastic Load Balancer' },
    ],
    correctId: 'b',
    explanation: 'Multi-AZ for RDS incurs ~2x the instance cost (standby replica in a second AZ). Development environments do not require production-level HA — a single-AZ dev RDS instance is sufficient, reducing RDS cost by ~50% for that environment. On-Demand (A) is more expensive than Reserved. Spot (C) is unsuitable for steady 80% CPU web servers (interruption risk). Removing the ELB (D) breaks traffic distribution and availability.',
    reference: '',
    keywords: ['RDS Multi-AZ', 'development environment', 'cost reduction', 'single-AZ', 'Reserved Instances', 'cost optimization'],
  },
  {
    id: 'wz6-049', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    scenario: 'You\'re building a highly available application. During testing, it fails until you add port 443 to the relevant security group. After adding the rule, how long until the application should start working on 443?',
    options: [
      { id: 'a', text: 'Generally, it takes 2-5 minutes for rules to propagate' },
      { id: 'b', text: 'Immediately after rebooting EC2 instances in that security group' },
      { id: 'c', text: 'Changes apply instantly; the application should respond on 443 right away' },
      { id: 'd', text: 'It takes 60 seconds for rules to apply to all AZs in the Region' },
    ],
    correctId: 'c',
    explanation: 'Security group rule changes take effect immediately — no reboot, no propagation delay. As soon as you save the new inbound rule for TCP 443, all existing and new connections are evaluated against the updated rules. This is one of the key advantages of security groups over traditional firewall rule systems. There is no propagation timer or reboot requirement.',
    reference: '',
    keywords: ['security group', 'immediate effect', 'rule change', 'no reboot', 'no propagation', 'TCP 443'],
  },
  {
    id: 'wz6-050', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'A team will run containers on Amazon ECS in us-east-1 and wants the least administrative overhead when launching and running tasks. Which approach best meets the requirement?',
    options: [
      { id: 'a', text: 'Use the Fargate launch type in Amazon ECS' },
      { id: 'b', text: 'Use the EC2 launch type in Amazon ECS' },
      { id: 'c', text: 'Use the Auto Scaling launch type in Amazon ECS' },
      { id: 'd', text: 'Use the ELB launch type in Amazon ECS' },
    ],
    correctId: 'a',
    explanation: 'ECS Fargate is a serverless compute engine for containers. AWS manages the underlying infrastructure — no EC2 instances to provision, patch, or scale. You define CPU and memory per task; Fargate handles everything else. EC2 launch type requires managing a cluster of EC2 instances (patching, scaling, capacity planning). "Auto Scaling launch type" and "ELB launch type" do not exist in ECS.',
    reference: '',
    keywords: ['ECS Fargate', 'serverless containers', 'no EC2 management', 'least overhead', 'managed compute'],
  },
  {
    id: 'wz6-051', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'A company wants to automate the data transfer between its SaaS applications (like Salesforce, ServiceNow, and others) and an Amazon S3 bucket while minimizing the need for custom development or complex code. Which AWS service should the company use to simplify this process?',
    options: [
      { id: 'a', text: 'Amazon Kinesis Data Streams' },
      { id: 'b', text: 'AWS DataSync' },
      { id: 'c', text: 'AWS Glue' },
      { id: 'd', text: 'AWS AppFlow' },
    ],
    correctId: 'd',
    explanation: 'AWS AppFlow is a fully managed integration service for bidirectional data transfer between SaaS applications (Salesforce, ServiceNow, Slack, Zendesk, SAP, etc.) and AWS services like S3, Redshift, and EventBridge — without writing custom code. It provides built-in connectors, data transformation, field mapping, filtering, and scheduling. DataSync transfers files between storage systems (NFS, SMB, S3) — not SaaS APIs. Kinesis is for streaming data ingestion. Glue is for ETL jobs.',
    reference: '',
    keywords: ['AppFlow', 'SaaS integration', 'Salesforce', 'ServiceNow', 'no-code', 'data transfer', 'managed connector'],
  },
  {
    id: 'wz6-052', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'You\'re re-hosting a licensed application on Amazon EC2 (Linux). The vendor license is bound to the NIC\'s MAC address, and operations require the app to survive reboots and stop/start cycles without breaking the license. You also want a recovery option that preserves the same MAC if you replace the instance. What should you do?',
    options: [
      { id: 'a', text: 'Assign a static MAC address during OS setup' },
      { id: 'b', text: 'Attach an Elastic Network Interface (ENI) and bind the app to that NIC' },
      { id: 'c', text: 'Place the instance in a private subnet so the MAC remains fixed' },
      { id: 'd', text: 'Tie the MAC address to the subnet' },
    ],
    correctId: 'b',
    explanation: 'An Elastic Network Interface (ENI) retains its MAC address across instance reboots and stop/start cycles. If the instance fails, you detach the ENI and attach it to a replacement instance — the MAC address stays the same, preserving the license. An ENI\'s MAC is tied to the ENI resource itself, not the underlying hardware. Subnet placement does not affect MAC addresses. OS-level static MAC config is overridden by hypervisor-level addressing in EC2.',
    reference: '',
    keywords: ['ENI', 'MAC address', 'license', 'Elastic Network Interface', 'persistent MAC', 'instance replacement', 'NIC'],
  },
  {
    id: 'wz6-053', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'A teammate created a production VPC with CIDR 10.0.0.0/24. Months later, IPs are exhausted. You have many dependencies (NAT gateways, endpoints, peering, security tooling) tied to this VPC, and leadership wants the least disruptive way to add capacity without rebuilding or moving workloads. What should you do?',
    options: [
      { id: 'a', text: 'Delete existing subnets and recreate larger subnets' },
      { id: 'b', text: 'Proceed with a new VPC only' },
      { id: 'c', text: 'Create a new VPC and peer to the old one' },
      { id: 'd', text: 'Add a secondary IPv4 CIDR block to the existing VPC and create new subnets there' },
    ],
    correctId: 'd',
    explanation: 'VPCs support multiple CIDR blocks — you can associate up to 5 IPv4 CIDR blocks with an existing VPC. Adding a secondary CIDR (e.g., 10.1.0.0/24) and creating new subnets there adds IP capacity without touching existing resources, peering, endpoints, or security groups. You cannot resize the primary CIDR. Creating a new VPC requires migrating all workloads — highly disruptive. Deleting subnets requires first terminating all resources in them.',
    reference: '',
    keywords: ['VPC secondary CIDR', 'IP exhaustion', 'expand VPC', 'additional CIDR', 'no migration', 'non-disruptive'],
  },
  {
    id: 'wz6-054', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    scenario: 'A financial institution wants to improve its customer service by automating certain tasks and providing a more personalized experience. They are considering using AWS services to achieve this goal. Which of the following AWS services can be used to enhance customer service in a financial institution? (Select TWO)',
    options: [
      { id: 'a', text: 'Amazon Polly' },
      { id: 'b', text: 'Amazon Fraud Detector' },
      { id: 'c', text: 'Amazon Kendra' },
      { id: 'd', text: 'Amazon Lex' },
      { id: 'e', text: 'Amazon Textract' },
    ],
    correctId: 'a,d',
    explanation: 'Amazon Lex (D) builds conversational chatbots/virtual assistants for customer service — handles common queries (account balance, transaction disputes, branch hours) 24/7 without human agents. Amazon Polly (A) provides natural text-to-speech for voice-enabled customer service — reads responses aloud for accessibility and IVR systems. Together they form a voice + chatbot customer service pipeline. Fraud Detector is for fraud scoring, not customer service. Textract extracts text from documents.',
    reference: '',
    keywords: ['Amazon Lex', 'Amazon Polly', 'chatbot', 'text-to-speech', 'customer service', 'virtual assistant', 'IVR', 'financial institution'],
  },
  {
    id: 'wz6-055', domain: 'd4', domainLabel: 'Design Cost-Optimized Architectures', difficulty: 'Easy',
    scenario: 'You host web content in S3 for a consumer app where object access patterns are unpredictable, some objects go hot, then cold. You want millisecond latency when accessed and automatic cost optimization when access drops, without building your own lifecycle rules. Which storage class should you choose?',
    options: [
      { id: 'a', text: 'S3 Standard-IA' },
      { id: 'b', text: 'S3 One Zone-IA' },
      { id: 'c', text: 'S3 Intelligent-Tiering' },
      { id: 'd', text: 'S3 Glacier Instant Retrieval' },
    ],
    correctId: 'c',
    explanation: 'S3 Intelligent-Tiering automatically moves objects between access tiers (Frequent, Infrequent, Archive Instant, Archive, Deep Archive) based on actual access patterns — no lifecycle rules needed. Objects that become hot are promoted instantly; cold objects are demoted to lower-cost tiers. Retrieval is always millisecond (for Frequent/Infrequent tiers). There is no retrieval fee. Standard-IA and One Zone-IA charge per-retrieval and require manual tier decisions.',
    reference: '',
    keywords: ['S3 Intelligent-Tiering', 'automatic tiering', 'unpredictable access', 'no lifecycle rules', 'cost optimization', 'millisecond access'],
  },
  {
    id: 'wz6-056', domain: 'd2', domainLabel: 'Design Resilient Architectures', difficulty: 'Medium',
    scenario: 'Your logging pipeline writes to a versioned S3 bucket. After 60 days, a cleanup job issues DELETE on each object key. Yet the bill still shows storage charges for those keys. Why is that?',
    options: [
      { id: 'a', text: 'DELETE removes only the latest version' },
      { id: 'b', text: 'DELETE places a delete marker; older versions still exist and incur charges' },
      { id: 'c', text: 'S3 moves objects to a recycle bin for 30 days' },
      { id: 'd', text: 'Only the console can permanently delete versions' },
    ],
    correctId: 'b',
    explanation: 'In a versioned S3 bucket, a DELETE request on an object key without specifying a version ID creates a delete marker — it does not remove any actual version. All previous versions remain in the bucket and continue incurring storage charges. To permanently remove all versions, you must delete each version explicitly (specifying the version ID) or use an S3 lifecycle rule to expire noncurrent versions. The delete marker itself is a lightweight object with negligible cost.',
    reference: '',
    keywords: ['S3 versioning', 'delete marker', 'noncurrent versions', 'DELETE behavior', 'storage charges', 'permanent delete'],
  },
  {
    id: 'wz6-057', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'After each multi-GB object upload completes to an Amazon S3 bucket, the platform must automatically email external recipients with a download link. The solution must be serverless, event-driven, and require no EC2. Which options fit? (Select TWO)',
    options: [
      { id: 'a', text: 'S3 Event Notification → Lambda → Amazon SES (production/out of sandbox)' },
      { id: 'b', text: 'S3 Event Notification → Amazon SNS email subscriptions' },
      { id: 'c', text: 'Custom script on EC2 polling S3 + SES (production)' },
      { id: 'd', text: 'Custom script on EC2 polling S3 + SES (sandbox)' },
    ],
    correctId: 'a,b',
    explanation: 'Both A and B are serverless and event-driven: (A) S3 Event Notification triggers Lambda on object upload; Lambda calls Amazon SES to send a custom email with the download link — fully serverless, no EC2. (B) S3 Event Notification → SNS topic with email subscriptions — SNS sends the notification email directly. Both options require no EC2. C and D use EC2 polling — not event-driven and not serverless.',
    reference: '',
    keywords: ['S3 Event Notification', 'Lambda', 'SES', 'SNS', 'email notification', 'serverless', 'event-driven', 'no EC2'],
  },
  {
    id: 'wz6-058', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'You run Amazon ECS with the EC2 launch type (container instances behind an Auto Scaling group). Each new host must apply Docker daemon and ECS agent settings at first boot (e.g., daemon.json, private registry auth, log driver, and ECS_CLUSTER/ECS_LOGLEVEL in /etc/ecs/ecs.config) so the instance registers correctly with the cluster. Where should you put this bootstrap logic?',
    options: [
      { id: 'a', text: 'ECS metadata during cluster creation' },
      { id: 'b', text: 'EC2 User Data on the container instance' },
      { id: 'c', text: 'Task definition' },
      { id: 'd', text: 'Service definition' },
    ],
    correctId: 'b',
    explanation: 'EC2 User Data runs shell scripts at first boot of each container instance. This is where you write ECS_CLUSTER and ECS_LOGLEVEL to /etc/ecs/ecs.config (so the ECS agent registers with the correct cluster), configure Docker daemon settings, and install software. Task definitions describe the container workload (image, CPU, memory, environment variables). Service definitions describe desired count and scheduling. ECS metadata at cluster creation does not bootstrap individual instances.',
    reference: '',
    keywords: ['EC2 User Data', 'ECS container instance', 'ECS_CLUSTER', 'ecs.config', 'bootstrap', 'Docker daemon', 'cluster registration'],
  },
  {
    id: 'wz6-059', domain: 'd1', domainLabel: 'Design Secure Architectures', difficulty: 'Easy',
    scenario: 'Your security team has discovered multiple Amazon ECS clusters across several AWS accounts in your AWS Organization. They need a definitive audit trail that shows who created each cluster, when, and from which source IP, and they want to query across accounts/Regions if needed. Where should they look?',
    options: [
      { id: 'a', text: 'Amazon EventBridge logs' },
      { id: 'b', text: 'AWS CloudTrail' },
      { id: 'c', text: 'Amazon CloudWatch Metrics' },
      { id: 'd', text: 'AWS Trusted Advisor' },
    ],
    correctId: 'b',
    explanation: 'AWS CloudTrail records all AWS API calls — including CreateCluster, DeleteCluster, and every ECS control plane action — with the caller\'s identity (IAM user/role), timestamp, source IP, request parameters, and response. For multi-account organizations, an Org-level CloudTrail trail aggregates logs from all accounts into a central S3 bucket, enabling cross-account and cross-region queries. CloudWatch Metrics shows operational data (CPU, memory). Trusted Advisor checks best practices. EventBridge routes events but doesn\'t store an audit trail.',
    reference: '',
    keywords: ['CloudTrail', 'ECS audit', 'who created', 'source IP', 'multi-account', 'Organizations', 'API audit trail'],
  },
  {
    id: 'wz6-060', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    scenario: 'You\'re building an external API on Amazon API Gateway. Some endpoints must proxy to public HTTP services; other endpoints should call AWS Lambda in a separate account, and an internal set must reach private microservices inside your VPC without exposing them publicly. Which integration targets are valid? (Select THREE)',
    options: [
      { id: 'a', text: 'Public HTTP endpoints on the internet' },
      { id: 'b', text: 'AWS Lambda functions in another AWS account' },
      { id: 'c', text: 'Direct database connections over the internet' },
      { id: 'd', text: 'VPC Link to private resources in your VPC' },
      { id: 'e', text: 'SFTP connection' },
    ],
    correctId: 'a,b,d',
    explanation: 'API Gateway supports three of these integration targets: (A) HTTP/HTTPS proxy to any public internet endpoint; (B) Lambda functions including cross-account (using the function ARN with appropriate resource-based policy); (D) VPC Link integrations that connect to private NLBs/ALBs inside a VPC without public exposure. API Gateway cannot make direct database connections (C) — databases require an application layer. SFTP (E) is not an API Gateway integration type.',
    reference: '',
    keywords: ['API Gateway', 'integration targets', 'HTTP proxy', 'cross-account Lambda', 'VPC Link', 'private endpoints'],
  },
  {
    id: 'wz6-061', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    scenario: 'Your firm fronts an Aurora-backed securities master with Amazon API Gateway + AWS Lambda. To reduce database load and latency, you enabled API Gateway caching on the GET /securities method. Product wants equity and fixed-income requests cached separately so that one group\'s updates don\'t invalidate the other\'s cache. You also want to avoid creating duplicate stages or APIs. What is the most efficient way to split cache entries?',
    options: [
      { id: 'a', text: 'Payload compression' },
      { id: 'b', text: 'Custom domain name' },
      { id: 'c', text: 'API Stage' },
      { id: 'd', text: 'Use a query-string parameter and include it in the cache key' },
    ],
    correctId: 'd',
    explanation: 'API Gateway method cache keys can include query string parameters (and headers). If you add a query param like ?type=equity vs ?type=fixed-income and configure API Gateway to include that parameter in the cache key, equity and fixed-income responses are cached as separate entries. Invalidating one doesn\'t affect the other. This requires no duplicate stages or APIs — just a cache key configuration change. Payload compression affects response size, not cache partitioning.',
    reference: '',
    keywords: ['API Gateway', 'cache key', 'query string parameter', 'cache partitioning', 'method caching', 'TTL', 'separate cache entries'],
  },
  {
    id: 'wz6-062', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Easy',
    scenario: 'Your data science team must build a customer churn prediction model from a large, mixed dataset (profile + behavior events). They want a managed service that supports feature engineering, training with AutoML or custom code, hyperparameter tuning, and one-click deployment to real-time inference (including serverless endpoints) with CI/CD support. Which service should they use?',
    options: [
      { id: 'a', text: 'Amazon SageMaker' },
      { id: 'b', text: 'Amazon Lex' },
      { id: 'c', text: 'Amazon Polly' },
      { id: 'd', text: 'Amazon Comprehend' },
    ],
    correctId: 'a',
    explanation: 'Amazon SageMaker is the end-to-end ML platform covering the full lifecycle: data preparation (Feature Store, Data Wrangler), training (built-in algorithms, custom code in any framework, AutoML via Autopilot), hyperparameter tuning (HPO), model registry, and deployment (real-time endpoints, serverless inference, batch transform, async inference) with built-in CI/CD (Pipelines). Lex, Polly, and Comprehend are pre-built AI services — they don\'t support custom model training.',
    reference: '',
    keywords: ['SageMaker', 'custom ML', 'AutoML', 'Autopilot', 'hyperparameter tuning', 'model deployment', 'serverless inference', 'churn prediction'],
  },
  {
    id: 'wz6-063', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    scenario: 'You\'re adding Lambda@Edge to a CloudFront distribution to enforce custom headers, transform requests, and modify origin responses. Which CloudFront event hooks can trigger your Lambda functions? (Select THREE)',
    options: [
      { id: 'a', text: 'Viewer Request' },
      { id: 'b', text: 'CloudFront Cache' },
      { id: 'c', text: 'Sender Request' },
      { id: 'd', text: 'Origin Request' },
      { id: 'e', text: 'Origin Response' },
    ],
    correctId: 'a,d,e',
    explanation: 'Lambda@Edge supports four CloudFront event hooks: Viewer Request (before cache check), Viewer Response (after origin/cache, before client), Origin Request (cache miss → before forwarding to origin), and Origin Response (after origin response, before caching). The correct three from the options are A (Viewer Request), D (Origin Request), and E (Origin Response). "CloudFront Cache" and "Sender Request" are not valid hook names.',
    reference: '',
    keywords: ['Lambda@Edge', 'CloudFront hooks', 'Viewer Request', 'Origin Request', 'Origin Response', 'edge computing', 'request transformation'],
  },
  {
    id: 'wz6-064', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Medium',
    scenario: 'You just updated the code of a high-traffic Lambda function used behind API Gateway. SRE asks what users experience immediately after the update while the service propagates the new code across AWS infrastructure. What should they expect?',
    options: [
      { id: 'a', text: 'Requests queue for ~5 minutes until propagation completes' },
      { id: 'b', text: 'All requests keep using the old version until you "enable" the new one' },
      { id: 'c', text: 'You must specify the version in the code for requests to work' },
      { id: 'd', text: 'Requests may be served by old or new code for a brief period (<1 minute) during propagation' },
    ],
    correctId: 'd',
    explanation: 'When you update a Lambda function, AWS propagates the new code across execution environments. During this brief propagation window (typically under 1 minute), some execution environments still have the old code while others have the new code — resulting in some requests being served by the old version and others by the new. Requests are never queued; there is no manual enable step required. To avoid this mixed-version period for critical deployments, use Lambda versioning and aliases with weighted traffic shifting.',
    reference: '',
    keywords: ['Lambda', 'deployment propagation', 'code update', 'mixed version', 'execution environment', 'versioning', 'aliases'],
  },
  {
    id: 'wz6-065', domain: 'd3', domainLabel: 'Design High-Performing Architectures', difficulty: 'Hard',
    scenario: 'Your architects are wiring up event source mappings to invoke Lambda functions without writing or managing polling code. Which of the following event sources support native Lambda event source mappings managed by AWS? (Select THREE)',
    options: [
      { id: 'a', text: 'Amazon SNS' },
      { id: 'b', text: 'Amazon Kinesis' },
      { id: 'c', text: 'Amazon SQS' },
      { id: 'd', text: 'Amazon DynamoDB' },
      { id: 'e', text: 'AWS CodePipeline' },
    ],
    correctId: 'b,c,d',
    explanation: 'Lambda event source mappings (where AWS manages polling on your behalf) are supported for: Kinesis Data Streams (B), SQS queues (C), DynamoDB Streams (D), Amazon MSK, Amazon MQ, and Kafka. These are "pull-based" sources — Lambda polls the stream/queue and invokes your function in batches. SNS (A) uses push-based invocation — SNS directly invokes Lambda (Lambda subscribes as a destination; no event source mapping). CodePipeline (E) invokes Lambda as an action via the pipeline configuration, not an event source mapping.',
    reference: '',
    keywords: ['Lambda event source mapping', 'Kinesis', 'SQS', 'DynamoDB Streams', 'pull-based', 'SNS push', 'polling'],
  },
]

const rows = questions.map((q, i) => {
  const options = escape(JSON.stringify(q.options))
  const expl = escape(JSON.stringify({ correct: q.explanation, incorrects: {} }))
  const keywords = escape(JSON.stringify(q.keywords))
  const reference = q.reference ? `'${escape(q.reference)}'` : 'NULL'
  const pageNumber = i + 1
  const screenshotUrl = `'/questions/wz6/${escape(q.id)}.png'`
  return `INSERT OR IGNORE INTO questions (id, domain, domain_label, difficulty, scenario, options, correct_id, explanation, reference, keywords, source, page_number, screenshot_url) VALUES ('${escape(q.id)}', '${q.domain}', '${escape(q.domainLabel)}', '${q.difficulty}', '${escape(q.scenario)}', '${options}', '${escape(q.correctId)}', '${expl}', ${reference}, '${keywords}', 'core', ${pageNumber}, ${screenshotUrl});`
})

writeFileSync('scripts/wz6.sql', rows.join('\n'))
console.log(`Generated ${rows.length} INSERT statements → scripts/wz6.sql`)
